export const buttonText = {
  defaultWidgetText: "Button",
  defaultWidgetName: "button1",
  buttonTextLabel: "Button text",
  loadingState: "Loading state",
  buttonDocumentationLink: "Read documentation for Button",
  backgroundColor: "Background color",
  textColor: "Text color",
  loaderColor: "Loader color",
  defaultBackgroundColor: "#375FCF",
  defaultTextColor: "#fff",
  defaultLoaderColor: "#fff",
  borderRadiusInput: "20",
  hoverBackgroundColor: "Hover background color",
  hoverTextColor: "Hover text color",
  hoverLoaderColor: "Hover loader color",
  defaultHoverBackgroundColor: "#2C4BA6",
  defaultHoverTextColor: "#fff",
  defaultHoverLoaderColor: "#fff",
  clickBackgroundColor: "Click background color",
  clickTextColor: "Click text color",
  clickLoaderColor: "Click loader color",
  defaultClickBackgroundColor: "#1F3A8A",
  defaultClickTextColor: "#fff",
  defaultClickLoaderColor: "#fff",
  disabledBackgroundColor: "Disabled background color",
  disabledTextColor: "Disabled text color",
  disabledLoaderColor: "Disabled loader color",
  defaultDisabledBackgroundColor: "#A0AEC0",
  defaultDisabledTextColor: "#fff",
  defaultDisabledLoaderColor: "#fff",
  buttonSize: "Button size",
  defaultButtonSize: "medium",
  buttonShape: "Button shape",
  defaultButtonShape: "rectangle",
  buttonIcon: "Button icon",
  defaultButtonIcon: "none",
  buttonIconPosition: "Button icon position",
  defaultButtonIconPosition: "left",
  buttonIconSize: "Button icon size",
  defaultButtonIconSize: "medium",
  buttonIconColor: "Button icon color",
  defaultButtonIconColor: "#fff",
  buttonIconHoverColor: "Button icon hover color",
  defaultButtonIconHoverColor: "#fff",
  buttonIconClickColor: "Button icon click color",
  defaultButtonIconClickColor: "#fff",
  buttonIconDisabledColor: "Button icon disabled color",
  defaultButtonIconDisabledColor: "#fff",
  buttonBorderWidth: "Button border width",
  defaultButtonBorderWidth: "1px",
  buttonBorderColor: "Button border color",
  defaultButtonBorderColor: "#375FCF",
  buttonBorderHoverColor: "Button border hover color",
  defaultButtonBorderHoverColor: "#2C4BA6",
  buttonBorderClickColor: "Button border click color",
  defaultButtonBorderClickColor: "#1F3A8A",
  buttonBorderDisabledColor: "Button border disabled color",
  defaultButtonBorderDisabledColor: "#A0AEC0",
  buttonBorderRadius: "Button border radius",
  defaultButtonBorderRadius: "4px",
  buttonPadding: "Button padding",
  defaultButtonPadding: "8px 16px",
  buttonMargin: "Button margin",
  defaultButtonMargin: "0",
  buttonFontSize: "Button font size",
  defaultButtonFontSize: "14px",
  buttonFontWeight: "Button font weight",
  defaultButtonFontWeight: "500",
  buttonTextTransform: "Button text transform",
  defaultButtonTextTransform: "none",
  buttonLetterSpacing: "Button letter spacing",
  defaultButtonLetterSpacing: "normal",
  buttonLineHeight: "Button line height",
  defaultButtonLineHeight: "1.5",
  buttonTextAlign: "Button text align",
  defaultButtonTextAlign: "center",
  buttonVerticalAlign: "Button vertical align",
  defaultButtonVerticalAlign: "middle",
  buttonWhiteSpace: "Button white space",
  defaultButtonWhiteSpace: "nowrap",
  buttonOverflow: "Button overflow",
  defaultButtonOverflow: "hidden",
  buttonTextOverflow: "Button text overflow",
  defaultButtonTextOverflow: "ellipsis",
  buttonCursor: "Button cursor",
  defaultButtonCursor: "pointer",
  buttonDisplay: "Button display",
  defaultButtonDisplay: "inline-block",
  buttonPosition: "Button position",
  defaultButtonPosition: "relative",
  buttonTop: "Button top",
  defaultButtonTop: "auto",
  buttonRight: "Button right",
  defaultButtonRight: "auto",
  buttonBottom: "Button bottom",
  defaultButtonBottom: "auto",
  buttonLeft: "Button left",
  defaultButtonLeft: "auto",
  buttonZIndex: "Button z-index",
  defaultButtonZIndex: "auto",
  buttonBoxShadow: "Button box shadow",
  defaultButtonBoxShadow: "none",
  buttonBoxShadowHover: "Button box shadow hover",
  defaultButtonBoxShadowHover: "none",
  buttonBoxShadowClick: "Button box shadow click",
  defaultButtonBoxShadowClick: "none",
  buttonBoxShadowDisabled: "Button box shadow disabled",
  defaultButtonBoxShadowDisabled: "none",
  buttonTransition: "Button transition",
  defaultButtonTransition: "all 0.2s ease-in-out",
  buttonAnimation: "Button animation",
  defaultButtonAnimation: "none",
  buttonTransform: "Button transform",
  defaultButtonTransform: "none",
  buttonFilter: "Button filter",
  defaultButtonFilter: "none",
  buttonBackdropFilter: "Button backdrop filter",
  defaultButtonBackdropFilter: "none",
  buttonOpacity: "Button opacity",
  defaultButtonOpacity: "1",
  buttonVisibility: "Button visibility",
  defaultButtonVisibility: "visible",
  buttonPointerEvents: "Button pointer events",
  defaultButtonPointerEvents: "auto",
  buttonUserSelect: "Button user select",
  defaultButtonUserSelect: "none",
  buttonWebkitAppearance: "Button webkit appearance",
  defaultButtonWebkitAppearance: "none",
  buttonMozAppearance: "Button moz appearance",
  defaultButtonMozAppearance: "none",
  buttonMsAppearance: "Button ms appearance",
  defaultButtonMsAppearance: "none",
  buttonOAppearance: "Button o appearance",
  defaultButtonOAppearance: "none",
  buttonAppearance: "Button appearance",
  defaultButtonAppearance: "none",
  buttonOutline: "Button outline",
  defaultButtonOutline: "none",
  buttonOutlineOffset: "Button outline offset",
  defaultButtonOutlineOffset: "0",
  buttonCaretColor: "Button caret color",
  defaultButtonCaretColor: "auto",
  buttonResize: "Button resize",
  defaultButtonResize: "none",
  buttonScrollBehavior: "Button scroll behavior",
  defaultButtonScrollBehavior: "auto",
  buttonScrollMargin: "Button scroll margin",
  defaultButtonScrollMargin: "0",
  buttonScrollMarginTop: "Button scroll margin top",
  defaultButtonScrollMarginTop: "0",
  buttonScrollMarginRight: "Button scroll margin right",
  defaultButtonScrollMarginRight: "0",
  buttonScrollMarginBottom: "Button scroll margin bottom",
  defaultButtonScrollMarginBottom: "0",
  buttonScrollMarginLeft: "Button scroll margin left",
  defaultButtonScrollMarginLeft: "0",
  buttonScrollPadding: "Button scroll padding",
  defaultButtonScrollPadding: "0",
  buttonScrollPaddingTop: "Button scroll padding top",
  defaultButtonScrollPaddingTop: "0",
  buttonScrollPaddingRight: "Button scroll padding right",
  defaultButtonScrollPaddingRight: "0",
  buttonScrollPaddingBottom: "Button scroll padding bottom",
  defaultButtonScrollPaddingBottom: "0",
  buttonScrollPaddingLeft: "Button scroll padding left",
  defaultButtonScrollPaddingLeft: "0",
  buttonScrollSnapAlign: "Button scroll snap align",
  defaultButtonScrollSnapAlign: "none",
  buttonScrollSnapStop: "Button scroll snap stop",
  defaultButtonScrollSnapStop: "normal",
  buttonScrollSnapType: "Button scroll snap type",
  defaultButtonScrollSnapType: "none",
  buttonScrollbarColor: "Button scrollbar color",
  defaultButtonScrollbarColor: "auto",
  buttonScrollbarWidth: "Button scrollbar width",
  defaultButtonScrollbarWidth: "auto",
  buttonShapeOutside: "Button shape outside",
  defaultButtonShapeOutside: "none",
  buttonShapeMargin: "Button shape margin",
  defaultButtonShapeMargin: "0",
  buttonTabSize: "Button tab size",
  defaultButtonTabSize: "8",
  buttonTableLayout: "Button table layout",
  defaultButtonTableLayout: "auto",
  buttonTextAlignLast: "Button text align last",
  defaultButtonTextAlignLast: "auto",
  buttonTextCombineUpright: "Button text combine upright",
  defaultButtonTextCombineUpright: "none",
  buttonTextDecoration: "Button text decoration",
  defaultButtonTextDecoration: "none",
  buttonTextDecorationColor: "Button text decoration color",
  defaultButtonTextDecorationColor: "currentColor",
  buttonTextDecorationLine: "Button text decoration line",
  defaultButtonTextDecorationLine: "none",
  buttonTextDecorationStyle: "Button text decoration style",
  defaultButtonTextDecorationStyle: "solid",
  buttonTextEmphasis: "Button text emphasis",
  defaultButtonTextEmphasis: "none",
  buttonTextEmphasisColor: "Button text emphasis color",
  defaultButtonTextEmphasisColor: "currentColor",
  buttonTextEmphasisStyle: "Button text emphasis style",
  defaultButtonTextEmphasisStyle: "none",
  buttonTextIndent: "Button text indent",
  defaultButtonTextIndent: "0",
  buttonTextJustify: "Button text justify",
  defaultButtonTextJustify: "auto",
  buttonTextOrientation: "Button text orientation",
  defaultButtonTextOrientation: "mixed",
  buttonTextRendering: "Button text rendering",
  defaultButtonTextRendering: "auto",
  buttonTextShadow: "Button text shadow",
  defaultButtonTextShadow: "none",
  buttonTextSizeAdjust: "Button text size adjust",
  defaultButtonTextSizeAdjust: "auto",
  buttonTextUnderlinePosition: "Button text underline position",
  defaultButtonTextUnderlinePosition: "auto",
  buttonTouchAction: "Button touch action",
  defaultButtonTouchAction: "auto",
  buttonTransformBox: "Button transform box",
  defaultButtonTransformBox: "border-box",
  buttonTransformOrigin: "Button transform origin",
  defaultButtonTransformOrigin: "50% 50%",
  buttonTransformStyle: "Button transform style",
  defaultButtonTransformStyle: "flat",
  buttonTransitionDelay: "Button transition delay",
  defaultButtonTransitionDelay: "0s",
  buttonTransitionDuration: "Button transition duration",
  defaultButtonTransitionDuration: "0.2s",
  buttonTransitionProperty: "Button transition property",
  defaultButtonTransitionProperty: "all",
  buttonTransitionTimingFunction: "Button transition timing function",
  defaultButtonTransitionTimingFunction: "ease-in-out",
  buttonUnicodeBidi: "Button unicode bidi",
  defaultButtonUnicodeBidi: "normal",
  buttonUserModify: "Button user modify",
  defaultButtonUserModify: "read-only",
  buttonUserZoom: "Button user zoom",
  defaultButtonUserZoom: "zoom",
  buttonVectorEffect: "Button vector effect",
  defaultButtonVectorEffect: "none",
  buttonVerticalAlign: "Button vertical align",
  defaultButtonVerticalAlign: "middle",
  buttonVisibility: "Button visibility",
  defaultButtonVisibility: "visible",
  buttonWhiteSpace: "Button white space",
  defaultButtonWhiteSpace: "nowrap",
  buttonWidows: "Button widows",
  defaultButtonWidows: "2",
  buttonWidth: "Button width",
  defaultButtonWidth: "auto",
  buttonWillChange: "Button will change",
  defaultButtonWillChange: "auto",
  buttonWordBreak: "Button word break",
  defaultButtonWordBreak: "normal",
  buttonWordSpacing: "Button word spacing",
  defaultButtonWordSpacing: "normal",
  buttonWordWrap: "Button word wrap",
  defaultButtonWordWrap: "normal",
  buttonWritingMode: "Button writing mode",
  defaultButtonWritingMode: "horizontal-tb",
  buttonZIndex: "Button z-index",
  defaultButtonZIndex: "auto",
  buttonZoom: "Button zoom",
  defaultButtonZoom: "1",
};
