export const buttonText = {
  defaultWidgetText: "Button",
  buttonProperties: "Properties",
  buttonStyles: "Styles",
  defaultWidgetName: "button1",
  buttonTextLabel: "Button Text",
  loadingState: "Loading State",
  eventsAccordion: "Events",
  buttonDocumentationLink: "Button documentation",
  backgroundColor: "Background color",
  textColor: "Text color",
  loaderColor: "Loader color",
  defaultBackgroundColor: "#375FCF",
  defaultTextColor: "#fff",
  defaultLoaderColor: "#fff",
  borderRadiusInput: "20",
};
