export const licenseText = {
    license: "License",
    licenseKey: "License Key",
    limitOption: "Limits",
    accessOption: "Access",
    domainOption: "Domain",
    updateButton: "Update",
    limitsTabTitle: "Limits",
    appsTab: "Apps",
    noOfAppsLabel: "Number of Apps",
    workspaceTab: "Workspaces",
    noOfworkspaceLabel: "Number of Workspaces",
    usersTab: "Users",
    noOfTotalUsersLabel: "Number of Total Users",
    noOfBuildersLabel: "Number of Builders",
    noOfEndUsersLabel: "Number of End Users",
    noOfSuperAdminLabel: "Number of Super Admins",
    tablesTab: "Tables",
    noOfTablesLabel: "Number of Tables",
};
