export const groupsText = {
  pageTitle: "User Groups",
  createNewGroupButton: "Create new group",
  tableHeader: "Name",
  allUsers: "All users",
  admin: "Admin",
  cardTitle: "Create new group",
  cancelButton: "Cancel",
  createGroupButton: "Create Group",
  groupNameExistToast: "Group name already exist",
  testGroup: "Test",
  groupCreatedToast: "Group has been created",
  userGroup: "User group",
  appsLink: "Apps",
  usersLink: "Users",
  permissionsLink: "Permissions",
  addButton: "Add apps",
  addUsersButton: "Add users",
  userNameTableHeader: "User name",
  permissionstableHedaer: "Permissions",
  emailTableHeader: "Email id",
  resourcesTableHeader: "Resources",
  resourcesApps: "Apps",
  resourcesFolders: "Folder",
  createLabel: "Create",
  folderCreateLabel: "Create/Update/Delete",
  folderHelperText: "All operations on folders",
  deleteLabel: "Delete",
  deleteMessage: "This permission will be permanently deleted. Do you want to continue?",
  permissionUpdatedToast: "Group permissions updated",
  confirmText:
    "This group will be permanently deleted. Do you want to continue?",
  confirmCancelButton: "Cancel",
  confirmYesButton: "Yes",
  resourcesWorkspaceVar: "Workspace constants/variables",
  workspaceCreateLabel: "Create/Update/Delete",
  workspaceHelperText: "All operations on workspace constants",
  textDefaultGroup: "Default group",
  textAppName: "App name",
  helperTextNoAppsAdded: "No apps are added to the group",
  helperTextPermissions:
    "Add app to the group to control permissions for users in this group",
  helperTextAllUsersIncluded:
    " All users within the workspace are included in this list. This list cannot be edited.",
  helperTextAdminAppAccess:
    "Admin has edit access to all apps. These are not editable",
  helperTextAdminPermissions: "Admin has all permissions",
  updateGroupNameModalTitle: "Update group",
  saveButton: "Save",
  groupNameUpdateSucessToast: "Group name updated successfully",
  editGroupNameButton: "Rename",
  deleteGroupButton: "Delete group",
  editPermissionModalTitle: "Edit app permissions",
  addPermissionModalTitle: "Add app permissions",
  appCreateHelperText: 'Create apps in this workspace',
  appDeleteHelperText: 'Delete any app in this workspace',
  appEditLabelText: 'Edit',
  appEditHelperText: 'Access to app builder',
  appViewLabel: 'View',
  appViewHelperText: "Only access released version of apps",
  appHideHelperText: "App will be accessible by URL only",
  appHideLabel: "Hide from dashbaord",
  groupChipText: 'All apps',
  adminAccessHelperText: " Admin has edit access to all apps. These are not editableread documentation to know more !",
  nameTableHeader: 'Name',
  permissionTableHeader: 'Permission',
  permissionNameLabel: 'Permission name',
  permissionNameHelperText: 'Permission name must be unique and max 50 characters',
  permissionLabel: 'Permission',
  editPermissionLabel: 'Edit',
  editPermissionHelperText: 'Access to app builder',
  viewPermissionLabel: 'View',
  viewPermissionHelperText: 'Only access released version of apps',
  resourcesheader: 'Resources',
  allAppsLabel: 'All apps',
  allAppsHelperText: 'This will select all apps in the workspace including any new apps created',
  customLabel: 'Custom',
  customHelperText: 'Select specific applications you want to add to the group',
  updateButtonText: 'Update',

};
