export const groupsText= {
  pageTitle: "User Groups",
  createNewGroupButton: "Create new group",
  tableHeader: "Name",
  allUsers: "All Users",
  admin: "Admin",
  cardTitle: "Add new group",
  cancelButton: "Cancel",
  createGroupButton: "Create Group",
  groupNameExistToast: "Group name already exist",
  testGroup: "Test",
  groupCreatedToast: "Group has been created",
  userGroup: "User group",
  appsLink: "Apps",
  usersLink: "Users",
  permissionsLink: "Permissions",
  addButton: "Add",
  nameTableHeader: "name",
  permissionstableHedaer: "Permissions",
  emailTableHeader: "email",
  resourcesTableHeader: "Resources",
  resourcesApps: "Apps",
  resourcesFolders: "Folder",
  createLabel: "Create",
  folderCreateLabel: "Create/Update/Delete",
  deleteLabel: "Delete",
  permissionUpdatedToast: "Group permissions updated",
  confirmText: "This group will be permanently deleted. Do you want to continue?",
  confirmCancelButton: "Cancel",
  confirmYesButton : "Yes",
};