export const ssoText = {
  pagetitle: "Manage SSO",
  generalSettingsElements: {
    generalSettings: "General Settings",
    enableSignupLabel: "Enable Signup",
    helperText: "New account will be created for user's first time SSO sign in",
    domainLabel: "Allowed domains",
  },
  cancelButton: "Cancel",
  saveButton: "Save",
  allowedDomain: "tooljet.io,gmail.com",
  ssoToast: "updated sso configurations",
  ssoToast2: "updated SSO configurations",
  googleTitle: "Google",
  enabledLabel: "Enabled",
  googleEnabledToast: "Enabled Google SSO",
  disabledLabel: "Disabled",
  googleDisableToast: "Disabled Google SSO",
  googleSignInText: "Sign in with Google",
  clientIdLabel: "Client Id",
  redirectUrlLabel: "Redirect URL",
  clientId: "24567098-mklj8t20za1smb2if.apps.googleusercontent.com",
  testClientId: "12345-client-id-.apps.googleusercontent.com",
  gitTitle: "GitHub",
  clientSecretLabel: "Client Secret",
  encriptedLabel: "Encrypted",
  gitEnabledToast: "Enabled GitHub SSO",
  gitDisabledToast: "Disabled GitHub SSO",
  gitSignInText: "Sign in with GitHub",
  passwordTitle: "Password Login",
  passwordEnabledToast: "Enabled Password login",
  passwordDisabledToast: "Disabled Password login",
  loginUrlLabel: "Login URL",
  loginHelpText: "Use this URL to login directly to this workspace",
  allowedDomainHelpText:
    "Support multiple domains. Enter domain names separated by comma. example: tooljet.com,tooljet.io,yourorganization.com",
  passwordDisableWarning:
    "Users won’t be able to login via username and password if password login is disabled. Please make sure that you have setup other authentication methods before disabling password login, do you want to continue?",
  hostNameLabel: "Host Name",
  hostNameHelpText: " Required if GitHub is self hosted",
  hostName: "Tooljet",
};
