export const ssoText ={
  pagetitle: "Manage SSO",
  generalSettings: "General Settings",
  enableSignupLabel: "Enable signup",
  helperText: "New account will be created for user's first time SSO sign in",
  domainLabel: "Allowed domains",
  cancelButton: "Cancel",
  saveButton: "Save",
  allowedDomain: "tooljet.io,gmail.com",
  ssoToast: "updated sso configurations",
  ssoToast2: "updated SSO configurations",
  googleTitle: "Google",
  enabledLabel: "Enabled",
  googleEnabledToast: "Enabled Google SSO",
  disabledLabel: "Disabled",
  googleDisableToast: "Disabled Google SSO",
  googleSignInText: "Sign in with Google",
  clientIdLabel: "Client Id",
  redirectUrlLabel: "Redirect URL",
  clientId: "24567098-mklj8t20za1smb2if.apps.googleusercontent.com",
  testClientId: "12345-client-id-.apps.googleusercontent.com",
  gitTitle: "GitHub",
  clientSecretLabel: "Client Secret",
  encriptedLabel: "Encrypted",
  gitEnabledToast: "Enabled GitHub SSO",
  gitDisabledToast: "Disabled GitHub SSO",
  gitSignInText: "Sign in with Github",
  passwordTitle: "Password Login",
  passwordEnabledToast: "Enabled Password login",
  passwordDisabledToast: "Disabled Password login",
  loginUrlLabel: "Login URL",
  loginHelpText: "Use this URL to login directly to this workspace",
};