export const groupsText = {
  pageTitle: "User Groups",
  createNewGroupButton: " group",
  tableHeader: "Name",
  allUsers: "All Users",
  admin: "Admin",
  cardTitle: "Add new group",
  cancelButton: "Cancel",
  createGroupButton: "Create Group",
  groupNameExistToast: "Group name already exist",
  testGroup: "Test",
  groupCreatedToast: "Group has been created",
  userGroup: "User group",
  appsLink: "Apps",
  usersLink: "User",
  permissionsLink: "Permissions",
  addButton: "Add apps",
  addUsersButton: "Add users",
  userNameTableHeader: "User name",
  permissionstableHedaer: "Permissions",
  emailTableHeader: "Email id",
  resourcesTableHeader: "Resources",
  resourcesApps: "Apps",
  resourcesFolders: "Folder",
  createLabel: "Create",
  folderCreateLabel: "Create/Update/Delete",
  deleteLabel: "Delete",
  permissionUpdatedToast: "Group permissions updated",
  confirmText:
    "This group will be permanently deleted. Do you want to continue?",
  confirmCancelButton: "Cancel",
  confirmYesButton: "Yes",
  resourcesWorkspaceVar: "Workspace Variables",
  textDefaultGroup: "Default group",
  textAppName: "App name",
  helperTextNoAppsAdded: "No apps are added to the group",
  helperTextPermissions:
    "",
  helperTextAllUsersIncluded:
    " All users include every users in the app. This list is not editable",
  helperTextAdminAppAccess:
    "Admin has edit access to all apps. These are not editable",
  helperTextAdminPermissions: "Admin has all permissions",
  updateGroupNameModalTitle: "Update group",
  saveButton: "Save",
  groupNameUpdateSucessToast: "Group name updated successfully",
  editGroupNameButton: "Edit name",
  deleteGroupButton: " Delete group",
};
