export const onboardingText = {
    welcomeHeader: "Welcome to ToolJet!",
    pageDescription: "Let's set up your admin account and workspace to get started!",
    setUpToolJetButton: "Set up ToolJet",
    userNameInputLabel: "User Name",
    nameInputLabel: "Name",
    emailInputLabel: "Email",
    passwordLabel: "Password",
    passwordHelper: "Password must be at least 8 characters.",
    termsOfServiceLink: "Terms of Service",
    privacyPolicyLink: "Privacy Policy",
    signUpTermsHelperTextCommunity: "By signing up you are agreeing to the terms and conditions.",
    signUpTermsHelperTextEnterprise: "By signing up you are agreeing to the",
    companyNameInputPlaceholder: "Company Name",
    buildPurposePlaceholder: "Purpose of building",
    workspaceNameInputLabelText: "Workspace Name",
    sampleAppHeaderText: "We've created a sample application for you!",
    sampleAppDescriptionText: "The sample application comes with a sample PostgreSQL database for you to play around with. You can also get started quickly with pre-built applications from our template collection!",
    freeTrialHeaderText: "Before we dive in, would you like to start your free trial?",
    monthlyPricingText: "Monthly",
    planToggleLabelText: "Monthly",
    builderPriceText: "$30",
    endUserPriceText: "$10",
    comparePlansText: "Compare plans",
    basicPlanText: "Basic Plan",
    flexibleText: "Flexible",
    businessText: "Business",
    enterpriseText: "Enterprise",
    customPricingText: "Custom pricing",
    noCreditCardText: "No credit card required!",
    priceMonthlyText: "/month",
    defaultPrice: "$0",
    infoDescriptionText: "Build & scale your internal tools faster than ever with our advanced features."
};
