export const profileText = {
  profileLink: "Profile",
  profileElements: {
    pageTitle: "Profile settings",
    profileCard: "Profile",
    firstNameLabel: "First name",
    lastNameLabel: "Last name",
    emailLabel: "Email",
    avatarLabel: "Avatar",
    passwordCard: "Change password",
    currentPasswordLabel: "Current password",
    newPasswordLabel: "New password",
    confirmPasswordLabel: "Confirm new password",
  },
  firstName: "The",
  lastName: "Developer",
  updateButton: "Update",
  email: "dev@tooljet.io",
  firstNameErrorToast: "First name can't be empty!",
  lastNameNameErrorToast: "Last name can't be empty!",
  nameSuccessToast: "Details updated!",
  nameErrorToast: "First name and last name can't be empty!",
  newPassword: "newpassword",
  changePasswordButton: "Change password",
  currentPasswordFieldEmptyToast: "Current password can't be empty!",
  newPasswordFieldEmptyToast: "New password can't be empty!",
  confirmPasswordFieldEmptyToast: "Confirm new password can't be empty!",
  samePasswordErrorToast: "New password can't be the same as the current one!",
  passwordSuccessToast: "Password updated successfully",
  loginErrorToast: "Invalid credentials",
  password: "password",
  newPassword: "Password",
};
