export const profileText={
  profileElements:{
    pageTitle: "Profile Settings",
    profileCard: "Profile",
    firstNameLabel: "First name ",
    lastNameLabel: "Last name",
    emailLabel: "Email ",
    passwordCard: "Change password",
    currentPasswordLabel: "Current password",
    newPasswordLabel: "New password",
  },
  firstName: "The",
  lastName: "Developer",
  updateButton: "Update",
  email: "dev@tooljet.io",
  nameSuccessToast: "Details updated!",
  nameErrorToast: "Name can't be empty!", 
  newPassword: "newpassword",
  changePasswordButton: "Change password",
  passwordErrorToast: "Please verify that you have entered the correct password",
  passwordSuccessToast: "Password updated successfully",
  loginErrorToast:"Invalid email or password",
}