export const restAPIText = {
  restAPI: "REST API",
  credentialsText: "CREDENTIALS",
  baseUrlLabel: "Base URL",
  headersLabel: "Headers",
  keyLabel: "KEY",
  valueLabel: "VALUE",
  urlParametesLabel: "URL parameters",
  bodyLabel: "Body",
  cookiesLabel: "Cookies",
  authenticationText: "AUTHENTICATION",
  authenticationTypeLabel: "Authentication type",
  noneText: "None",
  editButtonText: "Edit",
  basicAuth: {
    basicText: "Basic",
    usernameLabel: "Username",
    passwordLabel: "Password",
  },
  bearerAuth: {
    bearerText: "Bearer",
    tokenLabel: "Token",
  },
  oAuthText: "OAuth 2.0",
  grantTypeLabel: "Grant Type",
  authorizationCode: {
    authorizationCodeLabel: "Authorization Code",
    addAccessTokenLabel: "Add Access Token To",
    headerPrefixLabel: "Header Prefix",
    requestHeader: "Request Header",
    accessTokenURLLabel: "Access Token URL",
    accessTokenURLCustomHeadersLabel: "Access Token URL custom headers",
    clientIDLabel: "Client ID",
    clientSecretLabel: "Client Secret",
    scopeLabel: "Scope(s)",
    customQueryParametersLabel: "Custom Query Parameters",
    authorizationURLLabel: "Authorization URL",
    customAuthenticationParametersLabel: "Custom Authentication Parameters",
    clientAuthentication: "Client Authentication",
    sendBasicAuthheaderOption: "Send as Basic Auth header",
    authenticationRequiredUsersToggle: "Authentication Required for All Users",
  },
  authenticationHeader: "Authentication",
  secureSocketsLayerText: "SECURE SOCKETS LAYER",
  generalSettingsText: "GENERAL SETTINGS",
  retryNetworkErrorsToggleLabel: "Retry on network errors",
  retryToggleHelperText:
    "By default, ToolJet tries to hit API endpoint 3 times before declaring query failed as server did not respond",
};
