export const restAPIText = {
  restAPI: "REST API",
  credentialsText: "CREDENTIALS",
  baseUrlLabel: "Base URL",
  headersLabel: "Headers",
  urlParametesLabel: "URL parameters",
  bodyLabel: "Body",
  cookiesLabel: "Cookies",
  authenticationText: "AUTHENTICATION",
  authenticationTypeLabel: "Authentication type",
  noneText: "None",
  editButtonText: "Edit",
  basicAuth: {
    basicText: "Basic",
    usernameLabel: "Username",
    passwordLabel: "Password",
  },
  bearerAuth: {
    bearerText: "Bearer",
    tokenLabel: "Token",
  },
  oAuthText: "OAuth 2.0",
  grantTypeLabel: "Grant type",
  authorizationCode: {
    authorizationCodeLabel: "Authorization code",
    addAccessTokenLabel: "Add access token to",
    headerPrefixLabel: "Header prefix",
    requestHeader: "Request header",
    accessTokenURLLabel: "Access token URL",
    accessTokenURLCustomHeadersLabel: "Access token URL custom headers",
    clientIDLabel: "Client ID",
    clientSecretLabel: "Client secret",
    scopeLabel: "Scope(s)",
    customQueryParametersLabel: "Custom query parameters",
    authorizationURLLabel: "Authorization URL",
    customAuthenticationParametersLabel: "Custom authentication parameters",
    clientAuthentication: "Client authentication",
    sendBasicAuthheaderOption: "Send as basic auth header",
    sendClientCredentialsBodyOption: "Send client credentials in body",
    authenticationRequiredUsersToggle: "Authentication required for all users",
  },

  clientCredentials: {
    clientCredentialsLabel: "Client credentials",
    accessTokenURLLabel: "Access token URL",
    accessTokenURLCustomHeadersLabel: "Access token URL custom headers",
    clientIDLabel: "Client ID",
    clientSecretLabel: "Client secret",
    scopeLabel: "Scope(s)",
    audiencelabel: "Audience",
  },
  authenticationHeader: "Authentication",
  secureSocketsLayerText: "SECURE SOCKETS LAYER",
  generalSettingsText: "GENERAL SETTINGS",
  retryNetworkErrorsToggleLabel: "Retry on network errors",
  retryToggleHelperText:
    "By default, ToolJet tries to hit API endpoint 3 times before declaring query failed as server did not respond",
};
