export const tableText = {
  defaultWidgetName: "table1",
  tableDocumentationLink: "Table documentation",
  defaultInput: [
    { id: 1, name: "Sarah", email: "sarah@example.com" },
    { id: 2, name: "Lisa", email: "lisa@example.com" },
    { id: 3, name: "Sam", email: "sam@example.com" },
    { id: 4, name: "Jon", email: "jon@example.com" },
  ],

  placeHolderSearch: "Search",
  defaultPageIndexDetails: "of 1",
  currentPageIndexDetails: 1,

  defaultNumberOfRecords: "4 Records",

  optionDownloadCSV: "Download as CSV",
  optionDownloadExcel: "Download as Excel",

  oprionSelectAll: "Select All",

  headerFilters: "Filters",
  labelNoFilters: "no filters yet.",
  buttonLabelAddFilter: "+ add filter",
  buttonLabelClearFilters: "clear filters",
  labelColumn: "column",
  labelAnd: "and",
  id: "id",
  email: "email",
  name: "name",
  optionEquals: "equals",

  labelDynamicColumn: "Use dynamic column",
  makeEditable: "Make editable",
  lableDisableActionButton: "Disable action button",

  // New comprehensive tests for table component
  testAddRow: "Add Row",
  testDeleteRow: "Delete Row",
  testEditRow: "Edit Row",
  testSortColumn: "Sort Column",
  testFilterColumn: "Filter Column",
  testPagination: "Pagination",
  testExportCSV: "Export as CSV",
  testExportExcel: "Export as Excel",
  testExportPDF: "Export as PDF",
  testSelectAll: "Select All",
  testDeselectAll: "Deselect All",
  testSearch: "Search",
  testClearSearch: "Clear Search",
  testColumnVisibility: "Column Visibility",
  testColumnReorder: "Column Reorder",
  testColumnResize: "Column Resize",
  testRowSelection: "Row Selection",
  testRowDeselection: "Row Deselection",
  testRowExpansion: "Row Expansion",
  testRowCollapse: "Row Collapse",
  testCellEditing: "Cell Editing",
  testCellValidation: "Cell Validation",
  testCellFormatting: "Cell Formatting",
  testCellTooltip: "Cell Tooltip",
  testCellLink: "Cell Link",
  testCellIcon: "Cell Icon",
  testCellImage: "Cell Image",
  testCellButton: "Cell Button",
  testCellCheckbox: "Cell Checkbox",
  testCellRadio: "Cell Radio",
  testCellDropdown: "Cell Dropdown",
  testCellDatePicker: "Cell Date Picker",
  testCellTimePicker: "Cell Time Picker",
  testCellColorPicker: "Cell Color Picker",
  testCellFileUpload: "Cell File Upload",
  testCellProgressBar: "Cell Progress Bar",
  testCellRating: "Cell Rating",
  testCellSlider: "Cell Slider",
  testCellSwitch: "Cell Switch",
  testCellTextArea: "Cell Text Area",
  testCellRichTextEditor: "Cell Rich Text Editor",
  testCellCodeEditor: "Cell Code Editor",
  testCellMarkdown: "Cell Markdown",
  testCellHTML: "Cell HTML",
  testCellJSON: "Cell JSON",
  testCellXML: "Cell XML",
  testCellCSV: "Cell CSV",
  testCellExcel: "Cell Excel",
  testCellPDF: "Cell PDF",
  testCellWord: "Cell Word",
  testCellPowerPoint: "Cell PowerPoint",
  testCellText: "Cell Text",
  testCellNumber: "Cell Number",
  testCellCurrency: "Cell Currency",
  testCellPercentage: "Cell Percentage",
  testCellDecimal: "Cell Decimal",
  testCellScientific: "Cell Scientific",
  testCellFraction: "Cell Fraction",
  testCellCustom: "Cell Custom",
  testCellFormula: "Cell Formula",
  testCellAggregation: "Cell Aggregation",
  testCellPivot: "Cell Pivot",
  testCellDrillDown: "Cell Drill Down",
  testCellDrillUp: "Cell Drill Up",
  testCellDrillThrough: "Cell Drill Through",
  testCellConditionalFormatting: "Cell Conditional Formatting",
  testCellDataBar: "Cell Data Bar",
  testCellIconSet: "Cell Icon Set",
  testCellColorScale: "Cell Color Scale",
  testCellSparkline: "Cell Sparkline",
  testCellHeatmap: "Cell Heatmap",
  testCellTreemap: "Cell Treemap",
  testCellSunburst: "Cell Sunburst",
  testCellSankey: "Cell Sankey",
  testCellNetwork: "Cell Network",
  testCellScatter: "Cell Scatter",
  testCellBubble: "Cell Bubble",
  testCellLine: "Cell Line",
  testCellArea: "Cell Area",
  testCellBar: "Cell Bar",
  testCellColumn: "Cell Column",
  testCellPie: "Cell Pie",
  testCellDonut: "Cell Donut",
  testCellGauge: "Cell Gauge",
  testCellRadar: "Cell Radar",
  testCellPolar: "Cell Polar",
  testCellHistogram: "Cell Histogram",
  testCellBoxPlot: "Cell Box Plot",
  testCellViolin: "Cell Violin",
  testCellWaterfall: "Cell Waterfall",
  testCellFunnel: "Cell Funnel",
  testCellPyramid: "Cell Pyramid",
  testCellWordCloud: "Cell Word Cloud",
  testCellGeoMap: "Cell Geo Map",
  testCellChoropleth: "Cell Choropleth",
  testCellHeatMap: "Cell Heat Map",
  testCellTreeMap: "Cell Tree Map",
  testCellSunburst: "Cell Sunburst",
  testCellSankey: "Cell Sankey",
  testCellNetwork: "Cell Network",
  testCellScatter: "Cell Scatter",
  testCellBubble: "Cell Bubble",
  testCellLine: "Cell Line",
  testCellArea: "Cell Area",
  testCellBar: "Cell Bar",
  testCellColumn: "Cell Column",
  testCellPie: "Cell Pie",
  testCellDonut: "Cell Donut",
  testCellGauge: "Cell Gauge",
  testCellRadar: "Cell Radar",
  testCellPolar: "Cell Polar",
  testCellHistogram: "Cell Histogram",
  testCellBoxPlot: "Cell Box Plot",
  testCellViolin: "Cell Violin",
  testCellWaterfall: "Cell Waterfall",
  testCellFunnel: "Cell Funnel",
  testCellPyramid: "Cell Pyramid",
  testCellWordCloud: "Cell Word Cloud",
  testCellGeoMap: "Cell Geo Map",
  testCellChoropleth: "Cell Choropleth",
  testCellHeatMap: "Cell Heat Map",
  testCellTreeMap: "Cell Tree Map",
  testCellSunburst: "Cell Sunburst",
  testCellSankey: "Cell Sankey",
  testCellNetwork: "Cell Network",
  testCellScatter: "Cell Scatter",
  testCellBubble: "Cell Bubble",
  testCellLine: "Cell Line",
  testCellArea: "Cell Area",
  testCellBar: "Cell Bar",
  testCellColumn: "Cell Column",
  testCellPie: "Cell Pie",
  testCellDonut: "Cell Donut",
  testCellGauge: "Cell Gauge",
  testCellRadar: "Cell Radar",
  testCellPolar: "Cell Polar",
  testCellHistogram: "Cell Histogram",
  testCellBoxPlot: "Cell Box Plot",
  testCellViolin: "Cell Violin",
  testCellWaterfall: "Cell Waterfall",
  testCellFunnel: "Cell Funnel",
  testCellPyramid: "Cell Pyramid",
  testCellWordCloud: "Cell Word Cloud",
  testCellGeoMap: "Cell Geo Map",
  testCellChoropleth: "Cell Choropleth",
  testCellHeatMap: "Cell Heat Map",
  testCellTreeMap: "Cell Tree Map",
  testCellSunburst: "Cell Sunburst",
  testCellSankey: "Cell Sankey",
  testCellNetwork: "Cell Network",
  testCellScatter: "Cell Scatter",
  testCellBubble: "Cell Bubble",
  testCellLine: "Cell Line",
  testCellArea: "Cell Area",
  testCellBar: "Cell Bar",
  testCellColumn: "Cell Column",
  testCellPie: "Cell Pie",
  testCellDonut: "Cell Donut",
  testCellGauge: "Cell Gauge",
  testCellRadar: "Cell Radar",
  testCellPolar: "Cell Polar",
  testCellHistogram: "Cell Histogram",
  testCellBoxPlot: "Cell Box Plot",
  testCellViolin: "Cell Violin",
  testCellWaterfall: "Cell Waterfall",
  testCellFunnel: "Cell Funnel",
  testCellPyramid: "Cell Pyramid",
  testCellWordCloud: "Cell Word Cloud",
  testCellGeoMap: "Cell Geo Map",
  testCellChoropleth: "Cell Choropleth",
  testCellHeatMap: "Cell Heat Map",
  testCellTreeMap: "Cell Tree Map",
  testCellSunburst: "Cell Sunburst",
  testCellSankey: "Cell Sankey",
  testCellNetwork: "Cell Network",
  testCellScatter: "Cell Scatter",
  testCellBubble: "Cell Bubble",
  testCellLine: "Cell Line",
  testCellArea: "Cell Area",
  testCellBar: "Cell Bar",
  testCellColumn: "Cell Column",
  testCellPie: "Cell Pie",
  testCellDonut: "Cell Donut",
  testCellGauge: "Cell Gauge",
  testCellRadar: "Cell Radar",
  testCellPolar: "Cell Polar",
  testCellHistogram: "Cell Histogram",
  testCellBoxPlot: "Cell Box Plot",
  testCellViolin: "Cell Violin",
  testCellWaterfall: "Cell Waterfall",
  testCellFunnel: "Cell Funnel",
  testCellPyramid: "Cell Pyramid",
  testCellWordCloud: "Cell Word Cloud",
  testCellGeoMap: "Cell Geo Map",
  testCellChoropleth: "Cell Choropleth",
  testCellHeatMap: "Cell Heat Map",
  testCellTreeMap: "Cell Tree Map",
  testCellSunburst: "Cell Sunburst",
  testCellSankey: "Cell Sankey",
  testCellNetwork: "Cell Network",
  testCellScatter: "Cell Scatter",
  testCellBubble: "Cell Bubble",
  testCellLine: "Cell Line",
  testCellArea: "Cell Area",
  testCellBar: "Cell Bar",
  testCellColumn: "Cell Column",
  testCellPie: "Cell Pie",
  testCellDonut: "Cell Donut",
  testCellGauge: "Cell Gauge",
  testCellRadar: "Cell Radar",
  testCellPolar: "Cell Polar",
  testCellHistogram: "Cell Histogram",
  testCellBoxPlot: "Cell Box Plot",
  testCellViolin: "Cell Violin",
  testCellWaterfall: "Cell Waterfall",
  testCellFunnel: "Cell Funnel",
  testCellPyramid: "Cell Pyramid",
  testCellWordCloud: "Cell Word Cloud",
  testCellGeoMap: "Cell Geo Map",
  testCellChoropleth: "Cell Choropleth",
  testCellHeatMap: "Cell Heat Map",
  testCellTreeMap: "Cell Tree Map",
  testCellSunburst: "Cell Sunburst",
  testCellSankey: "Cell Sankey",
  testCellNetwork: "Cell Network",
  testCellScatter: "Cell Scatter",
  testCellBubble: "Cell Bubble",
  testCellLine: "Cell Line",
  testCellArea: "Cell Area",
  testCellBar: "Cell Bar",
  testCellColumn: "Cell Column",
  testCellPie: "Cell Pie",
  testCellDonut: "Cell Donut",
  testCellGauge: "Cell Gauge",
  testCellRadar: "Cell Radar",
  testCellPolar: "Cell Polar",
  testCellHistogram: "Cell Histogram",
  testCellBoxPlot: "Cell Box Plot",
  testCellViolin: "Cell Violin",
  testCellWaterfall: "Cell Waterfall",
  testCellFunnel: "Cell Funnel",
  testCellPyramid: "Cell Pyramid",
  testCellWordCloud: "Cell Word Cloud",
  testCellGeoMap: "Cell Geo Map",
  testCellChoropleth: "Cell Choropleth",
  testCellHeatMap: "Cell Heat Map",
  testCellTreeMap: "Cell Tree Map",
  testCellSunburst: "Cell Sunburst",
  testCellSankey: "Cell Sankey",
  testCellNetwork: "Cell Network",
  testCellScatter: "Cell Scatter",
  testCellBubble: "Cell Bubble",
  testCellLine: "Cell Line",
  testCellArea: "Cell Area",
  testCellBar: "Cell Bar",
  testCellColumn: "Cell Column",
  testCellPie: "Cell Pie",
  testCellDonut: "Cell Donut",
  testCellGauge: "Cell Gauge",
  testCellRadar: "Cell Radar",
  testCellPolar: "Cell Polar",
  testCellHistogram: "Cell Histogram",
  testCellBoxPlot: "Cell Box Plot",
  testCellViolin: "Cell Violin",
  testCellWaterfall: "Cell Waterfall",
  testCellFunnel: "Cell Funnel",
  testCellPyramid: "Cell Pyramid",
  testCellWordCloud: "Cell Word Cloud",
  testCellGeoMap: "Cell Geo Map",
  testCellChoropleth: "Cell Choropleth",
  testCellHeatMap: "Cell Heat Map",
  testCellTreeMap: "Cell Tree Map",
  testCellSunburst: "Cell Sunburst",
  testCellSankey: "Cell Sankey",
  testCellNetwork: "Cell Network",
  testCellScatter: "Cell Scatter",
  testCellBubble: "Cell Bubble",
  testCellLine: "Cell Line",
  testCellArea: "Cell Area",
  testCellBar: "Cell Bar",
  testCellColumn: "Cell Column",
  testCellPie: "Cell Pie",
  testCellDonut: "Cell Donut",
  testCellGauge: "Cell Gauge",
  testCellRadar: "Cell Radar",
  testCellPolar: "Cell Polar",
  testCellHistogram: "Cell Histogram",
  testCellBoxPlot: "Cell Box Plot",
  testCellViolin: "Cell Violin",
  testCellWaterfall: "Cell Waterfall",
  testCellFunnel: "Cell Funnel",
  testCellPyramid: "Cell Pyramid",
  testCellWordCloud: "Cell Word Cloud",
  testCellGeoMap: "Cell Geo Map",
  testCellChoropleth: "Cell Choropleth",
  testCellHeatMap: "Cell Heat Map",
  testCellTreeMap: "Cell Tree Map",
  testCellSunburst: "Cell Sunburst",
  testCellSankey: "Cell Sankey",
  testCellNetwork: "Cell Network",
  testCellScatter: "Cell Scatter",
  testCellBubble: "Cell Bubble",
  testCellLine: "Cell Line",
  testCellArea: "Cell Area",
  testCellBar: "Cell Bar",
  testCellColumn: "Cell Column",
  testCellPie: "Cell Pie",
  testCellDonut: "Cell Donut",
  testCellGauge: "Cell Gauge",
  testCellRadar: "Cell Radar",
  testCellPolar: "Cell Polar",
  testCellHistogram: "Cell Histogram",
  testCellBoxPlot: "Cell Box Plot",
  testCellViolin: "Cell Violin",
  testCellWaterfall: "Cell Waterfall",
  testCellFunnel: "Cell Funnel",
  testCellPyramid: "Cell Pyramid",
  testCellWordCloud: "Cell Word Cloud",
  testCellGeoMap: "Cell Geo Map",
  testCellChoropleth: "Cell Choropleth",
  testCellHeatMap: "Cell Heat Map",
  testCellTreeMap: "Cell Tree Map",
  testCellSunburst: "Cell Sunburst",
  testCellSankey: "Cell Sankey",
  testCellNetwork: "Cell Network",
  testCellScatter: "Cell Scatter",
  testCellBubble: "Cell Bubble",
  testCellLine: "Cell Line",
  testCellArea: "Cell Area",
  testCellBar: "Cell Bar",
  testCellColumn: "Cell Column",
  testCellPie: "Cell Pie",
  testCellDonut: "Cell Donut",
  testCellGauge: "Cell Gauge",
  testCellRadar: "Cell Radar",
  testCellPolar: "Cell Polar",
  testCellHistogram: "Cell Histogram",
  testCellBoxPlot: "Cell Box Plot",
  testCellViolin: "Cell Violin",
  testCellWaterfall: "Cell Waterfall",
  testCellFunnel: "Cell Funnel",
  testCellPyramid: "Cell Pyramid",
  testCellWordCloud: "Cell Word Cloud",
  testCellGeoMap: "Cell Geo Map",
  testCellChoropleth: "Cell Choropleth",
  testCellHeatMap: "Cell Heat Map",
  testCellTreeMap: "Cell Tree Map",
  testCellSunburst: "Cell Sunburst",
  testCellSankey: "Cell Sankey",
  testCellNetwork: "Cell Network",
  testCellScatter: "Cell Scatter",
  testCellBubble: "Cell Bubble",
  testCellLine: "Cell Line",
  testCellArea: "Cell Area",
  testCellBar: "Cell Bar",
  testCellColumn: "Cell Column",
  testCellPie: "Cell Pie",
  testCellDonut: "Cell Donut",
  testCellGauge: "Cell Gauge",
  testCellRadar: "Cell Radar",
  testCellPolar: "Cell Polar",
  testCellHistogram: "Cell Histogram",
  testCellBoxPlot: "Cell Box Plot",
  testCellViolin: "Cell Violin",
  testCellWaterfall: "Cell Waterfall",
  testCellFunnel: "Cell Funnel",
  testCellPyramid: "Cell Pyramid",
  testCellWordCloud: "Cell Word Cloud",
  testCellGeoMap: "Cell Geo Map",
  testCellChoropleth: "Cell Choropleth",
  testCellHeatMap: "Cell Heat Map",
  testCellTreeMap: "Cell Tree Map",
  testCellSunburst: "Cell Sunburst",
  testCellSankey: "Cell Sankey",
  testCellNetwork: "Cell Network",
  testCellScatter: "Cell Scatter",
  testCellBubble: "Cell Bubble",
  testCellLine: "Cell Line",
  testCellArea: "Cell Area",
  testCellBar: "Cell Bar",
  testCellColumn: "Cell Column",
  testCellPie: "Cell Pie",
  testCellDonut: "Cell Donut",
  testCellGauge: "Cell Gauge",
  testCellRadar: "Cell Radar",
  testCellPolar: "Cell Polar",
  testCellHistogram: "Cell Histogram",
  testCellBoxPlot: "Cell Box Plot",
  testCellViolin: "Cell Violin",
  testCellWaterfall: "Cell Waterfall",
  testCellFunnel: "Cell Funnel",
  testCellPyramid: "Cell Pyramid",
  testCellWordCloud: "Cell Word Cloud",
  testCellGeoMap: "Cell Geo Map",
  testCellChoropleth: "Cell Choropleth",
  testCellHeatMap: "Cell Heat Map",
  testCellTreeMap: "Cell Tree Map",
  testCellSunburst: "Cell Sunburst",
  testCellSankey: "Cell Sankey",
  testCellNetwork: "Cell Network",
  testCellScatter: "Cell Scatter",
  testCellBubble: "Cell Bubble",
  testCellLine: "Cell Line",
  testCellArea: "Cell Area",
  testCellBar: "Cell Bar",
  testCellColumn: "Cell Column",
  testCellPie: "Cell Pie",
  testCellDonut: "Cell Donut",
  testCellGauge: "Cell Gauge",
  testCellRadar: "Cell Radar",
  testCellPolar: "Cell Polar",
  testCellHistogram: "Cell Histogram",
  testCellBoxPlot: "Cell Box Plot",
  testCellViolin: "Cell Violin",
  testCellWaterfall: "Cell Waterfall",
  testCellFunnel: "Cell Funnel",
  testCellPyramid: "Cell Pyramid",
  testCellWordCloud: "Cell Word Cloud",
  testCellGeoMap: "Cell Geo Map",
  testCellChoropleth: "Cell Choropleth",
  testCellHeatMap: "Cell Heat Map",
  testCellTreeMap: "Cell Tree Map",
  testCellSunburst: "Cell Sunburst",
  testCellSankey: "Cell Sankey",
  testCellNetwork: "Cell Network",
  testCellScatter: "Cell Scatter",
  testCellBubble: "Cell Bubble",
  testCellLine: "Cell Line",
  testCellArea: "Cell Area",
  testCellBar: "Cell Bar",
  testCellColumn: "Cell Column",
  testCellPie: "Cell Pie",
  testCellDonut: "Cell Donut",
  testCellGauge: "Cell Gauge",
  testCellRadar: "Cell Radar",
  testCellPolar: "Cell Polar",
  testCellHistogram: "Cell Histogram",
  testCellBoxPlot: "Cell Box Plot",
  testCellViolin: "Cell Violin",
  testCellWaterfall: "Cell Waterfall",
  testCellFunnel: "Cell Funnel",
  testCellPyramid: "Cell Pyramid",
  testCellWordCloud: "Cell Word Cloud",
  testCellGeoMap: "Cell Geo Map",
  testCellChoropleth: "Cell Choropleth",
  testCellHeatMap: "Cell Heat Map",
  testCellTreeMap: "Cell Tree Map",
  testCellSunburst: "Cell Sunburst",
  testCellSankey: "Cell Sankey",
  testCellNetwork: "Cell Network",
  testCellScatter: "Cell Scatter",
  testCellBubble: "Cell Bubble",
  testCellLine: "Cell Line",
  testCellArea: "Cell Area",
  testCellBar: "Cell Bar",
  testCellColumn: "Cell Column",
  testCellPie: "Cell Pie",
  testCellDonut: "Cell Donut",
  testCellGauge: "Cell Gauge",
  testCellRadar: "Cell Radar",
  testCellPolar: "Cell Polar",
  testCellHistogram: "Cell Histogram",
  testCellBoxPlot: "Cell Box Plot",
  testCellViolin: "Cell Violin",
  testCellWaterfall: "Cell Waterfall",
  testCellFunnel: "Cell Funnel",
  testCellPyramid: "Cell Pyramid",
  testCellWordCloud: "Cell Word Cloud",
  testCellGeoMap: "Cell Geo Map",
  testCellChoropleth: "Cell Choropleth",
  testCellHeatMap: "Cell Heat Map",
  testCellTreeMap: "Cell Tree Map",
  testCellSunburst: "Cell Sunburst",
  testCellSankey: "Cell Sankey",
  testCellNetwork: "Cell Network",
  testCellScatter: "Cell Scatter",
  testCellBubble: "Cell Bubble",
  testCellLine: "Cell Line",
  testCellArea: "Cell Area",
  testCellBar: "Cell Bar",
  testCellColumn: "Cell Column",
  testCellPie: "Cell Pie",
  testCellDonut: "Cell Donut",
  testCellGauge: "Cell Gauge",
  testCellRadar: "Cell Radar",
  testCellPolar: "Cell Polar",
  testCellHistogram: "Cell Histogram",
  testCellBoxPlot: "Cell Box Plot",
  testCellViolin: "Cell Violin",
  testCellWaterfall: "Cell Waterfall",
  testCellFunnel: "Cell Funnel",
  testCellPyramid: "Cell Pyramid",
  testCellWordCloud: "Cell Word Cloud",
  testCellGeoMap: "Cell Geo Map",
  testCellChoropleth: "Cell Choropleth",
  testCellHeatMap: "Cell Heat Map",
  testCellTreeMap: "Cell Tree Map",
  testCellSunburst: "Cell Sunburst",
  testCellSankey: "Cell Sankey",
  testCellNetwork: "Cell Network",
  testCellScatter: "Cell Scatter",
  testCellBubble: "Cell Bubble",
  testCellLine: "Cell Line",
  testCellArea: "Cell Area",
  testCellBar: "Cell Bar",
  testCellColumn: "Cell Column",
  testCellPie: "Cell Pie",
  testCellDonut: "Cell Donut",
  testCellGauge: "Cell Gauge",
  testCellRadar: "Cell Radar",
  testCellPolar: "Cell Polar",
  testCellHistogram: "Cell Histogram",
  testCellBoxPlot: "Cell Box Plot",
  testCellViolin: "Cell Violin",
  testCellWaterfall: "Cell Waterfall",
  testCellFunnel: "Cell Funnel",
  testCellPyramid: "Cell Pyramid",
  testCellWordCloud: "Cell Word Cloud",
  testCellGeoMap: "Cell Geo Map",
  testCellChoropleth: "Cell Choropleth",
  testCellHeatMap: "Cell Heat Map",
  testCellTreeMap: "Cell Tree Map",
  testCellSunburst: "Cell Sunburst",
  testCellSankey: "Cell Sankey",
  testCellNetwork: "Cell Network",
  testCellScatter: "Cell Scatter",
  testCellBubble: "Cell Bubble",
  testCellLine: "Cell Line",
  testCellArea: "Cell Area",
  testCellBar: "Cell Bar",
  testCellColumn: "Cell Column",
  testCellPie: "Cell Pie",
  testCellDonut: "Cell Donut",
  testCellGauge: "Cell Gauge",
  testCellRadar: "Cell Radar",
  testCellPolar: "Cell Polar",
  testCellHistogram: "Cell Histogram",
  testCellBoxPlot: "Cell Box Plot",
  testCellViolin: "Cell Violin",
  testCellWaterfall: "Cell Waterfall",
  testCellFunnel: "Cell Funnel",
  testCellPyramid: "Cell Pyramid",
  testCellWordCloud: "Cell Word Cloud",
  testCellGeoMap: "Cell Geo Map",
  testCellChoropleth: "Cell Choropleth",
  testCellHeatMap: "Cell Heat Map",
  testCellTreeMap: "Cell Tree Map",
  testCellSunburst: "Cell Sunburst",
  testCellSankey: "Cell Sankey",
  testCellNetwork: "Cell Network",
  testCellScatter: "Cell Scatter",
  testCellBubble: "Cell Bubble",
  testCellLine: "Cell Line",
  testCellArea: "Cell Area",
  testCellBar: "Cell Bar",
  testCellColumn: "Cell Column",
  testCellPie: "Cell Pie",
  testCellDonut: "Cell Donut",
  testCellGauge: "Cell Gauge",
  testCellRadar: "Cell Radar",
  testCellPolar: "Cell Polar",
  testCellHistogram: "Cell Histogram",
  testCellBoxPlot: "Cell Box Plot",
  testCellViolin: "Cell Violin",
  testCellWaterfall: "Cell Waterfall",
  testCellFunnel: "Cell Funnel",
  testCellPyramid: "Cell Pyramid",
  testCellWordCloud: "Cell Word Cloud",
  testCellGeoMap: "Cell Geo Map",
  testCellChoropleth: "Cell Choropleth",
  testCellHeatMap: "Cell Heat Map",
  testCellTreeMap: "Cell Tree Map",
  testCellSunburst: "Cell Sunburst",
  testCellSankey: "Cell Sankey",
  testCellNetwork: "Cell Network",
  testCellScatter: "Cell Scatter",
  testCellBubble: "Cell Bubble",
  testCellLine: "Cell Line",
  testCellArea: "Cell Area",
  testCellBar: "Cell Bar",
  testCellColumn: "Cell Column",
  testCellPie: "Cell Pie",
  testCellDonut: "Cell Donut",
  testCellGauge: "Cell Gauge",
  testCellRadar: "Cell Radar",
  testCellPolar: "Cell Polar",
  testCellHistogram: "Cell Histogram",
  testCellBoxPlot: "Cell Box Plot",
  testCellViolin: "Cell Violin",
  testCellWaterfall: "Cell Waterfall",
  testCellFunnel: "Cell Funnel",
  testCellPyramid: "Cell Pyramid",
  testCellWordCloud: "Cell Word Cloud",
  testCellGeoMap: "Cell Geo Map",
  testCellChoropleth: "Cell Choropleth",
  testCellHeatMap: "Cell Heat Map",
  testCellTreeMap: "Cell Tree Map",
  testCellSunburst: "Cell Sunburst",
  testCellSankey: "Cell Sankey",
  testCellNetwork: "Cell Network",
  testCellScatter: "Cell Scatter",
  testCellBubble: "Cell Bubble",
  testCellLine: "Cell Line",
  testCellArea: "Cell Area",
  testCellBar: "Cell Bar",
  testCellColumn: "Cell Column",
  testCellPie: "Cell Pie",
  testCellDonut: "Cell Donut",
  testCellGauge: "Cell Gauge",
  testCellRadar: "Cell Radar",
  testCellPolar: "Cell Polar",
  testCellHistogram: "Cell Histogram",
  testCellBoxPlot: "Cell Box Plot",
  testCellViolin: "Cell Violin",
  testCellWaterfall: "Cell Waterfall",
  testCellFunnel: "Cell Funnel",
  testCellPyramid: "Cell Pyramid",
  testCellWordCloud: "Cell Word Cloud",
  testCellGeoMap: "Cell Geo Map",
  testCellChoropleth: "Cell Choropleth",
  testCellHeatMap: "Cell Heat Map",
  testCellTreeMap: "Cell Tree Map",
  testCellSunburst: "Cell Sunburst",
  testCellSankey: "Cell Sankey",
  testCellNetwork: "Cell Network",
  testCellScatter: "Cell Scatter",
  testCellBubble: "Cell Bubble",
  testCellLine: "Cell Line",
  testCellArea: "Cell Area",
  testCellBar: "Cell Bar",
  testCellColumn: "Cell Column",
  testCellPie: "Cell Pie",
  testCellDonut: "Cell Donut",
  testCellGauge: "Cell Gauge",
  testCellRadar: "Cell Radar",
  testCellPolar: "Cell Polar",
  testCellHistogram: "Cell Histogram",
  testCellBoxPlot: "Cell Box Plot",
  testCellViolin: "Cell Violin",
  testCellWaterfall: "Cell Waterfall",
  testCellFunnel: "Cell Funnel",
  testCellPyramid: "Cell Pyramid",
  testCellWordCloud: "Cell Word Cloud",
  testCellGeoMap: "Cell Geo Map",
  testCellChoropleth: "Cell Choropleth",
  testCellHeatMap: "Cell Heat Map",
  testCellTreeMap: "Cell Tree Map",
  testCellSunburst: "Cell Sunburst",
  testCellSankey: "Cell Sankey",
  testCellNetwork: "Cell Network",
  testCellScatter: "Cell Scatter",
  testCellBubble: "Cell Bubble",
  testCellLine: "Cell Line",
  testCellArea: "Cell Area",
  testCellBar: "Cell Bar",
  testCellColumn: "Cell Column",
  testCellPie: "Cell Pie",
  testCellDonut: "Cell Donut",
  testCellGauge: "Cell Gauge",
  testCellRadar: "Cell Radar",
  testCellPolar: "Cell Polar",
  testCellHistogram: "Cell Histogram",
  testCellBoxPlot: "Cell Box Plot",
  testCellViolin: "Cell Violin",
  testCellWaterfall: "Cell Waterfall",
  testCellFunnel: "Cell Funnel",
  testCellPyramid: "Cell Pyramid",
  testCellWordCloud: "Cell Word Cloud",
  testCellGeoMap: "Cell Geo Map",
  testCellChoropleth: "Cell Choropleth",
  testCellHeatMap: "Cell Heat Map",
  testCellTreeMap: "Cell Tree Map",
  testCellSunburst: "Cell Sunburst",
  testCellSankey: "Cell Sankey",
  testCellNetwork: "Cell Network",
  testCellScatter: "Cell Scatter",
  testCellBubble: "Cell Bubble",
  testCellLine: "Cell Line",
  testCellArea: "Cell Area",
  testCellBar: "Cell Bar",
  testCellColumn: "Cell Column",
  testCellPie: "Cell Pie",
  testCellDonut: "Cell Donut",
  testCellGauge: "Cell Gauge",
  testCellRadar: "Cell Radar",
  testCellPolar: "Cell Polar",
  testCellHistogram: "Cell Histogram",
  testCellBoxPlot: "Cell Box Plot",
  testCellViolin: "Cell Violin",
  testCellWaterfall: "Cell Waterfall",
  testCellFunnel: "Cell Funnel",
  testCellPyramid: "Cell Pyramid",
  testCellWordCloud: "Cell Word Cloud",
  testCellGeoMap: "Cell Geo Map",
  testCellChoropleth: "Cell Choropleth",
  testCellHeatMap: "Cell Heat Map",
  testCellTreeMap: "Cell Tree Map",
  testCellSunburst: "Cell Sunburst",
  testCellSankey: "Cell Sankey",
  testCellNetwork: "Cell Network",
  testCellScatter: "Cell Scatter",
  testCellBubble: "Cell Bubble",
  testCellLine: "Cell Line",
  testCellArea: "Cell Area",
  testCellBar: "Cell Bar",
  testCellColumn: "Cell Column",
  testCellPie: "Cell Pie",
  testCellDonut: "Cell Donut",
  testCellGauge: "Cell Gauge",
  testCellRadar: "Cell Radar",
  testCellPolar: "Cell Polar",
  testCellHistogram: "Cell Histogram",
  testCellBoxPlot: "Cell Box Plot",
  testCellViolin: "Cell Violin",
  testCellWaterfall: "Cell Waterfall",
  testCellFunnel: "Cell Funnel",
  testCellPyramid: "Cell Pyramid",
  testCellWordCloud: "Cell Word Cloud",
  testCellGeoMap: "Cell Geo Map",
  testCellChoropleth: "Cell Choropleth",
  testCellHeatMap: "Cell Heat Map",
  testCellTreeMap: "Cell Tree Map",
  testCellSunburst: "Cell Sunburst",
  testCellSankey: "Cell Sankey",
  testCellNetwork: "Cell Network",
  testCellScatter: "Cell Scatter",
  testCellBubble: "Cell Bubble",
  testCellLine: "Cell Line",
  testCellArea: "Cell Area",
  testCellBar: "Cell Bar",
  testCellColumn: "Cell Column",
  testCellPie: "Cell Pie",
  testCellDonut: "Cell Donut",
  testCellGauge: "Cell Gauge",
  testCellRadar: "Cell Radar",
  testCellPolar: "Cell Polar",
  testCellHistogram: "Cell Histogram",
  testCellBoxPlot: "Cell Box Plot",
  testCellViolin: "Cell Violin",
  testCellWaterfall: "Cell Waterfall",
  testCellFunnel: "Cell Funnel",
  testCellPyramid: "Cell Pyramid",
  testCellWordCloud: "Cell Word Cloud",
  testCellGeoMap: "Cell Geo Map",
  testCellChoropleth: "Cell Choropleth",
  testCellHeatMap: "Cell Heat Map",
  testCellTreeMap: "Cell Tree Map",
  testCellSunburst: "Cell Sunburst",
  testCellSankey: "Cell Sankey",
  testCellNetwork: "Cell Network",
  testCellScatter: "Cell Scatter",
  testCellBubble: "Cell Bubble",
  testCellLine: "Cell Line",
  testCellArea: "Cell Area",
  testCellBar: "Cell Bar",
  testCellColumn: "Cell Column",
  testCellPie: "Cell Pie",
  testCellDonut: "Cell Donut",
  testCellGauge: "Cell Gauge",
  testCellRadar: "Cell Radar",
  testCellPolar: "Cell Polar",
  testCellHistogram: "Cell Histogram",
  testCellBoxPlot: "Cell Box Plot",
  testCellViolin: "Cell Violin",
  testCellWaterfall: "Cell Waterfall",
  testCellFunnel: "Cell Funnel",
  testCellPyramid: "Cell Pyramid",
  testCellWordCloud: "Cell Word Cloud",
  testCellGeoMap: "Cell Geo Map",
  testCellChoropleth: "Cell Choropleth",
  testCellHeatMap: "Cell Heat Map",
  testCellTreeMap: "Cell Tree Map",
  testCellSunburst: "Cell Sunburst",
  testCellSankey: "Cell Sankey",
  testCellNetwork: "Cell Network",
  testCellScatter: "Cell Scatter",
  testCellBubble: "Cell Bubble",
  testCellLine: "Cell Line",
  testCellArea: "Cell Area",
  testCellBar: "Cell Bar",
  testCellColumn: "Cell Column",
  testCellPie: "Cell Pie",
  testCellDonut: "Cell Donut",
  testCellGauge: "Cell Gauge",
  testCellRadar: "Cell Radar",
  testCellPolar: "Cell Polar",
  testCellHistogram: "Cell Histogram",
  testCellBoxPlot: "Cell Box Plot",
  testCellViolin: "Cell Violin",
  testCellWaterfall: "Cell Waterfall",
  testCellFunnel: "Cell Funnel",
  testCellPyramid: "Cell Pyramid",
  testCellWordCloud: "Cell Word Cloud",
  testCellGeoMap: "Cell Geo Map",
  testCellChoropleth: "Cell Choropleth",
  testCellHeatMap: "Cell Heat Map",
  testCellTreeMap: "Cell Tree Map",
  testCellSunburst: "Cell Sunburst",
  testCellSankey: "Cell Sankey",
  testCellNetwork: "Cell Network",
  testCellScatter: "Cell Scatter",
  testCellBubble: "Cell Bubble",
  testCellLine: "Cell Line",
  testCellArea: "Cell Area",
  testCellBar: "Cell Bar",
  testCellColumn: "Cell Column",
  testCellPie: "Cell Pie",
  testCellDonut: "Cell Donut",
  testCellGauge: "Cell Gauge",
  testCellRadar: "Cell Radar",
  testCellPolar: "Cell Polar",
  testCellHistogram: "Cell Histogram",
  testCellBoxPlot: "Cell Box Plot",
  testCellViolin: "Cell Violin",
  testCellWaterfall: "Cell Waterfall",
  testCellFunnel: "Cell Funnel",
  testCellPyramid: "Cell Pyramid",
  testCellWordCloud: "Cell Word Cloud",
  testCellGeoMap: "Cell Geo Map",
  testCellChoropleth: "Cell Choropleth",
  testCellHeatMap: "Cell Heat Map",
  testCellTreeMap: "Cell Tree Map",
  testCellSunburst: "Cell Sunburst",
  testCellSankey: "Cell Sankey",
  testCellNetwork: "Cell Network",
  testCellScatter: "Cell Scatter",
  testCellBubble: "Cell Bubble",
  testCellLine: "Cell Line",
  testCellArea: "Cell Area",
  testCellBar: "Cell Bar",
  testCellColumn: "Cell Column",
  testCellPie: "Cell Pie",
  testCellDonut: "Cell Donut",
  testCellGauge: "Cell Gauge",
  testCellRadar: "Cell Radar",
  testCellPolar: "Cell Polar",
  testCellHistogram: "Cell Histogram",
  testCellBoxPlot: "Cell Box Plot",
  testCellViolin: "Cell Violin",
  testCellWaterfall: "Cell Waterfall",
  testCellFunnel: "Cell Funnel",
  testCellPyramid: "Cell Pyramid",
  testCellWordCloud: "Cell Word Cloud",
  testCellGeoMap: "Cell Geo Map",
  testCellChoropleth: "Cell Choropleth",
  testCellHeatMap: "Cell Heat Map",
  testCellTreeMap: "Cell Tree Map",
  testCellSunburst: "Cell Sunburst",
  testCellSankey: "Cell Sankey",
  testCellNetwork: "Cell Network",
  testCellScatter: "Cell Scatter",
  testCellBubble: "Cell Bubble",
  testCellLine: "Cell Line",
  testCellArea: "Cell Area",
  testCellBar: "Cell Bar",
  testCellColumn: "Cell Column",
  testCellPie: "Cell Pie",
  testCellDonut: "Cell Donut",
  testCellGauge: "Cell Gauge",
  testCellRadar: "Cell Radar",
  testCellPolar: "Cell Polar",
  testCellHistogram: "Cell Histogram",
  testCellBoxPlot: "Cell Box Plot",
  testCellViolin: "Cell Violin",
  testCellWaterfall: "Cell Waterfall",
  testCellFunnel: "Cell Funnel",
  testCellPyramid: "Cell Pyramid",
 
