import { FEATURE_KEY } from './index';
import { MODULES } from '@modules/app/constants/modules';
import { FeaturesConfig } from '../types';

export const FEATURES: FeaturesConfig = {
  [MODULES.APP_PERMISSIONS]: {
    [FEATURE_KEY.FETCH_USERS]: {},
    [FEATURE_KEY.FETCH_USER_GROUPS]: {},
    [FEATURE_KEY.FETCH_PAGE_PERMISSIONS]: {},
    [FEATURE_KEY.CREATE_PAGE_PERMISSIONS]: {},
    [FEATURE_KEY.UPDATE_PAGE_PERMISSIONS]: {},
    [FEATURE_KEY.DELETE_PAGE_PERMISSIONS]: {},
    [FEATURE_KEY.FETCH_QUERY_PERMISSIONS]: {},
    [FEATURE_KEY.CREATE_QUERY_PERMISSIONS]: {},
    [FEATURE_KEY.UPDATE_QUERY_PERMISSIONS]: {},
    [FEATURE_KEY.DELETE_QUERY_PERMISSIONS]: {},
  },
};
