export enum FEATURE_KEY {
  LIST_BRANCHES = 'LIST_BRANCHES',
  CREATE_BRANCH = 'CREATE_BRANCH',
  SWITCH_BRANCH = 'SWITCH_BRANCH',
  DELETE_BRANCH = 'DELETE_BRANCH',
  PUSH_WORKSPACE = 'PUSH_WORKSPACE',
  PULL_WORKSPACE = 'PULL_WORKSPACE',
  CHECK_UPDATES = 'CHECK_UPDATES',
  LIST_REMOTE_BRANCHES = 'LIST_REMOTE_BRANCHES',
  FETCH_PULL_REQUESTS = 'FETCH_PULL_REQUESTS',
  ENSURE_DRAFT = 'ENSURE_DRAFT',
}
