apiVersion: v1
kind: Service
metadata:
  name: tooljet
spec:
  type: {{ .Values.apps.tooljet.service.type }}
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: tooljet
