// Single source of truth for the list of app builder actions available in code hints.
export const ACTIONS = [
  'runQuery',
  'resetQuery',
  'setVariable',
  'unsetAllVariables',
  'unSetVariable',
  'showAlert',
  'logout',
  'showModal',
  'closeModal',
  'setLocalStorage',
  'copyToClipboard',
  'goToApp',
  'generateFile',
  'setPageVariable',
  'unsetAllPageVariables',
  'unsetPageVariable',
  'switchPage',
  'logInfo',
  'log',
  'logError',
  'toggleAppMode',
  'scrollComponentInToView',
];
