export enum FEATURE_KEY {
  CREATE_DS_FOLDER = 'CREATE_DS_FOLDER',
  UPDATE_DS_FOLDER = 'UPDATE_DS_FOLDER',
  DELETE_DS_FOLDER = 'DELETE_DS_FOLDER',
  ADD_DS_TO_FOLDER = 'ADD_DS_TO_FOLDER',
  REMOVE_DS_FROM_FOLDER = 'REMOVE_DS_FROM_FOLDER',
  BULK_MOVE_DS = 'BULK_MOVE_DS',
  GET_DS_FOLDERS = 'GET_DS_FOLDERS',
  GET_DS_IN_FOLDER = 'GET_DS_IN_FOLDER',
}
