export enum FEATURE_KEY {
  CREATE_DATA_SOURCE_FOLDER = 'CREATE_DATA_SOURCE_FOLDER',
  UPDATE_DATA_SOURCE_FOLDER = 'UPDATE_DATA_SOURCE_FOLDER',
  DELETE_DATA_SOURCE_FOLDER = 'DELETE_DATA_SOURCE_FOLDER',
  ADD_DATA_SOURCE_TO_FOLDER = 'ADD_DATA_SOURCE_TO_FOLDER',
  REMOVE_DATA_SOURCE_FROM_FOLDER = 'REMOVE_DATA_SOURCE_FROM_FOLDER',
  BULK_MOVE_DATA_SOURCES = 'BULK_MOVE_DATA_SOURCES',
  GET_DATA_SOURCE_FOLDERS = 'GET_DATA_SOURCE_FOLDERS',
  GET_DATA_SOURCES_IN_FOLDER = 'GET_DATA_SOURCES_IN_FOLDER',
}
