export enum FEATURE_KEY {
  CREATE_FOLDER_DATA_SOURCE = 'CREATE_FOLDER_DATA_SOURCE',
  UPDATE_FOLDER_DATA_SOURCE = 'UPDATE_FOLDER_DATA_SOURCE',
  DELETE_FOLDER_DATA_SOURCE = 'DELETE_FOLDER_DATA_SOURCE',
  ADD_DATA_SOURCE_TO_FOLDER = 'ADD_DATA_SOURCE_TO_FOLDER',
  REMOVE_DATA_SOURCE_FROM_FOLDER = 'REMOVE_DATA_SOURCE_FROM_FOLDER',
  BULK_MOVE_DATA_SOURCES = 'BULK_MOVE_DATA_SOURCES',
  GET_FOLDER_DATA_SOURCES = 'GET_FOLDER_DATA_SOURCES',
  GET_DATA_SOURCES_IN_FOLDER = 'GET_DATA_SOURCES_IN_FOLDER',
}
