require: rubocop-rails
AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 2.7
  # RuboCop has a bunch of cops enabled by default. This setting tells RuboCop
  # to ignore them, so only the ones explicitly set in this file are enabled.
  DisabledByDefault: true
  Exclude:
    - "**/templates/**/*"
    - "**/vendor/**/*"
    - "actionpack/lib/action_dispatch/journey/parser.rb"
    - "db/schema.rb"
    - "db/migrate/**/*"
    - "node_modules/**/*"
    - "bin/**"
    - "config/application.rb"
    - "config/boot.rb"
    - "config/environment.rb"
    - "config/environments/*.rb"
    - "config/routes.rb"

Rails/EnvironmentVariableAccess:
  Enabled: false

Rails/TimeZoneAssignment:
  Enabled: true

# Prefer &&/|| over and/or.
Style/AndOr:
  Enabled: true

# Align `when` with `case`.
Layout/CaseIndentation:
  Enabled: true

# Align comments with method definitions.
Layout/CommentIndentation:
  Enabled: true

Layout/EmptyLineAfterMagicComment:
  Enabled: true

# In a regular class definition, no empty lines around the body.
Layout/EmptyLinesAroundClassBody:
  Enabled: true

# In a regular method definition, no empty lines around the body.
Layout/EmptyLinesAroundMethodBody:
  Enabled: true

# In a regular module definition, no empty lines around the body.
Layout/EmptyLinesAroundModuleBody:
  Enabled: true

Layout/FirstArgumentIndentation:
  Enabled: true

# Use Ruby >= 1.9 syntax for hashes. Prefer { a: :b } over { :a => :b }.
Style/HashSyntax:
  Enabled: true

# Method definitions after `private` or `protected` isolated calls need one
# extra level of indentation.
Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: indented_internal_methods

# Two spaces, no tabs (for indentation).
Layout/IndentationWidth:
  Enabled: true

Layout/LeadingCommentSpace:
  Enabled: true

Layout/SpaceAfterColon:
  Enabled: true

Layout/SpaceAfterComma:
  Enabled: true

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: true

Layout/SpaceAroundKeyword:
  Enabled: true

# If we enable it then following code indentation fails
#     @current_row_project_name   = row["Project"]
#     @current_row_date           = row["Date"]
#     @current_row_email          = row["Email"]
#     @current_row_client_name    = row["Client"]
#     @current_row_task_name      = row["Task"]
#     @current_row_notes          = row["Notes"]
#     @current_row_hours          = row["Hours"]
Layout/SpaceAroundOperators:
  Enabled: false

Layout/SpaceBeforeComma:
  Enabled: true

Layout/SpaceBeforeFirstArg:
  Enabled: true

Style/DefWithParentheses:
  Enabled: true

# Defining a method with parameters needs parentheses.
Style/MethodDefParentheses:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

# Use `foo {}` not `foo{}`.
Layout/SpaceBeforeBlockBraces:
  Enabled: true

# Use `foo { bar }` not `foo {bar}`.
Layout/SpaceInsideBlockBraces:
  Enabled: true

# Use `{ a: 1 }` not `{a:1}`.
Layout/SpaceInsideHashLiteralBraces:
  Enabled: true

Layout/SpaceInsideParens:
  Enabled: true

# Check quotes usage according to lint rule below.
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

# This cop looks for trailing blank lines and a final newline in the source code.
# This is being disabled because the requirement to have a final newline is illogical.
Layout/TrailingEmptyLines:
  Enabled: false

# No trailing whitespace.
Layout/TrailingWhitespace:
  Enabled: true

# Use quotes for string literals when they are enough.
Style/RedundantPercentQ:
  Enabled: true

# Align `end` with the matching keyword or starting expression except for
# assignments, where it should be aligned with the LHS.
Layout/EndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: variable

# Use my_method(my_arg) not my_method( my_arg ) or my_method my_arg.
Lint/RequireParentheses:
  Enabled: true

Style/RedundantReturn:
  Enabled: true
  AllowMultipleReturnValues: true

Style/Semicolon:
  Enabled: true
  AllowAsExpressionSeparator: true

# Corrects usage of :true/:false to true/false
Lint/BooleanSymbol:
  Enabled: true

# No space in method name and the arguments
Lint/ParenthesesAsGroupedExpression:
  Enabled: true

# Enabled Rails cops for the command rubocop -a
Rails:
  Enabled: true

# Correct usage of Date methods in Rails
Rails/Date:
  Enabled: true

# Correct usage of TimeZone methods in Rails
Rails/TimeZone:
  Enabled: true

Rails/ActiveRecordCallbacksOrder:
  Enabled: true

Rails/FindById:
  Enabled: true

Rails/Inquiry:
  Enabled: false

Rails/MailerName:
  Enabled: true

Rails/MatchRoute:
  Enabled: true

Rails/NegateInclude:
  Enabled: true

Rails/Pluck:
  Enabled: true

Rails/PluckInWhere:
  Enabled: true

Rails/RenderInline:
  Enabled: true

Rails/RenderPlainText:
  Enabled: true

Rails/ShortI18n:
  Enabled: true

Rails/WhereExists:
  Enabled: true

Rails/AfterCommitOverride: 
  Enabled: true

Rails/SquishedSQLHeredocs:
  Enabled: true

Rails/WhereNot:
  Enabled: true

Rails/SkipsModelValidations:
  Enabled: false

Rails/AttributeDefaultBlockValue: # (new in 2.9)
  Enabled: true
Rails/WhereEquals: # (new in 2.9)
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging
    - heroku
