db-uri = "postgres://postgres:postgres@localhost:5432/tooljet_db"
db-pre-config = "postgrest.pre_config"
server-port = "3001"
jwt-secret = "4229d5774cfe7f60e75d6b3bf3a1dbb054a696b6d21b6d5de7b73291899797a"
