// Feature keys for the strategy-only endpoints that remain on /git-sync.
// DB-only feature keys (GET_ORGANIZATION_GIT, GET_ORGANIZATION_GIT_STATUS,
// CREATE_ORGANIZATION_GIT, UPDATE_PROVIDER_CONFIGS, UPDATE_ORGANIZATION_GIT_STATUS,
// DELETE_ORGANIZATION_GIT_CONFIGS) moved to the git-sync-configs module.
export enum FEATURE_KEY {
  SAVE_PROVIDER_CONFIGS = 'SAVE_PROVIDER_CONFIGS',
  FINALIZE_CONFIGS = 'FINALIZE_CONFIGS',
  SAVE_ENV_PROVIDER_CONFIGS = 'SAVE_ENV_PROVIDER_CONFIGS',
  ENABLE_AUTO_SYNC = 'ENABLE_AUTO_SYNC',
  DISABLE_AUTO_SYNC = 'DISABLE_AUTO_SYNC',
  ROTATE_AUTO_SYNC_SECRET = 'ROTATE_AUTO_SYNC_SECRET',
  GET_AUTO_SYNC_STATUS = 'GET_AUTO_SYNC_STATUS',
  GET_AUTO_SYNC_EVENTS = 'GET_AUTO_SYNC_EVENTS',
}
