export enum FEATURE_KEY {
  GET_ORGANIZATION_GIT = 'GET_ORGANIZATION_GIT',
  GET_ORGANIZATION_GIT_STATUS = 'GET_ORGANIZATION_GIT_STATUS',
  CREATE_ORGANIZATION_GIT = 'CREATE_ORGANIZATION_GIT',
  SAVE_PROVIDER_CONFIGS = 'SAVE_PROVIDER_CONFIGS',
  FINALIZE_CONFIGS = 'FINALIZE_CONFIGS',
  UPDATE_PROVIDER_CONFIGS = 'UPDATE_PROVIDER_CONFIGS',
  UPDATE_ORGANIZATION_GIT_STATUS = 'UPDATE_ORGANIZATION_GIT_STATUS',
  DELETE_ORGANIZATION_GIT_CONFIGS = 'DELETE_ORGANIZATION_GIT_CONFIGS',
}
