export const harperDbText = {
  harperDb: "HarperDB",
  cypressHarperDB: "cypressHarperDB",
  hostLabel: "Host",
  hostInputPlaceholder: "Enter host",
  portLabel: "Port",
  portPlaceholder: "Enter port",
  userNameLabel: "Username",
  passwordlabel: "Password",
  userNamePlaceholder: "Enter username",
  passwordPlaceholder: "**************",
  recordsValue: `[{id: 10, name: 'QA', age: 24}]`,
  hashValue: "[10]",
  attributesValue: "['name']",
  searchAttributeValue: "name",
  searchValue: "QA",
  condtionValue: `[{'search_attribute': 'name', 'search_type': 'between', 'search_value': [1, 5]}, {'search_attribute': 'name', 'search_type': 'equals', 'search_value': 'QA'}]`,
  sqlValue: "SELECT * FROM test_schema.test_table",
  schemaValue: "test_schema",
  tableValue: "test_table",
};
