import {
  APP_RESOURCE_ACTIONS,
  FOLDER_RESOURCE_ACTION,
  ORGANIZATION_CONSTANT_RESOURCE_ACTIONS,
  ORGANIZATION_VARIABLE_ACTIONS,
  TOOLJET_RESOURCE,
} from 'src/constants/global.constant';
import { ResourceType } from './granular-permissions.constant';
import { ResourceAction } from '../interface/permissions-ability.interface';

export const PERMISSION_RESOURCE_MAPPING = {
  [TOOLJET_RESOURCE.APP]: ResourceType.APP,
} as Record<TOOLJET_RESOURCE, ResourceType>;

export const ACTIONS_DATA_POINTS = {
  [TOOLJET_RESOURCE.APP]: {
    [APP_RESOURCE_ACTIONS.CREATE]: 'appCreate',
    [APP_RESOURCE_ACTIONS.DELETE]: 'appDelete',
    [APP_RESOURCE_ACTIONS.READ]: 'canView',
    [APP_RESOURCE_ACTIONS.UPDATE]: 'canEdit',
  },
  [TOOLJET_RESOURCE.FOLDER]: {
    [FOLDER_RESOURCE_ACTION.CREATE]: 'folderCRUD',
    [FOLDER_RESOURCE_ACTION.UPDATE]: 'folderCRUD',
    [FOLDER_RESOURCE_ACTION.DELETE]: 'folderCRUD',
  },
  [TOOLJET_RESOURCE.GLOBAL_DATA_SOURCE]: {},
  [TOOLJET_RESOURCE.ORGANIZATION_CONSTANT]: {
    [ORGANIZATION_CONSTANT_RESOURCE_ACTIONS.CREATE]: 'orgConstantCRUD',
    [ORGANIZATION_CONSTANT_RESOURCE_ACTIONS.UPDATE]: 'orgConstantCRUD',
    [ORGANIZATION_CONSTANT_RESOURCE_ACTIONS.DELETE]: 'orgConstantCRUD',
  },
  [TOOLJET_RESOURCE.ORGANIZATION_VARIABLE]: {
    [ORGANIZATION_VARIABLE_ACTIONS.CREATE]: 'orgVariableCRUD',
    [ORGANIZATION_VARIABLE_ACTIONS.UPDATE]: 'orgVariableCRUD',
    [ORGANIZATION_VARIABLE_ACTIONS.DELETE]: 'orgVariableCRUD',
  },
} as Record<TOOLJET_RESOURCE, Record<ResourceAction, string>>;

export const PERMISSIONS_PARENTS_RESOURCE = {
  [TOOLJET_RESOURCE.APP]: [TOOLJET_RESOURCE.APP],
  [TOOLJET_RESOURCE.THREAD]: [TOOLJET_RESOURCE.APP],
  [TOOLJET_RESOURCE.COMMENT]: [TOOLJET_RESOURCE.APP],
};

export const ADMIN_LEVEL_RESOURCES = [
  TOOLJET_RESOURCE.USER,
  TOOLJET_RESOURCE.GLOBAL_DATA_SOURCE,
  TOOLJET_RESOURCE.COMMENT,
];
