export enum DataBaseConstraints {
  FOLDER_NAME_UNIQUE = 'folder_name_organization_id_unique',
  APP_NAME_UNIQUE = 'app_name_organization_id_unique',
  APP_SLUG_UNIQUE = 'UQ_35eef0fb1f3f2b435b8b6d82ba0',
  WORKSPACE_NAME_UNIQUE = 'name_organizations_unique',
  WORKSPACE_SLUG_UNIQUE = 'slug_organizations_unique',
  USER_ORGANIZATION_UNIQUE = 'user_organization_unique',
  APP_VERSION_NAME_UNIQUE = 'name_app_id_app_versions_unique',
  APP_VERSION_SLUG_BRANCH_UNIQUE = 'app_versions_slug_branch_id_unique',
  APP_VERSION_APP_NAME_BRANCH_UNIQUE = 'app_versions_app_name_branch_id_unique',
  APP_VERSION_SLUG_DEFAULT_BRANCH_UNIQUE = 'app_versions_slug_default_branch_unique',
  APP_VERSION_APP_DEFAULT_BRANCH_DRAFT_UNIQUE = 'app_versions_app_default_branch_draft_unique',
  CONFIG_SCOPE_ORGANIZATION_SSO_UNIQUE = 'config_scope_organization_sso_unique',
  CONFIG_SCOPE_INSTANCE_SSO_UNIQUE = 'config_scope_sso_unique',
  GROUP_NAME_UNIQUE = 'group_name_organization_id_unique',
  GROUP_USER_UNIQUE = 'user_group_unique',
  GRANULAR_PERMISSIONS_NAME_UNIQUE = 'granular_permissions_name_unique',
  DATA_SOURCE_VERSION_DEFAULT_NAME_ORG_UNIQUE = 'data_source_version_default_name_organization_id_unique',
}
