export enum INSTANCE_SETTINGS_TYPE {
  USER = 'user',
  SYSTEM = 'system',
}

export enum INSTANCE_SYSTEM_SETTINGS {
  WHITE_LABEL_LOGO = 'WHITE_LABEL_LOGO',
  WHITE_LABEL_TEXT = 'WHITE_LABEL_TEXT',
  WHITE_LABEL_FAVICON = 'WHITE_LABEL_FAVICON',
  ALLOWED_DOMAINS = 'ALLOWED_DOMAINS',
  ENABLE_SIGNUP = 'ENABLE_SIGNUP',
  ENABLE_WORKSPACE_LOGIN_CONFIGURATION = 'ENABLE_WORKSPACE_LOGIN_CONFIGURATION',
}

export enum INSTANCE_USER_SETTINGS {
  ALLOW_PERSONAL_WORKSPACE = 'ALLOW_PERSONAL_WORKSPACE',
  ENABLE_MULTIPLAYER_EDITING = 'ENABLE_MULTIPLAYER_EDITING',
  ENABLE_COMMENTS = 'ENABLE_COMMENTS',
}

export const defaultWhiteLabellingSettings = {
  WHITE_LABEL_LOGO: 'https://uploads-ssl.webflow.com/6266634263b9179f76b2236e/62666392f32677b5cb2fb84b_logo.svg',
  WHITE_LABEL_TEXT: 'ToolJet',
  WHITE_LABEL_LOGO_URL: 'https://app.tooljet.com/logo.svg',
};
