import { FEATURE_KEY } from './index';
import { MODULES } from '@modules/app/constants/modules';
import { FeaturesConfig } from '../types';

export const FEATURES: FeaturesConfig = {
  [MODULES.WORKFLOWS]: {
    [FEATURE_KEY.EXECUTE_WORKFLOW]: {},
    [FEATURE_KEY.WORKFLOW_EXECUTION_STATUS]: {},
    [FEATURE_KEY.WORKFLOW_EXECUTION_DETAILS]: {}, //Basic plan users can access worfklows
    [FEATURE_KEY.LIST_WORKFLOW_EXECUTIONS]: {},
    [FEATURE_KEY.PREVIEW_QUERY_NODE]: {},

    [FEATURE_KEY.CREATE_WORKFLOW_SCHEDULE]: {},
    [FEATURE_KEY.LIST_WORKFLOW_SCHEDULES]: {},
    [FEATURE_KEY.FIND_WORKFLOW_SCHEDULE]: {},
    [FEATURE_KEY.UPDATE_SCHEDULED_WORKFLOW]: {},
    [FEATURE_KEY.ACTIVATE_SCHEDULED_WORKFLOW]: {},
    [FEATURE_KEY.REMOVE_SCHEDULED_WORKFLOW]: {},

    [FEATURE_KEY.WEBHOOK_TRIGGER_WORKFLOW]: {},
    [FEATURE_KEY.UPDATE_WORKFLOW_WEBHOOK_DETAILS]: {},

    [FEATURE_KEY.CREATE_WORKFLOW]: {},
  },
};
