import { FEATURE_KEY } from './index';
import { MODULES } from '@modules/app/constants/modules';
import { LICENSE_FIELD } from '@modules/licensing/constants';
import { FeaturesConfig } from '../types';

export const FEATURES: FeaturesConfig = {
  [MODULES.WORKFLOWS]: {
    [FEATURE_KEY.EXECUTE_WORKFLOW]: { license: LICENSE_FIELD.VALID },
    [FEATURE_KEY.WORKFLOW_EXECUTION_STATUS]: { license: LICENSE_FIELD.VALID },
    [FEATURE_KEY.WORKFLOW_EXECUTION_DETAILS]: { license: LICENSE_FIELD.VALID },
    [FEATURE_KEY.LIST_WORKFLOW_EXECUTIONS]: { license: LICENSE_FIELD.VALID },
    [FEATURE_KEY.PREVIEW_QUERY_NODE]: { license: LICENSE_FIELD.VALID },

    [FEATURE_KEY.CREATE_WORKFLOW_SCHEDULE]: { license: LICENSE_FIELD.VALID },
    [FEATURE_KEY.LIST_WORKFLOW_SCHEDULES]: { license: LICENSE_FIELD.VALID },
    [FEATURE_KEY.FIND_WORKFLOW_SCHEDULE]: { license: LICENSE_FIELD.VALID },
    [FEATURE_KEY.UPDATE_SCHEDULED_WORKFLOW]: { license: LICENSE_FIELD.VALID },
    [FEATURE_KEY.ACTIVATE_SCHEDULED_WORKFLOW]: { license: LICENSE_FIELD.VALID },
    [FEATURE_KEY.REMOVE_SCHEDULED_WORKFLOW]: { license: LICENSE_FIELD.VALID },

    [FEATURE_KEY.WEBHOOK_TRIGGER_WORKFLOW]: { license: LICENSE_FIELD.VALID },
    [FEATURE_KEY.UPDATE_WORKFLOW_WEBHOOK_DETAILS]: { license: LICENSE_FIELD.VALID },

    [FEATURE_KEY.CREATE_WORKFLOW]: { license: LICENSE_FIELD.VALID },
  },
};
