export const profileSelector = {
  profileDropdown: "[data-cy=dropdown-menu]",
  profileLink: "[data-cy=profile-link]",
  logoutLink: "[data-cy=logout-link]",
  profileElements: {
    pageTitle: '[data-cy="dashboard-section-header"]',
    profileCard: "[data-cy=card-title-profile]",
    firstNameLabel: "[data-cy=first-name-label]",
    emailLabel: "[data-cy=email-label]",
    avatarLabel: '[data-cy="avatar-label"]',
    passwordCard: "[data-cy=card-title-change-password]",
    currentPasswordLabel: "[data-cy=current-password-label]",
    newPasswordLabel: "[data-cy=new-password-label]",
    confirmPasswordLabel: '[data-cy="confirm-password-label"]',
  },
  userNameInput: '[data-cy="name-input-field"]',
  emailInput: "[data-cy=email-input]",
  avatarUploadField: '[data-cy="avatar-upload-field"]',
  updateButton: "[data-cy=update-button]",
  changePasswordButton: "[data-cy=change-password-button]",
  currentPasswordField: "[data-cy=current-password-input]",
  newPasswordField: "[data-cy=new-password-input]",
  confirmPasswordField: '[data-cy="confirm-password-input"]',
};
