export const buttonText={
    widgetName: "Button",
    buttonProperties: "Properties",
    buttonStyles: "Styles",
    buttonName: "button1",
    propertiesElements:{
        propertiesAccordion: "Properties",
        buttonTextLabel: "Button Text",
        buttonTextInput: "Button",
        loadingState: "Loading State",
        eventsAccordion: "Events",
        addEventListner: "+ Add event handler",
        noEventHandler: "This button doesn't have any event handlers",
        layoutAccordion: "Layout",
        showOnDesktopLabel: "Show on desktop",
        showOnMobileLabel: "Show on mobile",
        documentationLink: "Button documentation",
    },
    fxButton:"Fx",
    savedToast: "Saved!",
    invalidButtonName: "New Button",
    buttonNameErrToast: "Invalid widget name. Should be unique and only include letters, numbers and underscore.",
    validButtonName: "button",
    buttonText:"Send",
    trueText: "true",
    falseText:"false",
    eventLabel: "Event",
    actionLabel: "Action",
    actionOption: "Action options",
    messageLabel: "Message",
    alertTypeLabel: "Alert Type",
    newMessage: " new toast",
    newToast: "Hello world new toast",
    stylesElements:{
        backgroundColorLabel: "Background color",
        textColorLabel: "Text color",
        loaderColorLabel: "Loader color",
        visibilityLabel: "Visibility",
        disableLabel: "Disable",
        borderRadiusLabel: "Border radius",
    },
    backgroundColorInput: "#375FCF",
    textColorInput: "#fff",
    loaderColorInput: "#fff",
    borderRadiusInput: "15",
};