export const usersText = {
 usersElements:{
  pageTitle: "Users & Permissions",
  nameTitile: "Name",
  emailTitle: "Email",
  statusTitle: "Status",
  userName: "The Developer",
  userEmail: "dev@tooljet.io",
  userStatus: "active",
  userState: "Archive",
 },
 inviteUserButton:"Invite new user",
 cardTitle: "Add new user",
 emailLabel: "Email address",
 cancelButton: "Cancel",
 createUserButton: "Create User",
 fieldRequired: "This field is required",
 exsitingEmail: "User with such email already exists.",
 inviteCopiedToast: "Invitation URL copied",
 confirmInviteElements:{
  cardTitle: "Already have an account?",
  acceptInvite: "Accept invite",
  orOption: "OR",
  setupHeading: "Set up your account",
  passwordLabel: "Password",
  confirmpasswordLabel: "Confirm Password",
  termsInfo: "By clicking the button below, you agree to our Terms and Conditions.",
 },
 finishSetup: "Finish account setup and accept invite",
 password: "password",
 mismatchPassword: "newpassword",
 passwordErrToast:"Password shouldn't be empty or contain white space(s)",
 passwordMismatchToast: "Passwords don't match",
 passwordSuccessToast: "Added to the workspace and password has been set successfully.",
 createAppPermissionToast: "You do not have permissions to perform this action",
 activeStatus: "active",
 archivedStatus: "archived",
 invitedStatus: "invited",
 archivedToast: "The user has been archived"
}