export const usersText = {
  usersElements:{
    pageTitle: "Users & Permissions",
    nameTitile: "Name",
    emailTitle: "Email",
    statusTitle: "Status",
    userName: "The Developer",
    userEmail: "dev@tooljet.io",
    userStatus: "active",
    userState: "Archive",
  },
  inviteUserButton:"Invite new user",
  cardTitle: "Add new user",
  emailLabel: "Email address",
  cancelButton: "Cancel",
  createUserButton: "Create User",
  fieldRequired: "This field is required",
  exsitingEmail: "User with such email already exists.",
  inviteCopiedToast: "Invitation URL copied",
  confirmInviteElements:{
    cardTitle: "Set up your account",
    firstNameLabel: "First name",
    lastNameLabel: "Last name",
    companyLabel: "Company",
    roleLable: "Role",
    passwordLabel: "Password",
    confirmpasswordLabel: "Confirm Password",
    termsInfo: "By clicking the button below, you agree to our Terms and Conditions.",
  },
  acceptInvite: "Accept invite",
  acceptInviteErrorToast: "User not exist in the workspace, Please setup your account using link shared via email",
  finishSetup: "Finish account setup",
  password: "password",
  mismatchPassword: "newpassword",
  passwordErrToast:"Password shouldn't be empty or contain white space(s)",
  passwordMismatchToast: "Passwords don't match",
  passwordSuccessToast: "Account has been setup successfully.",
  createAppPermissionToast: "You do not have permissions to perform this action",
  activeStatus: "active",
  archivedStatus: "archived",
  invitedStatus: "invited",
  archivedToast: "The user has been archived",
  inviteToast: "Added to the workspace successfully.",
  singleWorkspaceElements:{
    cardTitle: "Set up your account",
    passwordLabel: "Password",
    confirmpasswordLabel: "Confirm Password",
    termsInfo: "By clicking the button below, you agree to our Terms and Conditions.",
  },
  swPasswordSuccessToast: "Added to the workspace and password has been set successfully."

}