export enum FEATURE_KEY {
  GET = 'GET',
  DELETE = 'DELETE',
  CREATE = 'CREATE',
  GET_ONE = 'GET_ONE',
  UPDATE = 'UPDATE',
  UPDATE_SETTINGS = 'UPDATE_SETTINGS',
  PROMOTE = 'PROMOTE',
  CREATE_COMPONENTS = 'CREATE_COMPONENTS',
  UPDATE_COMPONENTS = 'UPDATE_COMPONENTS',
  UPDATE_COMPONENT_LAYOUT = 'UPDATE_COMPONENT_LAYOUT',
  DELETE_COMPONENTS = 'DELETE_COMPONENTS',
  CREATE_PAGES = 'CREATE_PAGES',
  CLONE_PAGES = 'CLONE_PAGES',
  CLONE_GROUP = 'CLONE_GROUP',
  UPDATE_PAGES = 'UPDATE_PAGES',
  DELETE_PAGE = 'DELETE_PAGE',
  REORDER_PAGES = 'REORDER_PAGES',
  GET_EVENTS = 'GET_EVENTS',
  CREATE_EVENT = 'CREATE_EVENT',
  UPDATE_EVENT = 'UPDATE_EVENT',
  DELETE_EVENT = 'DELETE_EVENT',
  APP_VERSION_CREATE = 'APP_VERSION_CREATE',
  APP_VERSION_DELETE = 'APP_VERSION_DELETE',
  APP_VERSION_UPDATE = 'APP_VERSION_UPDATE',
  APP_DRAFT_VERSION_CREATE = 'APP_DRAFT_VERSION_CREATE',
}

/**
 * Audit log action types for module version operations.
 * Used by version/app services to override the default APP_* audit keys
 * when the operation targets a module.
 */
export const MODULE_VERSION_AUDIT_KEYS: Record<string, string> = {
  CREATE: 'MODULE_VERSION_CREATE',
  DELETE: 'MODULE_VERSION_DELETE',
  SAVE: 'MODULE_VERSION_SAVE',
  PROMOTE: 'MODULE_VERSION_PROMOTE',
  RELEASE: 'MODULE_VERSION_RELEASE',
};
