// Per-endpoint feature keys for the git-sync-configs module. Mirrors the DB-only
// subset of the legacy GitSync module's FEATURE_KEY enum so existing ability
// definitions can copy these over.
export enum FEATURE_KEY {
  GET_ORGANIZATION_GIT = 'GET_ORGANIZATION_GIT',
  GET_ORGANIZATION_GIT_STATUS = 'GET_ORGANIZATION_GIT_STATUS',
  CREATE_ORGANIZATION_GIT = 'CREATE_ORGANIZATION_GIT',
  UPDATE_PROVIDER_CONFIGS = 'UPDATE_PROVIDER_CONFIGS',
  UPDATE_ORGANIZATION_GIT_STATUS = 'UPDATE_ORGANIZATION_GIT_STATUS',
  DELETE_ORGANIZATION_GIT_CONFIGS = 'DELETE_ORGANIZATION_GIT_CONFIGS',
}
