/**
 * SPEC — Table — variants/number.
 *
 * FOR AI: covers the `number` COLUMN TYPE of the Table widget end to end — type
 * switching, column creation / duplication / deletion, its ONE type-specific
 * property (Decimal Places), the shared column controls, the two style controls
 * it exposes, all four validations it mounts and the rendered cell contract.
 * Source root: frontend/src/AppBuilder/RightSideBar/Inspector/Components/Table/
 * (`columns` is declared bare as `type:'array'` at table.js:44, so NONE of these
 * controls live in the widget config — they live in the ColumnManager).
 *
 * ── WHAT MAKES `number` DIFFERENT ───────────────────────────────────────────
 *   1. it is the ONLY type with `decimalPlaces` (PropertiesTabElements.jsx:367-384),
 *      and that field is unaddressable by data-cy — see F29 below;
 *   2. its <td> discriminator is `has-number` (TableRow.jsx:120) and it does NOT
 *      get `has-textarea`;
 *   3. an EDITABLE number cell renders a real `<input type="number">` plus a
 *      stepper (NumberRenderer.jsx:141-196) rather than text, so its value must
 *      be read with have.value, not have.text;
 *   4. it swaps string/text's Min length + Max length for Min value + Max value
 *      (ValidationProperties.jsx:74-96).
 *
 * ── WHY THE AUTO-GENERATED `phone` COLUMN IS THE SEED ───────────────────────
 * The shipped `columns` default declares a number column keyed `mobile_number`
 * (table.js:768) — but the shipped dataset has no such key; row 0 carries
 * `phone: 9876543210` (table.js:692). autoGenerateColumns.js:90-92 keeps an
 * `autogenerated` column only while its key is still present in the data, so
 * `mobile_number` is silently DROPPED; :85-100 then generates a fresh column for
 * the unmatched `phone` key whose columnType is
 * `convertDataTypeToColumnType(typeof 9876543210)` = 'number' (:110-119).
 * The result is a real, data-bound `number` column, already proven to exist at
 * runtime by inspector.cy.js:98 and properties.cy.js:166-170. Driving THAT column
 * means every assertion runs against real seed data; the first it-block asserts
 * the config-vs-data divergence explicitly instead of assuming it. Column
 * creation / duplication / deletion get their own it-blocks, where creation is
 * what is under test, and the Decimal Places block seeds its own decimal dataset
 * (the seed `phone` value is an integer, on which decimalPlaces is a no-op —
 * NumberRenderer.jsx:27-34 returns the value untouched when it has no '.').
 *
 * ── HARNESS (deliberate deviation from the generic facet header contract) ────
 * `waitForDropSettle` DOES NOT EXIST in this repo (repo-wide grep: no
 * definition), and the plain `query-manager-toggle-button` beforeEach leaves the
 * Table too short for its cells to be reachable. This spec reuses the
 * proven-green Table harness shared by basics.cy.js / inspector.cy.js /
 * contexts.cy.js / variants/string.cy.js: viewport → drag → hideTooltip →
 * modifyCanvasSize → close the settings panel → resizeTableWidget →
 * resizeQueryPanel('1') → openEditorSidebar. Exactly ONE cy.dragAndDropWidget
 * per test — cypress-real-dnd establishes its CDP intercept once per AUT load,
 * so a second drag in the same test silently never lands (F27 also notes that
 * cy.dragAndDropWidget clicks `right-sidebar-components-button` itself, so this
 * spec must NOT toggle that panel).
 *
 * ── TWO-NODE WIDGET ─────────────────────────────────────────────────────────
 * The Table renders `draggable-widget-table1` on BOTH the outer RenderWidget
 * wrapper AND its inner <table>, so `openStateFromComponent` / `openNode` /
 * `openAndVerifyNode` throw here (their internal realHover is unscoped). This
 * facet asserts only rendered-canvas + popover DOM, so it needs neither.
 *
 * ── POPOVER LIFECYCLE (load-bearing) ────────────────────────────────────────
 * The column popover is an OverlayTrigger with a CONTROLLED `show`
 * (Table.jsx:536-543) whose rootClose is disabled while any CodeHinter preview
 * popover is open (usePopoverState.js:33-43). A canvas click therefore may NOT
 * close it — every test closes it with `closeColumnPopover(<column>)`, which
 * re-clicks the list item and asserts the popover is gone. It also means
 * openColumnPopover() must never be called while the popover is already open
 * (the same click would toggle it shut).
 *
 * ── PRODUCT BUGS HONOURED HERE (not papered over) ────────────────────────────
 *  F1 (HIGH) no validation control has a usable data-cy — `getValidationList`
 *      writes `dateCy` (ValidationProperties.jsx:75,79,85,91) while every render
 *      branch reads `validation.dataCy` (:179,199,216), so React drops the
 *      attribute. setColumnValidation / verifyColumnValidation select on LABEL
 *      TEXT as the documented workaround.
 *  F18       a duplicated column KEEPS ITS NAME (listItemHelpers.js:45-48 swaps
 *      only the uuid), so two list items — and two rendered <th> — share a
 *      data-cy. Asserted explicitly below.
 *  F19       the column-list data-cy is NOT normalised (Table.jsx:571
 *      interpolates the raw display name), so all helpers use `columnListItem`
 *      rather than the older normalising `tableSelector.columnItem`.
 *  F21       cell colour must be read from `cellContentNode`
 *      (`div:not(:has(div))`), never `cellContent` (`<td> div`). For a READ-ONLY
 *      number cell that resolves to NumberRenderer.jsx:208-218, the single div
 *      that carries the inline `color`. (It is NOT usable once the column is
 *      editable — the editable branch, :141-196, mounts an <input> plus a
 *      two-div `.arror-container`.)
 *  F28 (MED) NEW — `maxValue` cannot see `cellValue`. `_helpers/utils.js:448`
 *      calls `resolveWidgetFieldValue(maxValue, currentState, undefined,
 *      customResolveObjects)` with FOUR arguments against the three-parameter
 *      signature `(prop, _default, customResolveObjects)` declared at :386, so
 *      `customResolveObjects` lands as `undefined` and any `{{cellValue…}}`
 *      max-value expression resolves to undefined — which makes the check
 *      SILENTLY SKIP (`resolvedMaxValue !== undefined` is false). minValue (:438)
 *      and customRule (:459) pass three arguments and behave correctly. The
 *      Max value it-block therefore uses a LITERAL, and says why.
 *  F29 (LOW) NEW — the Decimal Places field has NO data-cy. Every sibling field
 *      in PropertiesTabElements carries a wrapper data-cy (:118, :164, :182,
 *      :201, :220, :296, :312) but the Decimal Places wrapper at :368 has none,
 *      and its CodeHinter is mounted without a paramLabel so the editor itself is
 *      only the non-unique `-input-field`. `tableSelector.columnDecimalPlacesField`
 *      reaches it structurally as the one `.field.mb-2.px-3` without a data-cy.
 *
 * Helpers (all resolved through cypress/support/componentAutomation/type-helper-index.md):
 *   components/table.js — resizeTableWidget, setTableData, openColumnPopover,
 *     closeColumnPopover, switchColumnTab, setColumnType, addColumnOfType,
 *     duplicateColumn, deleteColumn, verifyAndEnterColumnOptionInput,
 *     setColumnCodeField, verifyColumnCodeField, setColumnProperty,
 *     verifyColumnProperty, toggleColumnProperty, toggleColumnFx,
 *     verifyColumnFxAbsent, setColumnColor, verifyColumnColor,
 *     setColumnValidation, verifyColumnValidation, setColumnAlignment,
 *     setPinPosition, verifyCellType, verifyCellValue, verifySingleValueOnTable,
 *     addInputOnTable, verifyInvalidFeedback
 *   appBuilder/properties.js — openEditorSidebar
 *   appBuilder/styles.js — verifyWidgetColorCss
 *   appBuilder/querymanager/queryPanel.js — resizeQueryPanel
 */
import { fake } from "Fixtures/fake";
import { tableSelector } from "Selectors/appBuilder/components/table";
import { tableText } from "Texts/appBuilder/components/table";
import {
  resizeTableWidget,
  setTableData,
  openColumnPopover,
  closeColumnPopover,
  switchColumnTab,
  setColumnType,
  addColumnOfType,
  duplicateColumn,
  deleteColumn,
  verifyAndEnterColumnOptionInput,
  setColumnCodeField,
  verifyColumnCodeField,
  setColumnProperty,
  verifyColumnProperty,
  toggleColumnProperty,
  toggleColumnFx,
  verifyColumnFxAbsent,
  setColumnColor,
  verifyColumnColor,
  setColumnValidation,
  verifyColumnValidation,
  setColumnAlignment,
  setPinPosition,
  verifyCellType,
  verifyCellValue,
  verifySingleValueOnTable,
  addInputOnTable,
  verifyInvalidFeedback,
} from "Support/utils/appBuilder/components/table";
import { openEditorSidebar } from "Support/utils/appBuilder/properties";
import { verifyWidgetColorCss } from "Support/utils/appBuilder/styles";
import { resizeQueryPanel } from "Support/utils/appBuilder/querymanager/queryPanel";

// testIsolation:false — cypress-real-dnd caches its CDP client for the spec run;
// testIsolation's per-test AUT reset leaves that client stale, so 2nd+ test drags
// throw "No dragIntercepted". Keeping the AUT stable across tests keeps the drag
// intercept valid. Each test still re-logs-in + creates its own app in beforeEach,
// so shared browser state is not relied upon.
describe("Table — variants/number column type", { testIsolation: false }, () => {
  const W = tableText.defaultWidgetName; // 'table1'
  const C = tableText.variantNumberColumn; // 'phone' — source: autoGenerateColumns.js:94-100

  beforeEach(() => {
    cy.apiLogin();
    cy.apiCreateApp(`${fake.companyName}-Table-Number-Column`); // dynamic: fake
    cy.openApp();
    cy.viewport(1400, 2200);
    cy.dragAndDropWidget("Table", 250, 100);
    cy.hideTooltip();
    cy.modifyCanvasSize(900, 800);
    cy.get("[data-cy='left-sidebar-settings-button']").click();
    resizeTableWidget(W, 750, 600);
    resizeQueryPanel("1");
    openEditorSidebar(W);
  });

  afterEach(() => {
    cy.apiDeleteApp();
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // COLUMN CREATION / TYPE SWITCH
  // ═══════════════════════════════════════════════════════════════════════════

  it("column type — the data-derived `phone` column ships as `number` and the type can be switched away and back", () => {
    // CONFIG-vs-DATA divergence, asserted rather than assumed: the definition's
    // `mobile_number` column (table.js:768) is autogenerated and its key is absent
    // from the dataset, so autoGenerateColumns.js:90-92 drops it and :85-100
    // generates `phone` in its place (typeof 9876543210 === 'number' → 'number',
    // :110-119).
    cy.get(
      tableSelector.columnListItem(tableText.variantNumberDroppedColumn)
    ).should("not.exist"); // source: autoGenerateColumns.js:90-92
    cy.get(tableSelector.columnListItem(C)).should("have.length", 1); // source: autoGenerateColumns.js:94-100

    // SelectComponent.jsx:51 resolves the raw stored value ('number') back to its
    // option, so the react-select SingleValue renders the option LABEL.
    openColumnPopover(C);
    cy.get(tableSelector.columnPopover)
      .find(tableSelector.columnTypeSelect)
      .should("contain.text", tableText.columnTypeLabel.number); // source: PropertiesTabElements.jsx:126
    // Decimal Places is gated on `columnType === 'number'`, so it is mounted here.
    cy.get(tableSelector.columnPopover).should(
      "contain.text",
      tableText.labelDecimalPlaces
    ); // source: PropertiesTabElements.jsx:367-369
    closeColumnPopover(C);

    // A number cell is discriminated ONLY by its <td> class — every column type
    // shares the `<table>-<header>-row-<i>` data-cy (F9).
    cy.forceClickOnCanvas();
    cy.get(tableSelector.cell(C, 0, W)).scrollIntoView();
    verifyCellType(C, 0, tableText.cellClassByType.number, W); // source: TableRow.jsx:120
    verifyCellValue(C, 0, tableText.variantNumberCellValueRow0, W); // source: table.js:692
    // `has-textarea` belongs to string|text only.
    cy.get(tableSelector.cell(C, 0, W)).should(
      "not.have.class",
      tableText.cellClassByType.string
    ); // source: TableRow.jsx:132

    // Switch to `string`: the renderer swaps, the td class follows it and the
    // number-only property disappears.
    setColumnType(C, tableText.columnTypeValue.string); // source: PropertiesTabElements.jsx:125
    cy.get(tableSelector.columnPopover).should(
      "not.contain.text",
      tableText.labelDecimalPlaces
    ); // source: PropertiesTabElements.jsx:367
    closeColumnPopover(C);
    cy.forceClickOnCanvas();
    verifyCellType(C, 0, tableText.cellClassByType.string, W); // source: TableRow.jsx:132
    cy.get(tableSelector.cell(C, 0, W)).should(
      "not.have.class",
      tableText.cellClassByType.number
    ); // source: TableRow.jsx:120

    // …and back to `number`.
    setColumnType(C, tableText.columnTypeValue.number); // source: PropertiesTabElements.jsx:126
    closeColumnPopover(C);
    cy.forceClickOnCanvas();
    verifyCellType(C, 0, tableText.cellClassByType.number, W); // source: TableRow.jsx:120
    verifyCellValue(C, 0, tableText.variantNumberCellValueRow0, W); // source: table.js:692
  });

  it("column manager — a `number` column can be added, bound to a key and deleted", () => {
    // addColumnOfType sets the TYPE first (so type-specific fields mount), then the
    // name, then the key — the key is what the row data is read from
    // (generateColumnsData.js:163 accessorKey = column.key || column.name).
    addColumnOfType(
      tableText.variantNewNumberColumn,
      tableText.columnTypeValue.number, // source: PropertiesTabElements.jsx:126
      tableText.variantNumberColumnKey // source: table.js:692
    );
    closeColumnPopover(tableText.variantNewNumberColumn);

    cy.forceClickOnCanvas();
    cy.get(tableSelector.columnHeader(tableText.variantNewNumberColumn))
      .scrollIntoView()
      .should("have.text", tableText.variantNewNumberColumn); // source: TableHeader.jsx:153
    // Bound to the seed `phone` key, so it renders the same value as the seed column.
    verifyCellValue(
      tableText.variantNewNumberColumn,
      0,
      tableText.variantNumberCellValueRow0,
      W
    ); // source: table.js:692
    verifyCellType(
      tableText.variantNewNumberColumn,
      0,
      tableText.cellClassByType.number,
      W
    ); // source: TableRow.jsx:120

    // deleteColumn drives the popover header's [title="Delete column"] and asserts
    // BOTH the inspector row and the rendered header are gone.
    deleteColumn(tableText.variantNewNumberColumn); // source: ColumnPopover.jsx:130-138
  });

  it("column manager — duplicating a `number` column keeps its name (F18)", () => {
    addColumnOfType(
      tableText.variantNewNumberColumn,
      tableText.columnTypeValue.number, // source: PropertiesTabElements.jsx:126
      tableText.variantNumberColumnKey // source: table.js:692
    );
    closeColumnPopover(tableText.variantNewNumberColumn);

    // PRODUCT BUG F18 (MED): duplicateWithNewId (shared/utils/listItemHelpers.js:45-48)
    // copies the item verbatim and swaps ONLY the uuid, so the clone keeps the same
    // display name. duplicateColumn already asserts the two colliding list rows; the
    // rendered side collides too, because TableHeader.jsx:153 derives the header
    // data-cy from that same name. Asserting the collision documents the bug instead
    // of hiding it behind a .first().
    duplicateColumn(tableText.variantNewNumberColumn);
    cy.forceClickOnCanvas();
    cy.get(tableSelector.columnHeader(tableText.variantNewNumberColumn)).should(
      "have.length",
      2
    ); // source: listItemHelpers.js:45-48
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // TYPE-SPECIFIC PROPERTY — Decimal Places (PropertiesTabElements.jsx:367-384)
  // ═══════════════════════════════════════════════════════════════════════════

  it("properties — Decimal Places truncates the rendered value and exposes no fx button", () => {
    // The seed `phone` value is an INTEGER and removingExcessDecimalPlaces returns
    // any value without a '.' untouched (NumberRenderer.jsx:27-34), so decimalPlaces
    // has no observable effect on it. Seed a decimal dataset instead:
    // autogenerateColumns ships ON (table.js:712), so the new `amount` key generates
    // its own number column (autoGenerateColumns.js:85-100, :110-119).
    setTableData(tableText.variantNumberDecimalData);
    cy.forceClickOnCanvas();
    cy.get(
      tableSelector.cell(tableText.variantDecimalColumn, 0, W)
    ).scrollIntoView();
    verifyCellType(
      tableText.variantDecimalColumn,
      0,
      tableText.cellClassByType.number,
      W
    ); // source: TableRow.jsx:120
    // Untouched to start with — `decimalPlaces` has no default, so
    // NumberColumnAdapter.jsx:25 resolves it to null and :73 skips the truncation.
    verifyCellValue(
      tableText.variantDecimalColumn,
      0,
      tableText.variantDecimalRawRow0,
      W
    ); // source: NumberRenderer.jsx:73

    openColumnPopover(tableText.variantDecimalColumn);
    // decimalPlaces is a BARE CodeHinter (not ProgramaticallyHandleProperties), so
    // it never renders an FxButton at all — its only "fx" is that the field itself
    // is always a code editor.
    verifyColumnFxAbsent(tableText.labelDecimalPlaces); // source: PropertiesTabElements.jsx:369-382
    // NOT ASSERTED ON THE EDITOR: `decimalPlaces` has no default —
    // initialValue={column?.decimalPlaces} is undefined and `{{2}}` is only the
    // PLACEHOLDER (:371-374). Reading that back through `.cm-line` is unsafe,
    // because CodeMirror 6's placeholder extension renders `.cm-placeholder`
    // INSIDE the first `.cm-line`, so an empty editor's text is the placeholder
    // string rather than ''. The untruncated 3.14159 asserted above is the
    // unambiguous, behavioural proof that no default is applied
    // (NumberColumnAdapter.jsx:25 → null → NumberRenderer.jsx:73 skips).
    // F29: this field is the one Properties-tab control with no data-cy — see the
    // selector's own comment for why `.field.mb-2.px-3:not([data-cy])` isolates it
    // for a `number` column.
    setColumnCodeField(
      tableSelector.columnDecimalPlacesField,
      tableText.variantDecimalPlaces
    ); // source: PropertiesTabElements.jsx:367-384
    closeColumnPopover(tableText.variantDecimalColumn);

    cy.forceClickOnCanvas();
    cy.get(
      tableSelector.cell(tableText.variantDecimalColumn, 0, W)
    ).scrollIntoView();
    // removingExcessDecimalPlaces splits on '.' and slices the fraction to the
    // allowed length, so 3.14159 renders as 3.14.
    verifyCellValue(
      tableText.variantDecimalColumn,
      0,
      tableText.variantDecimalTruncatedRow0,
      W
    ); // source: NumberRenderer.jsx:27-34, :73
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // SHARED PROPERTIES (Properties tab)
  // ═══════════════════════════════════════════════════════════════════════════

  it("properties — Column name renames the rendered column, Key rebinds its data", () => {
    openColumnPopover(C);
    verifyColumnCodeField(tableSelector.columnNameField, C); // source: PropertiesTabElements.jsx:164-181
    verifyColumnCodeField(
      tableSelector.columnKeyField,
      tableText.variantNumberColumnKey
    ); // source: PropertiesTabElements.jsx:182-197

    // Renaming re-keys the rendered header AND every cell data-cy, because both are
    // derived from `columnDef.header` = the resolved column name
    // (generateColumnsData.js:165 → TableHeader.jsx:153 / TableRow.jsx:102-105).
    verifyAndEnterColumnOptionInput(
      tableText.labelColumnName,
      tableText.variantRenamedColumn
    ); // source: PropertiesTabElements.jsx:166
    closeColumnPopover(tableText.variantRenamedColumn);
    cy.forceClickOnCanvas();
    cy.get(tableSelector.columnHeader(tableText.variantRenamedColumn))
      .scrollIntoView()
      .should("have.text", tableText.variantRenamedColumn); // source: TableHeader.jsx:153
    verifyCellValue(
      tableText.variantRenamedColumn,
      0,
      tableText.variantNumberCellValueRow0,
      W
    ); // source: table.js:692
    // The type survives the rename.
    verifyCellType(
      tableText.variantRenamedColumn,
      0,
      tableText.cellClassByType.number,
      W
    ); // source: TableRow.jsx:120

    // The Key is the accessor, so re-pointing it at `id` swaps the rendered value
    // while the header (and therefore the data-cy) stays put.
    openColumnPopover(tableText.variantRenamedColumn);
    verifyAndEnterColumnOptionInput(
      tableText.labelKey,
      tableText.variantNumberAltKey
    ); // source: PropertiesTabElements.jsx:183
    closeColumnPopover(tableText.variantRenamedColumn);
    cy.forceClickOnCanvas();
    verifyCellValue(
      tableText.variantRenamedColumn,
      0,
      tableText.variantNumberAltCellValueRow0,
      W
    ); // source: table.js:692
  });

  it("properties — Transformation rewrites the rendered cell value", () => {
    openColumnPopover(C);
    verifyColumnCodeField(
      tableSelector.columnTransformationField,
      tableText.defaultTransformation
    ); // source: PropertiesTabElements.jsx:205

    // columnSlice.js:99 deliberately DROPS a transformation equal to '{{cellValue}}',
    // so only a real expression reaches transformTableData.js:33, which rewrites the
    // row's value for this key before the renderer ever sees it. `*` is used rather
    // than `/` because clearAndTypeOnCodeMirror's tokenizer
    // (codemirrorCommands.js:29) silently DROPS `/`.
    setColumnCodeField(
      tableSelector.columnTransformationField,
      tableText.variantNumberTransformation
    ); // source: PropertiesTabElements.jsx:200-218
    closeColumnPopover(C);
    cy.forceClickOnCanvas();
    cy.get(tableSelector.cell(C, 0, W)).scrollIntoView();
    verifySingleValueOnTable(C, 0, tableText.variantNumberTransformedRow0); // source: transformTableData.js:33
  });

  it("properties — Visibility (fx) removes the column from the rendered table", () => {
    openColumnPopover(C);
    // `columnVisibility` is rendered by ProgramaticallyHandleProperties, so it is
    // fx-capable: the fx button exists and turning it ON is what mounts the code
    // field (SingleLineCodeEditor.jsx:794-802). fx state for a column is the
    // `fxActiveFields[]` array, not a per-field boolean
    // (ProgramaticallyHandleProperties.jsx:104-147).
    toggleColumnFx(tableText.labelVisibility); // source: PropertiesTabElements.jsx:449-466
    verifyColumnProperty(
      tableText.labelVisibility,
      tableText.variantDefaultColumnVisibility
    ); // source: ProgramaticallyHandleProperties.jsx:22
    setColumnProperty(
      tableText.labelVisibility,
      tableText.variantHiddenColumnVisibility
    ); // source: PropertiesTabElements.jsx:457
    closeColumnPopover(C);

    // generateColumnsData.js:159 returns null for an invisible column, so the whole
    // column — header AND cells — is removed from the rendered table.
    cy.forceClickOnCanvas();
    cy.get(tableSelector.columnHeader(C)).should("not.exist"); // source: generateColumnsData.js:159
    cy.get(tableSelector.cell(C, 0, W)).should("not.exist"); // source: generateColumnsData.js:159
  });

  it("properties — Freeze column pins the rendered cell to the left", () => {
    openColumnPopover(C);
    setPinPosition(tableText.pinLeft); // source: PropertiesTabElements.jsx:76
    closeColumnPopover(C);

    cy.forceClickOnCanvas();
    cy.get(tableSelector.cell(C, 0, W))
      .scrollIntoView()
      .should("have.class", tableText.cellClassPinnedLeft); // source: TableRow.jsx:138
    cy.get(tableSelector.cell(C, 0, W)).should(
      "have.class",
      tableText.cellClassPinned
    ); // source: TableRow.jsx:137
  });

  it("properties — Make editable turns the number cell into a real number input", () => {
    openColumnPopover(C);
    toggleColumnProperty(tableText.labelMakeEditable); // source: PropertiesTabElements.jsx:385-400
    closeColumnPopover(C);

    cy.forceClickOnCanvas();
    cy.get(tableSelector.cell(C, 0, W))
      .scrollIntoView()
      .should("have.class", tableText.cellClassEditable); // source: TableRow.jsx:135

    // NumberRenderer.jsx:141-172 replaces the read-only div with an
    // <input type="number">, so the value is no longer the cell's TEXT.
    cy.get(tableSelector.cellNumberInput(C, 0, W))
      .should("have.attr", "type", "number") // source: NumberRenderer.jsx:146
      .and("have.value", tableText.variantNumberCellValueRow0); // source: table.js:692
    // getInputStep(null) — with no decimalPlaces the step is unconstrained.
    cy.get(tableSelector.cellNumberInput(C, 0, W)).should(
      "have.attr",
      "step",
      tableText.variantNumberDefaultStep
    ); // source: NumberRenderer.jsx:10-22, :157

    // The edit commits on blur (:165-170); addInputOnTable's closing canvas click is
    // what blurs the input.
    addInputOnTable(C, 0, tableText.variantNumberEditedValue, "input"); // source: NumberRenderer.jsx:103-116
    cy.get(tableSelector.cellNumberInput(C, 0, W)).should(
      "have.value",
      tableText.variantNumberEditedValue
    ); // source: NumberRenderer.jsx:113-115
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // TYPE-SPECIFIC STYLES (Styles tab)
  // `number` is in the StylesTabElements type list at :131-144, so it gets exactly
  // Text Alignment (:29-52), Text color (:148-161) and Cell color (:163-176).
  // ═══════════════════════════════════════════════════════════════════════════

  it("styles — Text Alignment moves the rendered cell content", () => {
    openColumnPopover(C);
    switchColumnTab(tableText.columnTabStyles); // source: ColumnPopover.jsx:157
    // The label reads "Text Alignment" for number (it becomes "Alignment" only for
    // boolean / image / rating) — StylesTabElements.jsx:32-34.
    cy.get(tableSelector.columnPopover).should(
      "contain.text",
      tableText.labelTextAlignment
    ); // source: StylesTabElements.jsx:33
    setColumnAlignment(tableText.alignCenter); // source: StylesTabElements.jsx:44
    closeColumnPopover(C);

    cy.forceClickOnCanvas();
    cy.get(tableSelector.cell(C, 0, W))
      .scrollIntoView()
      .should("have.class", tableText.cellClassAlignCenter); // source: TableRow.jsx:114
  });

  it("styles — Text color paints the rendered cell content", () => {
    openColumnPopover(C);
    switchColumnTab(tableText.columnTabStyles); // source: ColumnPopover.jsx:157
    verifyColumnColor(
      tableText.labelTextColor,
      tableText.variantDefaultTextColor
    ); // source: ProgramaticallyHandleProperties.jsx:38
    setColumnColor(tableText.labelTextColor, tableText.variantTextColorRgba); // source: StylesTabElements.jsx:148-161
    closeColumnPopover(C);

    // useTextColor.js:7 falls back to the TABLE-level textColor whenever the column
    // value is falsy or still the '#11181C' default, so only a genuinely overridden
    // column colour can reach the rendered node — which is what this asserts.
    // F21: the READ-ONLY number cell is `<td> > div(color)`, so cellContentNode
    // (div:not(:has(div))) resolves exactly that one div.
    cy.forceClickOnCanvas();
    cy.get(tableSelector.cell(C, 0, W)).scrollIntoView();
    verifyWidgetColorCss(
      tableSelector.cellContentNode(C, 0, W),
      "color",
      tableText.variantTextColorRgba,
      true
    ); // source: NumberRenderer.jsx:212
  });

  it("styles — Cell color paints the rendered cell background", () => {
    openColumnPopover(C);
    switchColumnTab(tableText.columnTabStyles); // source: ColumnPopover.jsx:157
    // The default is the design token var(--cc-surface1-surface); BaseColorSwatches
    // renders the token NAME rather than the raw var (BaseColorSwatches.jsx:153-157).
    verifyColumnColor(tableText.labelCellColor, tableText.colorTokenSurface1); // source: ProgramaticallyHandleProperties.jsx:35
    setColumnColor(tableText.labelCellColor, tableText.variantCellColorRgba); // source: StylesTabElements.jsx:163-176
    closeColumnPopover(C);

    // cellBackgroundColor lands as an inline backgroundColor on the <td> itself.
    cy.forceClickOnCanvas();
    cy.get(tableSelector.cell(C, 0, W)).scrollIntoView();
    verifyWidgetColorCss(
      tableSelector.cell(C, 0, W),
      "background-color",
      tableText.variantCellColorRgba,
      true
    ); // source: TableRow.jsx:81
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // VALIDATIONS — mount ONLY while the column is editable
  // (PropertiesTabElements.jsx:401) and only render feedback in the editable
  // renderer branch (NumberRenderer.jsx:193-195).
  //
  // PRODUCT BUG F1 (HIGH): none of these controls has a usable data-cy —
  // getValidationList declares `dateCy` (ValidationProperties.jsx:75,79,85,91)
  // but the render branches read `validation.dataCy` (:179,199,216), so React
  // drops `data-cy={undefined}`. setColumnValidation / verifyColumnValidation
  // therefore address the field by its <label> text; that workaround is the only
  // reason these it-blocks can exist at all.
  // ═══════════════════════════════════════════════════════════════════════════

  it("validations — the `number` set is Regex / Min value / Max value / Custom rule, and Regex rejects a non-matching value", () => {
    openColumnPopover(C);
    toggleColumnProperty(tableText.labelMakeEditable); // source: PropertiesTabElements.jsx:385-400

    // The whole ordered label set, which is also how the absence of string/text's
    // Min length + Max length is proved (ValidationProperties.jsx:74-96).
    cy.get(tableSelector.columnValidationLabels).should(($labels) => {
      expect(Cypress._.map($labels, (el) => el.innerText.trim())).to.deep.equal(
        tableText.variantNumberValidationLabels
      ); // source: ValidationProperties.jsx:74-96
    });

    setColumnValidation(tableText.labelRegex, tableText.variantNumberRegex); // source: ValidationProperties.jsx:75
    verifyColumnValidation(tableText.labelRegex, tableText.variantNumberRegex); // source: ValidationProperties.jsx:75
    closeColumnPopover(C);

    cy.forceClickOnCanvas();
    cy.get(tableSelector.cell(C, 0, W)).scrollIntoView();
    // String(9876543210) contains no letter, so validateWidget returns the pattern
    // error and NumberRenderer mounts `.invalid-feedback` (:193-195).
    verifyInvalidFeedback(C, 0, tableText.variantNumberRegexError, W); // source: _helpers/utils.js:415
  });

  it("validations — Min value rejects a cell below the bound", () => {
    openColumnPopover(C);
    toggleColumnProperty(tableText.labelMakeEditable); // source: PropertiesTabElements.jsx:385-400
    setColumnValidation(tableText.labelMinValue, tableText.variantMinValue); // source: ValidationProperties.jsx:80
    verifyColumnValidation(tableText.labelMinValue, tableText.variantMinValue); // source: ValidationProperties.jsx:80
    closeColumnPopover(C);

    cy.forceClickOnCanvas();
    cy.get(tableSelector.cell(C, 0, W)).scrollIntoView();
    verifyInvalidFeedback(C, 0, tableText.variantMinValueError, W); // source: _helpers/utils.js:443
  });

  it("validations — Max value rejects a cell above the bound", () => {
    openColumnPopover(C);
    toggleColumnProperty(tableText.labelMakeEditable); // source: PropertiesTabElements.jsx:385-400
    // PRODUCT BUG F28 (MED): the bound MUST be a literal. _helpers/utils.js:448
    // calls resolveWidgetFieldValue(maxValue, currentState, undefined,
    // customResolveObjects) — FOUR arguments against the three-parameter signature
    // at :386 — so customResolveObjects arrives as `undefined` and a
    // `{{cellValue…}}` bound would resolve to undefined, which makes :449 skip the
    // check entirely instead of failing loudly. minValue (:438) and customRule
    // (:459) pass three arguments and do resolve `cellValue`.
    setColumnValidation(tableText.labelMaxValue, tableText.variantMaxValue); // source: ValidationProperties.jsx:86
    verifyColumnValidation(tableText.labelMaxValue, tableText.variantMaxValue); // source: ValidationProperties.jsx:86
    closeColumnPopover(C);

    cy.forceClickOnCanvas();
    cy.get(tableSelector.cell(C, 0, W)).scrollIntoView();
    verifyInvalidFeedback(C, 0, tableText.variantMaxValueError, W); // source: _helpers/utils.js:453
  });

  it("validations — Custom rule renders its message from the real cellValue", () => {
    openColumnPopover(C);
    toggleColumnProperty(tableText.labelMakeEditable); // source: PropertiesTabElements.jsx:385-400
    // A customRule that resolves to a NON-EMPTY STRING is the failure signal and the
    // string itself becomes the message (_helpers/utils.js:457-460). Deriving it from
    // `cellValue` proves the rule is evaluated against the real cell — and, unlike
    // maxValue (F28), customRule really does receive customResolveObjects (:459).
    setColumnValidation(
      tableText.labelCustomRule,
      tableText.variantNumberCustomRule
    ); // source: ValidationProperties.jsx:93
    verifyColumnValidation(
      tableText.labelCustomRule,
      tableText.variantNumberCustomRule
    ); // source: ValidationProperties.jsx:93
    closeColumnPopover(C);

    cy.forceClickOnCanvas();
    cy.get(tableSelector.cell(C, 0, W)).scrollIntoView();
    verifyInvalidFeedback(C, 0, tableText.variantNumberCustomRuleError, W); // source: _helpers/utils.js:459
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // CELL RENDERING CONTRACT
  // ═══════════════════════════════════════════════════════════════════════════

  it("cell rendering — a number cell is `has-number`, and picks up `has-text` once editable", () => {
    cy.forceClickOnCanvas();
    cy.get(tableSelector.cell(C, 0, W)).scrollIntoView();
    verifyCellType(C, 0, tableText.cellClassByType.number, W); // source: TableRow.jsx:120
    // Read-only, so it carries neither the editable marker nor the `text` class.
    cy.get(tableSelector.cell(C, 0, W)).should(
      "not.have.class",
      tableText.cellClassEditable
    ); // source: TableRow.jsx:135
    cy.get(tableSelector.cell(C, 0, W)).should(
      "not.have.class",
      tableText.cellClassEditableText
    ); // source: TableRow.jsx:118
    // horizontalAlignment defaults to 'left' (generateColumnsData.js:179).
    cy.get(tableSelector.cell(C, 0, W)).should(
      "have.class",
      tableText.cellClassAlignLeft
    ); // source: TableRow.jsx:116

    openColumnPopover(C);
    toggleColumnProperty(tableText.labelMakeEditable); // source: PropertiesTabElements.jsx:385-400
    closeColumnPopover(C);
    cy.forceClickOnCanvas();
    cy.get(tableSelector.cell(C, 0, W)).scrollIntoView();

    // SOURCE CONTRADICTION worth reporting: `has-text` is documented (and named) as
    // the `text` column type's discriminator, but TableRow.jsx:118 ORs it with
    // `isEditable` — so an EDITABLE NUMBER column carries `has-text` too. The td
    // class is therefore NOT a reliable type discriminator once editing is enabled;
    // only `has-number` (:120) identifies a number column. Pinned here rather than
    // assumed.
    cy.get(tableSelector.cell(C, 0, W)).should(
      "have.class",
      tableText.cellClassEditableText
    ); // source: TableRow.jsx:118
    verifyCellType(C, 0, tableText.cellClassByType.number, W); // source: TableRow.jsx:120
    verifyCellType(C, 0, tableText.cellClassEditable, W); // source: TableRow.jsx:135
    // Still not a textarea column.
    cy.get(tableSelector.cell(C, 0, W)).should(
      "not.have.class",
      tableText.cellClassByType.string
    ); // source: TableRow.jsx:132
  });
});
