---
name: 📝 Documentation Report
description: Use this template for reporting a documentation issue or submitting a feature request for documentation
title: "[docs]: "
labels: ["documentation"]

body:
- type: markdown
  attributes:
    value: >
      **Thank you for wanting to report a problem with ToolJet documentation!**
        Please fill out your suggestions below.
        
        ⚠ Verify first that your issue is not [already reported on GitHub][issue search].
        **Tip:** If you are seeking community support, please consider [joining Slack community][Slack community].
        
        [Slack community]: https://tooljet.com/slack
        
        [issue search]: ../search?q=is%3Aissue&type=issues
        
- type: textarea
  attributes:
    label: Summary
    description: >
      Explain the problem briefly below, add suggestions to wording or structure.
      
      **HINT:** Did you know the documentation has a `Edit this page` link at the bottom of every doc? Feel free to use it to start a pull request right from the GitHub UI!
    placeholder: >-
      I was reading the ToolJet documentation of Google Sheet data source, and I found the wrong syntax for expected value `{{xyz}}`. The value should be `{{abc}}`.
  validations:
    required: true

- type: dropdown
  attributes:
    label: Issue Type
    description: >
        Please select the type of the issue from the drop-down.
    options:
      - Documentation bug
      - Documentation feature/update
  validations:
    required: true

- type: input
  attributes:
    label: The entire URL of the documentation with the issue
    description: >
      Please provide a link to the documentation entry:
    placeholder: https://docs.tooljet.com/docs/intro
  validations:
    required: false

- type: textarea
  attributes:
    label: Steps to reproduce the issue
    description: >-
      Provide step by step instructions to reproduce the issue
    placeholder: >-
      1. Open docs, 2. Go to Google Sheet datasource, 3. click on right sidebar...
  validations:
    required: false

- type: textarea
  attributes:
    label: Additional Information
    description: >-
      Describe how this improves the documentation, e.g. before/after situation or screenshots.
    placeholder: >-
      When the improvement is applied, it makes it more straightforward to understand X.
  validations:
    required: false
    
- type: dropdown
  attributes:
    label: If the issue is confirmed, would you be willing to submit a pull request?
    options:
      - 'Yes'
      - 'No'
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Code of Conduct
    description: |
      Read the [ToolJet Code of Conduct][CoC] first.
      
      [CoC]: https://docs.tooljet.com/docs/contributing-guide/code-of-conduct
    options:
      - label: I agree to follow the ToolJet Code of Conduct
        required: true
        
- type: markdown
  attributes:
    value: >
      Thank you for your collaboration!

- type: markdown
  attributes:
    value: >
      **Performance Issue Report**
        Please fill out the details below to report a performance issue.
        
- type: textarea
  attributes:
    label: Summary
    description: >
      Provide a brief summary of the performance issue.
    placeholder: >-
      The application experiences significant lag when loading the dashboard.
  validations:
    required: true

- type: textarea
  attributes:
    label: Steps to reproduce the issue
    description: >-
      Provide step by step instructions to reproduce the performance issue.
    placeholder: >-
      1. Open the application, 2. Navigate to the dashboard, 3. Observe the lag...
  validations:
    required: true

- type: textarea
  attributes:
    label: Expected behavior
    description: >-
      Describe what you expected to happen.
    placeholder: >-
      The dashboard should load within 2 seconds.
  validations:
    required: true

- type: textarea
  attributes:
    label: Actual behavior
    description: >-
      Describe what actually happened.
    placeholder: >-
      The dashboard takes more than 10 seconds to load.
  validations:
    required: true

- type: textarea
  attributes:
    label: Additional Information
    description: >-
      Provide any additional information that may help in diagnosing the issue.
    placeholder: >-
      The issue occurs consistently during peak hours.
  validations:
    required: false

- type: markdown
  attributes:
    value: >
      **Security Vulnerability Report**
        Please fill out the details below to report a security vulnerability.
        
- type: textarea
  attributes:
    label: Summary
    description: >
      Provide a brief summary of the security vulnerability.
    placeholder: >-
      The application is vulnerable to SQL injection attacks.
  validations:
    required: true

- type: textarea
  attributes:
    label: Steps to reproduce the issue
    description: >-
      Provide step by step instructions to reproduce the security vulnerability.
    placeholder: >-
      1. Open the application, 2. Navigate to the login page, 3. Enter a malicious SQL query...
  validations:
    required: true

- type: textarea
  attributes:
    label: Expected behavior
    description: >-
      Describe what you expected to happen.
    placeholder: >-
      The application should sanitize user inputs to prevent SQL injection.
  validations:
    required: true

- type: textarea
  attributes:
    label: Actual behavior
    description: >-
      Describe what actually happened.
    placeholder: >-
      The application executes the malicious SQL query.
  validations:
    required: true

- type: textarea
  attributes:
    label: Additional Information
    description: >-
      Provide any additional information that may help in diagnosing the issue.
    placeholder: >-
      The issue occurs consistently when entering certain SQL queries.
  validations:
    required: false
...
