import {
  buttonConfig,
  tableConfig,
  chartConfig,
  modalConfig,
  modalV2Config,
  formConfig,
  textinputConfig,
  numberinputConfig,
  passinputConfig,
  datepickerConfig,
  checkboxConfig,
  radiobuttonConfig,
  radiobuttonV2Config,
  toggleswitchConfig,
  toggleSwitchV2Config,
  textareaConfig,
  daterangepickerConfig,
  textConfig,
  imageConfig,
  containerConfig,
  dropdownConfig,
  dropdownV2Config,
  multiselectConfig,
  multiselectV2Config,
  tagsInputConfig,
  richtextareaConfig,
  mapConfig,
  qrscannerConfig,
  starratingConfig,
  dividerConfig,
  filepickerConfig,
  calendarConfig,
  iframeConfig,
  codeEditorConfig,
  tabsConfig,
  timerConfig,
  listviewConfig,
  tagsConfig,
  paginationConfig,
  circularProgressbarConfig,
  spinnerConfig,
  libraryComponentConfig,
  statisticsConfig,
  rangeSliderConfig,
  timelineConfig,
  svgImageConfig,
  htmlConfig,
  verticalDividerConfig,
  customComponentConfig,
  buttonGroupConfig,
  pdfConfig,
  stepsConfig,
  kanbanConfig,
  colorPickerConfig,
  treeSelectConfig,
  cascaderConfig,
  linkConfig,
  iconConfig,
  boundedBoxConfig,
  kanbanBoardConfig,
  datetimePickerV2Config,
  datePickerV2Config,
  timePickerConfig,
  moduleContainerConfig,
  moduleViewerConfig,
  emailinputConfig,
  phoneinputConfig,
  currencyinputConfig,
  rangeSliderV2Config,
  chatConfig,
  popoverMenuConfig,
  keyValuePairConfig,
  progressbarConfig,
  audioRecorderConfig,
  cameraConfig,
  accordionConfig,
  reorderableListConfig,
  jsonExplorerConfig,
  jsonEditorConfig,
  fileinputConfig,
  navigationConfig,
  fileButtonConfig,
  buttonGroupV2Config,
  flexContainerConfig,
  NEW_REVAMPED_COMPONENTS,
  universalProps,
  legacyUniversalProps,
  combineProperties,
} from '@tooljet/widget-definitions';

const widgets = {
  buttonConfig,
  tableConfig,
  chartConfig,
  modalConfig, //!Depreciated
  modalV2Config,
  formConfig,
  textinputConfig,
  numberinputConfig,
  passinputConfig,
  datepickerConfig, //!Depreciated
  datetimePickerV2Config,
  datePickerV2Config,
  timePickerConfig,
  emailinputConfig,
  phoneinputConfig,
  currencyinputConfig,
  checkboxConfig,
  radiobuttonConfig, //!Depreciated
  radiobuttonV2Config,
  toggleswitchConfig, //!Depreciated
  toggleSwitchV2Config,
  textareaConfig, //! Deprecated
  daterangepickerConfig,
  textConfig,
  imageConfig,
  containerConfig,
  flexContainerConfig,
  dropdownConfig, //!Depreciated
  dropdownV2Config,
  multiselectConfig,
  multiselectV2Config, //!Depreciated
  tagsInputConfig,
  richtextareaConfig,
  mapConfig,
  qrscannerConfig,
  starratingConfig,
  dividerConfig,
  filepickerConfig,
  fileinputConfig,
  calendarConfig,
  iframeConfig,
  codeEditorConfig,
  tabsConfig,
  timerConfig,
  listviewConfig,
  tagsConfig,
  paginationConfig,
  circularProgressbarConfig,
  spinnerConfig,
  libraryComponentConfig,
  statisticsConfig,
  rangeSliderConfig,
  rangeSliderV2Config,
  timelineConfig,
  svgImageConfig,
  htmlConfig,
  verticalDividerConfig,
  customComponentConfig,
  buttonGroupConfig, //!Depreciated
  pdfConfig,
  stepsConfig,
  kanbanConfig,
  kanbanBoardConfig, //!Depreciated
  colorPickerConfig,
  treeSelectConfig,
  cascaderConfig,
  linkConfig,
  iconConfig,
  boundedBoxConfig,
  chatConfig,
  moduleContainerConfig,
  moduleViewerConfig,
  popoverMenuConfig,
  keyValuePairConfig,
  progressbarConfig,
  audioRecorderConfig,
  cameraConfig,
  accordionConfig,
  reorderableListConfig,
  jsonExplorerConfig,
  jsonEditorConfig,
  navigationConfig,
  fileButtonConfig,
  buttonGroupV2Config,
};

const newRevampedComponents = new Set(NEW_REVAMPED_COMPONENTS);

export const componentTypes = Object.values(widgets).map((widget) => {
  const baseProps = newRevampedComponents.has(widget.component) ? universalProps : legacyUniversalProps;
  const combined = {
    ...combineProperties(widget, baseProps),
    definition: combineProperties(
      widget.definition,
      baseProps.definition,
      true,
    ),
  };
  // Mirror of frontend componentTypes.js: LibraryComponent renders an iframe — a CSS
  // class on its wrapper can never reach the content inside; no false affordance.
  if (widget.component === 'LibraryComponent') {
    delete combined.styles.cssClass;
    delete combined.definition.styles.cssClass;
  }
  return combined;
});

export default widgets;
