import {
  buttonConfig,
  tableConfig,
  chartConfig,
  modalConfig,
  modalV2Config,
  formConfig,
  textinputConfig,
  numberinputConfig,
  passinputConfig,
  datepickerConfig,
  checkboxConfig,
  radiobuttonConfig,
  radiobuttonV2Config,
  toggleswitchConfig,
  toggleSwitchV2Config,
  textareaConfig,
  daterangepickerConfig,
  textConfig,
  imageConfig,
  containerConfig,
  dropdownConfig,
  dropdownV2Config,
  multiselectConfig,
  multiselectV2Config,
  tagsInputConfig,
  richtextareaConfig,
  mapConfig,
  qrscannerConfig,
  starratingConfig,
  dividerConfig,
  filepickerConfig,
  calendarConfig,
  iframeConfig,
  codeEditorConfig,
  tabsConfig,
  timerConfig,
  listviewConfig,
  tagsConfig,
  paginationConfig,
  circularProgressbarConfig,
  spinnerConfig,
  statisticsConfig,
  rangeSliderConfig,
  timelineConfig,
  svgImageConfig,
  htmlConfig,
  verticalDividerConfig,
  customComponentConfig,
  buttonGroupConfig,
  pdfConfig,
  stepsConfig,
  kanbanConfig,
  colorPickerConfig,
  treeSelectConfig,
  linkConfig,
  iconConfig,
  boundedBoxConfig,
  kanbanBoardConfig,
  datetimePickerV2Config,
  datePickerV2Config,
  timePickerConfig,
  moduleContainerConfig,
  moduleViewerConfig,
  emailinputConfig,
  phoneinputConfig,
  currencyinputConfig,
  rangeSliderV2Config,
  chatConfig,
  popoverMenuConfig,
  keyValuePairConfig,
  progressbarConfig,
  audioRecorderConfig,
  cameraConfig,
  accordionConfig,
  reorderableListConfig,
  jsonExplorerConfig,
  jsonEditorConfig,
  fileinputConfig,
  navigationConfig,
  fileButtonConfig,
  buttonGroupV2Config,
  flexContainerConfig,
  universalProps,
  combineProperties,
} from '@tooljet/widget-definitions';

const widgets = {
  buttonConfig,
  tableConfig,
  chartConfig,
  modalConfig, //!Depreciated
  modalV2Config,
  formConfig,
  textinputConfig,
  numberinputConfig,
  passinputConfig,
  datepickerConfig, //!Depreciated
  datetimePickerV2Config,
  datePickerV2Config,
  timePickerConfig,
  emailinputConfig,
  phoneinputConfig,
  currencyinputConfig,
  checkboxConfig,
  radiobuttonConfig, //!Depreciated
  radiobuttonV2Config,
  toggleswitchConfig, //!Depreciated
  toggleSwitchV2Config,
  textareaConfig, //! Deprecated
  daterangepickerConfig,
  textConfig,
  imageConfig,
  containerConfig,
  flexContainerConfig,
  dropdownConfig, //!Depreciated
  dropdownV2Config,
  multiselectConfig,
  multiselectV2Config, //!Depreciated
  tagsInputConfig,
  richtextareaConfig,
  mapConfig,
  qrscannerConfig,
  starratingConfig,
  dividerConfig,
  filepickerConfig,
  fileinputConfig,
  calendarConfig,
  iframeConfig,
  codeEditorConfig,
  tabsConfig,
  timerConfig,
  listviewConfig,
  tagsConfig,
  paginationConfig,
  circularProgressbarConfig,
  spinnerConfig,
  statisticsConfig,
  rangeSliderConfig,
  rangeSliderV2Config,
  timelineConfig,
  svgImageConfig,
  htmlConfig,
  verticalDividerConfig,
  customComponentConfig,
  buttonGroupConfig, //!Depreciated
  pdfConfig,
  stepsConfig,
  kanbanConfig,
  kanbanBoardConfig, //!Depreciated
  colorPickerConfig,
  treeSelectConfig,
  linkConfig,
  iconConfig,
  boundedBoxConfig,
  chatConfig,
  moduleContainerConfig,
  moduleViewerConfig,
  popoverMenuConfig,
  keyValuePairConfig,
  progressbarConfig,
  audioRecorderConfig,
  cameraConfig,
  accordionConfig,
  reorderableListConfig,
  jsonExplorerConfig,
  jsonEditorConfig,
  navigationConfig,
  fileButtonConfig,
  buttonGroupV2Config,
};

export const componentTypes = Object.values(widgets).map((widget) => {
  return {
    ...combineProperties(widget, universalProps),
    definition: combineProperties(widget.definition, universalProps.definition, true),
  };
});

export default widgets;
