export enum FEATURE_KEY {
  CREATE_LIBRARY = 'CREATE_LIBRARY',
  GET_LIBRARY = 'GET_LIBRARY',
  DELETE_LIBRARY = 'DELETE_LIBRARY',
  LIST_LIBRARIES = 'LIST_LIBRARIES',
  VALIDATE_TOKEN = 'VALIDATE_TOKEN',
  UPLOAD_DEV_BUNDLE = 'UPLOAD_DEV_BUNDLE',
  PUBLISH_REVISION = 'PUBLISH_REVISION',
  SERVE_BUNDLE = 'SERVE_BUNDLE',
  CREATE_CLI_TOKEN = 'CREATE_CLI_TOKEN',
  LIST_CLI_TOKENS = 'LIST_CLI_TOKENS',
  DELETE_CLI_TOKEN = 'DELETE_CLI_TOKEN',
}
