export enum FEATURE_KEY {
  CREATE_LIBRARY = 'CREATE_LIBRARY',
  FIND_OR_CREATE_LIBRARY = 'FIND_OR_CREATE_LIBRARY',
  GET_LIBRARY = 'GET_LIBRARY',
  DELETE_LIBRARY = 'DELETE_LIBRARY',
  LIST_LIBRARIES = 'LIST_LIBRARIES',
  UPLOAD_DEV_BUNDLE = 'UPLOAD_DEV_BUNDLE',
  STREAM_DEV_BUNDLE = 'STREAM_DEV_BUNDLE',
  PUBLISH_REVISION = 'PUBLISH_REVISION',
  SERVE_BUNDLE = 'SERVE_BUNDLE',
}
