export const countries = Object.entries({
  af: 'Afghanistan',
  al: 'Albania',
  dz: 'Algeria',
  um: 'United States Minor Outlying Islands',
  ad: 'Andorra',
  ao: 'Angola',
  ai: 'Anguilla',
  aq: 'Antarctica',
  ag: 'Antigua and Barbuda',
  sa: 'Saudi Arabia',
  ar: 'Argentina',
  am: 'Armenia',
  aw: 'Aruba',
  au: 'Australia',
  at: 'Austria',
  az: 'Azerbaijan',
  bs: 'Bahamas',
  bh: 'Bahrain',
  bd: 'Bangladesh',
  bb: 'Barbados',
  be: 'Belgium',
  bz: 'Belize',
  bj: 'Benin',
  bm: 'Bermuda',
  bt: 'Bhutan',
  by: 'Belarus',
  bo: 'Bolivia',
  ba: 'Bosnia and Herzegovina',
  bw: 'Botswana',
  br: 'Brazil',
  bn: 'Brunei',
  bg: 'Bulgaria',
  bf: 'Burkina Faso',
  bi: 'Burundi',
  kh: 'Cambodia',
  cm: 'Cameroon',
  ca: 'Canada',
  cv: 'Cape Verde',
  bq: 'Caribbean Netherlands',
  cz: 'Czechia',
  ea: 'Ceuta and Melilla',
  td: 'Chad',
  cl: 'Chile',
  cn: 'China',
  cy: 'Cyprus',
  va: 'Vatican City',
  co: 'Colombia',
  km: 'Comoros',
  cd: 'Congo - Kinshasa',
  cg: 'Congo - Brazzaville',
  kp: 'North Korea',
  kr: 'South Korea',
  ci: 'Ivory Coast',
  cr: 'Costa Rica',
  hr: 'Croatia',
  cu: 'Cuba',
  cw: 'Curaçao',
  dk: 'Denmark',
  dg: 'Diego Garcia',
  dm: 'Dominica',
  ec: 'Ecuador',
  eg: 'Egypt',
  sv: 'El Salvador',
  ae: 'United Arab Emirates',
  er: 'Eritrea',
  ee: 'Estonia',
  et: 'Ethiopia',
  fj: 'Fiji',
  ph: 'Philippines',
  fi: 'Finland',
  fr: 'France',
  ga: 'Gabon',
  gm: 'Gambia',
  ge: 'Georgia',
  gs: 'South Georgia and the South Sandwich Islands',
  de: 'Germany',
  gh: 'Ghana',
  jm: 'Jamaica',
  jp: 'Japan',
  gi: 'Gibraltar',
  dj: 'Djibouti',
  jo: 'Jordan',
  gr: 'Greece',
  gd: 'Grenada',
  gl: 'Greenland',
  gp: 'Guadeloupe',
  gu: 'Guam',
  gt: 'Guatemala',
  gg: 'Guernsey',
  gn: 'Guinea',
  gq: 'Equatorial Guinea',
  gw: 'Guinea-Bissau',
  gy: 'Guyana',
  gf: 'French Guiana',
  ht: 'Haiti',
  hn: 'Honduras',
  in: 'India',
  id: 'Indonesia',
  ir: 'Iran',
  iq: 'Iraq',
  ie: 'Ireland',
  is: 'Iceland',
  ac: 'Ascension Island',
  cx: 'Christmas Island',
  im: 'Isle of Man',
  nf: 'Norfolk Island',
  ax: 'Åland Islands',
  ic: 'Canary Islands',
  ky: 'Cayman Islands',
  cc: 'Cocos (Keeling) Islands',
  ck: 'Cook Islands',
  fo: 'Faroe Islands',
  fk: 'Falkland Islands',
  mp: 'Northern Mariana Islands',
  mh: 'Marshall Islands',
  pn: 'Pitcairn Islands',
  sb: 'Solomon Islands',
  tc: 'Turks and Caicos Islands',
  vi: 'U.S. Virgin Islands',
  vg: 'British Virgin Islands',
  il: 'Israel',
  it: 'Italy',
  je: 'Jersey',
  kz: 'Kazakhstan',
  ke: 'Kenya',
  kg: 'Kyrgyzstan',
  ki: 'Kiribati',
  xk: 'Kosovo',
  kw: 'Kuwait',
  la: 'Laos',
  ls: 'Lesotho',
  lv: 'Latvia',
  lb: 'Lebanon',
  lr: 'Liberia',
  ly: 'Libya',
  li: 'Liechtenstein',
  lt: 'Lithuania',
  lu: 'Luxembourg',
  mk: 'North Macedonia',
  mg: 'Madagascar',
  mw: 'Malawi',
  my: 'Malaysia',
  mv: 'Maldives',
  ml: 'Mali',
  mt: 'Malta',
  ma: 'Morocco',
  mq: 'Martinique',
  mr: 'Mauritania',
  mu: 'Mauritius',
  yt: 'Mayotte',
  mx: 'Mexico',
  fm: 'Micronesia',
  md: 'Moldova',
  mc: 'Monaco',
  mn: 'Mongolia',
  me: 'Montenegro',
  ms: 'Montserrat',
  mz: 'Mozambique',
  mm: 'Myanmar',
  na: 'Namibia',
  nr: 'Nauru',
  np: 'Nepal',
  ni: 'Nicaragua',
  ne: 'Niger',
  ng: 'Nigeria',
  nu: 'Niue',
  no: 'Norway',
  nc: 'New Caledonia',
  nz: 'New Zealand',
  om: 'Oman',
  nl: 'Netherlands',
  pk: 'Pakistan',
  pw: 'Palau',
  pa: 'Panama',
  pg: 'Papua New Guinea',
  py: 'Paraguay',
  pe: 'Peru',
  pf: 'French Polynesia',
  pl: 'Poland',
  pt: 'Portugal',
  pr: 'Puerto Rico',
  qa: 'Qatar',
  hk: 'Hong Kong SAR',
  mo: 'Macau SAR',
  gb: 'United Kingdom',
  cf: 'Central African Republic',
  do: 'Dominican Republic',
  re: 'Réunion',
  ro: 'Romania',
  rw: 'Rwanda',
  ru: 'Russia',
  eh: 'Western Sahara',
  kn: 'Saint Kitts and Nevis',
  lc: 'Saint Lucia',
  mf: 'Saint Martin',
  vc: 'Saint Vincent and the Grenadines',
  bl: 'Saint Barthélemy',
  pm: 'Saint Pierre and Miquelon',
  ws: 'Samoa',
  as: 'American Samoa',
  sm: 'San Marino',
  sh: 'Saint Helena',
  st: 'São Tomé and Príncipe',
  sn: 'Senegal',
  rs: 'Serbia',
  sc: 'Seychelles',
  sl: 'Sierra Leone',
  sg: 'Singapore',
  sx: 'Sint Maarten',
  sy: 'Syria',
  sk: 'Slovakia',
  si: 'Slovenia',
  so: 'Somalia',
  es: 'Spain',
  lk: 'Sri Lanka',
  us: 'United States',
  ss: 'South Sudan',
  za: 'South Africa',
  sd: 'Sudan',
  sr: 'Suriname',
  se: 'Sweden',
  ch: 'Switzerland',
  tj: 'Tajikistan',
  th: 'Thailand',
  tl: 'Timor-Leste',
  tg: 'Togo',
  tn: 'Tunisia',
  tr: 'Turkey',
  ua: 'Ukraine',
  ug: 'Uganda',
  hu: 'Hungary',
  uy: 'Uruguay',
  uz: 'Uzbekistan',
  vn: 'Vietnam',
  ye: 'Yemen',
  zm: 'Zambia',
  zw: 'Zimbabwe',
}).map(([value, label]) => ({ value, label }));
