export enum FEATURE_KEY {
  GET = 'GET',
  UPDATE = 'UPDATE',
  VALIDATE = 'VALIDATE',
  ACQUIRE_CERTIFICATE = 'ACQUIRE_CERTIFICATE',
  CERTIFICATE_STATUS = 'CERTIFICATE_STATUS',
  RENEW_CERTIFICATE = 'RENEW_CERTIFICATE',
  REQUEST_DOMAIN_CHANGE = 'REQUEST_DOMAIN_CHANGE',
  CANCEL_DOMAIN_CHANGE = 'CANCEL_DOMAIN_CHANGE',
}
