/**
 * `autoGenerateFields`: which fields are generated from `data`, which are kept,
 * and which are dropped, per the approved contract
 * (frontend/ee/test/app-builder/widgets/KeyValuePair/TESTING.md).
 *
 * Pure function, no store/DOM — a direct import is the approved public seam.
 * Test titles carry their approved scenario ID as a `[KeyValuePair-FAMILY-NNN]`
 * prefix, per the widget-testing-contract validator.
 */
import autoGenerateFields from '../autoGenerateFields';

describe('autoGenerateFields', () => {
  test('[KeyValuePair-AUTOGEN-001] generates a new field with inferred type and a humanized name for every new data key', () => {
    const fields = autoGenerateFields({ first_name: 'Ada', age: 36 }, [], [], false, []);

    const byKey = Object.fromEntries(fields.map((field) => [field.key, field]));
    // formatFieldName only capitalizes the leading character, not every word.
    expect(byKey.first_name).toMatchObject({
      name: 'First name',
      key: 'first_name',
      fieldType: 'string',
      autogenerated: true,
    });
    expect(byKey.age).toMatchObject({ name: 'Age', key: 'age', fieldType: 'number', autogenerated: true });
    expect(fields).toHaveLength(2);
  });

  test('[KeyValuePair-AUTOGEN-002] never regenerates a key that is present in fieldDeletionHistory', () => {
    // Break this catches: dropping the `fieldDeletionHistory` filter (or
    // checking it against the wrong array) resurrects a field an app author
    // deliberately deleted, the moment its key still exists in `data`.
    const fields = autoGenerateFields({ name: 'Ada', email: 'ada@example.com' }, [], ['email'], false, []);

    expect(fields.map((f) => f.key)).toEqual(['name']);
  });

  test('[KeyValuePair-AUTOGEN-003] keeps a user-created (non-autogenerated) field even when its key is absent from data', () => {
    const userField = { id: 'u1', key: 'note', name: 'Note', fieldType: 'string', autogenerated: false };

    const fields = autoGenerateFields({}, [userField], [], false, []);

    expect(fields).toEqual([userField]);
  });

  test('[KeyValuePair-AUTOGEN-004] drops an autogenerated field once its data key disappears', () => {
    const staleField = { id: 'g1', key: 'gone', name: 'Gone', fieldType: 'string', autogenerated: true };

    const fields = autoGenerateFields({ name: 'Ada' }, [staleField], [], false, []);

    expect(fields.map((f) => f.key)).toEqual(['name']);
  });

  test('[KeyValuePair-AUTOGEN-005] infers boolean, number, array-as-string, and default-to-string', () => {
    const fields = autoGenerateFields({ isActive: true, count: 3, tags: ['a', 'b'], label: 'x' }, [], [], false, []);
    const typeOf = (key) => fields.find((f) => f.key === key).fieldType;

    expect(typeOf('isActive')).toBe('boolean');
    expect(typeOf('count')).toBe('number');
    // Current behavior: arrays are inferred as 'string', not 'newMultiSelect'.
    expect(typeOf('tags')).toBe('string');
    expect(typeOf('label')).toBe('string');
  });

  test('[KeyValuePair-AUTOGEN-009] ignores fieldDeletionHistory entirely when useDynamicField is true', () => {
    // Break this catches: moving the `useDynamicField` early-return below the
    // deletion-history filter would let static-mode deletions suppress fields
    // an author explicitly configured for dynamic mode.
    const fields = autoGenerateFields({}, [], ['email'], true, [{ name: 'Email', key: 'email' }]);

    expect(fields.map((f) => f.key)).toEqual(['email']);
  });
});
