export const GIT_ENV_KEYS = {
  HTTPS: {
    URL: 'GITHUB_URL',
    BRANCH: 'GITHUB_BRANCH',
    APP_ID: 'GITHUB_APP_ID',
    INSTALLATION_ID: 'GITHUB_INSTALLATION_ID',
    PRIVATE_KEY: 'GITHUB_PRIVATE_KEY',
    ENTERPRISE_URL: 'GITHUB_ENTERPRISE_URL', // optional
    ENTERPRISE_API_URL: 'GITHUB_ENTERPRISE_API_URL', // optional
  },
  SSH: {
    GIT_URL: 'GIT_SSH_URL',
    BRANCH: 'GIT_SSH_BRANCH',
    PRIVATE_KEY: 'GIT_SSH_PRIVATE_KEY',
    PUBLIC_KEY: 'GIT_SSH_PUBLIC_KEY',
    KEY_TYPE: 'GIT_SSH_KEY_TYPE',
  },
  GITLAB: {
    URL: 'GITLAB_URL',
    BRANCH: 'GITLAB_BRANCH',
    PROJECT_ID: 'GITLAB_PROJECT_ID',
    PROJECT_ACCESS_TOKEN: 'GITLAB_PROJECT_ACCESS_TOKEN',
    ENTERPRISE_URL: 'GITLAB_ENTERPRISE_URL',
  },
} as const;

export const REQUIRED_KEYS = {
  HTTPS: [
    GIT_ENV_KEYS.HTTPS.URL,
    GIT_ENV_KEYS.HTTPS.BRANCH,
    GIT_ENV_KEYS.HTTPS.APP_ID,
    GIT_ENV_KEYS.HTTPS.INSTALLATION_ID,
    GIT_ENV_KEYS.HTTPS.PRIVATE_KEY,
  ],
  SSH: Object.values(GIT_ENV_KEYS.SSH),
  GITLAB: [GIT_ENV_KEYS.GITLAB.URL, GIT_ENV_KEYS.GITLAB.BRANCH, GIT_ENV_KEYS.GITLAB.PROJECT_ID],
} as const;
