export const instanceWorkspaceSelectors = {
  breadcrumbPageTitle: '[data-cy="breadcrumb-page-title"]',
  navAllWorkspaces: '[data-cy="all-workspaces-list-item"]',
  tabActive: '[data-cy="active-link"]',
  tabArchived: '[data-cy="archived-link"]',
  searchBar: '[data-cy="query-manager-search-bar"]',
  nameHeader: '[data-cy="name-header"]',
  workspaceRowContainer: '.mx-3.tj-text-sm.d-flex.align-items-center',
  defaultWorkspaceTag: '.default-workspace-tag',
  workspaceTableRow: 'tr.workspace-table-row',
  workspaceNameCellSuffix: '[data-cy$="-workspace"]',
  statusChangeButton: '[data-cy="button-ws-status-change"]',
  confirmButton: '[data-cy="confirm-button"]',
  continueButton: '[data-cy="continue-button"]',
  tooltipDefaultWorkspace: '[data-tooltip-id="default-workspace-tooltip"]',
  selectControl: '.tj-select .react-select__control',
  selectMenu: '.react-select__menu',
  selectOption: '.react-select__option',
  noResultFoundText: '[data-cy="text-no-result-found"]',
  acceptInviteButton: '[data-cy="accept-invite-button"]',
  shareButtonLink: '[data-cy="share-button-link"]',
  appSlugInput: '[data-cy="app-name-slug-input"]',
  makePublicToggle: '[data-cy="make-public-app-toggle"]',
  modalCloseButton: '[data-cy="modal-close-button"]',
};