export const licenseSelectors = {
    licenseOption: '[data-cy="license-list-item"]',
    licenseKeyOption: '[data-cy="license-key-list-item"]',
    limitOption: '[data-cy="limits-list-item"]',
    accessOption: '[data-cy="access-list-item"]',
    domainOption: '[data-cy="domain-list-item"]',
    licenseKeyTitle: '[data-cy="licenseKey-tab-title"]',
    licenseLabel: '[data-cy="license-label"]',
    updateButton: '[data-cy="update-button"]',
    limitsTabTitle: '[data-cy="limits-tab-title"]',
    appsTab: '[data-cy="apps-sub-tab"]',
    noOfAppsLabel: '[data-cy="number-of-apps-label"]',
    noOfAppsfield: '[data-cy="apps-field"]',
    workspaceTab: '[data-cy="workspaces-sub-tab"]',
    noOfworkspaceLabel: '[data-cy="number-of-workspaces-label"]',
    noOfWorkspacefield: '[data-cy="workspaces-field"]',
    usersTab: '[data-cy="users-sub-tab"]',
    noOfTotalUsersLabel: '[data-cy="number-of-total-users-label"]',
    noOfTotalUsersfield: '[data-cy="total-users-field"]',
    noOfBuildersLabel: '[data-cy="number-of-builders-label"]',
    noOfBuildersfield: '[data-cy="builders-field"]',
    noOfEndUsersLabel: '[data-cy="number-of-end-users-label"]',
    noOfEndUsersfield: '[data-cy="end-users-field"]',
    noOfSuperAdminLabel: '[data-cy="number-of-super-admins-label"]',
    noOfSuperAdminfield: '[data-cy="super-admins-field"]',
    tablesTab: '[data-cy="tables-sub-tab"]',
    noOfTablesLabel: '[data-cy="number-of-tables-label"]',
    noOfTablesfield: '[data-cy="tables-field"]',
    expiryStatus: '[data-cy="license-expiry-status"]',
    licenseTextArea: '[data-cy="license-text-area"]',
    paidFeatureButton: '[data-cy="paid-feature-button"]',
    accessTabTitle: '[data-cy="access-tab-title"]',
    enterpriseGradientIcon: '[data-cy="enterprise-gradient-icon"]',
    warningInfoText: '[data-cy="warning-info-text"]',
    lockGradientIcon: '[data-cy="lock-gradient"]',
    dsGradientIcon: '[data-cy="datasource-gradient"]',
};

export const cloudLicesningSelector = {
    subscriptionListItem: '[data-cy="subscription-list-item"]',
    builderUserInput: '[data-cy="no-of-builder-input"]',
    upgradePlanTabTitle: '[data-cy="upgrade-to-business-plan-tab-title"]',
    builderUserCostLabel: '[data-cy="monthly-builder-cost-label"]',
    builderUserLabel: '[data-cy="no-of-builder-label"]',
    endUserLabel: '[data-cy="no-of-end-user-label"]',
    endUserCostLabel: '[data-cy="monthly-end-user-cost-label"]',
    endUserInput: '[data-cy="no-of-end-user-input"]',
    promoCodeInput: '[data-cy="promo-code-input"]',
    offerToggle: '[data-cy="offer-toggle"]',
    offerToggleLabel: '[data-cy="offer-toggle-label"]',
    totalCostValue: '[data-cy="total-amount"]',
    termsHelperText: '[data-cy="terms-helper-text"]',
    termsLink: '[data-cy="terms-link"]',
    contactUsHelper: '[data-cy="contact-us-helper-text"]',
    subscriptionTabTitle: '[data-cy="subscription-key-tab-title"]',
    subscriptionKeyTextArea: '[data-cy="subscription-key-text-area"]',
    subscriptionKeyHelperText: '[data-cy="subscription-key-helper-text"]',
    warningTextHeader: '[data-cy="warning-text-header"]',
    upgradeLink: '[data-cy="upgrade-link"]',

    basicPlan: {
        apps: "Unlimited applications",
        sso: "SSO (Google & Github)",
        comminity: "Community support",
        tjDb: "Unlimited ToolJet tables and rows",
        multiplayer: "Multiplayer editing",
    },

};
