export const ssoSelector = {
  pagetitle: "[data-cy=manage-sso-page-title]",
  instanceLoginPage: {
    cardTitle: "[data-cy=card-title]",
    allowedDomainLabel: "[data-cy=allowed-domain-label]",
    allowedDomainInput: "[data-cy=allowed-domains]",
    allowedDomainHelperText: '[data-cy="allowed-allowedDomains-helper-text"]',
    superAdminUrlLabel: '[data-cy="workspace-login-url-label"]',
    superAdminUrl: '[data-cy="workspace-login-url"]',
    superAdminUrlHelperText: '[data-cy="workspace-login-help-text"]',
    enableSignupLabel: '[data-cy="enable-sign-up-label"]',
    enableSignupHelperText: "[data-cy=enable-sign-up-helper-text]",
    passwordLoginLabel: '[data-cy="label-password-login"]',
    passwordDisableHelperText: '[data-cy="disable-password-helper-text"]',
    workspaceConfigurationLabel: '[data-cy="enable-workspace-configuration-label"]',
    workspaceConfigurationHelperText: '[data-cy="enable-workspace-configuration-helper-text"]',
    autoSSOLabel: '[data-cy="auto-sso-label"]',
    autoSSOHelperText: '[data-cy="auto-sso-helper-text"]',
    instanceLogoutTitle: '[data-cy="instance-logout-title"]',
    customLogoutUrlLabel: '[data-cy="custom-logout-url-label"]',
    customLogoutUrlPlaceholder: '[data-cy="custom-logout-url-input"]',
    customLogoutUrlHelperText: '[data-cy="custom-logout-url-helper-text"]',
    ssoHeader: '[data-cy="sso-header"]',
    googleLabel: '[data-cy="google-label"]',
    githubLabel: '[data-cy="github-label"]',
    oidcLabel: '[data-cy="openid-connect-label"]',
  },
  workspaceLoginPage: {
    cardTitle: "[data-cy=card-title]",
    allowedDomainLabel: "[data-cy=allowed-domain-label]",
    allowedDomainInput: "[data-cy=allowed-domains]",
    allowedDomainHelperText: '[data-cy="allowed-domain-helper-text"]',
    workspaceLoginUrlLabel: '[data-cy="workspace-login-url-label"]',
    workspaceLoginUrl: '[data-cy="workspace-login-url"]',
    workspaceLoginUrlHelperText: '[data-cy="workspace-login-help-text"]',
    enableSignupLabel: '[data-cy="enable-sign-up-label"]',
    enableSignupHelperText: "[data-cy=enable-sign-up-helper-text]",
    passwordLoginLabel: '[data-cy="label-password-login"]',
    passwordDisableHelperText: '[data-cy="disable-password-helper-text"]',
    autoSSOLabel: '[data-cy="auto-sso-label"]',
    autoSSOHelperText: '[data-cy="auto-sso-helper-text"]',
    ssoHeader: '[data-cy="sso-header"]',
    instanceSsoCard: '[data-cy="instance-sso-card"]',
    instanceSsoHelperText: '[data-cy="instance-sso-helper-text"]',
    googleLabel: '[data-cy="google-label"]',
    githubLabel: '[data-cy="github-label"]',
    oidcLabel: '[data-cy="openid-connect-label"]',
    ldapLabel: '[data-cy="ldap-label"]',
    samlLabel: '[data-cy="saml-label"]',

  },
  googleSSOPageElements: {
    clientIdLabel: '[data-cy="client-id-label"]',
    clientIdInput: '[data-cy="client-id-input"]',
    redirectUrlLabel: '[data-cy="redirect-url-label"]',
  },
  ssoEnableModal: {
    modalTitle: '[data-cy="modal-title"]',
    modalMessage: '[data-cy="modal-message"]',
    confirmationText: '[data-cy="confirmation-text"]',
    enableButton: '[data-cy="enable-button"]',
  },
  githubSSOPageElements: {
    hostNameLabel: '[data-cy="host-name-label"]',
    hostNameInput: '[data-cy="host-name-input"]',
    clientIdLabel: '[data-cy="client-id-label"]',
    clientIdInput: '[data-cy="client-id-input"]',
    redirectUrlLabel: '[data-cy="redirect-url-label"]',
  },
  oidcSSOPageElements: {
    nameLabel: '[data-cy="name-label"]',
    nameInput: '[data-cy="name-input"]',
    clientIdLabel: '[data-cy="client-id-label"]',
    clientIdInput: '[data-cy="client-id-input"]',
    wellKnownUrlLabel: '[data-cy="well-known-url-label"]',
    wellKnownUrlInput: '[data-cy="well-known-url-input"]',
    redirectUrlLabel: '[data-cy="redirect-url-label"]',
  },
  ldapSSOPageElements: {
    nameLabel: '[data-cy="name-label"]',
    nameInput: '[data-cy="name-input"]',
    hostLabel: '[data-cy="host-label"]',
    hostInput: '[data-cy="host-input"]',
    portLabel: '[data-cy="port-label"]',
    portInput: '[data-cy="port-input"]',
    baseDnLabel: '[data-cy="base-dn-label"]',
    baseDnInput: '[data-cy="base-dn-input"]',
  },
  samlSSOPageElements: {
    nameLabel: '[data-cy="name-label"]',
    nameInput: '[data-cy="name-input"]',
    idpMetadataLabel: '[data-cy="idp-metadata-label"]',
    idpMetadataInput: '[data-cy="dp-metadata-input"]',
    groupAttributeLabel: '[data-cy="group-attribute-label"]',
    groupAttributeInput: '[data-cy="group-attribute-input"]',
    redirectUrlLabel: '[data-cy="redirect-url-label"]',
  },
  nameInput: '[data-cy="name-input"]',
  wellKnownUrlInput: '[data-cy="well-known-url-input"]',
  modalCloseButton: '[data-cy="modal-close-button"]',
  copyIcon: '[data-cy="copy-icon"]',
  cancelButton: '[data-cy="cancel-button"]',
  saveButton: "[data-cy=save-button]",
  enableButton: '[data-cy="enable-button"]',
  cardTitle: "[data-cy=card-title]",
  enableSignUpToggle: '[data-cy="enable-sign-up-toggle"]',
  superAdminInfoText: '[data-cy="superadmin-info-text"]',
  allowDefaultSSOToggle:
    '[style="padding-left: 0px; margin-bottom: 1px;"] > .switch > .slider',
  defaultSSOImage: '[data-cy="default-sso-status-image"]',
  allowedDomainInput: '[data-cy="allowed-domains"]',
  workspaceLoginUrl: '[data-cy="workspace-login-url"]',
  cancelButton: "[data-cy=cancel-button]",
  saveButton: "[data-cy=save-button]",
  modalTitle: '[data-cy="modal-title"]',
  google: '[data-cy="google-sso-card"]',
  googleEnableToggle: '[data-cy="google-enable-toggle"]',
  statusLabel: "[data-cy=status-label]",
  clientIdLabel: "[data-cy=client-id-label]",
  clientIdInput: "[data-cy=client-id-input]",
  redirectUrlLabel: "[data-cy=redirect-url-label]",
  redirectUrl: "[data-cy=redirect-url]",
  googleTile: '[data-cy="google-sign-in-text"]',
  googleIcon: "[data-cy=google-sso-button]",
  googleSSOText: "[data-cy=google-sso-button-text]",
  git: '[data-cy="github-sso-card"]',
  gitEnableToggle: '[data-cy="github-toggle-input"]',
  githubLabel: '[data-cy="github-label"]',
  autoSSOToggle: '[data-cy="auto-sso-toggle"]',
  instanceLoginListItem: '[data-cy="instance-login-list-item"]',
  modalMessage: '[data-cy="modal-message"]',
  clientSecretLabel: "[data-cy=client-secret-label]",
  encriptedLabel: "[data-cy=encripted-label]",
  clientSecretInput: "[data-cy=client-secret-input]",
  gitTile: "[data-cy=git-tile]",
  gitIcon: "[data-cy='git-sso-button-text']",
  gitSignInText: "[data-cy='git-sso-button-text']",
  gitSSOText: "[data-cy=git-sso-button-text]",
  password: "[data-cy=left-menu-items] :eq(3)",
  passwordEnableToggle: '[data-cy="password-enable-toggle"]',
  disablePasswordLoginTitle: '[data-cy="disable-password-login-title"]',
  loginHelpText: "[data-cy=login-help-text]",
  allowedDomainHelpText: "[data-cy=allowed-domain-help-text]",
  hostNameLabel: '[data-cy="host-name-label"]',
  hostNameInput: '[data-cy="host-name-input"]',
  hostNameHelpText: '[data-cy="git-sso-help-text"]',
  signInHeader: '[data-cy="sign-in-header"]',
  workspaceSubHeader: '[data-cy="workspace-sign-in-sub-header"]',
  noLoginMethodWarning: '[data-cy="no-login-methods-warning"]',
  passwordLoginToggleLbale: '[data-cy="label-password-login"]',
  alertText: '[data-cy="alert-text"]',
  disablePasswordHelperText: '[data-cy="disable-password-helper-text"]',
  defaultGoogle: '[data-cy="dropdown-options-google"]',
  defaultGithub: '[data-cy="dropdown-options-git"]',
  workspaceSignUpHeader: '[data-cy="workspace-signup-header"]',
  linkReadDocumentation: '[data-cy="link-read-documentation"]',
  instanceSsoToggle: '[data-cy="instance-sso-toggle"]',
  oidc: '[data-cy="openid-connect-sso-card"]',
  oidcEnableToggle: '[data-cy="openid-toggle-input"] > .slider',
  oidcTitle: '[data-cy="openid-toggle-label"]',
  credentialTitle: '[data-cy="credential-title"]',
  oidcIcon: '[data-cy="oidc-sso-button"]',
  oidcSSOText: '[data-cy="oidc-sso-button-text"]',
  wellKnownUrlInput: '[data-cy="well-known-url-input"]',
  ldap: '[data-cy="ldap-sso-card"]',
  ldapEnableToggle: '[data-cy="ldap-toggle-input"] > .slider',
  ldapIcon: '[data-cy="ldap-sso-button"]',
  ldapSSOText: '[data-cy="ldap-sso-button-text"]',
  ldapHelpText: '[data-cy="ldap-sso-help-text"]',
  ldapTitle: '[data-cy="ldap-toggle-label"]',
  baseDnHelperText: '[data-cy="base-dn-helper-text"]',
  sslLabel: '[data-cy="ssl-label"]',
  sslToggle: '[data-cy="ssl-toggle-input"]',
  hostInput: '[data-cy="host-input"]',
  portInput: '[data-cy="port-input"]',
  baseDnInput: '[data-cy="base-dn-input"]',
  groupAttributeHelperText: '[data-cy="group-attribute-helper-text"]',
  groupAttributeInput: '[data-cy="group-attribute-input"]',
  groupAttributeLabel: '[data-cy="group-attribute-label"]',
  saml: '[data-cy="saml-sso-card"]',
  samlEnableToggle: '[data-cy="saml-toggle-input"] > .slider',
  samlIcon: '[data-cy="saml-sso-button"]',
  samlSSOText: '[data-cy="saml-sso-button-text"]',
  samlTitle: '[data-cy="saml-toggle-label"]',
  samlNameInput: '[data-cy="name-input"]',
  samlMetadataInput: '[data-cy="dp-metadata-input"]',
  samlGroupAttributeInput: '[data-cy="group-attribute-input"]',
  groupsyncTitle: '[data-cy="group-sync-title"]',
  groupsyncToggle: '[data-cy="group-sync-toggle-input"] > .slider',
  groupsyncToggleLabel: '[data-cy="group-sync-toggle-label"]',
  groupsyncHelperText: '[data-cy="group-sync-heler-text"]',
  groupsyncElements: {
    groupsyncClaimLabel: '[data-cy="claim-name-label"]',
    groupsyncClaimInput: '[data-cy="claim-name-input"]',
    groupsyncMappingLabel: '[data-cy="group-mapping-label"]',
    groupsyncMappingInput: '[data-cy="group-mapping-input"]',
  },
  groupsyncMappingHelperText: '[data-cy="group-mapping-helper-text"]',
};

