export const usersSelector = {
  dropdown: "[data-cy=workspace-dropdown]",
  inviteUserButton: "[data-cy=invite-new-user]",
  usersElements: {
    pageTitle: "[data-cy=users-page-title]",
    nameTitile: "[data-cy=name-title]",
    emailTitle: "[data-cy=email-title]",
    statusTitle: "[data-cy=status-title]",
  },
  adminUserName: "[data-cy=user-name]",
  adminUserEmail: "[data-cy=user-email]",
  userStatus: "[data-cy=user-status]:eq(0)",
  userState: "[data-cy=user-state]:eq(0)",
  userStatus: "[data-cy=user-status]",
  cardTitle: "[data-cy=add-new-user]",
  firstNameInput: "[data-cy=first-name-input]",
  lastNameInput: "[data-cy=last-name-input]",
  emailLabel: "[data-cy=email-label]",
  emailInput: "[data-cy=email-input]",
  cancelButton: "[data-cy=cancel-button]",
  createUserButton: "[data-cy=create-user-button]",
  fisrtNameError: "[data-cy=first-name-error]",
  lastNameError: "[data-cy=last-name-error]",
  emailError: "[data-cy=email-error]",
  pageLogo: "[data-cy=page-logo]",
  invitePageHeader: '[data-cy="invite-page-header"]',
  invitePgaeSubHeader: '[data-cy="invite-page-sub-header"]',
  acceptInvite: "[data-cy=accept-invite-button]",
  firstNameField: "[data-cy=first-name-input]",
  lastNameField: "[data-cy=last-name-input]",
  workspaceField: "[data-cy=workspace-input]",
  roleOptions: "[data-cy=role-options]",
  passwordInput: "[data-cy=password-input]",
  confirmPasswordInput: "[data-cy=confirm-password-input]",
  finishSetup: "[data-cy=finish-setup-button]",
  emptyImage: "[data-cy=empty-img]",
  manageUsers: "[data-cy=manage-users]",
  createNewApp: "[data-cy=create-new-application]",
  dropdownText: "[data-cy=dropdown-organization-list]>>:eq(0)",
  arrowIcon: "[data-cy=workspace-arrow-icon]",
  singleWorkspaceElements: {
    cardTitle: "[data-cy=card-title]",
    passwordLabel: "[data-cy=password-label]",
    confirmpasswordLabel: "[data-cy=confirm-password-label]",
    termsInfo: "[data-cy=terms-and-condition-info]",
  },
  inviteBulkUserButton: '[data-cy="invite-bulk-user-button"]',
  bulkUserUploadPageTitle: '[data-cy="bulk-user-upload-page-title"]',
  bulkUSerUploadInput: '[data-cy="bulk-user-upload-input"]',
  downloadTemplateButton: '[data-cy="download-template-button"]',
  createUsersButton: '[data-cy="create-users-button"]',

};
