export const modalSelector = {
  modalHeader: '[data-cy="modal-header"]',
  modalBody: '[data-cy="modal-body"]',
  modalFooter: '[data-cy="modal-footer"]',
  modalCloseButton: '[data-cy="modal-close-button"]',
  modalContainer: ".modal",
  fullscreenModal: ".modal-fullscreen",
  loadingSpinner: ".spinner-border",
  disabledOverlay: '[data-cy="modal-body"] .tj-modal-disabled-overlay',
  heightInput: '[data-cy="height-input"]',
  widthDropdown: '[data-cy="dropdown-width"]',
  fontSizeInput: '[data-cy="font-size-input"]',
  widgetTooltip: '[data-cy="widget-tooltip"]',
  tooltipPlainText: '[data-cy="widget-tooltip"] > span.tw-whitespace-pre-wrap',
  tooltipMarkdown: '[data-cy="widget-tooltip"] > .widget-tooltip-markdown',
  tooltipHtml: '[data-cy="widget-tooltip"] > .widget-tooltip-html',
  tooltipInputField: '[data-cy="tooltip-input-field"]',
  tooltipFormatButton: (format) => `[data-cy="togglr-button-${format}"]`,
};
