export const postgreSqlSelector = {
  leftSidebarDatasourceButton: "[data-cy='left-sidebar-database-button']",
  labelDataSources: "[data-cy='label-datasources']",
  addDatasourceLink: "[data-cy='add-datasource-link']",

  allDatasourceLabelAndCount: '[data-cy="datasource-list-header"]',
  databaseLabelAndCount: '[data-cy="databases-datasource-button"]',
  apiLabelAndCount: '[data-cy="apis-datasource-button"]',
  cloudStorageLabelAndCount: '[data-cy="cloudstorage-datasource-button"]',
  pluginsLabelAndCount: '[data-cy="plugins-datasource-button"]',
  dataSourceSearchInputField: '[data-cy="home-page-search-bar"]',

  postgresDataSource: "[data-cy='data-source-postgresql']",
  dataSourceNameInputField: '[data-cy="data-source-name-input-filed"]',
  labelHost: '[data-cy="label-host"]',
  labelPort: '[data-cy="label-port"]',
  labelSsl: '[data-cy="label-ssl"]',
  labelDbName: '[data-cy="label-database-name"]',
  labelUserName: '[data-cy="label-username"]',
  labelPassword: '[data-cy="label-password"]',
  labelSSLCertificate: '[data-cy="ssl-certificate-dropdown-label"]',
  labelIpWhitelist: '[data-cy="white-list-ip-text"]',
  buttonCopyIp: '[data-cy="button-copy-ip"]',
  linkReadDocumentation: '[data-cy="link-read-documentation"]',
  buttonTestConnection: '[data-cy="test-connection-button"]',
  connectionFailedText: '[data-cy="test-connection-failed-text"]',
  buttonSave: '[data-cy="db-connection-save-button"] > .tj-base-btn',
  dangerAlertNotSupportSSL: '.go3958317564',

  passwordTextField: '[data-cy="password-text-field"]',
  textConnectionVerified: '[data-cy="test-connection-verified-text"]',
  datasourceLabelOnList: '[data-cy="datasource-Label"]',

  buttonAddNewQueries: '[data-cy="button-add-new-queries"]',
  addQueriesCard: '[data-cy="postgresql-add-query-card"]',
  headerQueryManager: '[data-cy="header-queries-on-query-manager"]',
  labelNoQuery: '[data-cy="no-query-text"]',
  createQueryButton: '[data-cy="query-create-and-run-button"]',
  querySearchBar: '[data-cy="home-page-search-bar"]',
  labelSelectDataSource: '[data-cy="label-select-datasource"]',
  queryTabGeneral: '[data-cy="query-tab-general"]',
  queryLabelInputField: '[data-cy="query-rename-input"]',
  queryPreviewButton: '[data-cy="query-preview-button"]',
  queryCreateAndRunButton: '[data-cy="query-run-button"]',
  queryCreateDropdown: '[data-cy="query-create-dropdown"]',
  queryCreateAndRunOption: '[data-cy="query-create-and-run-option"]',
  queryCreateOption: '[data-cy="query-create-option"]',
  queryInputField: '[data-cy="query-input-field"]',
  labelTransformation: '[data-cy="label-query-transformation"]',
  toggleTransformation: '[data-cy="transformation-toggle-switch"]',
  inputFieldTransformation: '[data-cy="transformation-input-input-field"]',

  headerQueryPreview: '.py-2',
  previewTabJson: '[data-cy="preview-tab-json"]',
  previewTabRaw: '[data-cy="preview-tab-raw"]',

  operationsDropDownLabel: '[data-cy="operation-dropdown-label"]',
  labelTableNameInputField: '[data-cy="label-table"]',
  labelPrimaryKeyColoumn: '[data-cy="label-primary-key-column"]',
  labelRecordsToUpdate: '[data-cy="label-records-to-update"]',

  queryTabAdvanced: '[data-cy="query-tab-advanced"]',

  labelRunQueryOnPageLoad: '[data-cy="run-on-app-load-toggle-label"]',
  labelRequestConfirmationOnRun:
    '[data-cy="confirmation-before-run-toggle-label"]',
  labelShowNotification: '[data-cy="notification-on-success-toggle-label"]',
  toggleNotification: '[data-cy="notification-on-success-toggle-switch"]',
  labelSuccessMessageInput: '[data-cy="label-success-message-input"]',
  notificationDurationInput: '[data-cy="label-notification-duration-input"]',
  addEventHandler: '[data-cy="add-event-handler"]',
  noEventHandlerMessage: '[data-cy="no-event-handler-message"]',
  postgresqlQueryRunButton: '[data-cy="postgresql1-query-run-button"]',
  psqlQueryLabel: '[data-cy="postgresql1-query-label"]',
  psqlQueryDeleteButton: '[data-cy="postgresql1-query-delete-button"]',
  deleteModalMessage: '[data-cy="modal-message"]',
  deleteModalCancelButton: '[data-cy="modal-cancel-button"]',
  deleteModalConfirmButton: '[data-cy="modal-confirm-button"]',

  querySelectDropdown: "[data-cy='query-select-dropdown']",
  opetionQuerySave: "[data-cy='query-save-option']",

  dataExistanceQuery: '[data-cy="existance_of_table-query-label"]',
  tableNameInputField: '[data-cy="table-input-field"]',
  primaryKeyColoumnInputField: '[data-cy="primary_key_column-input-field"]',
  recordsInputField: '[data-cy="records-input-field"]',

  eventQuerySelectionField: '[data-cy="query-selection-field"]',
};
