export const profileSelector={
  profileDropdown: "[data-cy=dropdown-menu]",  
  profileLink: "[data-cy=profile-link]",
  logoutLink: "[data-cy=logout-link]",
  profileElements:{
    pageTitle: "[data-cy=page-title]",
    profileCard: "[data-cy=card-title-profile]",
    firstNameLabel: "[data-cy=first-name-label]",
    lastNameLabel: "[data-cy=last-name-label]",
    emailLabel: "[data-cy=email-label]",
    passwordCard: "[data-cy=card-title-change-password]",
    currentPasswordLabel: "[data-cy=current-password-label]",
    newPasswordLabel: "[data-cy=new-password-label]",
  },
  firstNameInput: "[data-cy=first-name-input]",
  lastNameInput: "[data-cy=last-name-input]",
  emailInput: "[data-cy=email-input]",
  updateButton: "[data-cy=update-button]",
  changePasswordButton: "[data-cy=change-password-button]",
  currentPasswordField: "[data-cy=current-password-input]",
  newPasswordField: "[data-cy=new-password-input]",
}