export const instanceWorkspaceSelectors = {
  breadcrumbPageTitle: '[data-cy="breadcrumb-page-title"]',
  navAllWorkspaces: '[data-cy="all-workspaces-list-item"]',
  tabActive: '[data-cy="active-link"]',
  tabArchived: '[data-cy="archived-link"]',
  searchBar: '[data-cy="query-manager-search-bar"]',
  nameHeader: '[data-cy="name-header"]',
  workspaceRowContainer: '.mx-3.tj-text-sm.d-flex.align-items-center',
  defaultWorkspaceTag: '.default-workspace-tag',
  workspaceTableRow: 'tr.workspace-table-row',
  workspaceNameCellSuffix: '[data-cy$="-workspace"]',
  statusChangeButton: '[data-cy="button-ws-status-change"]',
  confirmButton: '[data-cy="confirm-button"]',
  continueButton: '[data-cy="continue-button"]',
  tooltipDefaultWorkspace: '[data-tooltip-id="default-workspace-tooltip"]',
  selectControl: '.tj-select .react-select__control',
  selectMenu: '.react-select__menu',
  selectOption: '.react-select__option',
  noResultFoundText: '[data-cy="text-no-result-found"]',
  acceptInviteButton: '[data-cy="accept-invite-button"]',
  shareButtonLink: '[data-cy="share-button-link"]',
  appSlugInput: '[data-cy="app-name-slug-input"]',
  makePublicToggle: '[data-cy="make-public-app-toggle"]',
  modalCloseButton: '[data-cy="modal-close-button"]',
  userActionButton: '[data-cy="user-actions-button"]',
  archiveButton: '[data-cy="archive-button"]',
  userSearchBar: '[data-cy="input-field-user-filter-search"]',
  passwordResetButton: '[data-cy="reset-password-button"]',
  createNewPasswordButton: '[data-cy="create-password-input"]',
  passwordInputField: '[data-cy="password-input"]',
  resetButton: '[data-cy="reset-button"]',
  viewTableNameColumnHeader: '[data-cy="users-table-name-column-header"]',
  viewTableStatusColumnHeader: '[data-cy="users-table-status-column-header"]',
  openWorkspaceTooltip: '[data-tooltip-id="tooltip-for-open-new-ws"]',
};

export const instanceAllUsersSelectors = {
  editUserDetailsButton: '[data-cy="edit-user-details-button"]',
  resetPasswordButton: '[data-cy="reset-password-button"]',
  archiveUserButton: '[data-cy="archive-button"]',
  inputFieldFullName: '[data-cy="input-field-full-name"]',
  inputFieldEmail: '[data-cy="input-field-email"]',
  updateButton: '[data-cy="update-button"]',
  viewTableNameColumnHeader: '[data-cy="users-table-name-column-header"]',
  viewTableStatusColumnHeader: '[data-cy="users-table-status-column-header"]',
  userStatusCell: (userName) => `[data-cy="${String(userName).toLowerCase()}-user-status"]`,
  userName: (userName) => `[data-cy="-${userName}-user-name"]`,
};

export const usersTableElementsInInstance = {
  usersTableNameColumnHeader: '[data-cy="users-table-name-column-header"]',
  usersTableStatusColumnHeader: '[data-cy="users-table-status-column-header"]',
  usersFilterLabel: '[data-cy="users-filter-label"]',
};

export const whiteLabelSelectors = {
  navWhiteLabellingListItem: '[data-cy="white-labelling-list-item"]',
  breadcrumbPageTitle: '[data-cy="breadcrumb-page-title"]',
  appLogoInput: '[data-cy="input-field-app-logo"]',
  pageTitleInput: '[data-cy="input-field-page-title"]',
  favIconInput: '[data-cy="input-field-fav-icon"]',
  appLogoHelpTextSelector: '[data-cy="app-logo-help-text"]',
  favIconHelpText: '[data-cy="fav-icon-help-text"]',
  cancelButton: '[data-cy="cancel-button"]',
  saveButton: '[data-cy="save-button"]',
};
export const smtpSelectors = {
  smtpEnableToggle: '[data-cy="smtp-enable-toggle"]',
  smtpListItem: '[data-cy="email-protocol-(smtp)-list-item"]',
  smtpHostInput: '[data-cy="input-field-host"]',
  smtpPortInput: '[data-cy="input-field-port"]',
  smtpUserInput: '[data-cy="input-field-user"]',
  smtpPasswordInput: '[data-cy="input-field-password"]',
  smtpStatuslabel: '[data-cy="status-label"]',
  };
  