{
  "openapi": "3.1.0",
  "info": {
    "title": "Microsoft Graph OneDrive API",
    "description": "Microsoft Graph API for OneDrive operations including file management, sharing, and collaboration",
    "version": "1.0.0",
    "contact": {
      "name": "Microsoft Graph",
      "url": "https://developer.microsoft.com/graph"
    }
  },
  "servers": [
    {
      "url": "https://graph.microsoft.com/v1.0",
      "description": "Microsoft Graph v1.0 endpoint"
    }
  ],
  "security": [
    {
      "oauth2": ["Files.Read", "Files.ReadWrite", "Files.Read.All", "Files.ReadWrite.All"]
    }
  ],
  "paths": {
    "/me/drive/root/children": {
      "get": {
        "summary": "List root folder contents",
        "description": "Retrieve the list of DriveItem objects in the root folder of the user's default drive",
        "operationId": "listRootChildren",
        "tags": ["DriveItem", "Children"],
        "security": [
          {
            "oauth2": ["Files.Read", "Files.ReadWrite"]
          }
        ]
      },
      "post": {
        "summary": "Create new item in root folder",
        "description": "Create a new folder or upload a file to the root folder",
        "operationId": "createRootItem",
        "tags": ["DriveItem", "Create"],
        "security": [
          {
            "oauth2": ["Files.ReadWrite"]
          }
        ]
      }
    },
    "/me/drive/recent": {
      "get": {
        "summary": "List recently accessed files",
        "description": "Retrieve a list of DriveItem resources that have been recently used by the signed-in user",
        "operationId": "listRecentFiles",
        "tags": ["DriveItem", "Recent"],
        "security": [
          {
            "oauth2": ["Files.Read", "Files.ReadWrite"]
          }
        ]
      }
    },
    "/me/drive/sharedWithMe": {
      "get": {
        "summary": "List items shared with me",
        "description": "Retrieve a collection of DriveItem resources that have been shared with the signed-in user",
        "operationId": "listSharedWithMe",
        "tags": ["DriveItem", "Sharing"],
        "security": [
          {
            "oauth2": ["Files.Read.All", "Files.ReadWrite.All"]
          }
        ]
      }
    },
    "/me/drive/root/search(q='{search-query}')": {
      "get": {
        "summary": "Search drive items",
        "description": "Search the hierarchy of items for items matching a query",
        "operationId": "searchDriveItems",
        "tags": ["DriveItem", "Search"],
        "security": [
          {
            "oauth2": ["Files.Read", "Files.ReadWrite"]
          }
        ]
      }
    },
    "/drives/{drive-id}/root/children": {
      "get": {
        "summary": "List drive root contents",
        "description": "Retrieve the list of DriveItem objects in the root folder of a specific drive",
        "operationId": "listDriveRootChildren",
        "tags": ["DriveItem", "Children"],
        "security": [
          {
            "oauth2": ["Files.Read", "Files.ReadWrite", "Files.Read.All", "Files.ReadWrite.All"]
          }
        ]
      }
    },
    "/drives/{drive-id}/items/{item-id}/children": {
      "get": {
        "summary": "List folder contents",
        "description": "Retrieve the list of DriveItem objects in a specific folder",
        "operationId": "listFolderChildren",
        "tags": ["DriveItem", "Children"],
        "security": [
          {
            "oauth2": ["Files.Read", "Files.ReadWrite", "Files.Read.All", "Files.ReadWrite.All"]
          }
        ]
      },
      "post": {
        "summary": "Create item in folder",
        "description": "Create a new folder or upload a file to a specific folder",
        "operationId": "createFolderItem",
        "tags": ["DriveItem", "Create"],
        "security": [
          {
            "oauth2": ["Files.ReadWrite", "Files.ReadWrite.All"]
          }
        ]
      }
    },
    "/drives/{drive-id}/items/{item-id}": {
      "get": {
        "summary": "Get drive item metadata",
        "description": "Retrieve the metadata for a DriveItem by ID",
        "operationId": "getDriveItem",
        "tags": ["DriveItem"],
        "security": [
          {
            "oauth2": ["Files.Read", "Files.ReadWrite", "Files.Read.All", "Files.ReadWrite.All"]
          }
        ]
      },
      "patch": {
        "summary": "Update drive item",
        "description": "Update the metadata for a DriveItem by ID",
        "operationId": "updateDriveItem",
        "tags": ["DriveItem"],
        "security": [
          {
            "oauth2": ["Files.ReadWrite", "Files.ReadWrite.All"]
          }
        ]
      },
      "delete": {
        "summary": "Delete drive item",
        "description": "Delete a DriveItem by ID",
        "operationId": "deleteDriveItem",
        "tags": ["DriveItem"],
        "security": [
          {
            "oauth2": ["Files.ReadWrite", "Files.ReadWrite.All"]
          }
        ]
      }
    },
    "/drives/{drive-id}/items/{item-id}/content": {
      "get": {
        "summary": "Download file content",
        "description": "Download the contents of a DriveItem",
        "operationId": "downloadFile",
        "tags": ["DriveItem", "Content"],
        "security": [
          {
            "oauth2": ["Files.Read", "Files.ReadWrite", "Files.Read.All", "Files.ReadWrite.All"]
          }
        ]
      },
      "put": {
        "summary": "Upload file content",
        "description": "Upload content for a new file or replace content of existing file",
        "operationId": "uploadFile",
        "tags": ["DriveItem", "Content"],
        "security": [
          {
            "oauth2": ["Files.ReadWrite", "Files.ReadWrite.All"]
          }
        ]
      }
    },
    "/drives/{drive-id}/items/{item-id}/createLink": {
      "post": {
        "summary": "Create sharing link",
        "description": "Create a sharing link for a DriveItem",
        "operationId": "createSharingLink",
        "tags": ["DriveItem", "Sharing"],
        "security": [
          {
            "oauth2": ["Files.ReadWrite", "Files.ReadWrite.All"]
          }
        ]
      }
    },
    "/drives/{drive-id}/items/{item-id}/permissions": {
      "get": {
        "summary": "List item permissions",
        "description": "List the permissions on a DriveItem",
        "operationId": "listPermissions",
        "tags": ["DriveItem", "Permissions"],
        "security": [
          {
            "oauth2": ["Files.Read", "Files.ReadWrite", "Files.Read.All", "Files.ReadWrite.All"]
          }
        ]
      }
    },
    "/me/drive": {
      "get": {
        "summary": "Get user's default drive",
        "description": "Retrieve the metadata for the user's default drive",
        "operationId": "getDefaultDrive",
        "tags": ["Drive"],
        "security": [
          {
            "oauth2": ["Files.Read", "Files.ReadWrite"]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "oauth2": {
        "type": "oauth2",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
            "tokenUrl": "https://login.microsoftonline.com/common/oauth2/v2.0/token",
            "scopes": {
              "Files.Read": "Read user files",
              "Files.Read.All": "Read all files that user can access",
              "Files.ReadWrite": "Have full access to user files",
              "Files.ReadWrite.All": "Have full access to all files user can access",
              "Sites.Read.All": "Read items in all site collections",
              "Sites.ReadWrite.All": "Edit or delete items in all site collections",
              "offline_access": "Maintain access to data you have given it access to"
            }
          }
        }
      }
    }
  },
  "tags": [
    {
      "name": "Drive",
      "description": "Operations on drives"
    },
    {
      "name": "DriveItem",
      "description": "Operations on files and folders"
    },
    {
      "name": "Children",
      "description": "Operations on folder contents"
    },
    {
      "name": "Content",
      "description": "Operations on file content"
    },
    {
      "name": "Sharing",
      "description": "File sharing operations"
    },
    {
      "name": "Permissions",
      "description": "Permission management"
    },
    {
      "name": "Search",
      "description": "Search operations"
    },
    {
      "name": "Recent",
      "description": "Recently accessed files"
    },
    {
      "name": "Create",
      "description": "Create new items"
    }
  ]
}