{
  "openapi": "3.1.0",
  "info": {
    "title": "Microsoft Graph API - Outlook Services",
    "version": "1.0",
    "description": "Microsoft Graph API specification for Outlook mail services including messages, mail folders, sendMail, and other mail operations"
  },
  "servers": [
    {
      "url": "https://graph.microsoft.com/v1.0",
      "description": "Microsoft Graph API v1.0"
    },
    {
      "url": "https://graph.microsoft.com/beta",
      "description": "Microsoft Graph API beta"
    }
  ],
  "paths": {
    "/me/messages": {
      "get": {
        "summary": "List messages",
        "description": "Get the messages in the signed-in user's mailbox",
        "operationId": "listMessages",
        "security": [
          {
            "oauth2": ["Mail.Read", "Mail.ReadWrite"]
          }
        ]
      },
      "post": {
        "summary": "Create message",
        "description": "Create a draft of a new message",
        "operationId": "createMessage",
        "security": [
          {
            "oauth2": ["Mail.ReadWrite"]
          }
        ]
      }
    },
    "/me/messages/{message-id}": {
      "get": {
        "summary": "Get message",
        "description": "Retrieve the properties and relationships of a message",
        "operationId": "getMessage",
        "security": [
          {
            "oauth2": ["Mail.Read", "Mail.ReadWrite"]
          }
        ]
      },
      "patch": {
        "summary": "Update message",
        "description": "Update the properties of a message",
        "operationId": "updateMessage",
        "security": [
          {
            "oauth2": ["Mail.ReadWrite"]
          }
        ]
      },
      "delete": {
        "summary": "Delete message",
        "description": "Delete a message",
        "operationId": "deleteMessage",
        "security": [
          {
            "oauth2": ["Mail.ReadWrite"]
          }
        ]
      }
    },
    "/me/messages/{message-id}/forward": {
      "post": {
        "summary": "Forward message",
        "description": "Forward a message",
        "operationId": "forwardMessage",
        "security": [
          {
            "oauth2": ["Mail.Send"]
          }
        ]
      }
    },
    "/me/messages/{message-id}/createForward": {
      "post": {
        "summary": "Create forward draft",
        "description": "Create a draft to forward an existing message",
        "operationId": "createForwardDraft",
        "security": [
          {
            "oauth2": ["Mail.ReadWrite"]
          }
        ]
      }
    },
    "/me/messages/{message-id}/reply": {
      "post": {
        "summary": "Reply to message",
        "description": "Reply to the sender of a message",
        "operationId": "replyToMessage",
        "security": [
          {
            "oauth2": ["Mail.Send"]
          }
        ]
      }
    },
    "/me/messages/{message-id}/createReply": {
      "post": {
        "summary": "Create reply draft",
        "description": "Create a draft to reply to an existing message",
        "operationId": "createReplyDraft",
        "security": [
          {
            "oauth2": ["Mail.ReadWrite"]
          }
        ]
      }
    },
    "/me/messages/{message-id}/replyAll": {
      "post": {
        "summary": "Reply all to message",
        "description": "Reply to all recipients of a message",
        "operationId": "replyAllToMessage",
        "security": [
          {
            "oauth2": ["Mail.Send"]
          }
        ]
      }
    },
    "/me/messages/{message-id}/createReplyAll": {
      "post": {
        "summary": "Create reply all draft",
        "description": "Create a draft to reply all to an existing message",
        "operationId": "createReplyAllDraft",
        "security": [
          {
            "oauth2": ["Mail.ReadWrite"]
          }
        ]
      }
    },
    "/me/messages/{message-id}/send": {
      "post": {
        "summary": "Send draft message",
        "description": "Send an existing draft message",
        "operationId": "sendDraftMessage",
        "security": [
          {
            "oauth2": ["Mail.Send"]
          }
        ]
      }
    },
    "/me/messages/{message-id}/move": {
      "post": {
        "summary": "Move message",
        "description": "Move a message to a different folder",
        "operationId": "moveMessage",
        "security": [
          {
            "oauth2": ["Mail.ReadWrite"]
          }
        ]
      }
    },
    "/me/messages/{message-id}/copy": {
      "post": {
        "summary": "Copy message",
        "description": "Copy a message to a different folder",
        "operationId": "copyMessage",
        "security": [
          {
            "oauth2": ["Mail.ReadWrite"]
          }
        ]
      }
    },
    "/me/sendMail": {
      "post": {
        "summary": "Send mail",
        "description": "Send a new message immediately",
        "operationId": "sendMail",
        "security": [
          {
            "oauth2": ["Mail.Send"]
          }
        ]
      }
    },
    "/me/mailFolders": {
      "get": {
        "summary": "List mail folders",
        "description": "Get the mail folder collection under the root folder of the signed-in user",
        "operationId": "listMailFolders",
        "security": [
          {
            "oauth2": ["Mail.Read", "Mail.ReadWrite"]
          }
        ]
      },
      "post": {
        "summary": "Create mail folder",
        "description": "Create a new mail folder",
        "operationId": "createMailFolder",
        "security": [
          {
            "oauth2": ["Mail.ReadWrite"]
          }
        ]
      }
    },
    "/me/mailFolders/{mailFolder-id}": {
      "get": {
        "summary": "Get mail folder",
        "description": "Get a specific mail folder",
        "operationId": "getMailFolder",
        "security": [
          {
            "oauth2": ["Mail.Read", "Mail.ReadWrite"]
          }
        ]
      },
      "patch": {
        "summary": "Update mail folder",
        "description": "Update the properties of a mail folder",
        "operationId": "updateMailFolder",
        "security": [
          {
            "oauth2": ["Mail.ReadWrite"]
          }
        ]
      },
      "delete": {
        "summary": "Delete mail folder",
        "description": "Delete a mail folder",
        "operationId": "deleteMailFolder",
        "security": [
          {
            "oauth2": ["Mail.ReadWrite"]
          }
        ]
      }
    },
    "/me/mailFolders/{mailFolder-id}/messages": {
      "get": {
        "summary": "List messages in folder",
        "description": "Get messages in a specific mail folder",
        "operationId": "listMessagesInFolder",
        "security": [
          {
            "oauth2": ["Mail.Read", "Mail.ReadWrite"]
          }
        ]
      }
    },
    "/me/mailFolders/Inbox/messages/delta": {
      "get": {
        "summary": "Get message changes in Inbox",
        "description": "Get incremental changes to messages in the Inbox folder",
        "operationId": "getInboxMessagesDelta",
        "security": [
          {
            "oauth2": ["Mail.Read", "Mail.ReadWrite"]
          }
        ]
      }
    },
    "/me/mailFolders/{mailFolder-id}/messages/delta": {
      "get": {
        "summary": "Get message changes in folder",
        "description": "Get incremental changes to messages in a specific mail folder",
        "operationId": "getMessagesDelta",
        "security": [
          {
            "oauth2": ["Mail.Read", "Mail.ReadWrite"]
          }
        ]
      }
    },
    "/me/mailFolders/delta": {
      "get": {
        "summary": "Get mail folder changes",
        "description": "Get incremental changes to mail folders",
        "operationId": "getMailFoldersDelta",
        "security": [
          {
            "oauth2": ["Mail.Read", "Mail.ReadWrite"]
          }
        ]
      }
    },
    "/me/outlook/masterCategories": {
      "get": {
        "summary": "List master categories",
        "description": "Get all the categories that have been defined for a user",
        "operationId": "listMasterCategories",
        "servers": [
          {
            "url": "https://graph.microsoft.com/v1.0",
            "description": "Available in v1.0"
          },
          {
            "url": "https://graph.microsoft.com/beta",
            "description": "Available in beta"
          }
        ],
        "security": [
          {
            "oauth2": ["Mail.Read", "Mail.ReadWrite", "MailboxSettings.Read", "MailboxSettings.ReadWrite"]
          }
        ]
      },
      "post": {
        "summary": "Create master category",
        "description": "Create a new category in the user's master list",
        "operationId": "createMasterCategory",
        "servers": [
          {
            "url": "https://graph.microsoft.com/v1.0",
            "description": "Available in v1.0"
          },
          {
            "url": "https://graph.microsoft.com/beta",
            "description": "Available in beta"
          }
        ],
        "security": [
          {
            "oauth2": ["MailboxSettings.ReadWrite"]
          }
        ]
      }
    },
    "/me/outlook/masterCategories/{outlookCategory-id}": {
      "get": {
        "summary": "Get master category",
        "description": "Get a specific category from the user's master list",
        "operationId": "getMasterCategory",
        "servers": [
          {
            "url": "https://graph.microsoft.com/v1.0",
            "description": "Available in v1.0"
          },
          {
            "url": "https://graph.microsoft.com/beta",
            "description": "Available in beta"
          }
        ],
        "security": [
          {
            "oauth2": ["Mail.Read", "Mail.ReadWrite", "MailboxSettings.Read", "MailboxSettings.ReadWrite"]
          }
        ]
      },
      "patch": {
        "summary": "Update master category",
        "description": "Update a category in the user's master list",
        "operationId": "updateMasterCategory",
        "servers": [
          {
            "url": "https://graph.microsoft.com/v1.0",
            "description": "Available in v1.0"
          },
          {
            "url": "https://graph.microsoft.com/beta",
            "description": "Available in beta"
          }
        ],
        "security": [
          {
            "oauth2": ["MailboxSettings.ReadWrite"]
          }
        ]
      },
      "delete": {
        "summary": "Delete master category",
        "description": "Delete a category from the user's master list",
        "operationId": "deleteMasterCategory",
        "servers": [
          {
            "url": "https://graph.microsoft.com/v1.0",
            "description": "Available in v1.0"
          },
          {
            "url": "https://graph.microsoft.com/beta",
            "description": "Available in beta"
          }
        ],
        "security": [
          {
            "oauth2": ["MailboxSettings.ReadWrite"]
          }
        ]
      }
    },
    "/me/findRooms": {
      "get": {
        "summary": "Find rooms",
        "description": "Get all meeting rooms in the user's tenant",
        "operationId": "findRooms",
        "servers": [
          {
            "url": "https://graph.microsoft.com/beta",
            "description": "Only available in beta"
          }
        ],
        "security": [
          {
            "oauth2": ["Place.Read.All", "User.Read.All"]
          }
        ]
      }
    },
    "/me/findRooms(RoomList='{roomList-emailAddress}')": {
      "get": {
        "summary": "Find rooms in room list",
        "description": "Get all meeting rooms in a specific room list",
        "operationId": "findRoomsInList",
        "servers": [
          {
            "url": "https://graph.microsoft.com/beta",
            "description": "Only available in beta"
          }
        ],
        "security": [
          {
            "oauth2": ["Place.Read.All", "User.Read.All"]
          }
        ]
      }
    },
    "/me/findRoomLists": {
      "get": {
        "summary": "Find room lists",
        "description": "Get all room lists defined in the tenant",
        "operationId": "findRoomLists",
        "servers": [
          {
            "url": "https://graph.microsoft.com/beta",
            "description": "Only available in beta"
          }
        ],
        "security": [
          {
            "oauth2": ["Place.Read.All", "User.Read.All"]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "oauth2": {
        "type": "oauth2",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
            "tokenUrl": "https://login.microsoftonline.com/common/oauth2/v2.0/token",
            "scopes": {
              "Mail.Read": "Read user mail",
              "Mail.ReadWrite": "Read and write user mail",
              "Mail.Send": "Send mail as the user",
              "Mail.Read.Shared": "Read mail user can access",
              "Mail.ReadWrite.Shared": "Read and write mail user can access",
              "MailboxSettings.Read": "Read user mailbox settings",
              "MailboxSettings.ReadWrite": "Read and write user mailbox settings",
              "Place.Read.All": "Read all company places",
              "User.Read": "Sign in and read user profile",
              "User.Read.All": "Read all users' profiles"
            }
          },
          "clientCredentials": {
            "tokenUrl": "https://login.microsoftonline.com/common/oauth2/v2.0/token",
            "scopes": {
              "Mail.Read": "Read mail in all mailboxes",
              "Mail.ReadWrite": "Read and write mail in all mailboxes",
              "Mail.Send": "Send mail as any user",
              "MailboxSettings.Read": "Read all users' mailbox settings",
              "MailboxSettings.ReadWrite": "Read and write all users' mailbox settings",
              "Place.Read.All": "Read all company places",
              "User.Read.All": "Read all users' profiles"
            }
          }
        }
      }
    }
  },
  "security": [
    {
      "oauth2": []
    }
  ]
}