{
  "openapi": "3.1.0",
  "info": {
    "title": "Microsoft Graph SharePoint API",
    "description": "Microsoft Graph API specification for SharePoint sites, lists, list items, and pages",
    "version": "1.0.0",
    "contact": {
      "name": "Microsoft Graph",
      "url": "https://developer.microsoft.com/graph"
    }
  },
  "servers": [
    {
      "url": "https://graph.microsoft.com/v1.0",
      "description": "Microsoft Graph v1.0 endpoint"
    }
  ],
  "security": [
    {
      "oauth2": []
    }
  ],
  "paths": {
    "/sites": {
      "get": {
        "summary": "List sites",
        "description": "Search across SharePoint sites in the organization. Use $search=* to return all sites.",
        "operationId": "listSites",
        "tags": ["Sites"],
        "security": [
          {
            "oauth2": ["Sites.Read.All"]
          }
        ]
      }
    },
    "/sites/{site-id}": {
      "get": {
        "summary": "Get site",
        "description": "Retrieve the properties and relationships of a SharePoint site",
        "operationId": "getSite",
        "tags": ["Sites"],
        "security": [
          {
            "oauth2": ["Sites.Read.All"]
          }
        ]
      }
    },
    "/sites/{site-id}/analytics": {
      "get": {
        "summary": "Get site analytics",
        "description": "Retrieve analytics data for a SharePoint site",
        "operationId": "getSiteAnalytics",
        "tags": ["Analytics"],
        "security": [
          {
            "oauth2": ["Sites.Read.All"]
          }
        ]
      }
    },
    "/sites/{site-id}/pages": {
      "get": {
        "summary": "List site pages",
        "description": "Retrieve the pages in a SharePoint site",
        "operationId": "listSitePages",
        "tags": ["Pages"],
        "security": [
          {
            "oauth2": ["Sites.Read.All"]
          }
        ]
      }
    },
    "/sites/{site-id}/lists": {
      "get": {
        "summary": "List lists",
        "description": "Retrieve the collection of lists in a SharePoint site",
        "operationId": "listLists",
        "tags": ["Lists"],
        "security": [
          {
            "oauth2": ["Sites.Read.All"]
          }
        ]
      },
      "post": {
        "summary": "Create list",
        "description": "Create a new list in a SharePoint site",
        "operationId": "createList",
        "tags": ["Lists"],
        "security": [
          {
            "oauth2": ["Sites.ReadWrite.All"]
          }
        ]
      }
    },
    "/sites/{site-id}/lists/{list-id}": {
      "get": {
        "summary": "Get list",
        "description": "Retrieve the metadata for a list in a SharePoint site",
        "operationId": "getList",
        "tags": ["Lists"],
        "security": [
          {
            "oauth2": ["Sites.Read.All"]
          }
        ]
      }
    },
    "/sites/{site-id}/lists/{list-id}/items": {
      "get": {
        "summary": "List list items",
        "description": "Retrieve the collection of items in a SharePoint list",
        "operationId": "listListItems",
        "tags": ["ListItems"],
        "security": [
          {
            "oauth2": ["Sites.Read.All"]
          }
        ]
      },
      "post": {
        "summary": "Create list item",
        "description": "Create a new item in a SharePoint list",
        "operationId": "createListItem",
        "tags": ["ListItems"],
        "security": [
          {
            "oauth2": ["Sites.ReadWrite.All"]
          }
        ]
      }
    },
    "/sites/{site-id}/lists/{list-id}/items/{item-id}": {
      "get": {
        "summary": "Get list item",
        "description": "Retrieve the metadata and field values of a list item",
        "operationId": "getListItem",
        "tags": ["ListItems"],
        "security": [
          {
            "oauth2": ["Sites.Read.All"]
          }
        ]
      },
      "patch": {
        "summary": "Update list item",
        "description": "Update the column values of a list item",
        "operationId": "updateListItem",
        "tags": ["ListItems"],
        "security": [
          {
            "oauth2": ["Sites.ReadWrite.All"]
          }
        ]
      },
      "delete": {
        "summary": "Delete list item",
        "description": "Delete a list item from a SharePoint list",
        "operationId": "deleteListItem",
        "tags": ["ListItems"],
        "security": [
          {
            "oauth2": ["Sites.ReadWrite.All"]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "oauth2": {
        "type": "oauth2",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
            "tokenUrl": "https://login.microsoftonline.com/common/oauth2/v2.0/token",
            "scopes": {
              "Sites.Read.All": "Read items in all site collections",
              "Sites.ReadWrite.All": "Edit or delete items in all site collections",
              "Sites.Manage.All": "Create, edit, and delete items and lists in all site collections",
              "Sites.FullControl.All": "Have full control of all site collections",
              "offline_access": "Maintain access to data you have given access to"
            }
          }
        }
      }
    }
  },
  "tags": [
    {
      "name": "Sites",
      "description": "Operations on SharePoint sites"
    },
    {
      "name": "Lists",
      "description": "Operations on SharePoint lists"
    },
    {
      "name": "ListItems",
      "description": "Operations on list items"
    },
    {
      "name": "Pages",
      "description": "Operations on site pages"
    },
    {
      "name": "Analytics",
      "description": "Site usage analytics"
    }
  ]
}
