{
  "openapi": "3.1.0",
  "info": {
    "title": "Microsoft Graph SharePoint API",
    "description": "Microsoft Graph API specification for SharePoint sites, lists, list items, and pages",
    "version": "1.0.0",
    "contact": {
      "name": "Microsoft Graph",
      "url": "https://developer.microsoft.com/graph"
    }
  },
  "servers": [
    {
      "url": "https://graph.microsoft.com/v1.0",
      "description": "Microsoft Graph v1.0 endpoint"
    }
  ],
  "security": [
    {
      "oauth2": []
    }
  ],
  "paths": {
    "/sites": {
      "get": {
        "summary": "List sites",
        "description": "Search across SharePoint sites in the organization. Use search=* to return all sites.",
        "operationId": "listSites",
        "tags": ["Sites"],
        "security": [
          {
            "oauth2": ["Sites.Read.All"]
          }
        ]
      }
    },
    "/sites/{site-id}": {
      "get": {
        "summary": "Get site",
        "description": "Retrieve the properties and relationships of a SharePoint site",
        "operationId": "getSite",
        "tags": ["Sites"],
        "security": [
          {
            "oauth2": ["Sites.Read.All"]
          }
        ]
      }
    },
    "/sites/{site-id}/analytics": {
      "get": {
        "summary": "Get site analytics",
        "description": "Retrieve analytics data for a SharePoint site",
        "operationId": "getSiteAnalytics",
        "tags": ["Analytics"],
        "security": [
          {
            "oauth2": ["Sites.Read.All"]
          }
        ]
      }
    },
    "/sites/{site-id}/pages": {
      "get": {
        "summary": "List site pages",
        "description": "Retrieve the pages in a SharePoint site",
        "operationId": "listSitePages",
        "tags": ["Pages"],
        "security": [
          {
            "oauth2": ["Sites.Read.All"]
          }
        ]
      }
    },
    "/sites/{site-id}/lists": {
      "get": {
        "summary": "List lists",
        "description": "Retrieve the collection of lists in a SharePoint site",
        "operationId": "listLists",
        "tags": ["Lists"],
        "security": [
          {
            "oauth2": ["Sites.Read.All"]
          }
        ]
      },
      "post": {
        "summary": "Create list",
        "description": "Create a new list in a SharePoint site",
        "operationId": "createList",
        "tags": ["Lists"],
        "security": [
          {
            "oauth2": ["Sites.ReadWrite.All"]
          }
        ]
      }
    },
    "/sites/{site-id}/lists/{list-id}": {
      "get": {
        "summary": "Get list",
        "description": "Retrieve the metadata for a list in a SharePoint site",
        "operationId": "getList",
        "tags": ["Lists"],
        "security": [
          {
            "oauth2": ["Sites.Read.All"]
          }
        ]
      },
      "patch": {
        "summary": "Update list",
        "description": "Update the properties of a SharePoint list",
        "operationId": "updateList",
        "tags": ["Lists"],
        "security": [
          {
            "oauth2": ["Sites.ReadWrite.All"]
          }
        ]
      },
      "delete": {
        "summary": "Delete list",
        "description": "Delete a SharePoint list",
        "operationId": "deleteList",
        "tags": ["Lists"],
        "security": [
          {
            "oauth2": ["Sites.ReadWrite.All"]
          }
        ]
      }
    },
    "/sites/{site-id}/lists/{list-id}/items": {
      "get": {
        "summary": "List list items",
        "description": "Retrieve the collection of items in a SharePoint list",
        "operationId": "listListItems",
        "tags": ["ListItems"],
        "security": [
          {
            "oauth2": ["Sites.Read.All"]
          }
        ]
      },
      "post": {
        "summary": "Create list item",
        "description": "Create a new item in a SharePoint list",
        "operationId": "createListItem",
        "tags": ["ListItems"],
        "security": [
          {
            "oauth2": ["Sites.ReadWrite.All"]
          }
        ]
      }
    },
    "/sites/root/drive": {
      "get": {
        "summary": "Get root site drive",
        "description": "Get the default document library (drive) for the tenant's root SharePoint site",
        "operationId": "getRootSiteDrive",
        "tags": ["Drives"],
        "security": [{ "oauth2": ["Sites.Read.All"] }]
      }
    },
    "/sites/{site-id}/drive": {
      "get": {
        "summary": "Get site drive",
        "description": "Get the default document library (drive) for a SharePoint site. The returned id is used for file operations.",
        "operationId": "getSiteDrive",
        "tags": ["Drives"],
        "security": [{ "oauth2": ["Sites.Read.All"] }]
      }
    },
    "/sites/{site-id}/drives": {
      "get": {
        "summary": "List site drives",
        "description": "List all document libraries (drives) in a SharePoint site",
        "operationId": "listSiteDrives",
        "tags": ["Drives"],
        "security": [{ "oauth2": ["Sites.Read.All"] }]
      }
    },
    "/sites/{site-id}/drives/{drive-id}": {
      "get": {
        "summary": "Get site drive by ID",
        "description": "Get a specific document library (drive) in a SharePoint site by its drive ID",
        "operationId": "getSiteDriveById",
        "tags": ["Drives"],
        "security": [{ "oauth2": ["Sites.Read.All"] }]
      }
    },
    "/drives/{drive-id}/items/{item-id}/content": {
      "get": {
        "summary": "Download file",
        "description": "Download the binary content of a file from a SharePoint document library. Returns base64-encoded content with mimeType and size.",
        "operationId": "downloadSharePointFile",
        "tags": ["Files"],
        "security": [{ "oauth2": ["Sites.Read.All"] }]
      }
    },
    "/drives/{drive-id}/items/{item-id}/children": {
      "get": {
        "summary": "List folder contents",
        "description": "List the files and folders inside a SharePoint document library folder. Use the drive id from Get Site Drive.",
        "operationId": "listFolderContents",
        "tags": ["Files"],
        "security": [{ "oauth2": ["Sites.Read.All"] }]
      }
    },
    "/drives/{drive-id}/items/{item-id}": {
      "get": {
        "summary": "Get file or folder metadata",
        "description": "Get metadata for a file or folder. The response includes @microsoft.graph.downloadUrl which can be used directly as a download link (valid for 1 hour).",
        "operationId": "getDriveItem",
        "tags": ["Files"],
        "security": [{ "oauth2": ["Sites.Read.All"] }]
      },
      "delete": {
        "summary": "Delete file or folder",
        "description": "Delete a file or folder from a SharePoint document library",
        "operationId": "deleteDriveItem",
        "tags": ["Files"],
        "security": [{ "oauth2": ["Sites.ReadWrite.All"] }]
      }
    },
    "/drives/{drive-id}/items/{parent-item-id}:/{filename}:/content": {
      "put": {
        "summary": "Upload file to folder",
        "description": "Upload a file (up to 4 MB) to a folder in a SharePoint document library. Provide fileContent as a base64-encoded string.",
        "operationId": "uploadFileToFolder",
        "tags": ["Files"],
        "security": [{ "oauth2": ["Sites.ReadWrite.All"] }]
      }
    },
    "/sites/{site-id}/lists/{list-id}/items/{item-id}": {
      "get": {
        "summary": "Get list item",
        "description": "Retrieve the metadata and field values of a list item",
        "operationId": "getListItem",
        "tags": ["ListItems"],
        "security": [
          {
            "oauth2": ["Sites.Read.All"]
          }
        ]
      },
      "patch": {
        "summary": "Update list item",
        "description": "Update the column values of a list item",
        "operationId": "updateListItem",
        "tags": ["ListItems"],
        "security": [
          {
            "oauth2": ["Sites.ReadWrite.All"]
          }
        ]
      },
      "delete": {
        "summary": "Delete list item",
        "description": "Delete a list item from a SharePoint list",
        "operationId": "deleteListItem",
        "tags": ["ListItems"],
        "security": [
          {
            "oauth2": ["Sites.ReadWrite.All"]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "oauth2": {
        "type": "oauth2",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
            "tokenUrl": "https://login.microsoftonline.com/common/oauth2/v2.0/token",
            "scopes": {
              "Sites.Read.All": "Read items in all site collections",
              "Sites.ReadWrite.All": "Edit or delete items in all site collections",
              "Sites.Manage.All": "Create, edit, and delete items and lists in all site collections",
              "Sites.FullControl.All": "Have full control of all site collections",
              "offline_access": "Maintain access to data you have given access to"
            }
          }
        }
      }
    }
  },
  "tags": [
    {
      "name": "Sites",
      "description": "Operations on SharePoint sites"
    },
    {
      "name": "Lists",
      "description": "Operations on SharePoint lists"
    },
    {
      "name": "ListItems",
      "description": "Operations on list items"
    },
    {
      "name": "Pages",
      "description": "Operations on site pages"
    },
    {
      "name": "Analytics",
      "description": "Site usage analytics"
    },
    {
      "name": "Drives",
      "description": "SharePoint document library drives"
    },
    {
      "name": "Files",
      "description": "File and folder operations in SharePoint document libraries"
    }
  ]
}
