{
  "openapi": "3.1.0",
  "info": {
    "title": "Microsoft Graph API - Users",
    "version": "1.0",
    "description": "Microsoft Graph API specification for /users and /users/{user-id} endpoints including all basic operations"
  },
  "servers": [
    {
      "url": "https://graph.microsoft.com/v1.0",
      "description": "Microsoft Graph API v1.0"
    }
  ],
  "paths": {
    "/users": {
      "get": {
        "summary": "List users",
        "description": "Retrieve a list of user objects from Azure AD",
        "operationId": "listUsers",
        "security": [
          {
            "oauth2": ["User.Read.All", "User.ReadWrite.All", "Directory.Read.All", "Directory.ReadWrite.All"]
          }
        ]
      },
      "post": {
        "summary": "Create user",
        "description": "Create a new user in Azure AD",
        "operationId": "createUser",
        "security": [
          {
            "oauth2": ["User.ReadWrite.All", "Directory.ReadWrite.All"]
          }
        ]
      }
    },
    "/users/{user-id}": {
      "get": {
        "summary": "Get user",
        "description": "Retrieve the properties and relationships of a user object",
        "operationId": "getUser",
        "security": [
          {
            "oauth2": ["User.Read", "User.Read.All", "User.ReadWrite", "User.ReadWrite.All", "Directory.Read.All", "Directory.ReadWrite.All"]
          }
        ]
      },
      "patch": {
        "summary": "Update user",
        "description": "Update the properties of a user object",
        "operationId": "updateUser",
        "security": [
          {
            "oauth2": ["User.ReadWrite", "User.ReadWrite.All", "Directory.ReadWrite.All"]
          }
        ]
      },
      "delete": {
        "summary": "Delete user",
        "description": "Delete a user. Deleted users are moved to a temporary container and can be restored within 30 days",
        "operationId": "deleteUser",
        "security": [
          {
            "oauth2": ["User.ReadWrite.All", "Directory.ReadWrite.All"]
          }
        ]
      }
    },
    "/me": {
      "get": {
        "summary": "Get current user",
        "description": "Retrieve the properties and relationships of the signed-in user",
        "operationId": "getCurrentUser",
        "security": [
          {
            "oauth2": ["User.Read", "User.ReadWrite"]
          }
        ]
      },
      "patch": {
        "summary": "Update current user",
        "description": "Update the properties of the signed-in user",
        "operationId": "updateCurrentUser",
        "security": [
          {
            "oauth2": ["User.ReadWrite"]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "oauth2": {
        "type": "oauth2",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
            "tokenUrl": "https://login.microsoftonline.com/common/oauth2/v2.0/token",
            "scopes": {
              "User.Read": "Read user profile",
              "User.ReadWrite": "Read and write user profile",
              "User.Read.All": "Read all users' profiles",
              "User.ReadWrite.All": "Read and write all users' profiles",
              "Directory.Read.All": "Read directory data",
              "Directory.ReadWrite.All": "Read and write directory data",
              "Directory.AccessAsUser.All": "Access directory as the signed-in user"
            }
          },
          "clientCredentials": {
            "tokenUrl": "https://login.microsoftonline.com/common/oauth2/v2.0/token",
            "scopes": {
              "User.Read.All": "Read all users' profiles",
              "User.ReadWrite.All": "Read and write all users' profiles",
              "Directory.Read.All": "Read directory data",
              "Directory.ReadWrite.All": "Read and write directory data"
            }
          }
        }
      }
    }
  },
  "security": [
    {
      "oauth2": []
    }
  ]
}
