openapi: 3.0.0
info:
  title: Xero Accounting API
  version: 12.0.0
  termsOfService: https://developer.xero.com/xero-developer-platform-terms-conditions/
  contact:
    name: Xero Platform Team
    email: api@xero.com
    url: https://developer.xero.com
servers:
  - description: The Xero Accounting API exposes accounting and related functions of the main Xero application and can be used for a variety of purposes such as creating transactions like invoices and credit notes, right through to extracting accounting data via our reports endpoint.
    url: https://api.xero.com/api.xro/2.0
paths:
  /Accounts:
    get:
      security:
        - OAuth2:
            - accounting.settings
            - accounting.settings.read
      tags:
        - Accounting
      operationId: getAccounts
      summary: Retrieves the full chart of accounts
    put:
      security:
        - OAuth2:
            - accounting.settings
      tags:
        - Accounting
      operationId: createAccount
      summary: Creates a new chart of accounts
      x-hasAccountingValidationError: true
  /Accounts/{AccountID}:
    get:
      security:
        - OAuth2:
            - accounting.settings
            - accounting.settings.read
      tags:
        - Accounting
      operationId: getAccount
      summary: Retrieves a single chart of accounts by using a unique account Id
    post:
      security:
        - OAuth2:
            - accounting.settings
      tags:
        - Accounting
      operationId: updateAccount
      summary: Updates a chart of accounts
      x-hasAccountingValidationError: true
    delete:
      security:
        - OAuth2:
            - accounting.settings
      tags:
        - Accounting
      operationId: deleteAccount
      x-hasAccountingValidationError: true
      summary: Deletes a chart of accounts
  /Accounts/{AccountID}/Attachments:
    get:
      security:
        - OAuth2:
            - accounting.attachments
            - accounting.attachments.read
      tags:
        - Accounting
      operationId: getAccountAttachments
      summary: Retrieves attachments for a specific accounts by using a unique account Id
  /Accounts/{AccountID}/Attachments/{AttachmentID}:
    get:
      security:
        - OAuth2:
            - accounting.attachments
            - accounting.attachments.read
      tags:
        - Accounting
      operationId: getAccountAttachmentById
      summary: Retrieves a specific attachment from a specific account using a unique attachment Id
  /Accounts/{AccountID}/Attachments/{FileName}:
    get:
      security:
        - OAuth2:
            - accounting.attachments
            - accounting.attachments.read
      tags:
        - Accounting
      operationId: getAccountAttachmentByFileName
      summary: Retrieves an attachment for a specific account by filename
    post:
      security:
        - OAuth2:
            - accounting.attachments
      tags:
        - Accounting
      operationId: updateAccountAttachmentByFileName
      x-hasAccountingValidationError: true
      summary: Updates attachment on a specific account by filename
    put:
      security:
        - OAuth2:
            - accounting.attachments
      tags:
        - Accounting
      operationId: createAccountAttachmentByFileName
      x-hasAccountingValidationError: true
      summary: Creates an attachment on a specific account
  /BatchPayments:
    description: Batch payments allow you to bundle multiple bills or invoices into one payment transaction. This means a single payment in Xero can be reconciled with a single transaction on the bank statement making for a much simpler bank reconciliation experience.
    get:
      security:
        - OAuth2:
            - accounting.transactions
            - accounting.transactions.read
      tags:
        - Accounting
      operationId: getBatchPayments
      summary: Retrieves either one or many batch payments for invoices
    put:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: createBatchPayment
      summary: Creates one or many batch payments for invoices
      x-hasAccountingValidationError: true
    post:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: deleteBatchPayment
      summary: Updates a specific batch payment for invoices and credit notes
      x-hasAccountingValidationError: true
  /BatchPayments/{BatchPaymentID}:
    get:
      security:
        - OAuth2:
            - accounting.transactions
            - accounting.transactions.read
      tags:
        - Accounting
      operationId: getBatchPayment
      summary: Retrieves a specific batch payment using a unique batch payment Id
    post:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: deleteBatchPaymentByUrlParam
      summary: Updates a specific batch payment for invoices and credit notes
  /BatchPayments/{BatchPaymentID}/History:
    get:
      security:
        - OAuth2:
            - accounting.transactions
            - accounting.transactions.read
      tags:
        - Accounting
      operationId: getBatchPaymentHistory
      summary: Retrieves history from a specific batch payment
    put:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: createBatchPaymentHistoryRecord
      summary: Creates a history record for a specific batch payment
      x-hasAccountingValidationError: true
  /BankTransactions:
    get:
      security:
        - OAuth2:
            - accounting.transactions
            - accounting.transactions.read
      tags:
        - Accounting
      operationId: getBankTransactions
      summary: Retrieves any spent or received money transactions
    put:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: createBankTransactions
      summary: Creates one or more spent or received money transaction
      x-hasAccountingValidationError: true
    post:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: updateOrCreateBankTransactions
      summary: Updates or creates one or more spent or received money transaction
      x-hasAccountingValidationError: true
  /BankTransactions/{BankTransactionID}:
    get:
      security:
        - OAuth2:
            - accounting.transactions
            - accounting.transactions.read
      tags:
        - Accounting
      operationId: getBankTransaction
      summary: Retrieves a single spent or received money transaction by using a unique bank transaction Id
    post:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: updateBankTransaction
      summary: Updates a single spent or received money transaction
      x-hasAccountingValidationError: true
  /BankTransactions/{BankTransactionID}/Attachments:
    get:
      security:
        - OAuth2:
            - accounting.attachments
            - accounting.attachments.read
      tags:
        - Accounting
      operationId: getBankTransactionAttachments
      summary: Retrieves any attachments from a specific bank transactions
  /BankTransactions/{BankTransactionID}/Attachments/{AttachmentID}:
    get:
      security:
        - OAuth2:
            - accounting.attachments
            - accounting.attachments.read
      tags:
        - Accounting
      operationId: getBankTransactionAttachmentById
      summary: Retrieves specific attachments from a specific BankTransaction using a unique attachment Id
  /BankTransactions/{BankTransactionID}/Attachments/{FileName}:
    get:
      security:
        - OAuth2:
            - accounting.attachments
            - accounting.attachments.read
      tags:
        - Accounting
      operationId: getBankTransactionAttachmentByFileName
      summary: Retrieves a specific attachment from a specific bank transaction by filename
    post:
      security:
        - OAuth2:
            - accounting.attachments
      tags:
        - Accounting
      operationId: updateBankTransactionAttachmentByFileName
      x-hasAccountingValidationError: true
      summary: Updates a specific attachment from a specific bank transaction by filename
    put:
      security:
        - OAuth2:
            - accounting.attachments
      tags:
        - Accounting
      operationId: createBankTransactionAttachmentByFileName
      x-hasAccountingValidationError: true
      summary: Creates an attachment for a specific bank transaction by filename
  /BankTransactions/{BankTransactionID}/History:
    get:
      security:
        - OAuth2:
            - accounting.transactions
            - accounting.transactions.read
      tags:
        - Accounting
      operationId: getBankTransactionsHistory
      summary: Retrieves history from a specific bank transaction using a unique bank transaction Id
    put:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: createBankTransactionHistoryRecord
      summary: Creates a history record for a specific bank transactions
      x-hasAccountingValidationError: true
  /BankTransfers:
    get:
      security:
        - OAuth2:
            - accounting.transactions
            - accounting.transactions.read
      tags:
        - Accounting
      operationId: getBankTransfers
      summary: Retrieves all bank transfers
    put:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: createBankTransfer
      summary: Creates a bank transfer
      x-hasAccountingValidationError: true
  /BankTransfers/{BankTransferID}:
    get:
      security:
        - OAuth2:
            - accounting.transactions
            - accounting.transactions.read
      tags:
        - Accounting
      operationId: getBankTransfer
      summary: Retrieves specific bank transfers by using a unique bank transfer Id
  /BankTransfers/{BankTransferID}/Attachments:
    get:
      security:
        - OAuth2:
            - accounting.attachments
            - accounting.attachments.read
      tags:
        - Accounting
      operationId: getBankTransferAttachments
      summary: Retrieves attachments from a specific bank transfer
  /BankTransfers/{BankTransferID}/Attachments/{AttachmentID}:
    get:
      security:
        - OAuth2:
            - accounting.attachments
            - accounting.attachments.read
      tags:
        - Accounting
      operationId: getBankTransferAttachmentById
      summary: Retrieves a specific attachment from a specific bank transfer using a unique attachment ID
  /BankTransfers/{BankTransferID}/Attachments/{FileName}:
    get:
      security:
        - OAuth2:
            - accounting.attachments
            - accounting.attachments.read
      tags:
        - Accounting
      operationId: getBankTransferAttachmentByFileName
      summary: Retrieves a specific attachment on a specific bank transfer by file name
    post:
      security:
        - OAuth2:
            - accounting.attachments
      tags:
        - Accounting
      operationId: updateBankTransferAttachmentByFileName
      x-hasAccountingValidationError: true
    put:
      security:
        - OAuth2:
            - accounting.attachments
      tags:
        - Accounting
      operationId: createBankTransferAttachmentByFileName
      x-hasAccountingValidationError: true
  /BankTransfers/{BankTransferID}/History:
    get:
      security:
        - OAuth2:
            - accounting.transactions
            - accounting.transactions.read
      tags:
        - Accounting
      operationId: getBankTransferHistory
      summary: Retrieves history from a specific bank transfer using a unique bank transfer Id
    put:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: createBankTransferHistoryRecord
      summary: Creates a history record for a specific bank transfer
      x-hasAccountingValidationError: true
  /BrandingThemes:
    get:
      security:
        - OAuth2:
            - accounting.settings
            - accounting.settings.read
      tags:
        - Accounting
      operationId: getBrandingThemes
      summary: Retrieves all the branding themes
  /BrandingThemes/{BrandingThemeID}:
    get:
      security:
        - OAuth2:
            - accounting.settings
            - accounting.settings.read
      tags:
        - Accounting
      operationId: getBrandingTheme
      summary: Retrieves a specific branding theme using a unique branding theme Id
  /BrandingThemes/{BrandingThemeID}/PaymentServices:
    get:
      security:
        - OAuth2:
            - paymentservices
      tags:
        - Accounting
      operationId: getBrandingThemePaymentServices
      summary: Retrieves the payment services for a specific branding theme
      x-excludeFromPreview: true
    post:
      security:
        - OAuth2:
            - paymentservices
      tags:
        - Accounting
      operationId: createBrandingThemePaymentServices
      summary: Creates a new custom payment service for a specific branding theme
      x-excludeFromPreview: true
      x-hasAccountingValidationError: true
  /Budgets:
    get:
      security:
        - OAuth2:
            - accounting.budgets.read
      tags:
        - Accounting
      operationId: getBudgets
      summary: Retrieve a list of budgets
  /Budgets/{BudgetID}:
    get:
      security:
        - OAuth2:
            - accounting.budgets.read
      tags:
        - Accounting
      operationId: getBudget
      summary: Retrieves a specific budget, which includes budget lines
  /Contacts:
    get:
      security:
        - OAuth2:
            - accounting.contacts
            - accounting.contacts.read
      tags:
        - Accounting
      operationId: getContacts
      summary: Retrieves all contacts in a Xero organisation
    put:
      security:
        - OAuth2:
            - accounting.contacts
      tags:
        - Accounting
      operationId: createContacts
      summary: Creates multiple contacts (bulk) in a Xero organisation
      x-hasAccountingValidationError: true
    post:
      security:
        - OAuth2:
            - accounting.contacts
      tags:
        - Accounting
      operationId: updateOrCreateContacts
      summary: Updates or creates one or more contacts in a Xero organisation
      x-hasAccountingValidationError: true
  /Contacts/{ContactNumber}:
    get:
      security:
        - OAuth2:
            - accounting.contacts
            - accounting.contacts.read
      tags:
        - Accounting
      operationId: getContactByContactNumber
      summary: Retrieves a specific contact by contact number in a Xero organisation
  /Contacts/{ContactID}:
    get:
      security:
        - OAuth2:
            - accounting.contacts
            - accounting.contacts.read
      tags:
        - Accounting
      operationId: getContact
      summary: Retrieves a specific contacts in a Xero organisation using a unique contact Id
    post:
      security:
        - OAuth2:
            - accounting.contacts
      tags:
        - Accounting
      operationId: updateContact
      summary: Updates a specific contact in a Xero organisation
      x-hasAccountingValidationError: true
  /Contacts/{ContactID}/Attachments:
    get:
      security:
        - OAuth2:
            - accounting.attachments
            - accounting.attachments.read
      tags:
        - Accounting
      operationId: getContactAttachments
      x-hasAccountingValidationError: true
      summary: Retrieves attachments for a specific contact in a Xero organisation
  /Contacts/{ContactID}/Attachments/{AttachmentID}:
    get:
      security:
        - OAuth2:
            - accounting.attachments
            - accounting.attachments.read
      tags:
        - Accounting
      operationId: getContactAttachmentById
      summary: Retrieves a specific attachment from a specific contact using a unique attachment Id
  /Contacts/{ContactID}/Attachments/{FileName}:
    get:
      security:
        - OAuth2:
            - accounting.attachments
            - accounting.attachments.read
      tags:
        - Accounting
      operationId: getContactAttachmentByFileName
      summary: Retrieves a specific attachment from a specific contact by file name
    post:
      security:
        - OAuth2:
            - accounting.attachments
      tags:
        - Accounting
      operationId: updateContactAttachmentByFileName
      x-hasAccountingValidationError: true
    put:
      security:
        - OAuth2:
            - accounting.attachments
      tags:
        - Accounting
      operationId: createContactAttachmentByFileName
      x-hasAccountingValidationError: true
  /Contacts/{ContactID}/CISSettings:
    get:
      security:
        - OAuth2:
            - accounting.settings
            - accounting.settings.read
      tags:
        - Accounting
      operationId: getContactCISSettings
      summary: Retrieves CIS settings for a specific contact in a Xero organisation
  /Contacts/{ContactID}/History:
    get:
      security:
        - OAuth2:
            - accounting.contacts
            - accounting.contacts.read
      tags:
        - Accounting
      operationId: getContactHistory
      summary: Retrieves history records for a specific contact
    put:
      security:
        - OAuth2:
            - accounting.contacts
      tags:
        - Accounting
      operationId: createContactHistory
      summary: Creates a new history record for a specific contact
      x-hasAccountingValidationError: true
  /ContactGroups:
    get:
      security:
        - OAuth2:
            - accounting.contacts
            - accounting.contacts.read
      tags:
        - Accounting
      operationId: getContactGroups
      summary: Retrieves the contact Id and name of each contact group
    put:
      security:
        - OAuth2:
            - accounting.contacts
      tags:
        - Accounting
      operationId: createContactGroup
      summary: Creates a contact group
      x-hasAccountingValidationError: true
  /ContactGroups/{ContactGroupID}:
    get:
      security:
        - OAuth2:
            - accounting.contacts
            - accounting.contacts.read
      tags:
        - Accounting
      operationId: getContactGroup
      summary: Retrieves a specific contact group by using a unique contact group Id
    post:
      security:
        - OAuth2:
            - accounting.contacts
      tags:
        - Accounting
      operationId: updateContactGroup
      summary: Updates a specific contact group
      x-hasAccountingValidationError: true
  /ContactGroups/{ContactGroupID}/Contacts:
    put:
      security:
        - OAuth2:
            - accounting.contacts
      tags:
        - Accounting
      operationId: createContactGroupContacts
      summary: Creates contacts to a specific contact group
      x-hasAccountingValidationError: true
    delete:
      security:
        - OAuth2:
            - accounting.contacts
      tags:
        - Accounting
      operationId: deleteContactGroupContacts
      summary: Deletes all contacts from a specific contact group
  /ContactGroups/{ContactGroupID}/Contacts/{ContactID}:
    delete:
      security:
        - OAuth2:
            - accounting.contacts
      tags:
        - Accounting
      operationId: deleteContactGroupContact
      summary: Deletes a specific contact from a contact group using a unique contact Id
  /CreditNotes:
    get:
      security:
        - OAuth2:
            - accounting.transactions
            - accounting.transactions.read
      tags:
        - Accounting
      operationId: getCreditNotes
      summary: Retrieves any credit notes
    put:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: createCreditNotes
      summary: Creates a new credit note
      x-hasAccountingValidationError: true
    post:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: updateOrCreateCreditNotes
      summary: Updates or creates one or more credit notes
      x-hasAccountingValidationError: true
  /CreditNotes/{CreditNoteID}:
    get:
      security:
        - OAuth2:
            - accounting.transactions
            - accounting.transactions.read
      tags:
        - Accounting
      operationId: getCreditNote
      summary: Retrieves a specific credit note using a unique credit note Id
    post:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: updateCreditNote
      summary: Updates a specific credit note
      x-hasAccountingValidationError: true
  /CreditNotes/{CreditNoteID}/Attachments:
    get:
      security:
        - OAuth2:
            - accounting.attachments
            - accounting.attachments.read
      tags:
        - Accounting
      operationId: getCreditNoteAttachments
      summary: Retrieves attachments for a specific credit notes
  /CreditNotes/{CreditNoteID}/Attachments/{AttachmentID}:
    get:
      security:
        - OAuth2:
            - accounting.attachments
            - accounting.attachments.read
      tags:
        - Accounting
      operationId: getCreditNoteAttachmentById
      summary: Retrieves a specific attachment from a specific credit note using a unique attachment Id
  /CreditNotes/{CreditNoteID}/Attachments/{FileName}:
    get:
      security:
        - OAuth2:
            - accounting.attachments
            - accounting.attachments.read
      tags:
        - Accounting
      operationId: getCreditNoteAttachmentByFileName
      summary: Retrieves a specific attachment on a specific credit note by file name
    post:
      security:
        - OAuth2:
            - accounting.attachments
      tags:
        - Accounting
      operationId: updateCreditNoteAttachmentByFileName
      x-hasAccountingValidationError: true
      summary: Updates attachments on a specific credit note by file name
    put:
      security:
        - OAuth2:
            - accounting.attachments
      tags:
        - Accounting
      operationId: createCreditNoteAttachmentByFileName
      x-hasAccountingValidationError: true
      summary: Creates an attachment for a specific credit note
  /CreditNotes/{CreditNoteID}/pdf:
    get:
      security:
        - OAuth2:
            - accounting.transactions
            - accounting.transactions.read
      tags:
        - Accounting
      operationId: getCreditNoteAsPdf
      x-path: /CreditNotes/{CreditNoteID}
      summary: Retrieves credit notes as PDF files
  /CreditNotes/{CreditNoteID}/Allocations:
    put:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: createCreditNoteAllocation
      summary: Creates allocation for a specific credit note
      x-hasAccountingValidationError: true
  /CreditNotes/{CreditNoteID}/Allocations/{AllocationID}:
    delete:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: deleteCreditNoteAllocations
      summary: Deletes an Allocation from a Credit Note
  /CreditNotes/{CreditNoteID}/History:
    get:
      security:
        - OAuth2:
            - accounting.transactions
            - accounting.transactions.read
      tags:
        - Accounting
      operationId: getCreditNoteHistory
      summary: Retrieves history records of a specific credit note
    put:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: createCreditNoteHistory
      summary: Retrieves history records of a specific credit note
      x-hasAccountingValidationError: true
  /Currencies:
    get:
      security:
        - OAuth2:
            - accounting.settings
            - accounting.settings.read
      tags:
        - Accounting
      operationId: getCurrencies
      summary: Retrieves currencies for your Xero organisation
    put:
      security:
        - OAuth2:
            - accounting.settings
      tags:
        - Accounting
      operationId: createCurrency
      summary: Create a new currency for a Xero organisation
      x-hasAccountingValidationError: true
  /Employees:
    get:
      deprecated: true
      security:
        - OAuth2:
            - accounting.settings
            - accounting.settings.read
      tags:
        - Accounting
      operationId: getEmployees
      summary: Retrieves employees used in Xero payrun
      description: This endpoint is deprecated and will be removed April 28, 2026
    put:
      deprecated: true
      security:
        - OAuth2:
            - accounting.settings
      tags:
        - Accounting
      operationId: createEmployees
      summary: Creates new employees used in Xero payrun
      description: This endpoint is deprecated and will be removed April 28, 2026
      x-hasAccountingValidationError: true
    post:
      deprecated: true
      security:
        - OAuth2:
            - accounting.settings
      tags:
        - Accounting
      operationId: updateOrCreateEmployees
      summary: Creates a single new employees used in Xero payrun
      description: This endpoint is deprecated and will be removed April 28, 2026
      x-hasAccountingValidationError: true
  /Employees/{EmployeeID}:
    get:
      deprecated: true
      security:
        - OAuth2:
            - accounting.settings
            - accounting.settings.read
      tags:
        - Accounting
      operationId: getEmployee
      summary: Retrieves a specific employee used in Xero payrun using a unique employee Id
      description: This endpoint is deprecated and will be removed April 28, 2026
  /ExpenseClaims:
    get:
      security:
        - OAuth2:
            - accounting.transactions
            - accounting.transactions.read
      tags:
        - Accounting
      operationId: getExpenseClaims
      summary: Retrieves expense claims
    put:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: createExpenseClaims
      summary: Creates expense claims
      x-hasAccountingValidationError: true
  /ExpenseClaims/{ExpenseClaimID}:
    get:
      security:
        - OAuth2:
            - accounting.transactions
            - accounting.transactions.read
      tags:
        - Accounting
      operationId: getExpenseClaim
      summary: Retrieves a specific expense claim using a unique expense claim Id
    post:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: updateExpenseClaim
      summary: Updates a specific expense claims
      x-hasAccountingValidationError: true
  /ExpenseClaims/{ExpenseClaimID}/History:
    get:
      security:
        - OAuth2:
            - accounting.transactions
            - accounting.transactions.read
      tags:
        - Accounting
      operationId: getExpenseClaimHistory
      summary: Retrieves history records of a specific expense claim
    put:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: createExpenseClaimHistory
      summary: Creates a history record for a specific expense claim
      x-hasAccountingValidationError: true
  /Invoices:
    get:
      security:
        - OAuth2:
            - accounting.transactions
            - accounting.transactions.read
      tags:
        - Accounting
      operationId: getInvoices
      summary: Retrieves sales invoices or purchase bills
    put:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: createInvoices
      summary: Creates one or more sales invoices or purchase bills
      x-hasAccountingValidationError: true
    post:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: updateOrCreateInvoices
      summary: Updates or creates one or more sales invoices or purchase bills
      x-hasAccountingValidationError: true
  /Invoices/{InvoiceID}:
    get:
      security:
        - OAuth2:
            - accounting.transactions
            - accounting.transactions.read
      tags:
        - Accounting
      operationId: getInvoice
      summary: Retrieves a specific sales invoice or purchase bill using a unique invoice Id
    post:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: updateInvoice
      summary: Updates a specific sales invoices or purchase bills
      x-hasAccountingValidationError: true
  /Invoices/{InvoiceID}/pdf:
    get:
      security:
        - OAuth2:
            - accounting.transactions
            - accounting.transactions.read
      tags:
        - Accounting
      operationId: getInvoiceAsPdf
      x-path: /Invoices/{InvoiceID}
      summary: Retrieves invoices or purchase bills as PDF files
  /Invoices/{InvoiceID}/Attachments:
    get:
      security:
        - OAuth2:
            - accounting.attachments
            - accounting.attachments.read
      tags:
        - Accounting
      operationId: getInvoiceAttachments
      summary: Retrieves attachments for a specific invoice or purchase bill
  /Invoices/{InvoiceID}/Attachments/{AttachmentID}:
    get:
      security:
        - OAuth2:
            - accounting.attachments
            - accounting.attachments.read
      tags:
        - Accounting
      operationId: getInvoiceAttachmentById
      summary: Retrieves a specific attachment from a specific invoices or purchase bills by using a unique attachment Id
  /Invoices/{InvoiceID}/Attachments/{FileName}:
    get:
      security:
        - OAuth2:
            - accounting.attachments
            - accounting.attachments.read
      tags:
        - Accounting
      operationId: getInvoiceAttachmentByFileName
      summary: Retrieves an attachment from a specific invoice or purchase bill by filename
    post:
      security:
        - OAuth2:
            - accounting.attachments
      tags:
        - Accounting
      operationId: updateInvoiceAttachmentByFileName
      x-hasAccountingValidationError: true
      summary: Updates an attachment from a specific invoices or purchase bill by filename
    put:
      security:
        - OAuth2:
            - accounting.attachments
      tags:
        - Accounting
      operationId: createInvoiceAttachmentByFileName
      x-hasAccountingValidationError: true
      summary: Creates an attachment for a specific invoice or purchase bill by filename
  /Invoices/{InvoiceID}/OnlineInvoice:
    get:
      security:
        - OAuth2:
            - accounting.transactions
            - accounting.transactions.read
      tags:
        - Accounting
      operationId: getOnlineInvoice
      summary: Retrieves a URL to an online invoice
  /Invoices/{InvoiceID}/Email:
    post:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: emailInvoice
      summary: Sends a copy of a specific invoice to related contact via email
      x-hasAccountingValidationError: true
  /Invoices/{InvoiceID}/History:
    get:
      security:
        - OAuth2:
            - accounting.transactions
            - accounting.transactions.read
      tags:
        - Accounting
      operationId: getInvoiceHistory
      summary: Retrieves history records for a specific invoice
    put:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: createInvoiceHistory
      summary: Creates a history record for a specific invoice
      x-hasAccountingValidationError: true
  /InvoiceReminders/Settings:
    get:
      security:
        - OAuth2:
            - accounting.settings
            - accounting.settings.read
      tags:
        - Accounting
      operationId: getInvoiceReminders
      summary: Retrieves invoice reminder settings
  /Items:
    get:
      security:
        - OAuth2:
            - accounting.settings
            - accounting.settings.read
      tags:
        - Accounting
      operationId: getItems
      summary: Retrieves items
    put:
      security:
        - OAuth2:
            - accounting.settings
      tags:
        - Accounting
      operationId: createItems
      summary: Creates one or more items
      x-hasAccountingValidationError: true
    post:
      security:
        - OAuth2:
            - accounting.settings
      tags:
        - Accounting
      operationId: updateOrCreateItems
      summary: Updates or creates one or more items
      x-hasAccountingValidationError: true
  /Items/{ItemID}:
    get:
      security:
        - OAuth2:
            - accounting.settings
            - accounting.settings.read
      tags:
        - Accounting
      operationId: getItem
      summary: Retrieves a specific item using a unique item Id
    post:
      security:
        - OAuth2:
            - accounting.settings
      tags:
        - Accounting
      operationId: updateItem
      summary: Updates a specific item
      x-hasAccountingValidationError: true
    delete:
      security:
        - OAuth2:
            - accounting.settings
      tags:
        - Accounting
      operationId: deleteItem
      summary: Deletes a specific item
  /Items/{ItemID}/History:
    get:
      security:
        - OAuth2:
            - accounting.settings
            - accounting.settings.read
      tags:
        - Accounting
      operationId: getItemHistory
      summary: Retrieves history for a specific item
    put:
      security:
        - OAuth2:
            - accounting.settings
      tags:
        - Accounting
      operationId: createItemHistory
      summary: Creates a history record for a specific item
      x-hasAccountingValidationError: true
  /Journals:
    get:
      security:
        - OAuth2:
            - accounting.journals.read
      tags:
        - Accounting
      operationId: getJournals
      summary: Retrieves journals
  /Journals/{JournalID}:
    get:
      security:
        - OAuth2:
            - accounting.journals.read
      tags:
        - Accounting
      operationId: getJournal
      summary: Retrieves a specific journal using a unique journal Id.
  /Journals/{JournalNumber}:
    get:
      security:
        - OAuth2:
            - accounting.journals.read
      tags:
        - Accounting
      operationId: getJournalByNumber
      summary: Retrieves a specific journal using a unique journal number.
  /LinkedTransactions:
    get:
      security:
        - OAuth2:
            - accounting.transactions
            - accounting.transactions.read
      tags:
        - Accounting
      operationId: getLinkedTransactions
      summary: Retrieves linked transactions (billable expenses)
    put:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: createLinkedTransaction
      summary: Creates linked transactions (billable expenses)
      x-hasAccountingValidationError: true
  /LinkedTransactions/{LinkedTransactionID}:
    get:
      security:
        - OAuth2:
            - accounting.transactions
            - accounting.transactions.read
      tags:
        - Accounting
      operationId: getLinkedTransaction
      summary: Retrieves a specific linked transaction (billable expenses) using a unique linked transaction Id
    post:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: updateLinkedTransaction
      summary: Updates a specific linked transactions (billable expenses)
      x-hasAccountingValidationError: true
    delete:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: deleteLinkedTransaction
      summary: Deletes a specific linked transactions (billable expenses)
  /ManualJournals:
    get:
      security:
        - OAuth2:
            - accounting.transactions
            - accounting.transactions.read
      tags:
        - Accounting
      operationId: getManualJournals
      summary: Retrieves manual journals
    put:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: createManualJournals
      summary: Creates one or more manual journals
      x-hasAccountingValidationError: true
    post:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: updateOrCreateManualJournals
      summary: Updates or creates a single manual journal
      x-hasAccountingValidationError: true
  /ManualJournals/{ManualJournalID}:
    get:
      security:
        - OAuth2:
            - accounting.transactions
            - accounting.transactions.read
      tags:
        - Accounting
      operationId: getManualJournal
      summary: Retrieves a specific manual journal
    post:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: updateManualJournal
      summary: Updates a specific manual journal
      x-hasAccountingValidationError: true
  /ManualJournals/{ManualJournalID}/Attachments:
    get:
      security:
        - OAuth2:
            - accounting.attachments
            - accounting.attachments.read
      tags:
        - Accounting
      operationId: getManualJournalAttachments
      summary: Retrieves attachment for a specific manual journal
  /ManualJournals/{ManualJournalID}/Attachments/{AttachmentID}:
    get:
      security:
        - OAuth2:
            - accounting.attachments
            - accounting.attachments.read
      tags:
        - Accounting
      operationId: getManualJournalAttachmentById
      summary: Allows you to retrieve a specific attachment from a specific manual journal using a unique attachment Id
  /ManualJournals/{ManualJournalID}/Attachments/{FileName}:
    get:
      security:
        - OAuth2:
            - accounting.attachments
            - accounting.attachments.read
      tags:
        - Accounting
      operationId: getManualJournalAttachmentByFileName
      summary: Retrieves a specific attachment from a specific manual journal by file name
    post:
      security:
        - OAuth2:
            - accounting.attachments
      tags:
        - Accounting
      operationId: updateManualJournalAttachmentByFileName
      x-hasAccountingValidationError: true
      summary: Updates a specific attachment from a specific manual journal by file name
    put:
      security:
        - OAuth2:
            - accounting.attachments
      tags:
        - Accounting
      operationId: createManualJournalAttachmentByFileName
      x-hasAccountingValidationError: true
      summary: Creates a specific attachment for a specific manual journal by file name
  /ManualJournals/{ManualJournalID}/History:
    get:
      security:
        - OAuth2:
            - accounting.transactions
            - accounting.transactions.read
      tags:
        - Accounting
      operationId: getManualJournalsHistory
      summary: Retrieves history for a specific manual journal
    put:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: createManualJournalHistoryRecord
      summary: Creates a history record for a specific manual journal
      x-hasAccountingValidationError: true
  /Organisation:
    get:
      security:
        - OAuth2:
            - accounting.settings
            - accounting.settings.read
      tags:
        - Accounting
      operationId: getOrganisations
      summary: Retrieves Xero organisation details
  /Organisation/Actions:
    get:
      security:
        - OAuth2:
            - accounting.settings
            - accounting.settings.read
      tags:
        - Accounting
      operationId: getOrganisationActions
      summary: Retrieves a list of the key actions your app has permission to perform in the connected Xero organisation.
  /Organisation/{OrganisationID}/CISSettings:
    get:
      security:
        - OAuth2:
            - accounting.settings
            - accounting.settings.read
      tags:
        - Accounting
      operationId: getOrganisationCISSettings
      summary: Retrieves the CIS settings for the Xero organistaion.
  /Overpayments:
    get:
      security:
        - OAuth2:
            - accounting.transactions
            - accounting.transactions.read
      tags:
        - Accounting
      operationId: getOverpayments
      summary: Retrieves overpayments
  /Overpayments/{OverpaymentID}:
    get:
      security:
        - OAuth2:
            - accounting.transactions
            - accounting.transactions.read
      tags:
        - Accounting
      operationId: getOverpayment
      summary: Retrieves a specific overpayment using a unique overpayment Id
  /Overpayments/{OverpaymentID}/Allocations:
    put:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: createOverpaymentAllocations
      summary: Creates a single allocation for a specific overpayment
      x-hasAccountingValidationError: true
  /Overpayments/{OverpaymentID}/Allocations/{AllocationID}:
    delete:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: deleteOverpaymentAllocations
      summary: Deletes an Allocation from an overpayment
  /Overpayments/{OverpaymentID}/History:
    get:
      security:
        - OAuth2:
            - accounting.transactions
            - accounting.transactions.read
      tags:
        - Accounting
      operationId: getOverpaymentHistory
      summary: Retrieves history records of a specific overpayment
    put:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: createOverpaymentHistory
      summary: Creates a history record for a specific overpayment
      x-hasAccountingValidationError: true
  /Payments:
    get:
      security:
        - OAuth2:
            - accounting.transactions
            - accounting.transactions.read
      tags:
        - Accounting
      operationId: getPayments
      summary: Retrieves payments for invoices and credit notes
    put:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: createPayments
      summary: Creates multiple payments for invoices or credit notes
      x-hasAccountingValidationError: true
    post:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: createPayment
      summary: Creates a single payment for invoice or credit notes
      x-hasAccountingValidationError: true
  /Payments/{PaymentID}:
    get:
      security:
        - OAuth2:
            - accounting.transactions
            - accounting.transactions.read
      tags:
        - Accounting
      operationId: getPayment
      summary: Retrieves a specific payment for invoices and credit notes using a unique payment Id
    post:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: deletePayment
      summary: Updates a specific payment for invoices and credit notes
      x-hasAccountingValidationError: true
  /Payments/{PaymentID}/History:
    get:
      security:
        - OAuth2:
            - accounting.transactions
            - accounting.transactions.read
      tags:
        - Accounting
      operationId: getPaymentHistory
      summary: Retrieves history records of a specific payment
    put:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: createPaymentHistory
      summary: Creates a history record for a specific payment
      x-hasAccountingValidationError: true
  /PaymentServices:
    get:
      security:
        - OAuth2:
            - paymentservices
      tags:
        - Accounting
      operationId: getPaymentServices
      summary: Retrieves payment services
      x-excludeFromPreview: true
    put:
      security:
        - OAuth2:
            - paymentservices
      tags:
        - Accounting
      operationId: createPaymentService
      summary: Creates a payment service
      x-excludeFromPreview: true
      x-hasAccountingValidationError: true
  /Prepayments:
    get:
      security:
        - OAuth2:
            - accounting.transactions
            - accounting.transactions.read
      tags:
        - Accounting
      operationId: getPrepayments
      summary: Retrieves prepayments
  /Prepayments/{PrepaymentID}:
    get:
      security:
        - OAuth2:
            - accounting.transactions
            - accounting.transactions.read
      tags:
        - Accounting
      operationId: getPrepayment
      summary: Allows you to retrieve a specified prepayments
  /Prepayments/{PrepaymentID}/Allocations:
    put:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: createPrepaymentAllocations
      summary: Allows you to create an Allocation for prepayments
      x-hasAccountingValidationError: true
  /Prepayments/{PrepaymentID}/Allocations/{AllocationID}:
    delete:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: deletePrepaymentAllocations
      summary: Deletes an Allocation from a Prepayment
  /Prepayments/{PrepaymentID}/History:
    get:
      security:
        - OAuth2:
            - accounting.transactions
            - accounting.transactions.read
      tags:
        - Accounting
      operationId: getPrepaymentHistory
      summary: Retrieves history record for a specific prepayment
    put:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: createPrepaymentHistory
      summary: Creates a history record for a specific prepayment
      x-hasAccountingValidationError: true
  /PurchaseOrders:
    get:
      security:
        - OAuth2:
            - accounting.transactions
            - accounting.transactions.read
      tags:
        - Accounting
      operationId: getPurchaseOrders
      summary: Retrieves purchase orders
    put:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: createPurchaseOrders
      summary: Creates one or more purchase orders
      x-hasAccountingValidationError: true
    post:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: updateOrCreatePurchaseOrders
      summary: Updates or creates one or more purchase orders
      x-hasAccountingValidationError: true
  /PurchaseOrders/{PurchaseOrderID}/pdf:
    get:
      security:
        - OAuth2:
            - accounting.transactions
            - accounting.transactions.read
      tags:
        - Accounting
      operationId: getPurchaseOrderAsPdf
      x-path: /PurchaseOrders/{PurchaseOrderID}
      summary: Retrieves specific purchase order as PDF files using a unique purchase order Id
  /PurchaseOrders/{PurchaseOrderID}:
    get:
      security:
        - OAuth2:
            - accounting.transactions
            - accounting.transactions.read
      tags:
        - Accounting
      operationId: getPurchaseOrder
      summary: Retrieves a specific purchase order using a unique purchase order Id
    post:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: updatePurchaseOrder
      summary: Updates a specific purchase order
      x-hasAccountingValidationError: true
  /PurchaseOrders/{PurchaseOrderNumber}:
    get:
      security:
        - OAuth2:
            - accounting.transactions
            - accounting.transactions.read
      tags:
        - Accounting
      operationId: getPurchaseOrderByNumber
      summary: Retrieves a specific purchase order using purchase order number
  /PurchaseOrders/{PurchaseOrderID}/History:
    get:
      security:
        - OAuth2:
            - accounting.transactions
            - accounting.transactions.read
      tags:
        - Accounting
      operationId: getPurchaseOrderHistory
      summary: Retrieves history for a specific purchase order
    put:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: createPurchaseOrderHistory
      summary: Creates a history record for a specific purchase orders
      x-hasAccountingValidationError: true
  /PurchaseOrders/{PurchaseOrderID}/Attachments:
    get:
      security:
        - OAuth2:
            - accounting.attachments
            - accounting.attachments.read
      tags:
        - Accounting
      operationId: getPurchaseOrderAttachments
      summary: Retrieves attachments for a specific purchase order
  /PurchaseOrders/{PurchaseOrderID}/Attachments/{AttachmentID}:
    get:
      security:
        - OAuth2:
            - accounting.attachments
            - accounting.attachments.read
      tags:
        - Accounting
      operationId: getPurchaseOrderAttachmentById
      summary: Retrieves specific attachment for a specific purchase order using a unique attachment Id
  /PurchaseOrders/{PurchaseOrderID}/Attachments/{FileName}:
    get:
      security:
        - OAuth2:
            - accounting.attachments
            - accounting.attachments.read
      tags:
        - Accounting
      operationId: getPurchaseOrderAttachmentByFileName
      summary: Retrieves a specific attachment for a specific purchase order by filename
    post:
      security:
        - OAuth2:
            - accounting.attachments
      tags:
        - Accounting
      operationId: updatePurchaseOrderAttachmentByFileName
      x-hasAccountingValidationError: true
      summary: Updates a specific attachment for a specific purchase order by filename
    put:
      security:
        - OAuth2:
            - accounting.attachments
      tags:
        - Accounting
      operationId: createPurchaseOrderAttachmentByFileName
      x-hasAccountingValidationError: true
      summary: Creates attachment for a specific purchase order
  /Quotes:
    get:
      security:
        - OAuth2:
            - accounting.transactions
            - accounting.transactions.read
      tags:
        - Accounting
      operationId: getQuotes
      summary: Retrieves sales quotes
    put:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: createQuotes
      summary: Create one or more quotes
      x-hasAccountingValidationError: true
    post:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: updateOrCreateQuotes
      summary: Updates or creates one or more quotes
      x-hasAccountingValidationError: true
  /Quotes/{QuoteID}:
    get:
      security:
        - OAuth2:
            - accounting.transactions
            - accounting.transactions.read
      tags:
        - Accounting
      operationId: getQuote
      summary: Retrieves a specific quote using a unique quote Id
    post:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: updateQuote
      summary: Updates a specific quote
      x-hasAccountingValidationError: true
  /Quotes/{QuoteID}/History:
    get:
      security:
        - OAuth2:
            - accounting.transactions
            - accounting.transactions.read
      tags:
        - Accounting
      operationId: getQuoteHistory
      summary: Retrieves history records of a specific quote
    put:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: createQuoteHistory
      summary: Creates a history record for a specific quote
      x-hasAccountingValidationError: true
  /Quotes/{QuoteID}/pdf:
    get:
      security:
        - OAuth2:
            - accounting.transactions
            - accounting.transactions.read
      tags:
        - Accounting
      operationId: getQuoteAsPdf
      x-path: /Quotes/{QuoteID}
      summary: Retrieves a specific quote as a PDF file using a unique quote Id
  /Quotes/{QuoteID}/Attachments:
    get:
      security:
        - OAuth2:
            - accounting.attachments
            - accounting.attachments.read
      tags:
        - Accounting
      operationId: getQuoteAttachments
      summary: Retrieves attachments for a specific quote
  /Quotes/{QuoteID}/Attachments/{AttachmentID}:
    get:
      security:
        - OAuth2:
            - accounting.attachments
            - accounting.attachments.read
      tags:
        - Accounting
      operationId: getQuoteAttachmentById
      summary: Retrieves a specific attachment from a specific quote using a unique attachment Id
  /Quotes/{QuoteID}/Attachments/{FileName}:
    get:
      security:
        - OAuth2:
            - accounting.attachments
            - accounting.attachments.read
      tags:
        - Accounting
      operationId: getQuoteAttachmentByFileName
      summary: Retrieves a specific attachment from a specific quote by filename
    post:
      security:
        - OAuth2:
            - accounting.attachments
      tags:
        - Accounting
      operationId: updateQuoteAttachmentByFileName
      x-hasAccountingValidationError: true
      summary: Updates a specific attachment from a specific quote by filename
    put:
      security:
        - OAuth2:
            - accounting.attachments
      tags:
        - Accounting
      operationId: createQuoteAttachmentByFileName
      x-hasAccountingValidationError: true
      summary: Creates attachment for a specific quote
  /Receipts:
    get:
      security:
        - OAuth2:
            - accounting.transactions
            - accounting.transactions.read
      tags:
        - Accounting
      operationId: getReceipts
      summary: Retrieves draft expense claim receipts for any user
    put:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: createReceipt
      summary: Creates draft expense claim receipts for any user
      x-hasAccountingValidationError: true
  /Receipts/{ReceiptID}:
    get:
      security:
        - OAuth2:
            - accounting.transactions
            - accounting.transactions.read
      tags:
        - Accounting
      operationId: getReceipt
      summary: Retrieves a specific draft expense claim receipt by using a unique receipt Id
    post:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: updateReceipt
      summary: Updates a specific draft expense claim receipts
      x-hasAccountingValidationError: true
  /Receipts/{ReceiptID}/Attachments:
    get:
      security:
        - OAuth2:
            - accounting.attachments
            - accounting.attachments.read
      tags:
        - Accounting
      operationId: getReceiptAttachments
      summary: Retrieves attachments for a specific expense claim receipt
  /Receipts/{ReceiptID}/Attachments/{AttachmentID}:
    get:
      security:
        - OAuth2:
            - accounting.attachments
            - accounting.attachments.read
      tags:
        - Accounting
      operationId: getReceiptAttachmentById
      summary: Retrieves a specific attachments from a specific expense claim receipts by using a unique attachment Id
  /Receipts/{ReceiptID}/Attachments/{FileName}:
    get:
      security:
        - OAuth2:
            - accounting.attachments
            - accounting.attachments.read
      tags:
        - Accounting
      operationId: getReceiptAttachmentByFileName
      summary: Retrieves a specific attachment from a specific expense claim receipts by file name
    post:
      security:
        - OAuth2:
            - accounting.attachments
      tags:
        - Accounting
      operationId: updateReceiptAttachmentByFileName
      x-hasAccountingValidationError: true
      summary: Updates a specific attachment on a specific expense claim receipts by file name
    put:
      security:
        - OAuth2:
            - accounting.attachments
      tags:
        - Accounting
      operationId: createReceiptAttachmentByFileName
      x-hasAccountingValidationError: true
      summary: Creates an attachment on a specific expense claim receipts by file name
  /Receipts/{ReceiptID}/History:
    get:
      security:
        - OAuth2:
            - accounting.transactions
            - accounting.transactions.read
      tags:
        - Accounting
      operationId: getReceiptHistory
      summary: Retrieves a history record for a specific receipt
    put:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: createReceiptHistory
      summary: Creates a history record for a specific receipt
      x-hasAccountingValidationError: true
  /RepeatingInvoices:
    get:
      security:
        - OAuth2:
            - accounting.transactions
            - accounting.transactions.read
      tags:
        - Accounting
      operationId: getRepeatingInvoices
      summary: Retrieves repeating invoices
    put:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: createRepeatingInvoices
      summary: Creates one or more repeating invoice templates
      x-hasAccountingValidationError: true
    post:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: updateOrCreateRepeatingInvoices
      summary: Creates or deletes one or more repeating invoice templates
      x-hasAccountingValidationError: true
  /RepeatingInvoices/{RepeatingInvoiceID}:
    get:
      security:
        - OAuth2:
            - accounting.transactions
            - accounting.transactions.read
      tags:
        - Accounting
      operationId: getRepeatingInvoice
      summary: Retrieves a specific repeating invoice by using a unique repeating invoice Id
    post:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: updateRepeatingInvoice
      summary: Deletes a specific repeating invoice template
      x-hasAccountingValidationError: true
  /RepeatingInvoices/{RepeatingInvoiceID}/Attachments:
    get:
      security:
        - OAuth2:
            - accounting.attachments
            - accounting.attachments.read
      tags:
        - Accounting
      operationId: getRepeatingInvoiceAttachments
      summary: Retrieves attachments from a specific repeating invoice
  /RepeatingInvoices/{RepeatingInvoiceID}/Attachments/{AttachmentID}:
    get:
      security:
        - OAuth2:
            - accounting.attachments
            - accounting.attachments.read
      tags:
        - Accounting
      operationId: getRepeatingInvoiceAttachmentById
      summary: Retrieves a specific attachment from a specific repeating invoice
  /RepeatingInvoices/{RepeatingInvoiceID}/Attachments/{FileName}:
    get:
      security:
        - OAuth2:
            - accounting.attachments
            - accounting.attachments.read
      tags:
        - Accounting
      operationId: getRepeatingInvoiceAttachmentByFileName
      summary: Retrieves a specific attachment from a specific repeating invoices by file name
    post:
      security:
        - OAuth2:
            - accounting.attachments
      tags:
        - Accounting
      operationId: updateRepeatingInvoiceAttachmentByFileName
      x-hasAccountingValidationError: true
      summary: Updates a specific attachment from a specific repeating invoices by file name
    put:
      security:
        - OAuth2:
            - accounting.attachments
      tags:
        - Accounting
      operationId: createRepeatingInvoiceAttachmentByFileName
      x-hasAccountingValidationError: true
      summary: Creates an attachment from a specific repeating invoices by file name
  /RepeatingInvoices/{RepeatingInvoiceID}/History:
    get:
      security:
        - OAuth2:
            - accounting.transactions
            - accounting.transactions.read
      tags:
        - Accounting
      operationId: getRepeatingInvoiceHistory
      summary: Retrieves history record for a specific repeating invoice
    put:
      security:
        - OAuth2:
            - accounting.transactions
      tags:
        - Accounting
      operationId: createRepeatingInvoiceHistory
      summary: Creates a  history record for a specific repeating invoice
      x-hasAccountingValidationError: true
  /Reports/TenNinetyNine:
    get:
      security:
        - OAuth2:
            - accounting.reports.read
            - accounting.reports.tenninetynine.read
      tags:
        - Accounting
      operationId: getReportTenNinetyNine
      summary: Retrieve reports for 1099
  /Reports/AgedPayablesByContact:
    get:
      security:
        - OAuth2:
            - accounting.reports.read
      tags:
        - Accounting
      operationId: getReportAgedPayablesByContact
      summary: Retrieves report for aged payables by contact
  /Reports/AgedReceivablesByContact:
    get:
      security:
        - OAuth2:
            - accounting.reports.read
      tags:
        - Accounting
      operationId: getReportAgedReceivablesByContact
      summary: Retrieves report for aged receivables by contact
  /Reports/BalanceSheet:
    get:
      security:
        - OAuth2:
            - accounting.reports.read
      tags:
        - Accounting
      operationId: getReportBalanceSheet
      summary: Retrieves report for balancesheet
  /Reports/BankSummary:
    get:
      security:
        - OAuth2:
            - accounting.reports.read
      tags:
        - Accounting
      operationId: getReportBankSummary
      summary: Retrieves report for bank summary
  /Reports/{ReportID}:
    get:
      security:
        - OAuth2:
            - accounting.reports.read
      tags:
        - Accounting
      operationId: getReportFromId
      summary: Retrieves a specific report using a unique ReportID
  /Reports/BudgetSummary:
    get:
      security:
        - OAuth2:
            - accounting.reports.read
      tags:
        - Accounting
      operationId: getReportBudgetSummary
      summary: Retrieves report for budget summary
  /Reports/ExecutiveSummary:
    get:
      security:
        - OAuth2:
            - accounting.reports.read
      tags:
        - Accounting
      operationId: getReportExecutiveSummary
      summary: Retrieves report for executive summary
  /Reports:
    get:
      security:
        - OAuth2:
            - accounting.reports.read
      tags:
        - Accounting
      operationId: getReportsList
      summary: Retrieves a list of the organistaions unique reports that require a uuid to fetch
  /Reports/ProfitAndLoss:
    get:
      security:
        - OAuth2:
            - accounting.reports.read
      tags:
        - Accounting
      operationId: getReportProfitAndLoss
      summary: Retrieves report for profit and loss
  /Reports/TrialBalance:
    get:
      security:
        - OAuth2:
            - accounting.reports.read
      tags:
        - Accounting
      operationId: getReportTrialBalance
      summary: Retrieves report for trial balance
  /Setup:
    post:
      security:
        - OAuth2:
            - accounting.settings
      tags:
        - Accounting
      operationId: postSetup
      summary: Sets the chart of accounts, the conversion date and conversion balances
  /TaxRates:
    get:
      security:
        - OAuth2:
            - accounting.settings
            - accounting.settings.read
      tags:
        - Accounting
      operationId: getTaxRates
      summary: Retrieves tax rates
    put:
      security:
        - OAuth2:
            - accounting.settings
      tags:
        - Accounting
      operationId: createTaxRates
      summary: Creates one or more tax rates
      x-hasAccountingValidationError: true
    post:
      security:
        - OAuth2:
            - accounting.settings
      tags:
        - Accounting
      operationId: updateTaxRate
      summary: Updates tax rates
      x-hasAccountingValidationError: true
  /TaxRates/{TaxType}:
    get:
      security:
        - OAuth2:
            - accounting.settings
            - accounting.settings.read
      tags:
        - Accounting
      operationId: getTaxRateByTaxType
      summary: Retrieves a specific tax rate according to given TaxType code
  /TrackingCategories:
    get:
      security:
        - OAuth2:
            - accounting.settings
            - accounting.settings.read
      tags:
        - Accounting
      operationId: getTrackingCategories
      summary: Retrieves tracking categories and options
    put:
      security:
        - OAuth2:
            - accounting.settings
      tags:
        - Accounting
      operationId: createTrackingCategory
      summary: Create tracking categories
      x-hasAccountingValidationError: true
  /TrackingCategories/{TrackingCategoryID}:
    get:
      security:
        - OAuth2:
            - accounting.settings
            - accounting.settings.read
      tags:
        - Accounting
      operationId: getTrackingCategory
      summary: Retrieves specific tracking categories and options using a unique tracking category Id
    post:
      security:
        - OAuth2:
            - accounting.settings
      tags:
        - Accounting
      operationId: updateTrackingCategory
      summary: Updates a specific tracking category
      x-hasAccountingValidationError: true
    delete:
      security:
        - OAuth2:
            - accounting.settings
      tags:
        - Accounting
      operationId: deleteTrackingCategory
      summary: Deletes a specific tracking category
  /TrackingCategories/{TrackingCategoryID}/Options:
    put:
      security:
        - OAuth2:
            - accounting.settings
      tags:
        - Accounting
      operationId: createTrackingOptions
      summary: Creates options for a specific tracking category
      x-hasAccountingValidationError: true
  /TrackingCategories/{TrackingCategoryID}/Options/{TrackingOptionID}:
    post:
      security:
        - OAuth2:
            - accounting.settings
      tags:
        - Accounting
      operationId: updateTrackingOptions
      summary: Updates a specific option for a specific tracking category
      x-hasAccountingValidationError: true
    delete:
      security:
        - OAuth2:
            - accounting.settings
      tags:
        - Accounting
      operationId: deleteTrackingOptions
      summary: Deletes a specific option for a specific tracking category
  /Users:
    get:
      security:
        - OAuth2:
            - accounting.settings
            - accounting.settings.read
      tags:
        - Accounting
      operationId: getUsers
      summary: Retrieves users
  /Users/{UserID}:
    get:
      security:
        - OAuth2:
            - accounting.settings
            - accounting.settings.read
      tags:
        - Accounting
      operationId: getUser
      summary: Retrieves a specific user
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      description: For more information
      flows:
        authorizationCode:
          authorizationUrl: https://login.xero.com/identity/connect/authorize
          tokenUrl: https://identity.xero.com/connect/token
          scopes:
            email: Grant read-only access to your email
            openid: Grant read-only access to your open id
            profile: your profile information
            accounting.attachments: Grant read-write access to attachments
            accounting.attachments.read: Grant read-only access to attachments
            accounting.budgets.read: Grant read-only access to read budgets
            accounting.contacts: Grant read-write access to contacts and contact groups
            accounting.contacts.read: Grant read-only access to contacts and contact groups
            accounting.journals.read: Grant read-only access to journals
            accounting.reports.read: Grant read-only access to accounting reports
            accounting.reports.tenninetynine.read: Grant read-only access to 1099 reports
            accounting.settings: Grant read-write access to organisation and account settings
            accounting.settings.read: Grant read-only access to organisation and account settings
            accounting.transactions: Grant read-write access to bank transactions, credit notes, invoices, repeating invoices
            accounting.transactions.read: Grant read-only access to invoices
            paymentservices: Grant read-write access to payment services