openapi: 3.0.0
info:
  version: 12.0.0
  title: "Xero Payroll NZ"
  description: "This is the Xero Payroll API for orgs in the NZ region."
  termsOfService: "https://developer.xero.com/xero-developer-platform-terms-conditions/"
  contact:
    name: Xero Platform Team
    email: api@xero.com
    url: https://developer.xero.com
tags:
  - name: PayrollNz
servers:
  - description: Xero Payroll NZ API
    url: https://api.xero.com/payroll.xro/2.0
paths:
  /Employees:
    get:
      security:
        - OAuth2:
            - payroll.employees
            - payroll.employees.read
      tags:
        - PayrollNz
      operationId: getEmployees
      x-hasPayrollUkProblem: true
      summary: Retrieves employees
    post:
      security:
        - OAuth2:
            - payroll.employees
      tags:
        - PayrollNz
      operationId: createEmployee
      x-hasPayrollUkProblem: true
      summary: Creates an employees
  /Employees/{EmployeeID}:
    get:
      security:
        - OAuth2:
            - payroll.employees
            - payroll.employees.read
      tags:
        - PayrollNz
      operationId: getEmployee
      x-hasPayrollUkProblem: true
      summary: Retrieves an employees using a unique employee ID
    put:
      security:
        - OAuth2:
            - payroll.employees
      tags:
        - PayrollNz
      operationId: updateEmployee
      x-hasPayrollUkProblem: true
      summary: Updates an existing employee
  /Employees/{EmployeeID}/Employment:
    post:
      security:
        - OAuth2:
            - payroll.employees
      tags:
        - PayrollNz
      operationId: createEmployment
      x-hasPayrollUkProblem: true
      summary: Creates an employment detail for a specific employee
  /Employees/{EmployeeID}/Tax:
    get:
      security:
        - OAuth2:
            - payroll.employees
            - payroll.employees.read
      tags:
        - PayrollNz
      operationId: getEmployeeTax
      x-hasPayrollUkProblem: true
      summary: Retrieves tax records for a specific employee
    post:
      security:
        - OAuth2:
            - payroll.employees
      tags:
        - PayrollNz
      operationId: updateEmployeeTax
      x-hasPayrollUkProblem: true
      summary: Updates the tax records for a specific employee
  /Employees/{EmployeeID}/OpeningBalances:
    get:
      security:
        - OAuth2:
            - payroll.employees
            - payroll.employees.read
      tags:
        - PayrollNz
      operationId: getEmployeeOpeningBalances
      x-hasPayrollUkProblem: true
      summary: Retrieves the opening balance for a specific employee
    post:
      security:
        - OAuth2:
            - payroll.employees
      tags:
        - PayrollNz
      operationId: createEmployeeOpeningBalances
      x-hasPayrollUkProblem: true
      summary: Creates opening balances for a specific employee
  /Employees/{EmployeeID}/Leave:
    get:
      security:
        - OAuth2:
            - payroll.employees
            - payroll.employees.read
      tags:
        - PayrollNz
      operationId: getEmployeeLeaves
      x-hasPayrollUkProblem: true
      summary: Retrieves leave records for a specific employee
    post:
      security:
        - OAuth2:
            - payroll.employees
      tags:
        - PayrollNz
      operationId: createEmployeeLeave
      x-hasPayrollUkProblem: true
      summary: Creates leave records for a specific employee
  /Employees/{EmployeeID}/Leave/{LeaveID}:
    put:
      security:
        - OAuth2:
            - payroll.employees
      tags:
        - PayrollNz
      operationId: updateEmployeeLeave
      x-hasPayrollUkProblem: true
      summary: Updates leave records for a specific employee
    delete:
      security:
        - OAuth2:
            - payroll.employees
      tags:
        - PayrollNz
      operationId: deleteEmployeeLeave
      x-hasPayrollUkProblem: true
      summary: Deletes a leave record for a specific employee
  /Employees/{EmployeeID}/LeaveBalances:
    get:
      security:
        - OAuth2:
            - payroll.employees
            - payroll.employees.read
      tags:
        - PayrollNz
      operationId: getEmployeeLeaveBalances
      x-hasPayrollUkProblem: true
      summary: Retrieves leave balances for a specific employee
  /Employees/{EmployeeID}/LeavePeriods:
    get:
      security:
        - OAuth2:
            - payroll.employees
            - payroll.employees.read
      tags:
        - PayrollNz
      operationId: getEmployeeLeavePeriods
      x-hasPayrollUkProblem: true
      summary: Retrieves leave periods for a specific employee
  /Employees/{EmployeeID}/LeaveSetup:
    post:
      security:
        - OAuth2:
            - payroll.employees
      tags:
        - PayrollNz
      operationId: createEmployeeLeaveSetup
      x-hasPayrollUkProblem: true
      summary: Creates a leave set-up for a specific employee. This is required before viewing, configuring and requesting leave for an employee
  /Employees/{EmployeeID}/LeaveTypes:
    get:
      security:
        - OAuth2:
            - payroll.employees
            - payroll.employees.read
      tags:
        - PayrollNz
      operationId: getEmployeeLeaveTypes
      x-hasPayrollUkProblem: true
      summary: Retrieves leave types for a specific employee
    post:
      security:
        - OAuth2:
            - payroll.employees
      tags:
        - PayrollNz
      operationId: createEmployeeLeaveType
      x-hasPayrollUkProblem: true
      summary: Creates leave type records for a specific employee
  /Employees/{EmployeeID}/PaymentMethods:
    get:
      security:
        - OAuth2:
            - payroll.employees
            - payroll.employees.read
      tags:
        - PayrollNz
      operationId: getEmployeePaymentMethod
      x-hasPayrollUkProblem: true
      summary: Retrieves available payment methods for a specific employee
    post:
      security:
        - OAuth2:
            - payroll.employees
      tags:
        - PayrollNz
      operationId: createEmployeePaymentMethod
      x-hasPayrollUkProblem: true
      summary: Creates a payment method for an employee
  /Employees/{EmployeeID}/PayTemplates:
    get:
      security:
        - OAuth2:
            - payroll.employees
            - payroll.employees.read
      tags:
        - PayrollNz
      operationId: getEmployeePayTemplates
      x-hasPayrollUkProblem: true
      summary: Retrieves pay templates for a specific employee
  /Employees/{EmployeeID}/PayTemplates/Earnings:
    post:
      security:
        - OAuth2:
            - payroll.employees
      tags:
        - PayrollNz
      operationId: createEmployeeEarningsTemplate
      x-hasPayrollUkProblem: true
      summary: Creates earnings template records for an employee
  /Employees/{EmployeeID}/PayTemplates/Earnings/{PayTemplateEarningID}:
    put:
      security:
        - OAuth2:
            - payroll.employees
      tags:
        - PayrollNz
      operationId: updateEmployeeEarningsTemplate
      x-hasPayrollUkProblem: true
      summary: Updates an earnings template records for an employee
    delete:
      security:
        - OAuth2:
            - payroll.employees
      tags:
        - PayrollNz
      operationId: deleteEmployeeEarningsTemplate
      summary: Deletes an employee's earnings template record
  /Employees/{EmployeeID}/PayTemplateEarnings:
    post:
      security:
        - OAuth2:
            - payroll.employees
      tags:
        - PayrollNz
      operationId: createMultipleEmployeeEarningsTemplate
      x-hasPayrollUkProblem: true
      summary: Creates multiple employee earnings template records for a specific employee
  /Deductions:
    get:
      security:
        - OAuth2:
            - payroll.settings
            - payroll.settings.read
      tags:
        - PayrollNz
      operationId: getDeductions
      x-hasPayrollUkProblem: true
      summary: Retrieves deductions for a specific employee
    post:
      security:
        - OAuth2:
            - payroll.settings
      tags:
        - PayrollNz
      operationId: createDeduction
      x-hasPayrollUkProblem: true
      summary: Creates a new deduction for a specific employee
  /Deductions/{deductionId}:
    get:
      security:
        - OAuth2:
            - payroll.settings
            - payroll.settings.read
      tags:
        - PayrollNz
      operationId: getDeduction
      x-hasPayrollUkProblem: true
      summary: Retrieves a single deduction by using a unique deduction ID
  /StatutoryDeductions:
    get:
      security:
        - OAuth2:
            - payroll.settings
            - payroll.settings.read
      tags:
        - PayrollNz
      operationId: getStatutoryDeductions
      summary: Retrieves statutory deductions
  /StatutoryDeductions/{id}:
    get:
      security:
        - OAuth2:
            - payroll.settings
            - payroll.settings.read
      tags:
        - PayrollNz
      operationId: getStatutoryDeduction
      summary: Retrieves a specific statutory deduction by using a unique statutory deductions id
  /Superannuations:
    get:
      security:
        - OAuth2:
            - payroll.settings
            - payroll.settings.read
      tags:
        - PayrollNz
      operationId: getSuperannuations
      summary: Retrieves superannuations
    post:
      security:
        - OAuth2:
            - payroll.settings
      tags:
        - PayrollNz
      operationId: createSuperannuation
      x-hasPayrollUkProblem: true
      summary: Creates a new superannuation
  /Superannuations/{SuperannuationID}:
    get:
      security:
        - OAuth2:
            - payroll.settings
            - payroll.settings.read
      tags:
        - PayrollNz
      operationId: getSuperannuation
      summary: Retrieves a specific superannuation using a unique superannuation ID
  /EarningsRates:
    get:
      security:
        - OAuth2:
            - payroll.settings
            - payroll.settings.read
      tags:
        - PayrollNz
      operationId: getEarningsRates
      x-hasPayrollUkProblem: true
      summary: Retrieves earnings rates
    post:
      security:
        - OAuth2:
            - payroll.settings
      tags:
        - PayrollNz
      operationId: createEarningsRate
      x-hasPayrollUkProblem: true
      summary: Creates a new earnings rate
  /EarningsRates/{EarningsRateID}:
    get:
      security:
        - OAuth2:
            - payroll.settings
            - payroll.settings.read
      tags:
        - PayrollNz
      operationId: getEarningsRate
      x-hasPayrollUkProblem: true
      summary: Retrieves a specific earnings rates by using a unique earnings rate id
  /LeaveTypes:
    get:
      security:
        - OAuth2:
            - payroll.settings
            - payroll.settings.read
      tags:
        - PayrollNz
      operationId: getLeaveTypes
      x-hasPayrollUkProblem: true
      summary: Retrieves leave types
    post:
      security:
        - OAuth2:
            - payroll.settings
      tags:
        - PayrollNz
      operationId: createLeaveType
      x-hasPayrollUkProblem: true
      summary: Creates a new leave type
  /LeaveTypes/{LeaveTypeID}:
    get:
      security:
        - OAuth2:
            - payroll.settings
            - payroll.settings.read
      tags:
        - PayrollNz
      operationId: getLeaveType
      x-hasPayrollUkProblem: true
      summary: Retrieves a specific leave type by using a unique leave type ID
  /Reimbursements:
    get:
      security:
        - OAuth2:
            - payroll.settings
            - payroll.settings.read
      tags:
        - PayrollNz
      operationId: getReimbursements
      x-hasPayrollUkProblem: true
      summary: Retrieves reimbursements
    post:
      security:
        - OAuth2:
            - payroll.settings
      tags:
        - PayrollNz
      operationId: createReimbursement
      x-hasPayrollUkProblem: true
      summary: Creates a new reimbursement
  /Reimbursements/{ReimbursementID}:
    get:
      security:
        - OAuth2:
            - payroll.settings
            - payroll.settings.read
      tags:
        - PayrollNz
      operationId: getReimbursement
      x-hasPayrollUkProblem: true
      summary: Retrieves a specific reimbursement by using a unique reimbursement ID
  /Timesheets:
    get:
      security:
        - OAuth2:
            - payroll.timesheets
            - payroll.timesheets.read
      tags:
        - PayrollNz
      operationId: getTimesheets
      x-hasPayrollUkProblem: true
      summary: Retrieves timesheets
    post:
      security:
        - OAuth2:
            - payroll.timesheets
      tags:
        - PayrollNz
      operationId: createTimesheet
      x-hasPayrollUkProblem: true
      summary: Creates a new timesheet
  /Timesheets/{TimesheetID}:
    get:
      security:
        - OAuth2:
            - payroll.timesheets
            - payroll.timesheets.read
      tags:
        - PayrollNz
      operationId: getTimesheet
      x-hasPayrollUkProblem: true
      summary: Retrieves a specific timesheet by using a unique timesheet ID
    delete:
      security:
        - OAuth2:
            - payroll.timesheets
      tags:
        - PayrollNz
      operationId: deleteTimesheet
      summary: Deletes a timesheet
  /Timesheets/{TimesheetID}/Lines:
    post:
      security:
        - OAuth2:
            - payroll.timesheets
      tags:
        - PayrollNz
      operationId: createTimesheetLine
      x-hasPayrollUkProblem: true
      summary: Create a new timesheet line for a specific time sheet
  /Timesheets/{TimesheetID}/Approve:
    post:
      security:
        - OAuth2:
            - payroll.timesheets
      tags:
        - PayrollNz
      operationId: approveTimesheet
      x-hasPayrollUkProblem: true
      summary: Approves a timesheet
  /Timesheets/{TimesheetID}/RevertToDraft:
    post:
      security:
        - OAuth2:
            - payroll.timesheets
      tags:
        - PayrollNz
      operationId: revertTimesheet
      x-hasPayrollUkProblem: true
      summary: Reverts a timesheet to draft
  /Timesheets/{TimesheetID}/Lines/{TimesheetLineID}:
    put:
      security:
        - OAuth2:
            - payroll.timesheets
      tags:
        - PayrollNz
      operationId: updateTimesheetLine
      x-hasPayrollUkProblem: true
      summary: Updates a timesheet line for a specific timesheet
    delete:
      security:
        - OAuth2:
            - payroll.timesheets
      tags:
        - PayrollNz
      operationId: deleteTimesheetLine
      summary: Deletes a timesheet line for a specific timesheet
  /PayRunCalendars:
    get:
      security:
        - OAuth2:
            - payroll.settings
            - payroll.settings.read
      tags:
        - PayrollNz
      operationId: getPayRunCalendars
      x-hasPayrollUkProblem: true
      summary: Retrieves payrun calendars
    post:
      security:
        - OAuth2:
            - payroll.settings
      tags:
        - PayrollNz
      operationId: createPayRunCalendar
      x-hasPayrollUkProblem: true
      summary: Creates a new payrun calendar
  /PayRunCalendars/{PayrollCalendarID}:
    get:
      security:
        - OAuth2:
            - payroll.settings
            - payroll.settings.read
      tags:
        - PayrollNz
      operationId: getPayRunCalendar
      x-hasPayrollUkProblem: true
      summary: Retrieves a specific payrun calendar by using a unique payroll calendar ID
  /Employees/{EmployeeID}/SalaryAndWages:
    get:
      security:
        - OAuth2:
            - payroll.employees
            - payroll.employees.read
      tags:
        - PayrollNz
      operationId: getEmployeeSalaryAndWages
      x-hasPayrollUkProblem: true
      summary: Retrieves an employee's salary and wages
    post:
      security:
        - OAuth2:
            - payroll.employees
      tags:
        - PayrollNz
      operationId: createEmployeeSalaryAndWage
      x-hasPayrollUkProblem: true
      summary: Creates an employee salary and wage record
  /Employees/{EmployeeID}/SalaryAndWages/{SalaryAndWagesID}:
    get:
      security:
        - OAuth2:
            - payroll.employees
            - payroll.employees.read
      tags:
        - PayrollNz
      operationId: getEmployeeSalaryAndWage
      x-hasPayrollUkProblem: true
      summary: Retrieves an employee's salary and wages record by using a unique salary and wage ID
    put:
      security:
        - OAuth2:
            - payroll.employees
      tags:
        - PayrollNz
      operationId: updateEmployeeSalaryAndWage
      x-hasPayrollUkProblem: true
      summary: Updates an employee's salary and wages record
    delete:
      security:
        - OAuth2:
            - payroll.employees
      tags:
        - PayrollNz
      operationId: deleteEmployeeSalaryAndWage
      summary: Deletes an employee's salary and wages record
  /PayRuns:
    get:
      security:
        - OAuth2:
            - payroll.payruns
            - payroll.payruns.read
      tags:
        - PayrollNz
      operationId: getPayRuns
      x-hasPayrollUkProblem: true
      summary: Retrieves pay runs
    post:
      security:
        - OAuth2:
            - payroll.payruns
      tags:
        - PayrollNz
      operationId: createPayRun
      x-hasPayrollUkProblem: true
      summary: Creates a pay run
  /PayRuns/{PayRunID}:
    get:
      security:
        - OAuth2:
            - payroll.payruns
            - payroll.payruns.read
      tags:
        - PayrollNz
      operationId: getPayRun
      x-hasPayrollUkProblem: true
      summary: Retrieves a specific pay run by using a unique pay run ID
  /PaySlips:
    get:
      security:
        - OAuth2:
            - payroll.payslip
            - payroll.payslip.read
      tags:
        - PayrollNz
      operationId: getPaySlips
      x-hasPayrollUkProblem: true
      summary: Retrieves payslips
  /PaySlips/{PaySlipID}:
    get:
      security:
        - OAuth2:
            - payroll.payslip
            - payroll.payslip.read
      tags:
        - PayrollNz
      operationId: getPaySlip
      x-hasPayrollUkProblem: true
      summary: Retrieves a specific payslip by a unique pay slip ID
    put:
      security:
        - OAuth2:
            - payroll.payslip
      tags:
        - PayrollNz
      operationId: updatePaySlipLineItems
      x-hasPayrollUkProblem: true
      summary: Creates an employee pay slip
  /Settings:
    get:
      security:
        - OAuth2:
            - payroll.settings
            - payroll.settings.read
      tags:
        - PayrollNz
      operationId: getSettings
      x-hasPayrollUkProblem: true
      summary: Retrieves settings
  /Settings/TrackingCategories:
    get:
      security:
        - OAuth2:
            - payroll.settings
            - payroll.settings.read
      tags:
        - PayrollNz
      operationId: getTrackingCategories
      x-hasPayrollUkProblem: true
      summary: Retrieves tracking categories
  /Employees/{EmployeeID}/Working-Patterns:
    get:
      security:
        - OAuth2:
            - payroll.employees
            - payroll.employees.read
      tags:
        - PayrollNz
      operationId: getEmployeeWorkingPatterns
      x-hasPayrollUkProblem: true
      summary: Retrieves employee's working patterns
    post:
      security:
        - OAuth2:
            - payroll.employees
      tags:
        - PayrollNz
      operationId: createEmployeeWorkingPattern
      x-hasPayrollUkProblem: true
      summary: Creates an employee working pattern
  /Employees/{EmployeeID}/Working-Patterns/{EmployeeWorkingPatternID}:
    get:
      security:
        - OAuth2:
            - payroll.employees
            - payroll.employees.read
      tags:
        - PayrollNz
      operationId: getEmployeeWorkingPattern
      x-hasPayrollUkProblem: true
      summary: Retrieves employee's working patterns
    delete:
      security:
        - OAuth2:
            - payroll.employees
      tags:
        - PayrollNz
      operationId: deleteEmployeeWorkingPattern
      x-hasPayrollUkProblem: true
      summary: deletes employee's working patterns
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      description: For more information visit https://developer.xero.com/documentation/oauth2/overview
      flows:
        authorizationCode:
          authorizationUrl: https://login.xero.com/identity/connect/authorize
          tokenUrl: https://identity.xero.com/connect/token
          scopes:
            payroll.employees: Grant read-write access to payroll employees
            payroll.employees.read: Grant read-only access to payroll employees
            payroll.payruns: Grant read-write access to payroll payruns
            payroll.payruns.read: Grant read-only access to payroll payruns
            payroll.payslip: Grant read-write access to payroll payslips
            payroll.payslip.read: Grant read-only access to payroll payslips
            payroll.settings: Grant read-write access to payroll settings
            payroll.settings.read: Grant read-only access to payroll settings
            payroll.timesheets: Grant read-write access to payroll timesheets
            payroll.timesheets.read: Grant read-only access to payroll timesheets