openapi: 3.0.0
info:
  version: 12.0.0
  title: "Xero Payroll UK"
  description: "This is the Xero Payroll API for orgs in the UK region."
  termsOfService: "https://developer.xero.com/xero-developer-platform-terms-conditions/"
  contact:
    name: Xero Platform Team
    email: api@xero.com
    url: https://developer.xero.com
tags:
  - name: PayrollUk
servers:
  - description: Xero Payroll UK API
    url: https://api.xero.com/payroll.xro/2.0
paths:
  /Employees:
    get:
      security:
        - OAuth2:
            - payroll.employees
            - payroll.employees.read
      tags:
        - PayrollUk
      operationId: getEmployees
      x-hasPayrollUkProblem: true
      summary: Retrieves employees
    post:
      security:
        - OAuth2:
            - payroll.employees
      tags:
        - PayrollUk
      operationId: createEmployee
      x-hasPayrollUkProblem: true
      summary: Creates employees
  /Employees/{EmployeeID}:
    get:
      security:
        - OAuth2:
            - payroll.employees
            - payroll.employees.read
      tags:
        - PayrollUk
      operationId: getEmployee
      x-hasPayrollUkProblem: true
      summary: Retrieves specific employees by using a unique employee ID
    put:
      security:
        - OAuth2:
            - payroll.employees
      tags:
        - PayrollUk
      operationId: updateEmployee
      x-hasPayrollUkProblem: true
      summary: Updates a specific employee's detail
  /Employees/{EmployeeID}/Employment:
    post:
      security:
        - OAuth2:
            - payroll.employees
      tags:
        - PayrollUk
      operationId: createEmployment
      x-hasPayrollUkProblem: true
      summary: Creates employment detail for a specific employee using a unique employee ID
  /Employees/{EmployeeID}/Tax:
    get:
      security:
        - OAuth2:
            - payroll.employees
            - payroll.employees.read
      tags:
        - PayrollUk
      operationId: getEmployeeTax
      x-hasPayrollUkProblem: true
      summary: Retrieves tax records for a specific employee using a unique employee ID
  /Employees/{EmployeeID}/ukopeningbalances:
    get:
      security:
        - OAuth2:
            - payroll.employees
            - payroll.employees.read
      tags:
        - PayrollUk
      operationId: getEmployeeOpeningBalances
      x-hasPayrollUkProblem: true
      summary: Retrieves a specific employee's openingbalances using a unique employee ID
    post:
      security:
        - OAuth2:
            - payroll.employees
      tags:
        - PayrollUk
      operationId: createEmployeeOpeningBalances
      x-hasPayrollUkProblem: true
      summary: Creates an opening balance for a specific employee
    put:
      security:
        - OAuth2:
            - payroll.employees
      tags:
        - PayrollUk
      operationId: updateEmployeeOpeningBalances
      x-hasPayrollUkProblem: true
      summary: Updates a specific employee's opening balances
  /Employees/{EmployeeID}/Leave:
    get:
      security:
        - OAuth2:
            - payroll.employees
            - payroll.employees.read
      tags:
        - PayrollUk
      operationId: getEmployeeLeaves
      x-hasPayrollUkProblem: true
      summary: Retrieves a specific employee's leave records using a unique employee ID
    post:
      security:
        - OAuth2:
            - payroll.employees
      tags:
        - PayrollUk
      operationId: createEmployeeLeave
      x-hasPayrollUkProblem: true
      summary: Creates leave records for a specific employee
  /Employees/{EmployeeID}/Leave/{LeaveID}:
    get:
      security:
        - OAuth2:
            - payroll.employees
            - payroll.employees.read
      tags:
        - PayrollUk
      operationId: getEmployeeLeave
      x-hasPayrollUkProblem: true
      summary: Retrieves a specific employee's leave record using a unique employee ID
    put:
      security:
        - OAuth2:
            - payroll.employees
      tags:
        - PayrollUk
      operationId: updateEmployeeLeave
      x-hasPayrollUkProblem: true
      summary: Updates a specific employee's leave records
    delete:
      security:
        - OAuth2:
            - payroll.employees
      tags:
        - PayrollUk
      operationId: deleteEmployeeLeave
      x-hasPayrollUkProblem: true
      summary: Deletes a specific employee's leave record
  /Employees/{EmployeeID}/LeaveBalances:
    get:
      security:
        - OAuth2:
            - payroll.employees
            - payroll.employees.read
      tags:
        - PayrollUk
      operationId: getEmployeeLeaveBalances
      x-hasPayrollUkProblem: true
      summary: Retrieves a specific employee's leave balances using a unique employee ID
  /Employees/{EmployeeID}/StatutoryLeaveBalance:
    get:
      security:
        - OAuth2:
            - payroll.employees
            - payroll.employees.read
      tags:
        - PayrollUk
      operationId: getEmployeeStatutoryLeaveBalances
      x-hasPayrollUkProblem: true
      summary: Retrieves a specific employee's leave balances using a unique employee ID
  /StatutoryLeaves/Summary/{EmployeeID}:
    get:
      security:
        - OAuth2:
            - payroll.settings
            - payroll.settings.read
      tags:
        - PayrollUk
      operationId: getStatutoryLeaveSummary
      x-hasPayrollUkProblem: true
      summary: Retrieves a specific employee's summary of statutory leaves using a unique employee ID
  /StatutoryLeaves/Sick:
    post:
      security:
        - OAuth2:
            - payroll.settings
      tags:
        - PayrollUk
      operationId: createEmployeeStatutorySickLeave
      x-hasPayrollUkProblem: true
      summary: Creates statutory sick leave records
  /StatutoryLeaves/Sick/{StatutorySickLeaveID}:
    get:
      security:
        - OAuth2:
            - payroll.settings
            - payroll.settings.read
      tags:
        - PayrollUk
      operationId: getEmployeeStatutorySickLeave
      x-hasPayrollUkProblem: true
      summary: Retrieves a statutory sick leave for an employee
  /Employees/{EmployeeID}/LeavePeriods:
    get:
      security:
        - OAuth2:
            - payroll.employees
            - payroll.employees.read
      tags:
        - PayrollUk
      operationId: getEmployeeLeavePeriods
      x-hasPayrollUkProblem: true
      summary: Retrieves a specific employee's leave periods using a unique employee ID
  /Employees/{EmployeeID}/LeaveTypes:
    get:
      security:
        - OAuth2:
            - payroll.employees
            - payroll.employees.read
      tags:
        - PayrollUk
      operationId: getEmployeeLeaveTypes
      x-hasPayrollUkProblem: true
      summary: Retrieves a specific employee's leave types using a unique employee ID
    post:
      security:
        - OAuth2:
            - payroll.employees
      tags:
        - PayrollUk
      operationId: createEmployeeLeaveType
      x-hasPayrollUkProblem: true
      summary: Creates employee leave type records
  /Employees/{EmployeeID}/PaymentMethods:
    get:
      security:
        - OAuth2:
            - payroll.employees
            - payroll.employees.read
      tags:
        - PayrollUk
      operationId: getEmployeePaymentMethod
      x-hasPayrollUkProblem: true
      summary: Retrieves a specific employee's payment method using a unique employee ID
    post:
      security:
        - OAuth2:
            - payroll.employees
      tags:
        - PayrollUk
      operationId: createEmployeePaymentMethod
      x-hasPayrollUkProblem: true
      summary: Creates an employee payment method
  /Employees/{EmployeeID}/PayTemplates:
    get:
      security:
        - OAuth2:
            - payroll.employees
            - payroll.employees.read
      tags:
        - PayrollUk
      operationId: getEmployeePayTemplate
      x-hasPayrollUkProblem: true
      summary: Retrieves a specific employee pay templates using a unique employee ID
  # 503
  /Employees/{EmployeeID}/PayTemplates/earnings:
    post:
      security:
        - OAuth2:
            - payroll.employees
      tags:
        - PayrollUk
      operationId: createEmployeeEarningsTemplate
      x-hasPayrollUkProblem: true
      summary: Creates an earnings template records for a specific employee
  /Employees/{EmployeeID}/PayTemplates/earnings/{PayTemplateEarningID}:
    put:
      security:
        - OAuth2:
            - payroll.employees
      tags:
        - PayrollUk
      operationId: updateEmployeeEarningsTemplate
      x-hasPayrollUkProblem: true
      summary: Updates a specific employee's earnings template records
    delete:
      security:
        - OAuth2:
            - payroll.employees
      tags:
        - PayrollUk
      operationId: deleteEmployeeEarningsTemplate
      summary: Deletes a specific employee's earnings template record
  /Employees/{EmployeeID}/paytemplateearnings:
    post:
      security:
        - OAuth2:
            - payroll.employees
      tags:
        - PayrollUk
      operationId: createMultipleEmployeeEarningsTemplate
      x-hasPayrollUkProblem: true
      summary: Creates multiple earnings template records for a specific employee using a unique employee ID
  /Benefits:
    get:
      security:
        - OAuth2:
            - payroll.settings
            - payroll.settings.read
      tags:
        - PayrollUk
      operationId: getBenefits
      x-hasPayrollUkProblem: true
      summary: Retrieves employee benefits
    post:
      security:
        - OAuth2:
            - payroll.settings
      tags:
        - PayrollUk
      operationId: createBenefit
      x-hasPayrollUkProblem: true
      summary: Creates a new employee benefit
  /Benefits/{id}:
    get:
      security:
        - OAuth2:
            - payroll.settings
            - payroll.settings.read
      tags:
        - PayrollUk
      operationId: getBenefit
      x-hasPayrollUkProblem: true
      summary: Retrieves a specific benefit by using a unique benefit ID
  /Deductions:
    get:
      security:
        - OAuth2:
            - payroll.settings
            - payroll.settings.read
      tags:
        - PayrollUk
      operationId: getDeductions
      x-hasPayrollUkProblem: true
      summary: Retrieves deductions
    post:
      security:
        - OAuth2:
            - payroll.settings
      tags:
        - PayrollUk
      operationId: createDeduction
      x-hasPayrollUkProblem: true
      summary: Creates a new deduction
  /Deductions/{deductionId}:
    get:
      security:
        - OAuth2:
            - payroll.settings
            - payroll.settings.read
      tags:
        - PayrollUk
      operationId: getDeduction
      x-hasPayrollUkProblem: true
      summary: Retrieves a specific deduction by using a unique deduction ID
  # NZ PAYROLL
  # /StatutoryDeductions:
  #   parameters:
  #     - $ref: '#/components/parameters/requiredHeader'
  #   get:
  #     security:
  #       - OAuth2: [payroll.settings, payroll.settings.read]
  #     tags:
  #       - PayrollNZ
  #     operationId: getStatutoryDeductions
  #     summary: searches statutory deductions
  #     parameters:
  #       - in: query
  #         name: page
  #         description: Page number which specifies the set of records to retrieve. By default the number of the records per set is 100.
  #         schema:
  #           type: integer
  #     responses:
  #       '200':
  #         description: search results matching criteria
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/StatutoryDeductions'
  # /StatutoryDeductions/{ID}:
  #   parameters:
  #     - $ref: '#/components/parameters/requiredHeader'
  #   get:
  #     security:
  #       - OAuth2: [payroll.settings, payroll.settings.read]
  #     tags:
  #       - PayrollUk
  #     operationId: getStatutoryDeduction
  #     summary: retrieve a single statutory deduction by id
  #     parameters:
  #       - in: path
  #         name: Id
  #         required: true
  #         description: Identifier for the statutory deduction
  #         schema:
  #           type: string
  #           format: uuid
  #     responses:
  #       '200':
  #         description: search results matching criteria
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/Benefit'
  /EarningsOrders:
    get:
      security:
        - OAuth2:
            - payroll.settings
            - payroll.settings.read
      tags:
        - PayrollUk
      operationId: getEarningsOrders
      x-hasPayrollUkProblem: true
      summary: Retrieves earnings orders
  /EarningsOrders/{id}:
    get:
      security:
        - OAuth2:
            - payroll.settings
            - payroll.settings.read
      tags:
        - PayrollUk
      operationId: getEarningsOrder
      x-hasPayrollUkProblem: true
      summary: Retrieves a specific earnings orders by using a unique earnings orders id
  /EarningsRates:
    get:
      security:
        - OAuth2:
            - payroll.settings
            - payroll.settings.read
      tags:
        - PayrollUk
      operationId: getEarningsRates
      x-hasPayrollUkProblem: true
      summary: Retrieves earnings rates
    post:
      security:
        - OAuth2:
            - payroll.settings
      tags:
        - PayrollUk
      operationId: createEarningsRate
      x-hasPayrollUkProblem: true
      summary: Creates a new earnings rate
  /EarningsRates/{EarningsRateID}:
    get:
      security:
        - OAuth2:
            - payroll.settings
            - payroll.settings.read
      tags:
        - PayrollUk
      operationId: getEarningsRate
      x-hasPayrollUkProblem: true
      summary: Retrieves a specific earnings rates by using a unique earnings rate id
  /LeaveTypes:
    get:
      security:
        - OAuth2:
            - payroll.settings
            - payroll.settings.read
      tags:
        - PayrollUk
      operationId: getLeaveTypes
      x-hasPayrollUkProblem: true
      summary: Retrieves leave types
    post:
      security:
        - OAuth2:
            - payroll.settings
      tags:
        - PayrollUk
      operationId: createLeaveType
      x-hasPayrollUkProblem: true
      summary: Creates a new leave type
  /LeaveTypes/{LeaveTypeID}:
    get:
      security:
        - OAuth2:
            - payroll.settings
            - payroll.settings.read
      tags:
        - PayrollUk
      operationId: getLeaveType
      x-hasPayrollUkProblem: true
      summary: Retrieves a specific leave type by using a unique leave type ID
  /Reimbursements:
    get:
      security:
        - OAuth2:
            - payroll.settings
            - payroll.settings.read
      tags:
        - PayrollUk
      operationId: getReimbursements
      x-hasPayrollUkProblem: true
      summary: Retrieves reimbursements
    post:
      security:
        - OAuth2:
            - payroll.settings
      tags:
        - PayrollUk
      operationId: createReimbursement
      x-hasPayrollUkProblem: true
      summary: Creates a new reimbursement
  /Reimbursements/{ReimbursementID}:
    get:
      security:
        - OAuth2:
            - payroll.settings
            - payroll.settings.read
      tags:
        - PayrollUk
      operationId: getReimbursement
      x-hasPayrollUkProblem: true
      summary: Retrieves a specific reimbursement by using a unique reimbursement id
  /Timesheets:
    get:
      security:
        - OAuth2:
            - payroll.timesheets
            - payroll.timesheets.read
      tags:
        - PayrollUk
      operationId: getTimesheets
      x-hasPayrollUkProblem: true
      summary: Retrieves timesheets
    post:
      security:
        - OAuth2:
            - payroll.timesheets
      tags:
        - PayrollUk
      operationId: createTimesheet
      x-hasPayrollUkProblem: true
      summary: Creates a new timesheet
  /Timesheets/{TimesheetID}:
    get:
      security:
        - OAuth2:
            - payroll.timesheets
            - payroll.timesheets.read
      tags:
        - PayrollUk
      operationId: getTimesheet
      x-hasPayrollUkProblem: true
      summary: Retrieve a specific timesheet by using a unique timesheet ID
    delete:
      security:
        - OAuth2:
            - payroll.timesheets
      tags:
        - PayrollUk
      operationId: deleteTimesheet
      summary: Deletes a specific timesheet
  /Timesheets/{TimesheetID}/Lines:
    post:
      security:
        - OAuth2:
            - payroll.timesheets
      tags:
        - PayrollUk
      operationId: createTimesheetLine
      x-hasPayrollUkProblem: true
      summary: Creates a new timesheet line for a specific timesheet using a unique timesheet ID
  /Timesheets/{TimesheetID}/Approve:
    post:
      security:
        - OAuth2:
            - payroll.timesheets
      tags:
        - PayrollUk
      operationId: approveTimesheet
      x-hasPayrollUkProblem: true
      summary: Approves a specific timesheet
  /Timesheets/{TimesheetID}/RevertToDraft:
    post:
      security:
        - OAuth2:
            - payroll.timesheets
      tags:
        - PayrollUk
      operationId: revertTimesheet
      x-hasPayrollUkProblem: true
      summary: Reverts a specific timesheet to draft
  /Timesheets/{TimesheetID}/Lines/{TimesheetLineID}:
    put:
      security:
        - OAuth2:
            - payroll.timesheets
      tags:
        - PayrollUk
      operationId: updateTimesheetLine
      x-hasPayrollUkProblem: true
      summary: Updates a specific timesheet line for a specific timesheet
    delete:
      security:
        - OAuth2:
            - payroll.timesheets
      tags:
        - PayrollUk
      operationId: deleteTimesheetLine
      summary: Deletes a specific timesheet line
  /PayRunCalendars:
    get:
      security:
        - OAuth2:
            - payroll.settings
            - payroll.settings.read
      tags:
        - PayrollUk
      operationId: getPayRunCalendars
      x-hasPayrollUkProblem: true
      summary: Retrieves payrun calendars
    post:
      security:
        - OAuth2:
            - payroll.settings
      tags:
        - PayrollUk
      operationId: createPayRunCalendar
      x-hasPayrollUkProblem: true
      summary: Creates a new payrun calendar
  /PayRunCalendars/{PayRunCalendarID}:
    get:
      security:
        - OAuth2:
            - payroll.settings
            - payroll.settings.read
      tags:
        - PayrollUk
      operationId: getPayRunCalendar
      x-hasPayrollUkProblem: true
      summary: Retrieves a specific payrun calendar by using a unique payrun calendar ID
  /Employees/{EmployeeID}/SalaryAndWages:
    get:
      security:
        - OAuth2:
            - payroll.employees
            - payroll.employees.read
      tags:
        - PayrollUk
      operationId: getEmployeeSalaryAndWages
      x-hasPayrollUkProblem: true
      summary: Retrieves a specific employee's salary and wages by using a unique employee ID
    post:
      security:
        - OAuth2:
            - payroll.employees
      tags:
        - PayrollUk
      operationId: createEmployeeSalaryAndWage
      x-hasPayrollUkProblem: true
      summary: Creates a salary and wage record for a specific employee
  /Employees/{EmployeeID}/SalaryAndWages/{SalaryAndWagesID}:
    get:
      security:
        - OAuth2:
            - payroll.employees
            - payroll.employees.read
      tags:
        - PayrollUk
      operationId: getEmployeeSalaryAndWage
      x-hasPayrollUkProblem: true
      summary: Retrieves a specific salary and wages record for a specific employee using a unique salary and wage id
    put:
      security:
        - OAuth2:
            - payroll.employees
      tags:
        - PayrollUk
      operationId: updateEmployeeSalaryAndWage
      x-hasPayrollUkProblem: true
      summary: Updates salary and wages record for a specific employee
    delete:
      security:
        - OAuth2:
            - payroll.employees
      tags:
        - PayrollUk
      operationId: deleteEmployeeSalaryAndWage
      summary: Deletes a salary and wages record for a specific employee
  /PayRuns:
    get:
      security:
        - OAuth2:
            - payroll.payruns
            - payroll.payruns.read
      tags:
        - PayrollUk
      operationId: getPayRuns
      x-hasPayrollUkProblem: true
      summary: Retrieves pay runs
  /PayRuns/{PayRunID}:
    get:
      security:
        - OAuth2:
            - payroll.payruns
            - payroll.payruns.read
      tags:
        - PayrollUk
      operationId: getPayRun
      x-hasPayrollUkProblem: true
      summary: Retrieves a specific pay run by using a unique pay run ID
  /Payslips:
    get:
      security:
        - OAuth2:
            - payroll.payslip
            - payroll.payslip.read
      tags:
        - PayrollUk
      operationId: getPaySlips
      x-hasPayrollUkProblem: true
      summary: Retrieves payslips
  /Payslips/{PayslipID}:
    get:
      security:
        - OAuth2:
            - payroll.payslip
            - payroll.payslip.read
      tags:
        - PayrollUk
      operationId: getPaySlip
      x-hasPayrollUkProblem: true
      summary: Retrieves a specific payslip by using a unique payslip ID
  /Settings:
    get:
      security:
        - OAuth2:
            - payroll.settings
            - payroll.settings.read
      tags:
        - PayrollUk
      operationId: getSettings
      x-hasPayrollUkProblem: true
      summary: Retrieves payroll settings
  /Settings/trackingCategories:
    get:
      security:
        - OAuth2:
            - payroll.settings
            - payroll.settings.read
      tags:
        - PayrollUk
      operationId: getTrackingCategories
      x-hasPayrollUkProblem: true
      summary: Retrieves tracking categories
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      description: For more information visit https://developer.xero.com/documentation/oauth2/overview
      flows:
        authorizationCode:
          authorizationUrl: https://login.xero.com/identity/connect/authorize
          tokenUrl: https://identity.xero.com/connect/token
          scopes:
            payroll.employees: Grant read-write access to payroll employees
            payroll.employees.read: Grant read-only access to payroll employees
            payroll.payruns: Grant read-write access to payroll payruns
            payroll.payruns.read: Grant read-only access to payroll payruns
            payroll.payslip: Grant read-write access to payroll payslips
            payroll.payslip.read: Grant read-only access to payroll payslips
            payroll.settings: Grant read-write access to payroll settings
            payroll.settings.read: Grant read-only access to payroll settings
            payroll.timesheets: Grant read-write access to payroll timesheets
            payroll.timesheets.read: Grant read-only access to payroll timesheets