openapi: 3.0.0
info:
  version: 12.0.0
  title: Xero Payroll AU API
  description: This is the Xero Payroll API for orgs in Australia region.
  termsOfService: https://developer.xero.com/xero-developer-platform-terms-conditions/
  contact:
    name: Xero Platform Team
    email: api@xero.com
    url: https://developer.xero.com
  license:
    name: MIT
    url: https://github.com/XeroAPI/Xero-OpenAPI/blob/master/LICENSE
servers:
  - description: Xero Payroll AU API
    url: https://api.xero.com/payroll.xro/1.0
tags:
  - name: PayrollAu
    description: Operations available to regular developers
paths:
  /Employees:
    get:
      security:
        - OAuth2:
            - payroll.employees
            - payroll.employees.read
      tags:
        - PayrollAu
      operationId: getEmployees
      summary: Searches payroll employees
    post:
      security:
        - OAuth2:
            - payroll.employees
      tags:
        - PayrollAu
      summary: Creates a payroll employee
      operationId: createEmployee
      x-hasPayrollAuProblem: true
  /Employees/{EmployeeID}:
    get:
      security:
        - OAuth2:
            - payroll.employees
            - payroll.employees.read
      tags:
        - PayrollAu
      summary: Retrieves an employee's detail by unique employee id
      operationId: getEmployee
    post:
      security:
        - OAuth2:
            - payroll.employees
      tags:
        - PayrollAu
      summary: Updates an employee's detail
      operationId: updateEmployee
      description: Update properties on a single employee
  /LeaveApplications:
    get:
      security:
        - OAuth2:
            - payroll.employees
            - payroll.employees.read
      tags:
        - PayrollAu
      operationId: getLeaveApplications
      summary: Retrieves leave applications
    post:
      security:
        - OAuth2:
            - payroll.employees
      tags:
        - PayrollAu
      summary: Creates a leave application
      operationId: createLeaveApplication
      x-hasPayrollAuProblem: true
  /LeaveApplications/v2:
    get:
      security:
        - OAuth2:
            - payroll.employees
            - payroll.employees.read
      tags:
        - PayrollAu
      operationId: getLeaveApplicationsV2
      summary: Retrieves leave applications including leave requests
  /LeaveApplications/{LeaveApplicationID}:
    get:
      security:
        - OAuth2:
            - payroll.employees
            - payroll.employees.read
      tags:
        - PayrollAu
      summary: Retrieves a leave application by a unique leave application id
      operationId: getLeaveApplication
    post:
      security:
        - OAuth2:
            - payroll.employees
      tags:
        - PayrollAu
      summary: Updates a specific leave application
      operationId: updateLeaveApplication
  /LeaveApplications/{LeaveApplicationID}/approve:
    post:
      security:
        - OAuth2:
            - payroll.employees
      tags:
        - PayrollAu
      summary: Approve a requested leave application by a unique leave application id
      operationId: approveLeaveApplication
  /LeaveApplications/{LeaveApplicationID}/reject:
    post:
      security:
        - OAuth2:
            - payroll.employees
      tags:
        - PayrollAu
      summary: Reject a leave application by a unique leave application id
      operationId: rejectLeaveApplication
  /PayItems:
    get:
      security:
        - OAuth2:
            - payroll.settings
            - payroll.settings.read
      tags:
        - PayrollAu
      operationId: getPayItems
      summary: Retrieves pay items
    post:
      security:
        - OAuth2:
            - payroll.settings
      tags:
        - PayrollAu
      summary: Creates a pay item
      operationId: createPayItem
  /PayrollCalendars:
    get:
      security:
        - OAuth2:
            - payroll.settings
            - payroll.settings.read
      tags:
        - PayrollAu
      operationId: getPayrollCalendars
      summary: Retrieves payroll calendars
    post:
      security:
        - OAuth2:
            - payroll.settings
      tags:
        - PayrollAu
      summary: Creates a Payroll Calendar
      operationId: createPayrollCalendar
      x-hasPayrollAuProblem: true
  /PayrollCalendars/{PayrollCalendarID}:
    get:
      security:
        - OAuth2:
            - payroll.settings
            - payroll.settings.read
      tags:
        - PayrollAu
      operationId: getPayrollCalendar
      summary: Retrieves payroll calendar by using a unique payroll calendar ID
  /PayRuns:
    get:
      security:
        - OAuth2:
            - payroll.payruns
            - payroll.payruns.read
      tags:
        - PayrollAu
      operationId: getPayRuns
      summary: Retrieves pay runs
    post:
      security:
        - OAuth2:
            - payroll.payruns
      tags:
        - PayrollAu
      summary: Creates a pay run
      operationId: createPayRun
      x-hasPayrollAuProblem: true
  /PayRuns/{PayRunID}:
    get:
      security:
        - OAuth2:
            - payroll.payruns
            - payroll.payruns.read
      tags:
        - PayrollAu
      summary: Retrieves a pay run by using a unique pay run id
      operationId: getPayRun
    post:
      security:
        - OAuth2:
            - payroll.payruns
      tags:
        - PayrollAu
      summary: Updates a pay run
      operationId: updatePayRun
      description: Update properties on a single PayRun
  /Payslip/{PayslipID}:
    get:
      security:
        - OAuth2:
            - payroll.payslip
            - payroll.payslip.read
      tags:
        - PayrollAu
      summary: Retrieves for a payslip by a unique payslip id
      operationId: getPayslip
    post:
      security:
        - OAuth2:
            - payroll.payslip
      tags:
        - PayrollAu
      summary: Updates a payslip
      operationId: updatePayslip
      x-hasPayrollAuError: true
      description: Update lines on a single payslips
  /Settings:
    get:
      security:
        - OAuth2:
            - payroll.settings
            - payroll.settings.read
      tags:
        - PayrollAu
      operationId: getSettings
      summary: Retrieves payroll settings
  /Superfunds:
    get:
      security:
        - OAuth2:
            - payroll.settings
            - payroll.settings.read
      tags:
        - PayrollAu
      operationId: getSuperfunds
      summary: Retrieves superfunds
    post:
      security:
        - OAuth2:
            - payroll.settings
      tags:
        - PayrollAu
      summary: Creates a superfund
      operationId: createSuperfund
      x-hasPayrollAuProblem: true
  /Superfunds/{SuperFundID}:
    get:
      security:
        - OAuth2:
            - payroll.settings
            - payroll.settings.read
      tags:
        - PayrollAu
      summary: Retrieves a superfund by using a unique superfund ID
      operationId: getSuperfund
    post:
      security:
        - OAuth2:
            - payroll.settings
      tags:
        - PayrollAu
      summary: Updates a superfund
      operationId: updateSuperfund
      description: Update properties on a single Superfund
  /SuperfundProducts:
    get:
      security:
        - OAuth2:
            - payroll.settings
            - payroll.settings.read
      tags:
        - PayrollAu
      operationId: getSuperfundProducts
      summary: Retrieves superfund products
  /Timesheets:
    get:
      security:
        - OAuth2:
            - payroll.timesheets
            - payroll.timesheets.read
      tags:
        - PayrollAu
      operationId: getTimesheets
      summary: Retrieves timesheets
    post:
      security:
        - OAuth2:
            - payroll.timesheets
      tags:
        - PayrollAu
      summary: Creates a timesheet
      operationId: createTimesheet
      x-hasPayrollAuProblem: true
  /Timesheets/{TimesheetID}:
    get:
      security:
        - OAuth2:
            - payroll.timesheets
            - payroll.timesheets.read
      tags:
        - PayrollAu
      summary: Retrieves a timesheet by using a unique timesheet id
      operationId: getTimesheet
    post:
      security:
        - OAuth2:
            - payroll.timesheets
      tags:
        - PayrollAu
      summary: Updates a timesheet
      operationId: updateTimesheet
      description: Update properties on a single timesheet
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      description: For more information visit https://developer.xero.com/documentation/oauth2/overview
      flows:
        authorizationCode:
          authorizationUrl: https://login.xero.com/identity/connect/authorize
          tokenUrl: https://identity.xero.com/connect/token
          scopes:
            email: Grant read-only access to your email
            openid: Grant read-only access to your open id
            profile: your profile information
            payroll.employees: Grant read-write access to payroll employees
            payroll.employees.read: Grant read-only access to payroll employees
            payroll.payruns: Grant read-write access to payroll payruns
            payroll.payruns.read: Grant read-only access to payroll payruns
            payroll.payslip: Grant read-write access to payroll payslips
            payroll.payslip.read: Grant read-only access to payroll payslips
            payroll.settings: Grant read-write access to payroll settings
            payroll.settings.read: Grant read-only access to payroll settings
            payroll.timesheets: Grant read-write access to payroll timesheets
            payroll.timesheets.read: Grant read-only access to payroll timesheets