export enum FEATURE_KEY {
  GET_ALL_USERS = 'GET_ALL_USERS',
  GET_USER = 'GET_USER',
  CREATE_USER = 'CREATE_USER',
  UPDATE_USER = 'UPDATE_USER',
  REPLACE_USER_WORKSPACES = 'REPLACE_USER_WORKSPACES',
  UPDATE_USER_WORKSPACE = 'UPDATE_USER_WORKSPACE',
  GET_ALL_WORKSPACES = 'GET_ALL_WORKSPACES',
  UPDATE_USER_ROLE = 'UPDATE_USER_ROLE',
}
