import { APP_RESOURCE_ACTIONS } from 'src/constants/global.constant';

export const UPDATE_LEVEL_ACTIONS = [
  APP_RESOURCE_ACTIONS.UPDATE,
  APP_RESOURCE_ACTIONS.EDIT,
  APP_RESOURCE_ACTIONS.VERSIONS_CREATE,
  APP_RESOURCE_ACTIONS.VERSION_DELETE,
  APP_RESOURCE_ACTIONS.VERSION_READ,
  APP_RESOURCE_ACTIONS.VERSION_UPDATE,
];
export const CREATE_LEVEL_ACTIONS = [APP_RESOURCE_ACTIONS.IMPORT, APP_RESOURCE_ACTIONS.CREATE];
export const UPDATE_CREATE_LEVEL_ACTIONS = [APP_RESOURCE_ACTIONS.CLONE];
export const READ_LEVEL_ACTIONS = [
  APP_RESOURCE_ACTIONS.READ,
  APP_RESOURCE_ACTIONS.VIEW,
  APP_RESOURCE_ACTIONS.VERSION_READ,
];
