export const commonSelectors={
  toastMessage: ".go318386747",
  appCard: "[data-cy=app-card]",
  editButton: "[data-cy=edit-button]",
  searchField:"[data-cy=widget-search-box]",
  firstWidget:"[data-cy=widget-list]:eq(0)",
  canvas:"[data-cy=real-canvas]",
  appCardOptions: "[data-cy=app-card-menu-icon]",
  folderItemOptions: "[data-cy=folder-item-menu-icon]",
  deleteApp: "[data-cy=card-options] :nth-child(5)>span",
  confirmButton: "[data-cy=confirm-yes-button]",
  autoSave: "[data-cy=autosave-indicator]",
  skipButton: ".driver-close-btn",
  skipInstallationModal: "[data-cy=skip-button]",
  homePageLogo: "[data-cy=home-page-logo]",
  emailField: "[data-cy=email-text-field]",
  passwordField: "[data-cy=password-text-field]",
  signInButton: "[data-cy=login-button]",
  dropdown: "[data-cy=workspace-dropdown]",
  backButton: "[data-cy=back-button]",
  emptyAppCreateButton: "[data-cy=create-new-application]",
  appCreateButton: "[data-cy=create-new-app-button]",
  createButton: "[data-cy=create-button]",
  appNameInput: "[data-cy=app-name-input]",
  dropdown: "[data-cy=workspace-dropdown]",
}