export const usersSelector ={
  dropdown: "[data-cy=workspace-dropdown]",
  inviteUserButton:"[data-cy=invite-new-user]",
  usersElements:{
    pageTitle: "[data-cy=users-page-title]",
    nameTitile: "[data-cy=name-title]",
    emailTitle: "[data-cy=email-title]",
    statusTitle: "[data-cy=status-title]",
    userName: "[data-cy=user-name]:eq(0)",
    userEmail: "[data-cy=user-email]:eq(0)",
    userStatus: "[data-cy=user-status]:eq(0)",
    userState: "[data-cy=user-state]:eq(0)",
  },
  cardTitle: "[data-cy=add-new-user]",
  firstNameInput: "[data-cy=first-name-input]",
  lastNameInput: "[data-cy=last-name-input]",
  emailLabel: "[data-cy=email-label]",
  emailInput: "[data-cy=email-input]",
  cancelButton: "[data-cy=cancel-button]",
  createUserButton: "[data-cy=create-user-button]",
  fisrtNameError: "[data-cy=first-name-error]",
  lastNameError: "[data-cy=last-name-error]",
  emailError: "[data-cy=email-error]",
  confirmInvitePage: "[data-cy=confirm-invite-container]",
  pageLogo: "[data-cy=page-logo]",
  confirmInviteElements:{
    cardTitle: "[data-cy=card-title]",
    acceptInvite: "[data-cy=accept-invite-button]",
    orOption: "[data-cy=or-option]",
    setupHeading: "[data-cy=setup-heading]",
    passwordLabel: "[data-cy=password-label]",
    confirmpasswordLabel: "[data-cy=confirm-password-label]",
    termsInfo: "[data-cy=terms-and-condition-info]",
  },
  passwordInput: "[data-cy=password-input]",
  confirmPasswordInput: "[data-cy=confirm-password-input]",
  finishSetup: "[data-cy=finish-setup-button]",
  emptyImage: "[data-cy=empty-img]",
  manageUsers: "[data-cy=manage-users]",
  createNewApp: "[data-cy=create-new-application]"
}