export const groupsSelector= {
  pageTitle: "[data-cy=user-groups-title]",
  createNewGroupButton: "[data-cy=create-new-group-button]",
  tableHeader: "[data-cy=table-header]",
  groupName:"[data-cy=group-name]",
  cardTitle: "[data-cy=card-title]",
  groupNameInput: "[data-cy=group-name-input]",
  cancelButton: "[data-cy=cancel-button]",
  createGroupButton: "[data-cy=create-group-button]",
  userGroup: "[data-cy=user-groups]",
  groupName: "[data-cy=group-name]",
  appsLink: "[data-cy=apps-link]",
  usersLink: "[data-cy=users-link]",
  permissionsLink: "[data-cy=permissions-link]",
  searchBox: ".select-search__input",
  addButton: ".active > .row > .col-auto",
  nameTableHeader: ".active [data-cy=name-header]",
  permissionstableHedaer: ".active [data-cy=permissions-header]",
  emailTableHeader: "[data-cy=email-header]",
  resourcesTableHeader: "[data-cy=resource-header]",
  resourcesApps: "[data-cy=resource-apps]",
  resourcesFolders: "[data-cy=resource-folders]",
  appsCreateCheck: "[data-cy=app-create-checkbox]",
  appsCreateLabel: "[data-cy=app-create-label]",
  appsDeleteCheck: "[data-cy=app-delete-checkbox]",
  appsDeleteLabel: "[data-cy=app-delete-label]",
  foldersCreateCheck: "[data-cy=folder-create-checkbox]",
  foldersCreateLabel: "[data-cy=folder-create-label]",
  confirmText: "[data-cy=modal-message]",
  confirmCancelButton: "[data-cy=confirm-cancel-button]",
  confirmYesButton : "[data-cy=confirm-yes-button]",
};