export enum FEATURE_KEY {
  GET_ALL_USERS = 'GET_ALL_USERS',
  UPDATE_USER_TYPE = 'UPDATE_USER_TYPE',
  AUTO_UPDATE_USER_PASSWORD = 'AUTO_UPDATE_USER_PASSWORD',
  CHANGE_USER_PASSWORD = 'CHANGE_USER_PASSWORD',
  UPDATE_USER_TYPE_INSTANCE = 'UPDATE_USER_TYPE_INSTANCE',
}
