export const fileButtonConfig = {
  name: 'FileButton',
  displayName: 'File button',
  description: 'A button that triggers file selection. Label updates to show selected file count after selection.',
  component: 'FileButton',
  defaultSize: {
    width: 10,
    height: 40,
  },
  others: {
    showOnDesktop: { type: 'toggle', displayName: 'Show on desktop' },
    showOnMobile: { type: 'toggle', displayName: 'Show on mobile' },
  },
  properties: {
    buttonText: {
      type: 'code',
      displayName: 'Button text',
      validation: { schema: { type: 'string' }, defaultValue: 'Upload file' },
      accordian: 'Data',
    },
    enableMultiple: {
      type: 'toggle',
      displayName: 'Enable multiple files',
      validation: { schema: { type: 'boolean' }, defaultValue: false },
      accordian: 'Data',
    },
    parseContent: {
      type: 'toggle',
      displayName: 'Parse file content',
      validation: { schema: { type: 'boolean' }, defaultValue: false },
      accordian: 'Data',
    },
    parseFileType: {
      type: 'select',
      displayName: 'File type',
      options: [
        { name: 'Autodetect from extension', value: 'auto-detect' },
        { name: 'CSV', value: 'csv' },
        { name: 'XLS', value: 'xls' },
        { name: 'XLSX', value: 'xlsx' },
        { name: 'JSON', value: 'json' },
      ],
      validation: { schema: { type: 'string' }, defaultValue: 'auto-detect' },
      conditionallyRender: { key: 'parseContent', value: true },
      accordian: 'Data',
    },
    delimiter: {
      type: 'code',
      displayName: 'Delimiter',
      validation: { schema: { type: 'string' }, defaultValue: ',' },
      conditionallyRender: [
        { key: 'parseContent', value: true },
        { key: 'parseFileType', value: 'csv' },
      ],
      accordian: 'Data',
    },
    enableClearSelection: {
      type: 'toggle',
      displayName: 'Enable clear selection',
      validation: { schema: { type: 'boolean' }, defaultValue: true },
      section: 'additionalActions',
    },
    loadingState: {
      type: 'toggle',
      displayName: 'Loading state',
      validation: { schema: { type: 'boolean' }, defaultValue: false },
      section: 'additionalActions',
    },
    visibility: {
      type: 'toggle',
      displayName: 'Visibility',
      validation: { schema: { type: 'boolean' }, defaultValue: true },
      section: 'additionalActions',
    },
    disabledState: {
      type: 'toggle',
      displayName: 'Disable',
      validation: { schema: { type: 'boolean' }, defaultValue: false },
      section: 'additionalActions',
    },
    tooltip: {
      type: 'code',
      displayName: 'Tooltip',
      validation: { schema: { type: 'string' }, defaultValue: '' },
      section: 'additionalActions',
      placeholder: 'Enter tooltip text',
    },
  },
  validation: {
    enableValidation: {
      type: 'toggle',
      displayName: 'Make this field mandatory',
      validation: { schema: { type: 'boolean' }, defaultValue: false },
    },
    fileType: {
      type: 'code',
      displayName: 'Accepted file types',
      validation: { schema: { type: 'string' }, defaultValue: '*/*' },
    },
    minSize: {
      type: 'code',
      displayName: 'Min size (bytes)',
      validation: {
        schema: { type: 'union', schemas: [{ type: 'string' }, { type: 'number' }] },
        defaultValue: 0,
      },
    },
    maxSize: {
      type: 'code',
      displayName: 'Max size (bytes)',
      validation: {
        schema: { type: 'union', schemas: [{ type: 'string' }, { type: 'number' }] },
        defaultValue: 1048576,
      },
    },
    minFileCount: {
      type: 'code',
      displayName: 'Min file count',
      validation: {
        schema: { type: 'union', schemas: [{ type: 'string' }, { type: 'number' }] },
        defaultValue: 1,
      },
      conditionallyRender: [{ key: 'enableMultiple', value: true, parentObjectKey: 'properties' }],
    },
    maxFileCount: {
      type: 'code',
      displayName: 'Max file count',
      validation: {
        schema: { type: 'union', schemas: [{ type: 'string' }, { type: 'number' }] },
        defaultValue: 2,
      },
      conditionallyRender: [{ key: 'enableMultiple', value: true, parentObjectKey: 'properties' }],
    },
  },
  events: {
    onFileSelected: { displayName: 'On file selected' },
    onFileLoaded: { displayName: 'On file loaded' },
  },
  styles: {
    labelSize: {
      type: 'numberInput',
      displayName: 'Label size',
      validation: {
        schema: { type: 'union', schemas: [{ type: 'string' }, { type: 'number' }] },
        defaultValue: 14,
      },
      accordian: 'label and icon',
    },
    labelWeight: {
      type: 'select',
      displayName: 'Label weight',
      options: [
        { name: 'Normal', value: 'normal' },
        { name: 'Medium', value: 'medium' },
        { name: 'Bold', value: 'bold' },
      ],
      validation: { schema: { type: 'string' }, defaultValue: 'medium' },
      accordian: 'label and icon',
    },
    labelColor: {
      type: 'colorSwatches',
      displayName: 'Label color',
      validation: { schema: { type: 'string' }, defaultValue: 'var(--cc-surface1-surface)' },
      accordian: 'label and icon',
    },
    icon: {
      type: 'icon',
      displayName: 'Icon',
      validation: { schema: { type: 'string' }, defaultValue: 'IconFileSearch' },
      accordian: 'label and icon',
      visibility: false,
    },
    iconColor: {
      type: 'colorSwatches',
      displayName: 'Icon color',
      validation: { schema: { type: 'string' }, defaultValue: 'var(--cc-surface1-surface)' },
      accordian: 'label and icon',
      showLabel: false,
      visibility: false,
    },
    iconDirection: {
      type: 'switch',
      displayName: '',
      showLabel: false,
      isIcon: true,
      isFxNotRequired: true,
      options: [
        { displayName: 'alignleftinspector', value: 'left', iconName: 'alignleftinspector' },
        { displayName: 'alignrightinspector', value: 'right', iconName: 'alignrightinspector' },
      ],
      accordian: 'label and icon',
    },
    loaderColor: {
      type: 'colorSwatches',
      displayName: 'Loader color',
      validation: { schema: { type: 'string' }, defaultValue: 'var(--cc-surface1-surface)' },
      accordian: 'label and icon',
    },
    contentAlignment: {
      type: 'switch',
      displayName: 'Content alignment',
      isIcon: true,
      isFxNotRequired: true,
      options: [
        { displayName: 'left', value: 'left', iconName: 'IconAlignLeft' },
        { displayName: 'center', value: 'center', iconName: 'IconAlignCenter' },
        { displayName: 'right', value: 'right', iconName: 'IconAlignRight' },
      ],
      accordian: 'label and icon',
    },
    buttonType: {
      type: 'switch',
      displayName: 'Button type',
      isFxNotRequired: true,
      options: [
        { displayName: 'Solid', value: 'solid' },
        { displayName: 'Outline', value: 'outline' },
      ],
      validation: { schema: { type: 'string' }, defaultValue: 'solid' },
      accordian: 'button',
    },
    backgroundColor: {
      type: 'colorSwatches',
      displayName: 'Background',
      validation: { schema: { type: 'string' }, defaultValue: 'var(--cc-primary-brand)' },
      conditionallyRender: {
        key: 'buttonType',
        value: 'solid',
      },
      accordian: 'button',
    },
    // hoverBackgroundColor: {
    //   type: 'colorSwatches',
    //   displayName: 'Hover background',
    //   validation: { schema: { type: 'string' }, defaultValue: 'auto' },
    //   accordian: 'button',
    // },
    borderRadius: {
      type: 'numberInput',
      displayName: 'Border radius',
      validation: {
        schema: { type: 'union', schemas: [{ type: 'string' }, { type: 'number' }] },
        defaultValue: 6,
      },
      accordian: 'button',
    },
    boxShadow: {
      type: 'boxShadow',
      displayName: 'Box shadow',
      validation: {
        schema: { type: 'union', schemas: [{ type: 'string' }, { type: 'number' }] },
        defaultValue: '0px 0px 0px 0px #00000040',
      },
      conditionallyRender: {
        key: 'buttonType',
        value: 'solid',
      },
      accordian: 'button',
    },
    padding: {
      type: 'switch',
      displayName: 'Padding',
      isFxNotRequired: true,
      options: [
        { displayName: 'Default', value: 'default' },
        { displayName: 'None', value: 'none' },
      ],
      validation: { schema: { type: 'string' }, defaultValue: 'default' },
      accordian: 'button',
    },
  },
  exposedVariables: {
    files: [],
    isParsing: false,
    isValid: false,
    isMandatory: false,
    isLoading: false,
    isVisible: true,
    isDisabled: false,
  },
  actions: [
    {
      handle: 'clear',
      displayName: 'Clear',
    },
    {
      handle: 'setFocus',
      displayName: 'Set focus',
    },
    {
      handle: 'setBlur',
      displayName: 'Set blur',
    },
    {
      handle: 'setVisibility',
      displayName: 'Set visibility',
      params: [{ handle: 'value', displayName: 'Value', defaultValue: '{{true}}', type: 'toggle' }],
    },
    {
      handle: 'setDisable',
      displayName: 'Set disable',
      params: [{ handle: 'value', displayName: 'Value', defaultValue: '{{false}}', type: 'toggle' }],
    },
    {
      handle: 'setLoading',
      displayName: 'Set loading',
      params: [{ handle: 'value', displayName: 'Value', defaultValue: '{{false}}', type: 'toggle' }],
    },
  ],
  definition: {
    others: {
      showOnDesktop: { value: '{{true}}' },
      showOnMobile: { value: '{{false}}' },
    },
    properties: {
      buttonText: { value: 'Upload file' },
      enableMultiple: { value: '{{false}}', fxActive: false },
      parseContent: { value: '{{false}}' },
      parseFileType: { value: 'auto-detect' },
      delimiter: { value: ',' },
      enableClearSelection: { value: '{{true}}' },
      loadingState: { value: '{{false}}' },
      visibility: { value: '{{true}}' },
      disabledState: { value: '{{false}}' },
      tooltip: { value: '' },
    },
    events: [],
    styles: {
      labelSize: { value: '14' },
      labelWeight: { value: 'medium' },
      labelColor: { value: 'var(--cc-surface1-surface)' },
      icon: { value: 'IconHome2' },
      iconVisibility: { value: false },
      iconColor: { value: 'var(--cc-surface1-surface)' },
      iconDirection: { value: 'left' },
      loaderColor: { value: 'var(--cc-surface1-surface)' },
      contentAlignment: { value: 'center' },
      buttonType: { value: 'solid' },
      backgroundColor: { value: 'var(--cc-primary-brand)' },
      // hoverBackgroundColor: { value: 'auto' },
      borderRadius: { value: '6' },
      boxShadow: { value: '0px 0px 0px 0px #00000040' },
      padding: { value: 'default' },
    },
    validation: {
      enableValidation: { value: '{{false}}' },
      fileType: { value: '*/*' },
      minSize: { value: '{{0}}' },
      maxSize: { value: '{{1048576}}' },
      minFileCount: { value: '{{1}}' },
      maxFileCount: { value: '{{2}}' },
    },
  },
};
