export const navigationConfig = {
  name: 'Navigation',
  displayName: 'Navigation',
  description: 'Create custom navigation menus',
  component: 'Navigation',
  defaultSize: {
    width: 20,
    height: 60,
  },
  others: {
    showOnDesktop: { type: 'toggle', displayName: 'Show on desktop' },
    showOnMobile: { type: 'toggle', displayName: 'Show on mobile' },
  },
  properties: {
    orientation: {
      type: 'switch',
      displayName: 'Orientation',
      validation: { schema: { type: 'string' } },
      options: [
        { displayName: 'Horizontal', value: 'horizontal' },
        { displayName: 'Vertical', value: 'vertical' },
      ],
      accordian: 'Menu',
    },
    displayStyle: {
      type: 'select',
      displayName: 'Style',
      validation: { schema: { type: 'string' } },
      options: [
        { name: 'Text and icon', value: 'textAndIcon' },
        { name: 'Text only', value: 'textOnly' },
        { name: 'Icon only', value: 'iconOnly' },
      ],
      accordian: 'Menu',
    },
    loadingState: {
      type: 'toggle',
      displayName: 'Loading state',
      validation: { schema: { type: 'boolean' }, defaultValue: false },
      section: 'additionalActions',
    },
    visibility: {
      type: 'toggle',
      displayName: 'Visibility',
      validation: { schema: { type: 'boolean' }, defaultValue: true },
      section: 'additionalActions',
    },
    disabledState: {
      type: 'toggle',
      displayName: 'Disable',
      validation: { schema: { type: 'boolean' }, defaultValue: false },
      section: 'additionalActions',
    },
  },
  events: {
    onClick: { displayName: 'On click' },
  },
  styles: {
    // Nav menu item styles
    unselectedTextColor: {
      type: 'colorSwatches',
      displayName: 'Text',
      validation: { schema: { type: 'string' }, defaultValue: 'var(--cc-primary-text)' },
      accordian: 'Nav menu item',
    },
    unselectedIconColor: {
      type: 'colorSwatches',
      displayName: 'Icon',
      validation: { schema: { type: 'string' }, defaultValue: 'var(--cc-default-icon)' },
      accordian: 'Nav menu item',
    },
    hoverPillBackgroundColor: {
      type: 'colorSwatches',
      displayName: 'Hover pill background',
      validation: { schema: { type: 'string' }, defaultValue: 'var(--cc-surface1-surface)' },
      accordian: 'Nav menu item',
    },
    selectedTextColor: {
      type: 'colorSwatches',
      displayName: 'Selected text',
      validation: { schema: { type: 'string' }, defaultValue: 'var(--cc-primary-brand)' },
      accordian: 'Nav menu item',
    },
    selectedIconColor: {
      type: 'colorSwatches',
      displayName: 'Selected icon',
      validation: { schema: { type: 'string' }, defaultValue: 'var(--cc-primary-brand)' },
      accordian: 'Nav menu item',
    },
    selectedPillBackgroundColor: {
      type: 'colorSwatches',
      displayName: 'Selected pill background',
      validation: { schema: { type: 'string' }, defaultValue: 'var(--cc-surface2-surface)' },
      accordian: 'Nav menu item',
    },
    pillBorderRadius: {
      type: 'numberInput',
      displayName: 'Pill border radius',
      validation: { schema: { type: 'union', schemas: [{ type: 'string' }, { type: 'number' }] }, defaultValue: 6 },
      accordian: 'Nav menu item',
    },
    // Container styles
    backgroundColor: {
      type: 'colorSwatches',
      displayName: 'Background',
      validation: { schema: { type: 'string' }, defaultValue: 'var(--cc-surface1-surface)' },
      accordian: 'Container',
    },
    borderColor: {
      type: 'colorSwatches',
      displayName: 'Border',
      validation: { schema: { type: 'string' }, defaultValue: 'var(--cc-weak-border)' },
      accordian: 'Container',
    },
    borderRadius: {
      type: 'numberInput',
      displayName: 'Border radius',
      validation: { schema: { type: 'union', schemas: [{ type: 'string' }, { type: 'number' }] }, defaultValue: 8 },
      accordian: 'Container',
    },
    padding: {
      type: 'numberInput',
      displayName: 'Padding',
      validation: { schema: { type: 'union', schemas: [{ type: 'string' }, { type: 'number' }] }, defaultValue: 8 },
      accordian: 'Container',
    },
  },
  exposedVariables: {
    selectedItem: null,
    previousSelectedItem: null,
    isVisible: true,
    isDisabled: false,
    isLoading: false,
  },
  actions: [
    {
      handle: 'setVisibility',
      displayName: 'Set visibility',
      params: [{ handle: 'visibility', displayName: 'Value', defaultValue: '{{true}}', type: 'toggle' }],
    },
    {
      handle: 'setDisable',
      displayName: 'Set disable',
      params: [{ handle: 'disable', displayName: 'Value', defaultValue: '{{false}}', type: 'toggle' }],
    },
    {
      handle: 'setLoading',
      displayName: 'Set loading',
      params: [{ handle: 'loading', displayName: 'Value', defaultValue: '{{false}}', type: 'toggle' }],
    },
    {
      handle: 'selectItem',
      displayName: 'Select item',
      params: [{ handle: 'id', displayName: 'Item ID', defaultValue: '', type: 'text' }],
    },
  ],
  definition: {
    others: {
      showOnDesktop: { value: '{{true}}' },
      showOnMobile: { value: '{{false}}' },
    },
    properties: {
      orientation: { value: 'horizontal' },
      displayStyle: { value: 'textAndIcon' },
      menuItems: {
        value: [
          {
            id: 'item1',
            label: 'System',
            icon: { value: 'IconArchive' },
            iconVisibility: true,
            visible: { value: '{{false}}' },
            disable: { value: '{{false}}' },
            isGroup: false,
          },
          {
            id: 'item2',
            label: 'Spindle IOT Whitelist',
            icon: { value: 'IconListDetails' },
            iconVisibility: true,
            visible: { value: '{{false}}' },
            disable: { value: '{{false}}' },
            isGroup: false,
          },
          {
            id: 'group1',
            label: 'Group 1',
            icon: { value: 'IconFolder' },
            iconVisibility: true,
            visible: { value: '{{false}}' },
            disable: { value: '{{false}}' },
            isGroup: true,
            children: [
              {
                id: 'item3',
                label: 'Facilities',
                icon: { value: 'IconFileCode' },
                iconVisibility: true,
                visible: { value: '{{false}}' },
                disable: { value: '{{false}}' },
                isGroup: false,
              },
              {
                id: 'item4',
                label: 'Requirements',
                icon: { value: 'IconBulb' },
                iconVisibility: true,
                visible: { value: '{{false}}' },
                disable: { value: '{{false}}' },
                isGroup: false,
              },
            ],
          },
          {
            id: 'item5',
            label: 'Portlet KPI Target',
            icon: { value: 'IconLock' },
            iconVisibility: true,
            visible: { value: '{{false}}' },
            disable: { value: '{{false}}' },
            isGroup: false,
          },
          {
            id: 'item6',
            label: 'KPI Entry',
            icon: { value: 'IconMap' },
            iconVisibility: true,
            visible: { value: '{{false}}' },
            disable: { value: '{{false}}' },
            isGroup: false,
          },
          {
            id: 'group2',
            label: 'Group 2',
            icon: { value: 'IconFolder' },
            iconVisibility: true,
            visible: { value: '{{false}}' },
            disable: { value: '{{false}}' },
            isGroup: true,
            children: [
              {
                id: 'item7',
                label: 'Alerts',
                icon: { value: 'IconBolt' },
                iconVisibility: true,
                visible: { value: '{{false}}' },
                disable: { value: '{{false}}' },
                isGroup: false,
              },
            ],
          },
          {
            id: 'item8',
            label: 'Spindle Login Station',
            icon: { value: 'IconArchive' },
            iconVisibility: true,
            visible: { value: '{{false}}' },
            disable: { value: '{{false}}' },
            isGroup: false,
          },
          {
            id: 'item9',
            label: 'KPI Feature',
            icon: { value: 'IconListDetails' },
            iconVisibility: true,
            visible: { value: '{{false}}' },
            disable: { value: '{{false}}' },
            isGroup: false,
          },
          {
            id: 'item10',
            label: 'Translation',
            icon: { value: 'IconMap' },
            iconVisibility: true,
            visible: { value: '{{false}}' },
            disable: { value: '{{false}}' },
            isGroup: false,
          },
        ],
      },
      visibility: { value: '{{true}}' },
      disabledState: { value: '{{false}}' },
      loadingState: { value: '{{false}}' },
    },
    events: [],
    styles: {
      unselectedTextColor: { value: 'var(--cc-primary-text)' },
      unselectedIconColor: { value: 'var(--cc-default-icon)' },
      hoverPillBackgroundColor: { value: 'var(--cc-surface3-surface)' },
      selectedTextColor: { value: 'var(--cc-primary-brand)' },
      selectedIconColor: { value: 'var(--cc-primary-brand)' },
      selectedPillBackgroundColor: { value: 'var(--cc-surface2-surface)' },
      pillBorderRadius: { value: '6' },
      backgroundColor: { value: 'var(--cc-surface1-surface)' },
      borderColor: { value: 'var(--cc-weak-border)' },
      borderRadius: { value: '8' },
      padding: { value: '8' },
    },
  },
};
