export enum FEATURE_KEY {
  GET_CUSTOM_STYLES = 'GET_CUSTOM_STYLES',
  GET_CUSTOM_STYLES_FOR_APP = 'GET_CUSTOM_STYLES_FOR_APP',
  GET_CUSTOM_STYLES_FROM_APP = 'GET_CUSTOM_STYLES_FROM_APP',
  SAVE_CUSTOM_STYLES = 'SAVE_CUSTOM_STYLES',
}
