export const TypeMapping = {
  text: 'Text',
  string: 'Text',
  color: 'Color',
  json: 'Json',
  code: 'Code',
  toggle: 'Toggle',
  select: 'Select',
  alignButtons: 'AlignButtons',
  number: 'Number',
  boxShadow: 'BoxShadow',
  clientServerSwitch: 'ClientServerSwitch',
  checkbox: 'Checkbox',
  slider: 'Slider',
  switch: 'Switch',
  input: 'Input',
  icon: 'Icon',
  visibility: 'Visibility',
  numberInput: 'NumberInput',
};
