/**
 * Setting a column's type to Multiselect must seed coloured tags.
 *
 * Covered separately from the widget spec because the two routes to a
 * multiselect column — a fresh Table's autogenerated one and this hook — share
 * no code.
 */
import { renderHook } from '@testing-library/react';
import { useColumnManager } from '../useColumnManager';

// paramUpdated is the only call that persists columns into the app definition.
const savedColumn = (paramUpdated) => {
  const [property, , columns] = paramUpdated.mock.calls.at(-1);
  expect(property).toEqual({ name: 'columns' });
  return columns[0];
};

const setup = () => {
  const paramUpdated = jest.fn();
  const columns = [{ name: 'interest', key: 'interest', id: 'col-interest', columnType: 'string' }];
  const component = {
    component: { definition: { properties: { columns: { value: columns }, isAllColumnsEditable: { value: false } } } },
  };
  const { result } = renderHook(() => useColumnManager({ component, paramUpdated, currentState: {} }));
  return { result, paramUpdated };
};

describe('column type defaults', () => {
  test('choosing Multiselect turns coloured tags on', () => {
    const { result, paramUpdated } = setup();

    result.current.updateColumnProperty(0, 'columnType', 'newMultiSelect');

    expect(savedColumn(paramUpdated).autoAssignColors).toBe(true);
  });

  // Guards against the seeding being widened into a blanket default.
  test('choosing a type with no tags does not get the flag', () => {
    const { result, paramUpdated } = setup();

    result.current.updateColumnProperty(0, 'columnType', 'datepicker');

    expect(savedColumn(paramUpdated).autoAssignColors).toBeUndefined();
  });
});
