name: Deploy docs to netfliy 

on:
  push:
    branches:
    - develop
    paths: 
    - docs/**  
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
    - name: Trigger hook to deploy docs on Netlify
      run: curl -X POST -d {} ${{ secrets.NETLIFY_HOOK }}
