name: Deploy docs to Netlify

on:
  workflow_dispatch:
  push:
    branches: [develop]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Trigger hook to deploy docs on Netlify
      run: curl -X POST -d {} ${{ secrets.NETLIFY_HOOK }}
