name: LTS Test system deploy

on:
  workflow_run:
    workflows: ["Tooljet release docker images build"]
    types:
      - completed

jobs:
  Build-and-update-image:
    runs-on: ubuntu-22.04

    steps:
      - name: SSH into GCP VM instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_INSTANCE_IP }}
          username: ${{ secrets.GCP_USERNAME }}
          key: ${{ secrets.EC2_INSTANCE_SSH_KEY }}
          script: |
            ls -lah

            # Stop the Docker containers
            sudo docker-compose down

            # Remove the existing tooljet/* images
            sudo docker images -a | grep 'tooljet/' | awk '{print $3}' | xargs sudo docker rmi -f

            # Check remaining images
            sudo docker images

            # Update docker-compose.yml with the new image for tooljet service
            sed -i '/^[[:space:]]*tooljet:/,/^[[:space:]]*[^:]*$/ { /^[[:space:]]*image:[[:space:]]*tooljet\/tj-osv/s|\(image:[[:space:]]*\).*|\1tooljet/tj-osv:'"${{ env.SAFE_BRANCH_NAME }}"'| }' docker-compose.yaml

            # Start the Docker containers
            cat docker-compose.yaml
            sudo docker-compose up -d

            #View containers
            sudo docker ps
