{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Deals",
    "version" : "v3"
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com/"
  } ],
  "tags" : [ {
    "name" : "Associations"
  }, {
    "name" : "Basic"
  }, {
    "name" : "Batch"
  }, {
    "name" : "Search"
  }, {
    "name" : "Public_Object"
  } ],
  "paths" : {
    "/crm/v3/objects/deals" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "List",
        "description" : "Read a page of deals. Control what is returned via the `properties` query param.",
        "operationId" : "get-/crm/v3/objects/deals_getPage",
        "security" : [ {
          "hapikey" : [ ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        } ]
      },
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Create",
        "description" : "Create a deal with the given properties and return a copy of the object, including the ID. Documentation and examples for creating standard deals is provided.",
        "operationId" : "post-/crm/v3/objects/deals_create",
        "security" : [ {
          "hapikey" : [ ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        } ]
      }
    },
    "/crm/v3/objects/deals/batch/archive" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Archive a batch of deals by ID",
        "operationId" : "post-/crm/v3/objects/deals/batch/archive_archive",
        "security" : [ {
          "hapikey" : [ ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        } ]
      }
    },
    "/crm/v3/objects/deals/batch/create" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Create a batch of deals",
        "operationId" : "post-/crm/v3/objects/deals/batch/create_create",
        "security" : [ {
          "hapikey" : [ ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        } ]
      }
    },
    "/crm/v3/objects/deals/batch/read" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Read a batch of deals by internal ID, or unique property values",
        "operationId" : "post-/crm/v3/objects/deals/batch/read_read",
        "security" : [ {
          "hapikey" : [ ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        } ]
      }
    },
    "/crm/v3/objects/deals/batch/update" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Update a batch of deals",
        "operationId" : "post-/crm/v3/objects/deals/batch/update_update",
        "security" : [ {
          "hapikey" : [ ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        } ]
      }
    },
    "/crm/v3/objects/deals/merge" : {
      "post" : {
        "tags" : [ "Public_Object" ],
        "summary" : "Merge two deals with same type",
        "operationId" : "post-/crm/v3/objects/deals/merge_merge",
        "security" : [ {
          "hapikey" : [ ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        } ]
      }
    },
    "/crm/v3/objects/deals/search" : {
      "post" : {
        "tags" : [ "Search" ],
        "operationId" : "post-/crm/v3/objects/deals/search_doSearch",
        "security" : [ {
          "hapikey" : [ ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        } ],
        "x-hubspot-rate-limit-exemptions" : [ "ten-secondly" ]
      }
    },
    "/crm/v3/objects/deals/{dealId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Read",
        "description" : "Read an Object identified by `{dealId}`. `{dealId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param.  Control what is returned via the `properties` query param.",
        "operationId" : "get-/crm/v3/objects/deals/{dealId}_getById",
        "security" : [ {
          "hapikey" : [ ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Archive",
        "description" : "Move an Object identified by `{dealId}` to the recycling bin.",
        "operationId" : "delete-/crm/v3/objects/deals/{dealId}_archive",
        "security" : [ {
          "hapikey" : [ ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Basic" ],
        "summary" : "Update",
        "description" : "Perform a partial update of an Object identified by `{dealId}`. `{dealId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param. Provided property values will be overwritten. Read-only and non-existent properties will be ignored. Properties values can be cleared by passing an empty string.",
        "operationId" : "patch-/crm/v3/objects/deals/{dealId}_update",
        "security" : [ {
          "hapikey" : [ ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.objects.deals.read" : " ",
              "crm.objects.deals.write" : " "
            }
          }
        }
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "PHP", "Node", "Python", "Ruby" ]
}