{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "CRM Pipelines",
    "description" : "Pipelines represent distinct stages in a workflow, like closing a deal or servicing a support ticket. These endpoints provide access to read and modify pipelines in HubSpot. Pipelines support `deals` and `tickets` object types.\n\n## Pipeline ID validation\n\nWhen calling endpoints that take pipelineId as a parameter, that ID must correspond to an existing, un-archived pipeline. Otherwise the request will fail with a `404 Not Found` response.",
    "version" : "v3"
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com/"
  } ],
  "tags" : [ {
    "name" : "Pipeline Stages"
  }, {
    "name" : "Pipelines"
  }, {
    "name" : "Pipeline Audits"
  }, {
    "name" : "Pipeline Stage Audits"
  } ],
  "paths" : {
    "/crm/v3/pipelines/{objectType}" : {
      "get" : {
        "tags" : [ "Pipelines" ],
        "summary" : "Retrieve all pipelines",
        "description" : "Return all pipelines for the object type specified by `{objectType}`.",
        "operationId" : "get-/crm/v3/pipelines/{objectType}_getAll",
        "security" : [ {
          "oauth2_legacy" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps_legacy" : [ "timeline" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2_legacy" : [ "crm.schemas.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.schemas.quotes.read" ]
        }, {
          "private_apps" : [ "crm.schemas.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps_legacy" : [ "crm.schemas.custom.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps" : [ "crm.schemas.deals.read" ]
        }, {
          "oauth2" : [ "crm.schemas.deals.read" ]
        }, {
          "oauth2_legacy" : [ "timeline" ]
        }, {
          "private_apps_legacy" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.read" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.read" ]
        }, {
          "oauth2_legacy" : [ "tickets" ]
        }, {
          "hapikey" : [ ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.schemas.companies.read" ]
        }, {
          "oauth2" : [ "crm.schemas.companies.read" ]
        }, {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "tickets" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps" : [ "crm.schemas.line_items.read" ]
        }, {
          "oauth2" : [ "crm.schemas.line_items.read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Pipelines" ],
        "summary" : "Create a pipeline",
        "description" : "Create a new pipeline with the provided property values. The entire pipeline object, including its unique ID, will be returned in the response.",
        "operationId" : "post-/crm/v3/pipelines/{objectType}_create",
        "security" : [ {
          "oauth2_legacy" : [ "tickets" ]
        }, {
          "hapikey" : [ ]
        }, {
          "oauth2" : [ "crm.schemas.deals.write" ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.write" ]
        }, {
          "oauth2" : [ "crm.schemas.companies.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.write" ]
        }, {
          "private_apps" : [ "crm.schemas.companies.write" ]
        }, {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "tickets" ]
        }, {
          "private_apps_legacy" : [ "crm.schemas.custom.write" ]
        }, {
          "private_apps" : [ "crm.schemas.deals.write" ]
        } ]
      }
    },
    "/crm/v3/pipelines/{objectType}/{pipelineId}" : {
      "get" : {
        "tags" : [ "Pipelines" ],
        "summary" : "Return a pipeline by ID",
        "description" : "Return a single pipeline object identified by its unique `{pipelineId}`.",
        "operationId" : "get-/crm/v3/pipelines/{objectType}/{pipelineId}_getById",
        "security" : [ {
          "oauth2_legacy" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps_legacy" : [ "timeline" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2_legacy" : [ "crm.schemas.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.schemas.quotes.read" ]
        }, {
          "private_apps" : [ "crm.schemas.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps_legacy" : [ "crm.schemas.custom.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps" : [ "crm.schemas.deals.read" ]
        }, {
          "oauth2" : [ "crm.schemas.deals.read" ]
        }, {
          "oauth2_legacy" : [ "timeline" ]
        }, {
          "private_apps_legacy" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.read" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.read" ]
        }, {
          "oauth2_legacy" : [ "tickets" ]
        }, {
          "hapikey" : [ ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.schemas.companies.read" ]
        }, {
          "oauth2" : [ "crm.schemas.companies.read" ]
        }, {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "tickets" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps" : [ "crm.schemas.line_items.read" ]
        }, {
          "oauth2" : [ "crm.schemas.line_items.read" ]
        } ]
      },
      "put" : {
        "tags" : [ "Pipelines" ],
        "summary" : "Replace a pipeline",
        "description" : "Replace all the properties of an existing pipeline with the values provided. This will overwrite any existing pipeline stages. The updated pipeline will be returned in the response.",
        "operationId" : "put-/crm/v3/pipelines/{objectType}/{pipelineId}_replace",
        "security" : [ {
          "oauth2_legacy" : [ "tickets" ]
        }, {
          "hapikey" : [ ]
        }, {
          "oauth2" : [ "crm.schemas.deals.write" ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.write" ]
        }, {
          "oauth2" : [ "crm.schemas.companies.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.write" ]
        }, {
          "private_apps" : [ "crm.schemas.companies.write" ]
        }, {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "tickets" ]
        }, {
          "private_apps_legacy" : [ "crm.schemas.custom.write" ]
        }, {
          "private_apps" : [ "crm.schemas.deals.write" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Pipelines" ],
        "summary" : "Delete a pipeline",
        "description" : "Delete the pipeline identified by `{pipelineId}`.",
        "operationId" : "delete-/crm/v3/pipelines/{objectType}/{pipelineId}_archive",
        "security" : [ {
          "oauth2_legacy" : [ "tickets" ]
        }, {
          "hapikey" : [ ]
        }, {
          "oauth2" : [ "crm.schemas.deals.write" ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.write" ]
        }, {
          "oauth2" : [ "crm.schemas.companies.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.write" ]
        }, {
          "private_apps" : [ "crm.schemas.companies.write" ]
        }, {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "tickets" ]
        }, {
          "private_apps_legacy" : [ "crm.schemas.custom.write" ]
        }, {
          "private_apps" : [ "crm.schemas.deals.write" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Pipelines" ],
        "summary" : "Update a pipeline",
        "description" : "Perform a partial update of the pipeline identified by `{pipelineId}`. The updated pipeline will be returned in the response.",
        "operationId" : "patch-/crm/v3/pipelines/{objectType}/{pipelineId}_update",
        "security" : [ {
          "oauth2_legacy" : [ "tickets" ]
        }, {
          "hapikey" : [ ]
        }, {
          "oauth2" : [ "crm.schemas.deals.write" ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.write" ]
        }, {
          "oauth2" : [ "crm.schemas.companies.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.write" ]
        }, {
          "private_apps" : [ "crm.schemas.companies.write" ]
        }, {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "tickets" ]
        }, {
          "private_apps_legacy" : [ "crm.schemas.custom.write" ]
        }, {
          "private_apps" : [ "crm.schemas.deals.write" ]
        } ]
      }
    },
    "/crm/v3/pipelines/{objectType}/{pipelineId}/audit" : {
      "get" : {
        "tags" : [ "Pipeline Audits" ],
        "summary" : "Return an audit of all changes to the pipeline",
        "description" : "Return a reverse chronological list of all mutations that have occurred on the pipeline identified by `{pipelineId}`.",
        "operationId" : "get-/crm/v3/pipelines/{objectType}/{pipelineId}/audit_getAudit",
        "security" : [ {
          "oauth2_legacy" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps_legacy" : [ "timeline" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2_legacy" : [ "crm.schemas.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.schemas.quotes.read" ]
        }, {
          "private_apps" : [ "crm.schemas.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps_legacy" : [ "crm.schemas.custom.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps" : [ "crm.schemas.deals.read" ]
        }, {
          "oauth2" : [ "crm.schemas.deals.read" ]
        }, {
          "oauth2_legacy" : [ "timeline" ]
        }, {
          "private_apps_legacy" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.read" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.read" ]
        }, {
          "oauth2_legacy" : [ "tickets" ]
        }, {
          "hapikey" : [ ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.schemas.companies.read" ]
        }, {
          "oauth2" : [ "crm.schemas.companies.read" ]
        }, {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "tickets" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps" : [ "crm.schemas.line_items.read" ]
        }, {
          "oauth2" : [ "crm.schemas.line_items.read" ]
        } ]
      }
    },
    "/crm/v3/pipelines/{objectType}/{pipelineId}/stages" : {
      "get" : {
        "tags" : [ "Pipeline Stages" ],
        "summary" : "Return all stages of a pipeline",
        "description" : "Return all the stages associated with the pipeline identified by `{pipelineId}`.",
        "operationId" : "get-/crm/v3/pipelines/{objectType}/{pipelineId}/stages_getAll",
        "security" : [ {
          "oauth2_legacy" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps_legacy" : [ "timeline" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2_legacy" : [ "crm.schemas.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.schemas.quotes.read" ]
        }, {
          "private_apps" : [ "crm.schemas.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps_legacy" : [ "crm.schemas.custom.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps" : [ "crm.schemas.deals.read" ]
        }, {
          "oauth2" : [ "crm.schemas.deals.read" ]
        }, {
          "oauth2_legacy" : [ "timeline" ]
        }, {
          "private_apps_legacy" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.read" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.read" ]
        }, {
          "oauth2_legacy" : [ "tickets" ]
        }, {
          "hapikey" : [ ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.schemas.companies.read" ]
        }, {
          "oauth2" : [ "crm.schemas.companies.read" ]
        }, {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "tickets" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps" : [ "crm.schemas.line_items.read" ]
        }, {
          "oauth2" : [ "crm.schemas.line_items.read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Pipeline Stages" ],
        "summary" : "Create a pipeline stage",
        "description" : "Create a new stage associated with the pipeline identified by `{pipelineId}`. The entire stage object, including its unique ID, will be returned in the response.",
        "operationId" : "post-/crm/v3/pipelines/{objectType}/{pipelineId}/stages_create",
        "security" : [ {
          "oauth2_legacy" : [ "tickets" ]
        }, {
          "hapikey" : [ ]
        }, {
          "oauth2" : [ "crm.schemas.deals.write" ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.write" ]
        }, {
          "oauth2" : [ "crm.schemas.companies.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.write" ]
        }, {
          "private_apps" : [ "crm.schemas.companies.write" ]
        }, {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "tickets" ]
        }, {
          "private_apps_legacy" : [ "crm.schemas.custom.write" ]
        }, {
          "private_apps" : [ "crm.schemas.deals.write" ]
        } ]
      }
    },
    "/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}" : {
      "get" : {
        "tags" : [ "Pipeline Stages" ],
        "summary" : "Return a pipeline stage by ID",
        "description" : "Return the stage identified by `{stageId}` associated with the pipeline identified by `{pipelineId}`.",
        "operationId" : "get-/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}_getById",
        "security" : [ {
          "oauth2_legacy" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps_legacy" : [ "timeline" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2_legacy" : [ "crm.schemas.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.schemas.quotes.read" ]
        }, {
          "private_apps" : [ "crm.schemas.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps_legacy" : [ "crm.schemas.custom.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps" : [ "crm.schemas.deals.read" ]
        }, {
          "oauth2" : [ "crm.schemas.deals.read" ]
        }, {
          "oauth2_legacy" : [ "timeline" ]
        }, {
          "private_apps_legacy" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.read" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.read" ]
        }, {
          "oauth2_legacy" : [ "tickets" ]
        }, {
          "hapikey" : [ ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.schemas.companies.read" ]
        }, {
          "oauth2" : [ "crm.schemas.companies.read" ]
        }, {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "tickets" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps" : [ "crm.schemas.line_items.read" ]
        }, {
          "oauth2" : [ "crm.schemas.line_items.read" ]
        } ]
      },
      "put" : {
        "tags" : [ "Pipeline Stages" ],
        "summary" : "Replace a pipeline stage",
        "description" : "Replace all the properties of an existing pipeline stage with the values provided. The updated stage will be returned in the response.",
        "operationId" : "put-/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}_replace",
        "security" : [ {
          "oauth2_legacy" : [ "tickets" ]
        }, {
          "hapikey" : [ ]
        }, {
          "oauth2" : [ "crm.schemas.deals.write" ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.write" ]
        }, {
          "oauth2" : [ "crm.schemas.companies.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.write" ]
        }, {
          "private_apps" : [ "crm.schemas.companies.write" ]
        }, {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "tickets" ]
        }, {
          "private_apps_legacy" : [ "crm.schemas.custom.write" ]
        }, {
          "private_apps" : [ "crm.schemas.deals.write" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Pipeline Stages" ],
        "summary" : "Delete a pipeline stage",
        "description" : "Delete the pipeline stage identified by `{stageId}` associated with the pipeline identified by `{pipelineId}`.",
        "operationId" : "delete-/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}_archive",
        "security" : [ {
          "oauth2_legacy" : [ "tickets" ]
        }, {
          "hapikey" : [ ]
        }, {
          "oauth2" : [ "crm.schemas.deals.write" ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.write" ]
        }, {
          "oauth2" : [ "crm.schemas.companies.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.write" ]
        }, {
          "private_apps" : [ "crm.schemas.companies.write" ]
        }, {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "tickets" ]
        }, {
          "private_apps_legacy" : [ "crm.schemas.custom.write" ]
        }, {
          "private_apps" : [ "crm.schemas.deals.write" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Pipeline Stages" ],
        "summary" : "Update a pipeline stage",
        "description" : "Perform a partial update of the pipeline stage identified by `{stageId}` associated with the pipeline identified by `{pipelineId}`. Any properties not included in this update will keep their existing values. The updated stage will be returned in the response.",
        "operationId" : "patch-/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}_update",
        "security" : [ {
          "oauth2_legacy" : [ "tickets" ]
        }, {
          "hapikey" : [ ]
        }, {
          "oauth2" : [ "crm.schemas.deals.write" ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.write" ]
        }, {
          "oauth2" : [ "crm.schemas.companies.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.write" ]
        }, {
          "private_apps" : [ "crm.schemas.companies.write" ]
        }, {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "tickets" ]
        }, {
          "private_apps_legacy" : [ "crm.schemas.custom.write" ]
        }, {
          "private_apps" : [ "crm.schemas.deals.write" ]
        } ]
      }
    },
    "/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}/audit" : {
      "get" : {
        "tags" : [ "Pipeline Stage Audits" ],
        "summary" : "Return an audit of all changes to the pipeline stage",
        "description" : "Return a reverse chronological list of all mutations that have occurred on the pipeline stage identified by `{stageId}`.",
        "operationId" : "get-/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}/audit_getAudit",
        "security" : [ {
          "oauth2_legacy" : [ "media_bridge.read" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps_legacy" : [ "timeline" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "oauth2_legacy" : [ "crm.schemas.custom.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.schemas.quotes.read" ]
        }, {
          "private_apps" : [ "crm.schemas.quotes.read" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps_legacy" : [ "crm.schemas.custom.read" ]
        }, {
          "private_apps_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps" : [ "crm.schemas.deals.read" ]
        }, {
          "oauth2" : [ "crm.schemas.deals.read" ]
        }, {
          "oauth2_legacy" : [ "timeline" ]
        }, {
          "private_apps_legacy" : [ "media_bridge.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.read" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.read" ]
        }, {
          "oauth2_legacy" : [ "tickets" ]
        }, {
          "hapikey" : [ ]
        }, {
          "private_apps_legacy" : [ "e-commerce" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.schemas.companies.read" ]
        }, {
          "oauth2" : [ "crm.schemas.companies.read" ]
        }, {
          "oauth2_legacy" : [ "e-commerce" ]
        }, {
          "private_apps_legacy" : [ "tickets" ]
        }, {
          "oauth2_legacy" : [ "crm.objects.goals.read" ]
        }, {
          "private_apps" : [ "crm.schemas.line_items.read" ]
        }, {
          "oauth2" : [ "crm.schemas.line_items.read" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2_legacy" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.objects.goals.read" : "Read goals",
              "tickets" : "Read and write tickets",
              "crm.schemas.custom.read" : "View custom object definitions",
              "timeline" : "Create timeline events",
              "e-commerce" : "e-commerce",
              "media_bridge.read" : "Read media and media events"
            }
          }
        }
      },
      "hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.schemas.deals.read" : " ",
              "crm.objects.deals.write" : " ",
              "crm.schemas.line_items.read" : "Line Items schemas",
              "crm.objects.deals.read" : " ",
              "crm.schemas.companies.read" : " ",
              "crm.objects.companies.read" : " ",
              "crm.objects.companies.write" : " ",
              "crm.schemas.contacts.read" : " ",
              "crm.objects.contacts.write" : " ",
              "crm.schemas.quotes.read" : "Quotes schemas",
              "crm.objects.contacts.read" : " ",
              "crm.schemas.companies.write" : " ",
              "crm.schemas.contacts.write" : " ",
              "crm.schemas.deals.write" : " "
            }
          }
        }
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "PHP", "Node", "Python", "Ruby" ]
}