{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Timeline events",
    "description" : "This feature allows an app to create and configure custom events that can show up in the timelines of certain CRM objects like contacts, companies, tickets, or deals. You'll find multiple use cases for this API in the sections below.",
    "version" : "v3"
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com/"
  } ],
  "tags" : [ {
    "name" : "Templates",
    "description" : "Definitions and configuration for timeline events."
  }, {
    "name" : "Tokens",
    "description" : "Specific tokens that map to CRM properties and can be used by timeline events. This is how you can use property stamping to create full CRM objects."
  }, {
    "name" : "Events",
    "description" : "Events shown on a CRM object's timeline."
  } ],
  "paths" : {
    "/crm/v3/timeline/events" : {
      "post" : {
        "tags" : [ "Events" ],
        "summary" : "Create a single event",
        "description" : "Creates an instance of a timeline event based on an event template. Once created, this event is immutable on the object timeline and cannot be modified. If the event template was configured to update object properties via `objectPropertyName`, this call will also attempt to updates those properties, or add them if they don't exist.",
        "operationId" : "post-/integrators/timeline/v3/events_create",
        "security" : [ {
          "oauth2_legacy" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.schemas.deals.write" ]
        }, {
          "private_apps_legacy" : [ "timeline" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.schemas.companies.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.write" ]
        }, {
          "private_apps" : [ "crm.schemas.companies.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "private_apps_legacy" : [ "tickets" ]
        }, {
          "oauth2_legacy" : [ "timeline" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "private_apps" : [ "crm.schemas.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        } ]
      }
    },
    "/crm/v3/timeline/events/batch/create" : {
      "post" : {
        "tags" : [ "Events" ],
        "summary" : "Creates multiple events",
        "description" : "Creates multiple instances of timeline events based on an event template. Once created, these event are immutable on the object timeline and cannot be modified. If the event template was configured to update object properties via `objectPropertyName`, this call will also attempt to updates those properties, or add them if they don't exist.",
        "operationId" : "post-/integrators/timeline/v3/events/batch/create_createBatch",
        "security" : [ {
          "oauth2_legacy" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.schemas.deals.write" ]
        }, {
          "private_apps_legacy" : [ "timeline" ]
        }, {
          "oauth2" : [ "crm.schemas.contacts.write" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.write" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.write" ]
        }, {
          "oauth2" : [ "crm.schemas.companies.write" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.write" ]
        }, {
          "private_apps" : [ "crm.schemas.companies.write" ]
        }, {
          "private_apps" : [ "crm.objects.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.deals.write" ]
        }, {
          "private_apps_legacy" : [ "tickets" ]
        }, {
          "oauth2_legacy" : [ "timeline" ]
        }, {
          "private_apps" : [ "crm.objects.companies.write" ]
        }, {
          "private_apps" : [ "crm.schemas.deals.write" ]
        }, {
          "oauth2" : [ "crm.objects.companies.write" ]
        } ]
      }
    },
    "/crm/v3/timeline/events/{eventTemplateId}/{eventId}" : {
      "get" : {
        "tags" : [ "Events" ],
        "summary" : "Gets the event",
        "description" : "This returns the previously created event. It contains all existing info for the event, but not necessarily the CRM object.",
        "operationId" : "get-/integrators/timeline/v3/events/{eventTemplateId}/{eventId}_getById",
        "security" : [ {
          "oauth2" : [ "crm.schemas.contacts.read" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.read" ]
        }, {
          "oauth2_legacy" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps_legacy" : [ "timeline" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps" : [ "crm.schemas.companies.read" ]
        }, {
          "oauth2" : [ "crm.schemas.companies.read" ]
        }, {
          "private_apps_legacy" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.schemas.deals.read" ]
        }, {
          "oauth2" : [ "crm.schemas.deals.read" ]
        }, {
          "oauth2_legacy" : [ "timeline" ]
        } ]
      }
    },
    "/crm/v3/timeline/events/{eventTemplateId}/{eventId}/detail" : {
      "get" : {
        "tags" : [ "Events" ],
        "summary" : "Gets the detailTemplate as rendered",
        "description" : "This will take the `detailTemplate` from the event template and return an object rendering the specified event. If the template references `extraData` that isn't found in the event, it will be ignored and we'll render without it.",
        "operationId" : "get-/integrators/timeline/v3/events/{eventTemplateId}/{eventId}/detail_getDetailById",
        "security" : [ {
          "oauth2" : [ "crm.schemas.contacts.read" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.read" ]
        }, {
          "oauth2_legacy" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps_legacy" : [ "timeline" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps" : [ "crm.schemas.companies.read" ]
        }, {
          "oauth2" : [ "crm.schemas.companies.read" ]
        }, {
          "private_apps_legacy" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.schemas.deals.read" ]
        }, {
          "oauth2" : [ "crm.schemas.deals.read" ]
        }, {
          "oauth2_legacy" : [ "timeline" ]
        } ]
      }
    },
    "/crm/v3/timeline/events/{eventTemplateId}/{eventId}/render" : {
      "get" : {
        "tags" : [ "Events" ],
        "summary" : "Renders the header or detail as HTML",
        "description" : "This will take either the `headerTemplate` or `detailTemplate` from the event template and render for the specified event as HTML. If the template references `extraData` that isn't found in the event, it will be ignored and we'll render without it.",
        "operationId" : "get-/integrators/timeline/v3/events/{eventTemplateId}/{eventId}/render_getRenderById",
        "security" : [ {
          "oauth2" : [ "crm.schemas.contacts.read" ]
        }, {
          "private_apps" : [ "crm.schemas.contacts.read" ]
        }, {
          "oauth2_legacy" : [ "tickets" ]
        }, {
          "oauth2" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps_legacy" : [ "timeline" ]
        }, {
          "oauth2" : [ "crm.objects.deals.read" ]
        }, {
          "private_apps_legacy" : [ "contacts" ]
        }, {
          "private_apps" : [ "crm.objects.contacts.read" ]
        }, {
          "private_apps" : [ "crm.objects.companies.read" ]
        }, {
          "oauth2" : [ "crm.objects.companies.read" ]
        }, {
          "private_apps" : [ "crm.schemas.companies.read" ]
        }, {
          "oauth2" : [ "crm.schemas.companies.read" ]
        }, {
          "private_apps_legacy" : [ "tickets" ]
        }, {
          "private_apps" : [ "crm.schemas.deals.read" ]
        }, {
          "oauth2" : [ "crm.schemas.deals.read" ]
        }, {
          "oauth2_legacy" : [ "timeline" ]
        } ]
      }
    },
    "/crm/v3/timeline/{appId}/event-templates" : {
      "get" : {
        "tags" : [ "Templates" ],
        "summary" : "List all event templates for your app",
        "description" : "Use this to list all event templates owned by your app.",
        "operationId" : "get-/integrators/timeline/v3/{appId}/event-templates_getAll",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      },
      "post" : {
        "tags" : [ "Templates" ],
        "summary" : "Create an event template for your app",
        "description" : "Event templates define the general structure for a custom timeline event. This includes formatted copy for its heading and details, as well as any custom property definitions. The event could be something like viewing a video, registering for a webinar, or filling out a survey. A single app can define multiple event templates.\n\nEvent templates will be created for contacts by default, but they can be created for companies, tickets, and deals as well.\n\nEach event templ[...]",
        "operationId" : "post-/integrators/timeline/v3/{appId}/event-templates_create",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      }
    },
    "/crm/v3/timeline/{appId}/event-templates/{eventTemplateId}" : {
      "get" : {
        "tags" : [ "Templates" ],
        "summary" : "Gets a specific event template for your app",
        "description" : "View the current state of a specific template and its tokens.",
        "operationId" : "get-/integrators/timeline/v3/{appId}/event-templates/{eventTemplateId}_getById",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      },
      "put" : {
        "tags" : [ "Templates" ],
        "summary" : "Update an existing event template",
        "description" : "Updates an existing template and its tokens. This is primarily used to update the headerTemplate/detailTemplate, and those changes will take effect for existing events.\n\nYou can also update or replace all the tokens in the template here instead of doing individual API calls on the `/tokens` endpoint.",
        "operationId" : "put-/integrators/timeline/v3/{appId}/event-templates/{eventTemplateId}_update",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      },
      "delete" : {
        "tags" : [ "Templates" ],
        "summary" : "Deletes an event template for the app",
        "description" : "This will delete the event template. All associated events will be removed from search results and the timeline UI.\n\nThis action can't be undone, so it's highly recommended that you stop using any associated events before deleting a template.",
        "operationId" : "delete-/integrators/timeline/v3/{appId}/event-templates/{eventTemplateId}_archive",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      }
    },
    "/crm/v3/timeline/{appId}/event-templates/{eventTemplateId}/tokens" : {
      "post" : {
        "tags" : [ "Tokens" ],
        "summary" : "Adds a token to an existing event template",
        "description" : "Once you've defined an event template, it's likely that you'll want to define tokens for it as well. You can do this on the event template itself or update individual tokens here.\n\nEvent type tokens allow you to attach custom data to events displayed in a timeline or used for list segmentation.\n\nYou can also use `objectPropertyName` to associate any CRM object properties. This will allow you to fully build out CRM objects.\n\nToken names should be unique across the t[...]",
        "operationId" : "post-/integrators/timeline/v3/{appId}/event-templates/{eventTemplateId}/tokens_create",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      }
    },
    "/crm/v3/timeline/{appId}/event-templates/{eventTemplateId}/tokens/{tokenName}" : {
      "put" : {
        "tags" : [ "Tokens" ],
        "summary" : "Updates an existing token on an event template",
        "description" : "This will update the existing token on an event template. Name and type can't be changed on existing tokens.",
        "operationId" : "put-/integrators/timeline/v3/{appId}/event-templates/{eventTemplateId}/tokens/{tokenName}_update",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      },
      "delete" : {
        "tags" : [ "Tokens" ],
        "summary" : "Removes a token from the event template",
        "description" : "This will remove the token from an existing template. Existing events and CRM objects will still retain the token and its mapped object properties, but new ones will not.\n\nThe timeline will still display this property for older CRM objects if it's still referenced in the template `Markdown`. New events will not.\n\nAny lists or reports referencing deleted tokens will no longer return new contacts, but old ones will still exist in the lists.",
        "operationId" : "delete-/integrators/timeline/v3/{appId}/event-templates/{eventTemplateId}/tokens/{tokenName}_archive",
        "security" : [ {
          "developer_hapikey" : [ ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oauth2_legacy" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "tickets" : "Read and write tickets",
              "timeline" : "Create timeline events"
            }
          }
        }
      },
      "developer_hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.schemas.contacts.write" : " ",
              "crm.objects.contacts.write" : " ",
              "crm.schemas.companies.write" : " ",
              "crm.objects.companies.write" : " ",
              "crm.objects.deals.write" : " ",
              "crm.schemas.deals.write" : " ",
              "crm.objects.contacts.read" : " ",
              "crm.schemas.contacts.read" : " ",
              "crm.schemas.companies.read" : " ",
              "crm.objects.companies.read" : " ",
              "crm.objects.deals.read" : " ",
              "crm.schemas.deals.read" : " "
            }
          }
        }
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      }
    }
  },
  "x-hubspot-available-client-libraries" : [ "PHP", "Node", "Python", "Ruby" ]
}