import _ from 'lodash';
import moment from 'moment';
import { v4 as uuidv4 } from 'uuid';
import useStore from '@/AppBuilder/_stores/store';

export default function autogenerateColumns(
  firstRow = {},
  existingColumns = [],
  columnDeletionHistory,
  useDynamicColumn,
  dynamicColumn = [],
  generateNestedColumns,
  componentId
) {
  if (useDynamicColumn) {
    const generatedColumns = dynamicColumn
      .filter((item) => {
        if (item?.name) return true;
        useStore.getState().debugger.log({
          logLevel: 'error',
          type: 'component',
          kind: 'component',
          key: `Table "Column data" - entry missing "name"`,
          componentId,
          strace: 'page_level',
          message: `A "Column data" entry (${JSON.stringify(item)}) is missing "name" and was skipped.`,
          error: { componentId, value: item },
          errorTarget: 'Component Property',
          timestamp: moment().toISOString(),
        });
        return false;
      })
      .map((item) => {
        const id = `${item?.id ?? uuidv4()}`;
        return {
          ...item,
          id: id,
          name: item.name,
          key: item?.key || item.name,
          autogenerated: true,
        };
      });
    return generatedColumns;
  }

  const isValueIsPremitiveOrArray = (value) => {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return true;
  };

  const isValueIsPlainObject = (value) => {
    if (typeof value === 'object' && !Array.isArray(value) && value !== null) return true;
  };

  const limitToOneLevelNestingHelperFunc = (data, presentKey) => {
    return Object.entries(data).reduce((accumulator, [key, value]) => {
      if (isValueIsPremitiveOrArray(value)) {
        accumulator.push(`${presentKey}.${key}`);
      }
      return accumulator;
    }, []);
  };
  const generateNestedColumnsHelperFunc = (data, parentKey = '') => {
    return Object.entries(data).reduce((accumulator, [key, value]) => {
      const currentKey = parentKey ? `${parentKey}.${key}` : key;
      if (isValueIsPlainObject(value)) {
        // if value is object particularly, then we only want nested keys till one level of nesting
        accumulator.push(...limitToOneLevelNestingHelperFunc(value, currentKey));
      } else if (isValueIsPremitiveOrArray(value)) {
        // check if value is premitive or array then simply push current key in the accumulator.
        accumulator.push(currentKey);
      }
      return accumulator;
    }, []);
  };

  const generateColumnKeys = (firstRow, generateNestedColumns) => {
    if (generateNestedColumns) {
      // This block is responsible to get all the keys, nested keys till one level of nesting from the firstRow
      return generateNestedColumnsHelperFunc(firstRow);
    } else {
      /*
        return keys whose value is premitive data type to support backward compatibility for older app,
        where we do not auto-generate column for nested data
      */
      return Object.entries(firstRow).reduce((accumulator, [key, value]) => {
        if (value === null || typeof value !== 'object') accumulator.push(key);
        return accumulator;
      }, []);
    }
  };

  /*
    A key containing a literal "." (e.g. "a.b") cannot be told apart from the dot-separated
    path syntax used for one-level-nested auto-generated columns (e.g. "address.city"), and it
    breaks TanStack Table's accessorKey resolution (which treats "." as a nested-path separator).
    Such keys are not supported for column auto-generation, so they're skipped and reported.
  */
  const sanitizedFirstRow = Object.keys(firstRow).reduce((accumulator, key) => {
    if (key.includes('.')) {
      useStore.getState().debugger.log({
        logLevel: 'error',
        type: 'component',
        kind: 'component',
        key: `Table - column key contains "."`,
        componentId,
        strace: 'page_level',
        message: `A key ("${key}") contains a "." which is not supported for auto-generated columns and was skipped.`,
        error: { componentId, value: key },
        errorTarget: 'Component Property',
        timestamp: moment().toISOString(),
      });
    } else {
      accumulator[key] = firstRow[key];
    }
    return accumulator;
  }, {});

  // mapping the keys of first row with one level of nested elements.
  const keysOfTableData = generateColumnKeys(sanitizedFirstRow, generateNestedColumns);

  const keysOfExistingColumns = existingColumns.map((column) => column?.key || column?.name);

  const keysFromWhichNewColumnsShouldBeGenerated = _.difference(keysOfTableData, [
    ...keysOfExistingColumns,
    ...columnDeletionHistory,
  ]);

  const keysAndDataTypesToGenerateNewColumns = keysFromWhichNewColumnsShouldBeGenerated?.map((key) => [
    key,
    typeof firstRow[key],
  ]);

  const keysOfExistingColumnsThatNeedToPersist = existingColumns
    .filter((column) => !column?.autogenerated || keysOfTableData.includes(column.key || column.name))
    .map((column) => column?.key || column?.name);

  const generatedColumns = keysAndDataTypesToGenerateNewColumns.map(([key, dataType]) => ({
    id: uuidv4(),
    name: key,
    key: key,
    columnType: convertDataTypeToColumnType(dataType),
    autogenerated: true,
  }));

  const finalKeys = [...keysFromWhichNewColumnsShouldBeGenerated, ...keysOfExistingColumnsThatNeedToPersist];
  const finalColumns = [...existingColumns, ...generatedColumns].filter((column) =>
    finalKeys.includes(column?.key || column?.name)
  );

  return finalColumns;
}

const dataTypeToColumnTypeMapping = {
  string: 'string',
  number: 'number',
  boolean: 'boolean',
};

const convertDataTypeToColumnType = (dataType) => {
  if (Object.keys(dataTypeToColumnTypeMapping).includes(dataType)) return dataTypeToColumnTypeMapping[dataType];
  else return 'string';
};
